- features/vaultHistory/vaultHistory.ts
The way the whitelisting is implemented in the spock requires `operationName` to be send with query. The library that we use does not support that so custom fetch function needed to be implemented.
> Prepare history fetching for whitelisting

- .github/pull_request_template.md
- features/ilks/popularIlksFilters.ts
- features/ilks/populartilksFilters.ts
- features/landing/FiltersWithPopular.tsx
- features/landing/LandingView.tsx
- features/landing/landing.ts
- features/landing/tests/landing.test.ts
- public/locales/en/common.json
- Added `popular` filter option, first 12 ilks with the most debt generated and that still have some debt available
- Open landing page
- You should see by default 12 ilks filtered by popularity
> Popular assets

- .gitignore
- components/Links.tsx
- components/Table.tsx
- features/landing/FeaturedIlks.tsx
- features/landing/LandingView.tsx
- features/openVaultOverview/OpenVaultOverview.tsx
- features/openVaultOverview/SelectVaultTypeModal.tsx
- features/openVaultOverview/useRedirectToOpenVault.tsx
- features/vaultHistory/VaultHistoryView.tsx
- features/vaultsOverview/VaultsOverviewView.tsx
- helpers/stories/OpenVaultStory.tsx
- public/locales/en/common.json
- theme/index.tsx
- Implement select vault type modal
- Open modal for relevant vaults 
- Click on the open Vault link from landing page and from list page
- For ETH based vaults you will be prompted with modal
- For none ETH vaults you should be redirected to open vault page
> Select vault type

- components/Announcement.tsx
- components/Layouts.tsx
- features/landing/LandingView.tsx
> Remove infra banners

- .github/workflows/aws-prod.yaml
- blockchain/config.ts
> CI changes for oasis.app

- theme/index.tsx
- Extra path removed from dai icon
- Compare Dai icon from landing page with production
> Remove extra path in Icon

- features/landing/FeaturedIlks.tsx
- features/manageVault/ManageVaultDetails.tsx
- features/manageVault/ManageVaultIlkDetails.tsx
- features/openVault/OpenVaultDetails.tsx
- features/openVault/OpenVaultIlkDetails.tsx
- reduce decimals in several places
- inspect landing cards, open and manage vault to see reduced decimals
> Reduce decimals

- next.config.js
- change `basePath` to root
- deploy on staging, see borrow routes working as expected
> Change basePath

- README.md
- components/Links.tsx
- server/app.ts
- sitemapGenerator.ts
> Remove unsed const, fix path for production on app.ts

- features/landing/LandingView.tsx
- pages/support.tsx
> Remove welcone announcement, fix contact link

- next.config.js
Add the following redirects:
- /borrow/{sub routes} -\> /{sub routes}
- /dashboard -\> /daiwallet/dashboard
- A path starting with /{eth address} -\> /daiwallet/dashboard
- Check that the redirects work.
> Add redirects for becoming the root of the site.

- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
> Add missing translation

- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/manifest.json
- Added description to manifest 
- Added missing translate key
> Release 1.0.22

- components/HeadTags.tsx
> Remove borrow from headtag

- components/HeadTags.tsx
> Remove trailing slash

- components/HeadTags.tsx
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- public/manifest.json
> Remove borrow from headtags & manifest

- pages/[vault]/index.tsx
- public/locales/en/common.json
- detect if [vaultId] is integer and show 404 page if it is not
- change copy
- visit `/boom` or some other `/non-existing` address
> Detect proper vault id, show 404 page

- features/manageVault/manageVaultConditions.ts
- When debt is zero user wasn't able to withdraw all collateral 
- if you have a vault, pay back all debt 
- if the vault debt is 0 then try to withdraw collateral
> Check if debt is zero

- blockchain/ilks.ts
- features/collateralPrices/CollateralPricesView.tsx
- features/landing/LandingView.tsx
- features/manageVault/ManageVaultView.tsx
- features/openVault/OpenVaultView.tsx
- features/openVaultOverview/OpenVaultOverview.tsx
- helpers/AppSpinner.tsx
- helpers/errorHandlers/ErrorModal.tsx
- helpers/errorHandlers/WithErrorHandler.tsx
- pages/owner/[address]/index.tsx
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
This is alternative, probably better implementation than:
https://github.com/OasisDEX/oasis-borrow/pull/295
- Added error page
- Changed translation from 'Go to home' to 'Go to hompage'
- Added new error handling coponents to do it outside AppSpinner
- Turn off developer tools go to network tab block requests from infura
- After 3 request fail one should be redirected to error page
- On error page one should be able to see error details. after clisking button 'See details'
- [✔️ ] End-to-end tests for happy path
> Story 2159 Feauture/error hook

- blockchain/ilks.ts
- features/collateralPrices/CollateralPricesView.tsx
- features/content/support/en.ts
- features/content/support/es.ts
- features/content/support/support.ts
- features/landing/LandingView.tsx
- features/manageVault/ManageVaultErrors.tsx
- features/manageVault/ManageVaultView.tsx
- features/manageVault/manageVaultConditions.ts
- features/manageVault/manageVaultValidations.ts
- features/manageVault/stories/ManageVaultErrors.stories.tsx
- features/manageVault/tests/manageVaultValidations.test.ts
- features/openVault/OpenVaultView.tsx
- features/openVaultOverview/OpenVaultOverview.tsx
- helpers/AppSpinner.tsx
- helpers/errorHandlers/ErrorModal.tsx
- helpers/errorHandlers/WithErrorHandler.tsx
- pages/owner/[address]/index.tsx
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
> Release 1.0.26

- blockchain/config.ts
> Change cache endpoint

- blockchain/config.ts
- next.config.js
- pages/owner/[address]/index.tsx
> Release 1.0.27

- analytics/mixpanel.ts
> Update proxy url

- analytics/mixpanel.ts
- Updated mixpanel prod URL
-view mixpanel on production
> Update Mixpanel production URL

- package.json
- yarn.lock
No clubhouse link updated wallectconnect dependency asap, ran all tests on localhost 
https://twitter.com/WalletConnect/status/1419999849068564505
- updated wallectconnect dependency to https://www.npmjs.com/package/@web3-react/walletconnect-connector/v/6.2.4
- 
- step 1 ...
- [ x] Acceptance criteria for each issue met
- [x ] End-to-end tests for happy path
- [] Project builds without errors
> updated @web3-react/walletconnect-connector to at least 6.2.4

- components/vault/VaultActionInput.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultEditing.tsx
- features/manageMultiplyVault/manageMultiplyVault.ts
- theme/index.tsx
Still some logic for inputs/handler functions might change when we will have more details.
- add `Select` for other actions
- mock slider, inputs for other actions
- mock screen for close actions
- go to manage multiply vault, see UI changes
> Other actions, mock slider, add different inputs

- analytics/mixpanel.ts
> For testing mixpanel on Brave

- .env
- features/openVault/openVaultTransactions.ts
- package.json
- server/database/.env
- server/database/migrations/002-vault.sql
- server/database/schema.prisma
- server/middleware/vault/createOrUpdate.ts
- yarn.lock
> Revert prisma, add .subscribe, test saving on openVault

- features/manageMultiplyVault/components/ManageMultiplyVaultChangesInformation.tsx
- features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
- features/manageMultiplyVault/tests/manageMultiplyVaultAdjustPositionCalculations.test.ts
- features/manageMultiplyVault/tests/manageMultiplyVaultAdjustPositionValidations.test.ts
- features/manageVault/ManageVaultChangesInformation.tsx
- features/openMultiplyVault/components/OpenMultiplyVaultChangesInformation.tsx
- features/openMultiplyVault/openMultiplyVaultCalculations.ts
- features/openMultiplyVault/tests/openMultiplyVault.test.ts
- features/openVault/components/OpenVaultChangesInformation.tsx
- helpers/multiply/calculations.ts
- update oazo fee
- fix tests
- display `zero` for 3rd party fees on open/manage for regular vault
- step 1 ...
> Update oazo fee, add zero for 3rd party fees on regular vault

- features/manageMultiplyVault/components/ManageMultiplyVaultButton.tsx
- features/openMultiplyVault/openMultiplyVaultCalculations.ts
- helpers/multiply/calculations.ts
- public/locales/en/common.json
> Remove redundant fee, fix FF to proper number, fix copy for close button

- scripts/docker-compose.yml
> Add Rinkeby Alchemy Key for localnode conf

- features/manageMultiplyVault/components/ManageMultiplyVaultEditing.tsx
- disable toggling buy/sell inputs on Adjust Position for MVP
- test UI/Storybook
> Disable triggering Sell/Buy inputs for adjust position

- blockchain/config.ts
> Update mainnet contracts

- features/manageMultiplyVault/components/ManageMultiplyVaultView.tsx
- features/manageMultiplyVault/manageMultiplyVault.ts
- features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
- features/manageMultiplyVault/manageMultiplyVaultConditions.ts
- features/manageMultiplyVault/manageMultiplyVaultForm.ts
- features/manageMultiplyVault/manageMultiplyVaultInput.ts
- features/manageMultiplyVault/manageMultiplyVaultTransitions.ts
- features/manageMultiplyVault/tests/manageMultiplyVault.test.ts
- features/manageVault/ManageVaultView.tsx
- features/manageVault/manageVault.ts
- features/manageVault/manageVaultTransitions.ts
- features/manageVault/tests/manageVault.test.ts
- features/openMultiplyVault/components/OpenMultiplyVaultView.tsx
- features/openMultiplyVault/openMultiplyVault.ts
- features/openMultiplyVault/openMultiplyVaultCalculations.ts
- features/openMultiplyVault/openMultiplyVaultConditions.ts
- features/openMultiplyVault/openMultiplyVaultTransitions.ts
- features/openMultiplyVault/tests/openMultiplyVault.test.ts
- features/openVault/components/OpenVaultView.tsx
- features/openVault/openVault.ts
- features/openVault/openVaultTransitions.ts
- features/openVault/tests/openVault.test.ts
- helpers/stories/OpenMultiplyVaultStory.tsx
Fixes:
- add `clear` function to all 4 flows, trigger it if component is unmounted to reset input values and set initial state
- play with flows, you don't have to trigger tx eg:
- go to `/open` input some values, go to other state than initial one
- go to another page via client-side navigation
- go back to `/open` via Back Button
- see that inputs were cleared and you are in initial state
> Fix non cleared form states

- features/openMultiplyVault/openMultiplyVault.ts
- fix reseting screen on open multiply
- go to open multiply, open vault, leave UI on success screen for 30 secs - it shouldn't go back to initial state
> Fix success screen reset

- features/exchange/exchange.ts
> Use precision when calculating the price from 1inch

- public/locales/es/common.json
common es file updated to include new keys fully translated. 
- step 1 ...
> Spanish translation updates on multiply feature

- features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
> Use afterdebt

- features/manageMultiplyVault/components/ManageMultiplyVaultChangesInformation.tsx
- features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
- features/openMultiplyVault/openMultiplyVaultCalculations.ts
- features/shared/priceImpact.ts
https://www.notion.so/oazo/Multiply-MVP-tests-Feedback-bugs-2a776db8d0cf4acdb42717c96ccdf9d2#8f81f6c323df46dd94940a438018ce9a
Calculate the price impact for both opening and managing vault position.
> Calculate price impact

- features/landing/LandingView.tsx
- features/landing/TypeformWidget.tsx
- Added Typeform (a feedback form widget) to the homepage.
It must be tested using https , or it doesn't work. Test deployment: https://oasis-borrow-ft-feedbac-hi2vev.herokuapp.com/
> Add feedback form.

- components/vault/VaultDetails.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultDetails.tsx
- features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
- hides P&L
- extracted card to have one common component instead of duplication
> Unify NetValue card, comment unrealised P&L

- public/locales/cn/common.json
> update chinese (by Hazel :))

- features/manageVault/ManageVaultChangesInformation.tsx
- features/openVault/components/OpenVaultChangesInformation.tsx
- helpers/stories/ManageVaultStory.tsx
- hide fees section on open/manage regular vault
- fix storybook for manage regular
- test in UI/Storybok
> Hide fees on regular vault views, fix storybook

- features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
- features/manageMultiplyVault/tests/manageMultiplyVaultAdjustPositionCalculations.test.ts
- change `currentCollateralPrice` to `marketPrice` for calculations of (after consultations with Frank list got extended to 4 items):
-  collateralDeltaUSD
- netValueUSD
- afterNetValueUSD
- afterCloseToCollateralUSD
- add tests 
- [x ] Acceptance criteria for each issue met
- [x ] Unit tests written where needed and passing
> Fix collateral buying usd calc price

- features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
> fixed issue exposure

- README.md
- features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
- added link to multiply docs.
> Add link to Multiply smart contract documentation.

- features/vaultHistory/vaultMultiplyHistory.ts
- add hash to multiply events query 
- Check history for vault `25553` using staging api
> Fix etherscan link in multiply event

- features/openMultiplyVault/components/OpenMultiplyVaultChangesInformation.tsx
- Replace marketPriceWithSlippage to MarketPrice on open multiply vault flow
- step 1 ...
> Replace marketPriceWithSlippage to marketPrice

- blockchain/config.ts
- default to mainnet contracts for hardhat env if env variables are not set
- set .env variables for contracts to empty values or comment them out, restart frontend, see that you can still interact with app
> Default to mainnet contracts for hardhat

- features/generalManageVault/GeneralManageVaultView.tsx
Fix multiply events and vat events sorting.
Fix wrong value for debt displaying in multiply events.
> Multiply history fixes

- blockchain/config.ts
> Change cache url to production 

- features/landing/TypeformWidget.tsx
- Update feedback widget color to white
-
> Update Feedback widget color

- public/locales/en/common.json
- to test: verify the copy on heroku.
> Updated copy of titles & few minor copy fixes

- features/careers/listings/example-careers/smart-contract-engineer.mdx
- features/careers/listings/full-stack-developer.mdx
Fix typo: work@oazo.com -> work@oasis.app
> Fix work e-mail.

- features/manageVault/ManageVaultButton.tsx
This is a fix for a bug that Lucian posted in the channel. IT's about a user who couldn't neither pay, not withdraw.
> Improve conditional check for the vault management button

- .github/workflows/aws-prod.yaml
> Build prod image with cache

- features/careers/listings/full-stack-developer.mdx
Edits here: https://docs.google.com/document/d/1wNAaFzDDGHrAPkjpy9AQAFLSOHnZRDy2L8BmO0RoXBc/edit#heading=h.f2i1taa0anf
> Edit career listing.

- components/vault/VaultChangesInformation.tsx
> Change error text on gas estimation

- package.json
- The user gets disconnected if they have auto-connect and change to an unsupported network
> Release 2.0.3

- components/connectWallet/ConnectWallet.tsx
- public/locales/en/common.json
Improve handling unsupported network
> Improve handling unsupported networks

- package.json
- Fix handling unsupported networks
> Release 2.0.4

- features/manageMultiplyVault/components/ManageMultiplyVaultConfirmation.tsx
- features/manageVault/ManageVaultConfirmation.tsx
https://cdn.discordapp.com/attachments/839088233353576468/890613398092525648/Screenshot_2021-09-23_at_15.58.37.png
- fix stuck gas estimation on confirmation for manage flows:
- test in UI
> Fix stuck gas estimation on confirmation screen

- components/vault/VaultDetails.tsx
- features/manageVault/ManageVaultDetails.tsx
> Replace mocked modal

- analytics/analytics.ts
- components/AppContext.ts
- components/vault/VaultDetails.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultConfirmation.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultView.tsx
- features/manageMultiplyVault/manageMultiplyVaultAnalytics.ts
- features/manageVault/ManageVaultConfirmation.tsx
- features/manageVault/ManageVaultDetails.tsx
- features/openMultiplyVault/components/OpenMultiplyVaultView.tsx
- features/openMultiplyVault/openMultiplyVaultAnalytics.ts
- Fix stuck gas estimation on confirmation screen (#489)
- Replace mocked modal (#491)
- Add multiply confirm button and transaction events (#481) …
> Release 2.0.5

- components/vault/TxStatusCard.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultConfirmation.tsx
- features/manageMultiplyVault/stories/ManageMultiplyVaultView.stories.tsx
- features/manageVault/ManageVaultConfirmation.tsx
- features/openMultiplyVault/components/OpenMultiplyVaultConfirmation.tsx
- features/openVault/components/OpenVaultConfirmation.tsx
- public/locales/en/common.json
- restore cards for `inProgress` states
- add multiply copy
- add additional stories for manage multiply
> In progress Tx Link

- analytics/analytics.ts
- analytics/mixpanel.ts
- components/vault/TxStatusCard.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultConfirmation.tsx
- features/manageMultiplyVault/stories/ManageMultiplyVaultView.stories.tsx
- features/manageVault/ManageVaultConfirmation.tsx
- features/openMultiplyVault/components/OpenMultiplyVaultConfirmation.tsx
- features/openVault/components/OpenVaultConfirmation.tsx
- package.json
- pages/api/t.tsx
- public/locales/en/common.json
- yarn.lock
- Restore in progress cards, add to multiply, add copy, add stories (#471)
- Add internal mixpanel api endpoint (#496)
> Release 2.0.6

- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
> copy fixes

- blockchain/vaults.ts
- components/AppContext.ts
- features/banners/vaultsBanners.ts
- features/generalManageVault/vaultTypeLocalStorage.ts
- features/manageMultiplyVault/manageMultiplyVault.ts
- features/manageVault/manageVault.ts
- features/openMultiplyVault/openMultiplyVaultTransactions.ts
- features/openVault/openVaultTransactions.ts
- features/shared/vaultApi.ts
- helpers/mocks/vaults.mock.ts
- server/database/migrations/003-chain-id.sql
- server/database/migrations/004_vault_id_chain_id_constraint.sql
- server/database/schema.prisma
- server/middleware/vault/createOrUpdate.ts
* added saving chain_id to database upon vault creation
* handled saving vault chainId for vault that existed on blockcchain but not in db. TBD: add mocking context in test, in db change id to be no longer unique but rather pair of an id and chainId
* added mock for test, ran linter TBD migrate db and schema for id to be no longer unique key but rater id+chainId
* added constraint for pair of vault_id and chain_id to be unique key, added to schema and migration script
* added constraint for pair of vault_id and chain_id to be unique key, added to schema and migration script
* uncommented commented out part of docker-compose :)
* removed pointless debug console.logs
- item 1 …
> Lw/story/2893/save network (#550)

- components/InfoBadge.tsx
- features/ilks/IlkPanel.tsx
- features/ilks/stories/IlkPanel.stories.tsx
- features/landing/HowItWorks.tsx
- features/landing/LandingView.tsx
- public/locales/en/common.json
- theme/index.tsx
- added ilk panel component
- added story in storybook
- test using storybook
> added single ilk panel

- components/Footer.tsx
- components/Layouts.tsx
we're updating the discord link to the new vanity link.
> Update discord link

- blockchain/config.ts
> Add GuniMultiplyProxyActions mainnet address to the config

- blockchain/config.ts
> Update GuniMPA mainnet address

- features/generalManageVault/GeneralManageVaultView.tsx
> removed manage for guni container attached to eth-a

- components/vault/VaultDetails.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultDetails.tsx
- features/manageMultiplyVault/components/ManageMultiplyVaultView.tsx
- features/manageMultiplyVault/manageMultiplyVaultCalculations.ts
- features/openMultiplyVault/components/OpenMultiplyVaultDetails.tsx
- helpers/multiply/calculations.ts
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- scripts/docker-compose.yml
> added PnL to modal and market price to details

- blockchain/config.ts
- features/openGuniVault/guniActionsCalls.ts
- features/openGuniVault/openGuniVault.ts
- features/openMultiplyVault/variants/guni/open/GuniOpenMultiplyVaultEditing.tsx
> Fix values in calculations

- features/openGuniVault/guniForm.ts
> fixed link to etherscan

- features/openGuniVault/guniForm.ts
> fixed allowance for custom values

- features/careers/listings/smart-contract-developer.mdx
> Add career.

- features/manageGuniVault/manageGuniVault.ts
> fixed selling usdc value

- analytics/adroll.ts
- analytics/common.ts
- components/CookieBanner.tsx
- components/stories/CookieBanner.stories.tsx
- helpers/useLocalStorage.ts
- pages/_app.tsx
> adroll-bug-investigation

- features/landing/LandingView.tsx
Hiding the typeform for the month of December. We will add it again when we want to publish a new survey.
> Hide typeform

- components/TabSwitchLayout.tsx
- components/dumb/PickCloseState.tsx
- components/dumb/SliderValuePicker.tsx
- components/dumb/TxStatusSection.tsx
- components/vault/detailsCards/VaultDetailsCardDynamicStopPrice.tsx
- components/vault/detailsCards/VaultDetailsCardMaxTokenOnStopLossTrigger.tsx
- components/vault/detailsCards/VaultDetailsCardStopLossCollRatio.tsx
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/AdjustSlFormLayout.tsx
- theme/index.tsx
- ui fixes according to Hazel review
- heroku
> automation ui fixes

- features/openGuniVault/openGuniMultiplyVaultTransactions.ts
- features/openGuniVault/openGuniVault.ts
- helpers/multiply/calculations.ts
> Add new fee tier for Guni (0.04%)

- pages/_app.tsx
> adroll temporary disabled

- package.json
- pages/_app.tsx
> Release 2.7.1

- package.json
- pages/_app.tsx
> Sp/adroll enabled (#659)

- features/vaultHistory/VaultHistoryView.tsx
- features/vaultHistory/vaultMultiplyHistory.ts
> added gas fee to total fees in vault history

- features/openMultiplyVault/openMultiplyVaultTransactions.ts
> Update gasEstimation params for Guni

- blockchain/calls/automationBot.ts
- components/AppContext.ts
- features/automation/common/AutomationTransactionPlunger.ts
- features/automation/common/StopLossTriggerDataExtractor.ts
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/CancelSlFormControl.tsx
- features/automation/controls/CancelSlFormLayout.tsx
- features/automation/triggers/AutomationTriggersData.ts
- pages/[vault]/index.tsx
- public/locales/en/common.json
> Lw/story 3207/cancel

- features/manageGuniVault/manageGuniVault.ts
- features/openGuniVault/openGuniVault.ts
- helpers/multiply/calculations.ts
- guni slippage changed from 0.005 to 0.001
- heroku
> changed slippage from 0.005 to 0.001

- blockchain/config.ts
- features/automation/common/AutomationTransactionPlunger.ts
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/CancelSlFormControl.tsx
- features/automation/controls/CancelSlFormLayout.tsx
…comment and created task
- item 1
- step 1 ...
> Minor new year refactorings

- package.json
> 2.9.0 release preparation

- blockchain/calls/proxyActions.ts
- blockchain/utils.ts
> HOTFIX: BigNumber Rounding

- .github/workflows/release.yaml
- .release-it.json
- package.json
- yarn.lock
> Add github action for automation

- blockchain/utils.test.ts
- blockchain/utils.ts
- components/constants.ts
- features/manageMultiplyVault/tests/manageMultiplyVaultAdjustPositionCalculations.test.ts
- helpers/multiply/calculations.test.ts
> FIX: BigNumber Decimal Places Misconfiguration

- .github/workflows/release.yaml
> fix automation

- blockchain/abi/automation-bot.json
- blockchain/config.ts
- features/automation/triggers/AutomationTriggersData.ts
> Update Automation Bot Info

- blockchain/ens.ts
> FIX: ENS Lookup On Unsupported Networks

- blockchain/addresses/addressesUtils.ts
> getCollateralJoinContracts fix

- features/automation/common/StopLossTriggerDataExtractor.ts
- features/automation/triggers/AutomationTriggersData.ts
> FIX: Trigger Event Handling

- components/ProductCardBorrow.tsx
- components/ProductCardMultiply.tsx
- features/borrow/BorrowView.tsx
- features/homepage/HomepageView.tsx
- features/multiply/MultiplyView.tsx
- helpers/productCards.ts
- public/locales/en/common.json
- heroku / staging / locally
- step 1 ...
> added translations

- components/Footer.tsx
> added feature toggle to footer background

- public/locales/en/common.json
> Update copy for multiply -> borrow switch

- features/automation/common/StopLossTriggerDataExtractor.ts
Requested by @rkrasiuk sending to triggers data more generic triggersType (uint16) instead of boolean flag
> change triggersData format

- components/AppContext.ts
- components/devModeHelpers.ts
- features/exchange/exchange.ts
- helpers/multiply/calculations.ts
- open vault GUNIV3DAIUSDC2-A (test gas estimation for few values, 1k DAI, 5k DAI, 50k DAI, 200k DAI)
- close this vault 
- test other multiply flows
- step 1 ...
> Use PSM for guni operations - guni bug fix

- features/form/warningMessagesHandler.ts
> Disable slippage warning on guni flow

- theme/Background.tsx
- theme/BackgroundLight.tsx
> Fixed background

- helpers/useFeatureToggle.ts
> enable asset landing pages featuretoggle

- components/ProductCardBorrow.tsx
- borrow cards banner for lp tokens adjusted
> borrow cards banner for lp tokens adjusted

- components/ProductCardMultiply.tsx
- features/newsletter/NewsletterView.tsx
- helpers/productCards.test.ts
- helpers/productCards.ts
- Newsletter and ilks order adjusted
> Newsletter and ilks order adjusted

- components/ProductCardMultiply.tsx
- helpers/productCards.ts
- public/locales/en/common.json
> Guni cards adjusted

- features/homepage/HomepageView.tsx
- public/locales/en/common.json
- theme/index.tsx
> Slide in pills.  Adjust header size and subheader words and width

- components/InfoCard.tsx
- features/homepage/HomepageView.tsx
> style tweak background images on info cards

- components/ProductCardBorrow.tsx
- components/ProductCardMultiply.tsx
- helpers/productCards.ts
- helpers/roundToThousand.test.ts
- helpers/roundToThousand.ts
- Multiply banner calculations adjusted
- heroku.
> Multiply banner calculations adjusted

- components/ProductCard.tsx
- components/ProductCardBorrow.tsx
- components/ProductCardMultiply.tsx
- components/TabSwitcher.tsx
- features/vaultsOverview/VaultsOverviewView.tsx
- public/locales/en/common.json
- Pre-release fixes implemented
- loading icon added to the product card buttons
-  link on the /owner/0x0 page should redirect to landing page
- Stability Fee -> Variable Annual Fee
> Pre-release fixes implemented

- components/FloatingLabel.tsx
- components/ProductCard.tsx
- Adjusted floating label in product card (shadow and position)
- heroku
> Adjusted floating label in product card

- features/asset/AssetView.tsx
- Asset page header icon size change to 64px
- heroku
> Asset page header icon size change

- public/locales/cn/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- fixed missing keys for other langues for product cards
- heroku
> Translations fix

- components/Header.tsx
- navlink has different color when active
- heroku
> Active nav links

- features/homepage/HomepageView.tsx
- pages/_app.tsx
- public/locales/en/common.json
- Added see products button (when connected, in the same place as connect a wallet button)
- heroku
> Added see products button

- helpers/productCards.ts
- pages/asset/[asset].tsx
- pages/owner/[address]/index.tsx
- pages/vaults/open-multiply/[ilk].tsx
- pages/vaults/open/[ilk].tsx
- open-multiply/[ilk] static generation
- heroku
> static ilks page try

- .github/workflows/aws-prod.yaml
- .github/workflows/aws-staging.yaml
Adding Cloudfront invalidation after new deployments.
> CloudFront invalidation

- components/ProductCardEarn.tsx
- features/earn/EarnView.tsx
- helpers/productCards.ts
- public/locales/en/common.json
- added product card earn component
- heroku
> Added product card earn with mocked data

- components/TabSwitcher.tsx
- features/homepage/HomepageView.tsx
- helpers/productCards.ts
- adjusted tab content for earn, fixed filtering
- heroku
> Adjusted tab content for earn, fixed filtering

- components/TabSwitchLayout.tsx
- features/automation/common/UITypes/AddFormChange.ts
- features/automation/common/UITypes/TabChange.ts
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/borrow/manage/containers/ManageVaultView.tsx
- pages/[vault]/index.tsx
- public/locales/en/common.json
- public/static/img/automation.svg
- scripts/docker/compose.yml
- Added protection banner
- Click button on protection banner
- be redirected to Protection Tab
Note testing automation branch on hardhat forked from mainnet will cause issues because of missing automationBot contract that is deployed on Goerli. One can test everything on Goerli
- [x ] Non-functional requirements met
> Added get vault protection banner 

- components/Header.tsx
- public/locales/en/common.json
> Design fixes

- components/Links.tsx
- components/TabSwitcher.tsx
- features/homepage/HomepageView.tsx
- features/vaultsOverview/VaultsOverviewView.tsx
- fixed links with hash tag
- heroku
> Fixed links with hash tag

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- features/multiply/manage/pipes/manageMultiplyQuote.ts
- features/multiply/manage/pipes/manageMultiplyVaultCalculations.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultForm.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransitions.ts
- fixed closing vault action when debt is zero
- heroku using multiply vault with and without debt
> Fixed closing vault action when debt is zero

- pages/owner/[address]/index.tsx
- switched back to getServerSideProps
- heroku
> Fixed locales issue for owner page

- public/locales/es/common.json
- most of the strings in public/locales/es/common.json are translated to spanish
- step 1 ...
> Updated spanish translations

- components/TabSwitchLayout.tsx
- components/vault/DefaultVaultHeaderControl.tsx
- components/vault/DefaultVaultHeaderLayout.tsx
- components/vault/DefaultVaultLayout.tsx
- components/vault/GeneralManageControl.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/GeneralVaultFormControl.tsx
- components/vault/HistoryControl.tsx
- components/vault/ProtectionControl.tsx
- components/vault/commonMultiply/ManageMultiplyVaultContainer.tsx
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/CancelSlFormControl.tsx
- features/automation/controls/ProtectionDetailsControl.tsx
- features/automation/controls/ProtectionFormControl.tsx
- features/automation/controls/ProtectionFormLayout.tsx
- features/borrow/manage/containers/ManageVaultView.tsx
- features/generalManageVault/GeneralManageVaultView.tsx
- features/vaultHistory/VaultHistoryDetailsControl.tsx
- helpers/stories/ManageMultiplyVaultStory.tsx
- helpers/stories/ManageVaultStory.tsx
- pages/[vault]/index.tsx
- added history tab
- changed data flow for manage vaults
> History tab and data flow adjustment

- components/AppContext.ts
- components/vault/VaultChangesInformation.tsx
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/AdjustSlFormLayout.tsx
- features/automation/controls/CancelSlFormControl.tsx
- features/automation/controls/CancelSlFormLayout.tsx
- added gas estimation to automation forms
- heroku / locally using goerli testnet, vault id 84 or 55
> Added gas estimation to automation forms

- .gitignore
- blockchain/abi/automation-bot.json
- blockchain/calls/automationBot.ts
- blockchain/config.ts
- components/AppContext.ts
- features/automation/common/StopLossTriggerDataExtractor.ts
- features/automation/common/enums/TriggersTypes.ts
- features/automation/common/service/allActiveTriggers.ts
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/CancelSlFormControl.tsx
- features/automation/controls/GetProtectionBannerControl.tsx
- features/automation/controls/ProtectionDetailsControl.tsx
- features/automation/controls/StopLossBannerControl.tsx
- features/automation/triggers/AutomationTriggersData.ts
- scripts/docker/compose.yml
> FIX: Automation Contract Updates

- .github/workflows/aws-prod.yaml
- .github/workflows/aws-staging.yaml
- Adding to GH Actions workflows 2 Env vars new on borrow
> Adding sentry env vars to GH Actions

- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/AdjustSlFormLayout.tsx
- features/automation/controls/ProtectionDetailsControl.tsx
- helpers/observableHook.ts
- public/locales/en/common.json
- added summary for adding stop loss trigger
> Added summary for adding stop loss trigger

- components/dumb/RetryableLoadingButton.tsx
- components/dumb/TxStatusSection.tsx
- features/automation/common/UITypes/AddFormChange.ts
- features/automation/common/components/AutomationFormButtons.tsx
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/CancelSlFormControl.tsx
- features/automation/controls/ProtectionDetailsControl.tsx
- features/automation/controls/ProtectionDetailsLayout.tsx
- slider starts from the middle when SL is not enabled
- added confirm button when SL is not enabled
- unified isEditing state
> Protection ui adjustments

- features/automation/controls/AdjustSlFormControl.tsx
> disabled stop loss btn fix

- features/automation/controls/AdjustSlFormLayout.tsx
> summary dai fix

- features/automation/controls/GetProtectionBannerLayout.tsx
- adjusted styles of get protection banner
> Adjusted styles of get protection banner

- features/generalManageVault/GeneralManageVaultView.tsx
> guni history fix

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- features/multiply/manage/pipes/manageMultiplyQuote.ts
- features/multiply/manage/pipes/manageMultiplyVaultCalculations.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultForm.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransitions.ts
This reverts commit 606d6e6a4e6666d4a7f28d7abdf7ee7284dcfacf.
- item 1
- step 1 ...
> Revert "Fixed closing vault action when debt is zero (#794)"

- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/AdjustSlFormLayout.tsx
- public/locales/en/common.json
- stop loss triggered estimation update
> stop loss triggered estimation

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- features/multiply/manage/pipes/manageMultiplyQuote.ts
- features/multiply/manage/pipes/manageMultiplyVaultCalculations.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultForm.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransitions.ts
This reverts commit 606d6e6a4e6666d4a7f28d7abdf7ee7284dcfacf.
- item 1
- step 1 ...
> Update dev with revert from mian

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- features/multiply/manage/pipes/manageMultiplyQuote.ts
- features/multiply/manage/pipes/manageMultiplyVaultCalculations.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultForm.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransitions.ts
This reverts commit 606d6e6a4e6666d4a7f28d7abdf7ee7284dcfacf.
- item 1
- step 1 ...
> Revert "Fixed closing vault action when debt is zero (#794)" (#859)

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- features/multiply/manage/pipes/manageMultiplyQuote.ts
- features/multiply/manage/pipes/manageMultiplyVaultCalculations.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransitions.ts
- closing vault when debt is zero perform withdraw action
- hardhat using mulitply vault, test closin to collateral / dai action when vault has debt and without debt, its recommended to test other actions as well (depositing dai)
> zero debt close vault issue

- features/automation/controls/AdjustSlFormLayout.tsx
- features/borrow/manage/containers/ManageVaultForm.tsx
- features/multiply/manage/containers/ManageMultiplyVaultForm.tsx
- when SL has been triggered and user clicks on Reopen position within form, user should be moved to other actions -> deposit collateral stage (multiply)
- removed fact section from adjust sl form
- set `const stopLossTriggered = true` within manageMultiplyVaultConditons.ts and in manageVaultConditions.ts for borrow vaults
> Reopen position & deposit

- components/vault/GeneralManageControl.tsx
- components/vault/GeneralManageLayout.tsx
- features/automation/common/components/AutomationFormButtons.tsx
- features/automation/common/helpers.ts
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/AdjustSlFormLayout.tsx
- features/automation/controls/CancelSlFormLayout.tsx
- features/automation/controls/ProtectionDetailsControl.tsx
- features/automation/controls/ProtectionDetailsLayout.tsx
> automation fixes

- components/AppContext.ts
- components/vault/VaultDetails.tsx
- features/vaultsOverview/VaultsOverviewView.tsx
- features/vaultsOverview/vaultsFilters.ts
- features/vaultsOverview/vaultsOverview.ts
- public/locales/en/common.json
- added stop loss label to vaults list
> added stop loss label to vaults list

- blockchain/calls/cdpRegistry.ts
- blockchain/calls/getCdps.ts
- blockchain/getRegistryCdps.ts
- blockchain/vaults.ts
- components/AppContext.ts
> Get charter cropper vaults

- components/vault/detailsCards/VaultDetailsCardLiquidationPrice.tsx
- features/automation/triggers/AutomationTriggersData.ts
- features/borrow/manage/tests/manageVaultValidations.test.ts
- features/multiply/manage/tests/manageMultiplyVaultAdjustPositionValidations.test.ts
- features/multiply/manage/tests/manageMultiplyVaultOtherActionsValidations.test.ts
- features/vaultsOverview/vaultsOverview.ts
- fixed issue with automation api calls when feature flag is set to false
> fixed issue with automation api calls when feature flag is set to false

- components/SwitchNetworkModal.tsx
- components/SwitchWalletModal.tsx
- public/locales/en/common.json
- public/static/img/switch_wallet.svg
- implemented modal according to design (without logic)
- locally, import SwitchNetworkModal component in for example _app.tsx and place it next to <CookieBanner ... />
> Switch network modal design

- blockchain/calls/proxyActions/proxyActions.ts
- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- features/multiply/manage/pipes/manageMultiplyVault.ts
- features/multiply/manage/pipes/manageMultiplyVaultCalculations.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultForm.ts
- features/multiply/manage/pipes/manageMultiplyVaultInput.ts
- features/multiply/manage/tests/manageMultiplyVault.test.ts
- features/vaultHistory/VaultHistoryView.tsx
- added possibility to deposit and multiply at the same time
- hardhat
> deposit and multiply

- next.config.js
- package.json
- pages/_error.tsx
> fixed issue with mdx and local builds

- blockchain/config.ts
Updating contracts to new adresses
> Automation redeployment

- components/Footer.tsx
- components/vault/commonMultiply/ManageMultiplyVaultContainer.tsx
- features/earn/guni/open/containers/GuniOpenVaultView.tsx
- features/generalManageVault/GeneralManageVaultView.tsx
- package.json
- pages/multiply.tsx
- pages/vaults/open-multiply/[ilk].tsx
- public/locales/en/common.json
- yarn.lock
Adds a survey to the multiply page.  Buttons are hidden after form is opened and closed.
> Add multiply survey

- components/connectWallet/ConnectWallet.tsx
> enable gnosis goerli

- components/vault/MultipleRangeSlider.tsx
- features/multiply/open/containers/OpenMultiplyVaultEditing.tsx
- theme/index.tsx
- added multiply range slider
- locally using open multiply flow (dummy slider is rendered there)
> Multi-range slider

- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
> allow user to close vault with SL trigger

- components/Header.tsx
- features/userSettings/UserSettingsView.tsx
- theme/index.tsx
Changes seen here: https://www.notion.so/oazo/New-Header-v1-9009000c4ed448b59c32925cadd7300f
> Update header style

- components/uniswapWidget/UniswapWidget.tsx
- yarn.lock
Replaces dynamic import with normal import of Uniswap widget.
> Import Uniswap widget normally.

- features/asset/AssetView.tsx
https://localhost:3443/asset/eth?network=goerli currently causes the page to error.  This fixes that.
> check for undefined as well as null on product card data

- features/careers/listings/cto.mdx
- features/careers/listings/full-stack-developer.mdx
- features/careers/listings/smart-contract-developer.mdx
- features/careers/listings/software-Engineer-in-test.mdx
Created CTO Job offer at career page.
Self explanatory 🤷‍♂️
> CTO job offer

- .github/pull_request_template.md
- Removes definition of done section of template.
- Clubhouse -> Shortcut.
> Update PR template.

- components/uniswapWidget/UniswapWidget.tsx
- package.json
- yarn.lock
Fix a bug where the tooltip in slippage settings would appear blank.
> Fix uniswap widget tooltip bug.

- features/careers/listings/cto.mdx
- features/careers/listings/full-stack-developer.mdx
- features/careers/listings/smart-contract-developer.mdx
- features/careers/listings/software-Engineer-in-test.mdx
- pages/careers/index.tsx
https://app.shortcut.com/oazo-apps/story/3987/careers-update-the-about-us-section-in-the-full-stack-job-ad
https://app.shortcut.com/oazo-apps/story/3986/careers-add-software-engineer-in-test-job-ad-to-careers
https://app.shortcut.com/oazo-apps/story/4059/careers-add-cto-job-ad-to-careers
Cherrypicked commits: https://github.com/OasisDEX/oasis-borrow/commit/14cfce09206ebb3f0192b0466702794d4dce57fd, https://github.com/OasisDEX/oasis-borrow/commit/a7e602a022a72a5547109a798aa63e45e2ffe306.
> Cherrypicked changes in job offers

- package.json
- yarn.lock
> Updated @oasisdex/automation package version

- features/automation/controls/AdjustSlFormControl.tsx
- added toCollateral ui state update
- if there is no SL added to vault, when user use slider to change SL ratio and get back to initial state changes should be still visible
> SL slider issue fix

- content/assets.ts
- helpers/productCards.test.ts
- helpers/productCards.ts
> remove crv asset

- features/vaultHistory/VaultHistoryEntry.tsx
- features/vaultHistory/VaultHistoryView.tsx
- Updated layout in vault history section.
- Removed extensive usage of `div`s all over the place and changed some of them into other tags according to `HTML` semantics.
Check out manage vault page or, in case of automation feature flag enabled, "history" tab on vault page. Please not that you need to check multiply vault to see events on in history that has details.
> Update vault history section

- components/Announcement.tsx
- features/generalManageVault/GeneralManageVaultView.tsx
- Added temporary banner on vault pages with `CRVV1ETHSTETH-A` ilk.
- Added parameter that allows to disable closing announcement banner.
- Set discord link as optional.
> Publish banner on CRVV1ETHSTETH-A vaults

- components/Announcement.tsx
- features/generalManageVault/GeneralManageVaultView.tsx
* display generic announcement on CRVV1ETHSTETH-A vaults
* update copy and make discord link optional
* prettier fix
- item 1
- step 1 ...
> Publish banner on CRVV1ETHSTETH-A vaults (#964)

- components/uniswapWidget/UniswapWidget.tsx
- Added uniswap fonts import
- staging using windows
This is how text currently looks like on Windows
This is how it should look like
> Added uniswap fonts import

- features/vaultsOverview/vaultsFilters.ts
- features/vaultsOverview/vaultsOverview.ts
- removed initial state from pipe that delivers data for owner page
- goerli with automation flag turned on, you can use following owner 0xB710940E3659415ebd5492f43B247891De14D872
- compare it with staging instance and see if there is an loading speed improvement
> Owner page vault loading time fix

- components/DetailsSection.tsx
- components/DetailsSectionContentCard.tsx
- components/DetailsSectionFooterItem.tsx
- components/ExpandableButton.tsx
- components/WithArrow.tsx
- components/dumb/ExpandableArrow.tsx
- components/vault/VaultTabTag.tsx
- features/borrow/manage/containers/ManageVaultContainer.tsx
- theme/index.tsx
This story PR consists of three stories, they couldn't be tested separately.
- https://app.shortcut.com/oazo-apps/story/3857/redesign-update-detail-section
- https://app.shortcut.com/oazo-apps/story/3856/redesign-update-detail-cards
- https://app.shortcut.com/oazo-apps/story/4134/redesign-update-detail-section-footer
New components created for this view:
- `DetailsSection`,
- `DetailsSectionContentCard`,
- `DetailsSectionFooterItem`,
- `ExpandableButton`,
- `ExpandableArrow`.
All of those components are meant to be used in new layout of vault on every tab. Although, `ExpandableArrow` is little animation component with up/down arrow that could be use in every place that has expandable secions like FAQ, vault history or language selector. This animation (and rest of them) were discussed …
> New vault details section

- blockchain/config.ts
> hardhat cache api change

- components/vault/VaultProxy.tsx
- features/borrow/manage/containers/ManageVaultForm.tsx
- features/borrow/manage/pipes/viewStateTransforms/manageVaultTransactions.ts
- features/borrow/open/containers/OpenVaultView.tsx
- features/borrow/open/pipes/openVaultTransactions.ts
- features/earn/guni/manage/containers/GuniManageMultiplyVaultForm.tsx
- features/earn/guni/manage/pipes/manageGuniVaultTransactions.ts
- features/earn/guni/open/containers/GuniOpenMultiplyVaultForm.tsx
- features/earn/guni/open/pipes/openGuniMultiplyVaultTransactions.ts
- features/multiply/manage/containers/ManageMultiplyVaultForm.tsx
- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/multiply/open/containers/OpenMultiplyVaultForm.tsx
- features/multiply/open/pipes/openMultiplyVaultTransactions.ts
- helpers/extractGasDataFromState.ts
- public/locales/en/common.json
- theme/icons.tsx
- added gas estimation to proxy step
- try to create proxy using borrow / multiple / earn opening flow
- try to create proxy using borrow / multiple manage flow
> Added gas estimation to proxy step

- blockchain/tokensMetadata.ts
- components/vault/GeneralManageLayout.tsx
- features/automation/protection/controls/GetProtectionBannerControl.tsx
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
- features/multiply/open/containers/OpenMultiplyVaultDetails.tsx
- added ilks allowed for automation
- try to use ilk that is not supported, protection tab and banners shouldn't be displayed in that case
> Added ilks allowed for automation

- content/assets.ts
- features/automation/protection/controls/StopLossTriggeredFormLayout.tsx
- helpers/productCards.ts
> Trigger executed summary fix, prettier

- .github/workflows/aws-staging.yaml
> secret name adjusted for staging

- components/uniswapWidget/UniswapWidget.tsx
> fix uniswap font import

- helpers/useFeatureToggle.ts
- Automaton feature toggle set true as default
- when merge to dev, on staging feature toggle automation should be set to true as default
> Automaton feature toggle set true as default

- package.json
- yarn.lock
* fix
* add yarn.lock
Co-authored-by: Adam Skrodzki <adam@oazoapps.com>
- item 1
- step 1 ...
> Main To Dev

- components/vault/GeneralManageLayout.tsx
- features/generalManageVault/GeneralManageVaultView.tsx
- helpers/productCards.ts
> FIX: Remove CRV from Landing Page & Delete CRV Warning Banners

- components/vault/ProtectionControl.tsx
> zero debt vault protection header and description fix

- features/automation/protection/common/ProtectionBanner.tsx
- features/automation/protection/controls/StopLossTriggeredBannerLayout.tsx
> fix banner image

- next-i18next.config.js
- Fix translation resolution for SSR pages
- checkout owner page on vercel deployment
> Fix translation resolve

- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
Cherrypicked https://github.com/OasisDEX/oasis-borrow/pull/1022
> Cherrypick a1d3347

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
> Hide deposit dai

- helpers/productCards.ts
- Filter ilks in ProductCards to remove those with debt ceilings of zero
- Add USDC to a wallet you control
- Navigate to My Positions view
- Check that USDC card does NOT appear in suggested cards list
> Off-board ilks that have a debt ceiling of zero from suggestions area

- features/automation/protection/common/consts/calculations.ts
- features/automation/protection/common/helpers.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
This reverts commit cba967517d6815e1ebae9dd5e1209e8cba88c8e8.
- item 1
- step 1 ...
> Revert "added 0.05 offset to liquidation ratio when setting SL (#1027)"

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- features/multiply/manage/pipes/manageMultiplyVaultCalculations.ts
- fixed UI calculations for oaza fee when depositing DAI and multiplying
- locally using hardhat
> Oazo fee fix when depositing dai and multiplying

- components/vault/GeneralManageLayout.tsx
- features/automation/protection/controls/GetProtectionBannerControl.tsx
- helpers/useFeatureToggle.ts
Fix bug with `ALLOWED_AUTOMATION_ILKS` being variable was still in the code.
> showProtectionTab should use isSupportedAutomationIlk method

- components/ProductCard.tsx
- components/TabSwitcher.tsx
- Fix spacings
-  Fix 'key duplication' warnings
> Fix spacing in product cards

- components/vault/ProtectionControl.tsx
- components/vault/commonMultiply/ManageMultiplyVaultContainer.tsx
- components/vault/detailsCards/VaultDetailsCardLiquidationPrice.tsx
- components/vault/detailsSection/ContentCardLiquidationPrice.tsx
- features/automation/protection/common/components/AutomationFormButtons.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/triggers/AutomationTriggersData.ts
- features/borrow/manage/containers/ManageVaultContainer.tsx
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/borrow/manage/containers/ManageVaultForm.tsx
- features/instiVault/manage/containers/ManageInstiVaultContainer.tsx
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
- features/multiply/manage/containers/ManageMultiplyVaultForm.tsx
- features/vaultsOverview/vaultsOverview.ts
- helpers/useFeatureToggle.ts
- pages/[vault]/index.tsx
- Renamed `Automation` feature flag into `StopLossRead`.
- Moved commented parts of code regarding SL configuration into `StopLossWrite` feature flag.
Try setting up SL with flag on and off.
> StopLossRead and StopLossWrite feature flags

- features/multiply/manage/containers/ManageMultiplyVaultEditing.tsx
- updated label for deposit dai and payback action
- open multiply vault (or use existing one), go to other tab and check if action labels are updated
> Updated label for deposit dai and payback action

- helpers/productCards.ts
Visiting https://oasis.app/vaults/open-multiply/GUNIV3DAIUSDC1-A leads to an infinite loop and browser crash.
- item 1
on dev visiting : http://localhost:3000/vaults/open-multiply/GUNIV3DAIUSDC1-A
should reproduce
> Fixed loading of GUNIV3DAIUSDC1-A

- public/locales/en/common.json
Updated message in translations.
> Update SL too low coll ratio message

- features/automation/protection/common/helpers.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/CancelSlFormControl.tsx
- features/automation/protection/controls/CancelSlFormLayout.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLoss.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLossCancelStage.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLossEditingStage.tsx
- features/shared/balanceInfo.ts
- features/sidebar/getPrimaryButtonLabel.ts
- features/sidebar/getSidebarProgress.ts
- features/sidebar/getSidebarSuccess.ts
- features/sidebar/getSidebarTitle.ts
- updated sidebar in cancel stop loss form
- using feature flag NewComponent, StopLossRead, StopLossWrite try to add / adjust / cancel stop loss
> Updated sidebar in cancel stop loss form

- features/earn/guni/open/containers/GuniOpenMultiplyVaultEditing.tsx
- features/earn/guni/open/containers/GuniOpenMultiplyVaultForm.tsx
- features/earn/guni/open/containers/sidebar/SidebarOpenGuniVault.tsx
- features/earn/guni/open/containers/sidebar/SidebarOpenGuniVaultOpenStage.tsx
- features/earn/guni/open/pipes/openGuniVault.ts
- features/earn/guni/open/pipes/openGuniVaultConditions.ts
- features/sidebar/getPrimaryButtonLabel.ts
- features/sidebar/getSidebarProgress.ts
- features/sidebar/getSidebarSuccess.ts
- features/sidebar/getSidebarTitle.ts
- features/types/vaults/sidebarLabels.ts
- Added new sidebar design to open guni flow
- using hardhat and NewComponents feature toggle try to open guni vault and check whether design is ok
> Added new sidebar design to open guni flow

- components/smartProxy/SmartProxyStageOne.tsx
- public/locales/en/common.json
- public/locales/es/common.json
Bugfix for translation issue in new smart proxy setup flow
> Fix bugfix translation issue for new smart proxy screens

- content/assets.ts
- helpers/productCards.ts
- GUNIV3DAIUSDC1-A in multiply product
- GUNIV3DAIUSDC1-A should appear in multiply product near GUNIV3DAIUSDC2-A
> support for GUNIV3DAIUSDC1-A

- helpers/useFeatureToggle.ts
Set `StopLossWrite` to `true`.
> Set StopLossWrite to true

- components/AppContext.ts
https://discord.com/channels/837076147694207067/983675454940651530/983707896992899092
> fix issue with ever-increasing calls to token prices

- features/vaultsOverview/VaultOverviewView.tsx
- features/vaultsOverview/containers/AssetsAndPositionsOverview.tsx
- places old stuff on the vault overview page behind earn feature flag
- fixes position bug with asset menu display
- with earn feature toggle enabled: wallet connected, disconnected, different position
- with earn feature toggle disabled: wallet connected, disconnected, different position
> Tidy vault overview

- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
> slider min boundary fix

- features/automation/protection/common/consts/automationDefaults.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
> stoploss slider fill fix

- features/vaultsOverview/vaultsOverview.ts
- helpers/productCards.ts
- helpers/useFeatureToggle.ts
* Set feature toggle to 'true'
* Reorder feature product cards
> enable earn product

- components/vault/detailsCards/VaultDetailsCardStopLossCollRatio.tsx
- components/vault/detailsSection/ContentCardStopLossCollateralRatio.tsx
- components/vault/stories/VaultDetailsCard.stories.tsx
- features/automation/protection/common/consts/automationDefaults.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/ProtectionDetailsControl.tsx
- features/automation/protection/controls/ProtectionDetailsLayout.tsx
- public/locales/en/common.json
> stop loss adjusted validation

- public/locales/en/common.json
updates the dai description link
> update dai description

- components/VaultTabSwitch.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/OptimizationControl.tsx
- features/automation/optimization/controls/OptimizationDetailsControl.tsx
- features/automation/optimization/controls/OptimizationDetailsLayout.tsx
- features/automation/optimization/controls/OptimizationFormControl.tsx
- helpers/useFeatureToggle.ts
- public/locales/en/common.json
Required for https://app.shortcut.com/oazo-apps/story/3869/basic-buy-form and other basic BS related stories.
Created a new tab for Optimization for vaults. Currently the tab does not have any actual content. Component structure was based on Protection tab and contains some empty components, but they are going to be needed in the future.
Go to any vault and see if Optimization tab is available.
> Basic BS tab

- components/vault/VaultErrors.tsx
- features/automation/protection/common/consts/automationDefaults.ts
- features/automation/protection/common/validation.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/CancelSlFormControl.tsx
- features/automation/protection/controls/CancelSlFormLayout.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLoss.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLoss.tsx
- features/form/errorMessagesHandler.ts
- public/locales/en/common.json
> max debt for setting stop loss

- scripts/docker/compose.yml
- scripts/docker/launch.sh
Small changes for a better development experience. 
Add project name to `docker compose` command. Now our compose looks like:
Added also volume to allow the database to persist data.
> Docker compose project name & volume for PostgreSQL DB

- components/vault/sidebar/SidebarSliders.tsx
> sidebar slider fill fix

- components/dumb/PositionList.tsx
Some font updates on the positions table.
> update fonts on positions table

- helpers/cacheObject.tsx
- pages/api/stats.tsx
- server/config.ts
- server/services/getOasisStats.ts
- Do not display any data if snowflake is disabled, (default data removed)
- Bug fixed in parsing config
- When data unavailable api returns 404
- Adjust logic to missing data in snowflake
> Stats fixes

- features/vaultsOverview/pipes/positionsOverviewSummary.ts
Improves performance on postions page.
> debounce and distinct positions list

- public/locales/en/common.json
> Estimated fees on sl execution tooltip update

- features/automation/protection/controls/CancelSlFormLayout.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLossCancelStage.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLossEditingStage.tsx
- public/locales/en/common.json
> added selected sl coll ratio on cancel protection for closed vault

- blockchain/config.ts
> use staging cache on hardhat network as default

- components/sidebar/SidebarSectionFooter.tsx
- components/vault/sidebar/SidebarSliders.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLossCancelStage.tsx
- features/automation/protection/openFlow/openVaultStopLoss.ts
- features/borrow/open/pipes/openVault.ts
- features/borrow/open/pipes/openVaultConditions.ts
- features/borrow/open/sidebars/SidebarOpenBorrowVault.tsx
- features/earn/guni/open/sidebars/SidebarOpenGuniVaultEditingState.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVaultEditingStage.tsx
- features/multiply/open/pipes/openMultiplyVault.ts
- features/multiply/open/pipes/openMultiplyVaultConditions.ts
- features/multiply/open/sidebars/SidebarOpenMultiplyVault.tsx
- features/multiply/open/sidebars/SidebarOpenMultiplyVaultEditingState.tsx
- features/sidebar/getSidebarStatus.ts
- theme/useBreakpointIndex.ts
> new design fixes

- blockchain/config.ts
> CHORE: New Goerli Exchange Address

- features/multiply/open/tests/openMultiplyVault.test.ts
- helpers/useFeatureToggle.ts
- enabled NewComponents and StopLossOpenFlow feature toggle flag
> Enable NewComponents and StopLossOpenFlow feature toggle flag

- features/vaultHistory/VaultHistoryEntry.tsx
- features/vaultHistory/vaultHistoryEvents.ts
- public/locales/en/common.json
- added handling to basic buy and sell history events
- use vault with basic buy and sell triggers added
> Basic BS history handling

- features/automation/protection/common/dropdown.ts
- features/automation/protection/controls/sidebar/SidebarAdjustStopLoss.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLoss.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- Passed t function instead of using hook
- step 1 ...
> Passed t function instead of using hook

- blockchain/calls/automationBot.ts
- components/vault/GeneralManageLayout.tsx
- components/vault/detailsCards/VaultDetailsCardLiquidationPrice.tsx
- features/automation/protection/triggers/AutomationTriggersData.ts
- features/multiply/open/containers/OpenMultiplyVaultEditing.tsx
- features/vaultHistory/VaultHistoryView.tsx
- theme/index.tsx
New components flag was already removed and merged here - https://github.com/OasisDEX/oasis-borrow/pull/1150.
Scope of this PR is to clean up the remaining dead code and TODOs from old components.
- Check if everything is fine.
- Let me know if there are more pieces of code that can be removed.
- Help me clarify if `TODO` in `GeneralManageLayout.tsx` is up to date, what can be removed?
> removed remaining old components code

- .github/workflows/aws-prod.yaml
- .github/workflows/aws-staging.yaml
- features/homepage/HomepageView.tsx
- server/services/getOasisStats.ts
Reverts OasisDEX/oasis-borrow#1155
> Revert "Fix stats"

- components/VaultTabSwitch.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/commonMultiply/OpenMultiplyVaultContainer.tsx
- features/content/faqs/guni/en.mdx
- features/earn/guni/manage/containers/GuniManageMultiplyVaultDetails.tsx
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- Add FAQ tab (now called "Position Info") to manage Earn position.
- Update FAQ content.
- Fix parenthesis showing up in UI.
> FAQ changes

- .graphqlconfig
- blockchain/collateral.test.ts
- blockchain/collateral.ts
- components/AppContext.ts
- components/ProductCardEarn.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/earn/ManageEarnVaultContainer.tsx
- features/earn/guni/common/GuniVaultHeader.tsx
- features/earn/guni/manage/pipes/manageGuniVault.ts
- features/earn/guni/open/containers/GuniOpenVaultView.tsx
- features/earn/guni/open/pipes/openGuniVault.ts
- features/earn/guni/open/tests/OpenGuniVault.test.ts
- features/earn/makerOracleTokenPrices.ts
- features/earn/yieldCalculations.ts
- helpers/mocks/guniOpenEarnVault.mock.ts
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- schema.graphql
* New way to get yields from API
* Change In yield (manage, open earn)
> change in yields in vault header

- features/automation/basicBuySell/InfoSections/AddAutoSellInfoSection.tsx
- features/automation/basicBuySell/InfoSections/BuyInfoSection.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyRemovalEditingStage.tsx
- public/locales/en/common.json
> polished summary section for basic buy

- components/TabBar.tsx
> udpate z index on recommended positions drop-down

- pages/support.tsx
- Fix top navigation urls in /support page.
> Fix support links with hash.

- features/survey/surveysConfig.json
Added a survey to the homepage
> update survey on the homepage

- features/earn/guni/open/containers/GuniOpenMultiplyVaultDetails.tsx
- helpers/multiply/calculations.ts
- When clicking the button, set hash instead of publishing tab change event.
> Fix "learn more" button on open GUNI.

- features/automation/common/basicBSTriggerData.ts
- updated deviation calculation due to change in SC
- step 1 ...
> Deviation calc update

- features/borrow/manage/pipes/viewStateTransforms/manageVaultConditions.ts
- features/form/commonValidators.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- adjusted stop loss triggered validator
- stop loss executed banner should not be visible when auto buy or sell trigger has been executed
> Adjusted stop loss triggered validator

- blockchain/prices.ts
- blockchain/vaults.ts
- components/AppContext.ts
- features/vaultHistory/vaultHistory.ts
- features/vaultHistory/vaultHistoryEvents.ts
- features/vaultHistory/vaultsHistory.ts
- features/vaultsOverview/VaultOverviewView.tsx
- features/vaultsOverview/pipes/positionsList.ts
- features/vaultsOverview/pipes/positionsOverviewSummary.ts
- features/vaultsOverview/vaultsOverview.ts
- pages/owner/[address]/index.tsx
We introduced a regression on the overview page. Loading was infinite. 
* Top Assets and position have timeout - 10 sec. After that time the component will not show. 
* Requests for cache for positions are combined in one request. 
* Go to the overview page
> [sc-5119]  Bug overview page stays loading infinitely

- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- public/locales/en/common.json
fixes in comments:
https://app.shortcut.com/oazo-apps/story/5111/add-explanation-wording-next-to-slider-auto-buy
https://app.shortcut.com/oazo-apps/story/5104/add-explanation-wording-next-to-slider-auto-sell
- item 1
- step 1 ...
> copyfix as discussed with Sam

- .github/workflows/aws-staging.yaml
- .github/workflows/build.yml
- Add missing build step to release to staging process. 
- step 1 ...
> Add build to release

- .dockerignore
- Dockerfile
> Add migration

- Dockerfile
> install next

- public/locales/en/common.json
reasable → reusable
as many time as you’d like →as many times as you like.
FAQ's → FAQs
> Copy change on referral page

- blockchain/config.ts
> New Goerli Redeemer address

- package.json
- yarn.lock
> updated common dependency, rebuild project

- features/automation/common/helpers.ts
- Updated basic buy and sell is disable method
- added verification whether execCollRatio or targetCollRatio is zero
> Updated basic buy and sell is disable method

- helpers/useFeatureToggle.ts
- enabled BasicBS feature toggle
- visit app and check whether auto buy / auto sell are visible
> Enable BasicBS by default

- components/ReferralModal.tsx
- components/SuccessfullJoinModal.tsx
- features/referralOverview/ReferralLayout.tsx
- features/referralOverview/ReferralsView.tsx
- features/referralOverview/user.ts
Sum of all user claims (present and past) is calculated with 
`const totalClaims =  weeklyClaims?.reduce((p, c) => p.plus(c.amount), new BigNumber('0'));`
where `WeeklyClaims` contain all claim objects that contain `amount` of each claim
- step 1 ...
> Update total claims calc + colors

- pages/referrals/index.tsx
> fix inifinite load on wallet not connected

- components/SuccessfullJoinModal.tsx
changed `You will now receive 5% of all fees that they generate on Oasis.app. You can now go directly to the Oasis.app homepage or see your referral dashboard.` to `You will now receive 5% of all fees that you generate on Oasis.app. You can now go directly to the Oasis.app homepage and start exploring products to deploy capital into Defi.`
> Update referral modal copy

- blockchain/config.ts
> Redeemer mainnet address

- components/ReferralModal.tsx
- features/referralOverview/ReferralLayout.tsx
- public/locales/en/common.json
> Updated referral FAQ and blog links

- public/locales/en/common.json
- fixed max gass fee copy
- check if copy is ok
> Fixed max gas fee copy

- components/ReferralModal.tsx
- features/referralOverview/ReferralLayout.tsx
> Remove `latest` from links

- features/automation/common/basicBSTriggerData.ts
- item 1
go to http://localhost:3000/xxx?network=goerli#protection
go to http://localhost:3000/xxx?network=goerli#optimization
and check the default gas fee
> Update default gas fee to 300gwei

- features/vaultHistory/VaultHistoryEntry.tsx
- features/vaultHistory/vaultHistory.ts
- features/vaultHistory/vaultHistoryEvents.ts
- public/locales/en/common.json
- Extended automation history events
- go to vault with history regarding automation (add / remove / update / execute) and check if all events have detailed information about trigger
> Extended automation history events

- helpers/useFeatureToggle.ts
> Flip Referrals flag to `true` [DO NOT MERGE]

- features/referralOverview/ReferralLayout.tsx
> Fix referral kb link

- components/ReferralBanner.tsx
- public/locales/en/common.json
Update the referral banner to :
open homepage
> Update Referral Banner copy and behavior

- pages/referrals/index.tsx
- public/locales/en/common.json
Added title and description, to change the Google search preview
- step 1 ...
> Update referrals page title and description

- theme/Background.tsx
- theme/BackgroundLight.tsx
- theme/BackgroundLighter.tsx
- theme/ProductBackground.tsx
changed background z-index to -1
- step 1 ...
> Fix the scrollbar

- components/vault/VaultWarnings.tsx
- features/automation/protection/common/consts/automationDefaults.ts
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/form/warningMessagesHandler.ts
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
- public/locales/en/common.json
- Added warning banner to vaults affected by auto-sell SC change
- for vaults 1935  and 28734 a warning banner should be visible within overview details page
> Added warning banner to vaults affected by auto-sell SC change

- features/homepage/HomepageView.tsx
> fix cards on homepage

- helpers/productCards.ts
Based on discord conversation here: https://discord.com/channels/837076147694207067/1001457837777637376/1001467679523209216
We are updating the links to the GUNI blog
- item 1
- step 1 ...
> Update blog links for GUNI

- blockchain/calls/ilkToToken.ts
- blockchain/ilks.ts
- components/AppContext.ts
- helpers/productCards.test.ts
- helpers/productCards.ts
- filter ilks by supported network on product cards
- ilkToToken maps using case-insensitive address mappings
- URL borrow?network=goerli works
- cards on other networks appear the same
> fix goerli cards

- features/homepage/HomepageView.tsx
- terms of service flow added to homepage
- remove your JWT token from localstorage or use account on which you didn't generate one, connect wallet on homepage (ToS flow should appear)
> ToS flow on homepage

- blockchain/calls/automationBotAggregator.ts
- features/automation/common/constanMultipleHandlers.tsx
- features/automation/optimization/controls/ConstantMultipleFormControl.tsx
- features/automation/optimization/controls/constantMultipleTriggersData.tsx
- features/automation/protection/common/service/allActiveTriggers.ts
- features/automation/protection/useConstantMultipleStateInitialization.ts
Allows to edit existing trigger on a vault instead of incrementing another one.
Try editing trigger on a vault that already has one.
> Edit existing constant multiple trigger

- features/walletAssociatedRisk/WalletAssociatedRisk.tsx
- public/locales/en/common.json
Quick fix as Requested by Sam to update the copy, there is no ticket for this.
> Updated copy in WalletAssosiatedRisk

- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/optimization/validators.ts
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/form/warningMessagesHandler.ts
- features/vaultHistory/VaultHistoryEntry.tsx
- helpers/gasEstimate.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
- added validation to constant multiple form
- verify whether validation works correctly for CM inputs (min sell / max buy price) according to story
> Constant multiple inputs validation

- features/content/index.tsx
- public/locales/en/common.json
> changes to trigger new terms of service pop up

- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- public/locales/en/common.json
- Added description to Constant Multiple form.
- Check if there is description from screenshot above Constant Multiple form.
> Add description to Constant Multiple Set-up

- features/vaultHistory/vaultsHistory.ts
- fixed issue with groupId in query not hidden behind feature toggle
- on local go to `http://localhost:3000/owner/0xe7129bf98fefc005dcd716536e9b9ed877477819` with constant multiple feature toggle off and check whether you will get error
> GroupId fix

- scripts/docker/launch.sh
> launch.sh, dev.sh fix duplicates in .env an .env.local

- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- public/locales/en/common.json
- Changed collateral ration in Constant Multiple form description to multiplier.
- Self explanatory.
> Update Constant Multiple description in form

- features/content/index.tsx
Hotfix - Roll back version number
> hotfix for tos version

- components/vault/detailsSection/ContentCardOperatingCost.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsControl.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsLayout.tsx
- features/vaultHistory/vaultHistory.ts
- features/vaultHistory/vaultHistoryEvents.ts
- features/vaultHistory/vaultsHistory.ts
- helpers/multiply/calculations.ts
- public/locales/en/common.json
- added real data to Total Cost & PnL detail card in Constant Multiple view
- Total cost should show in USD sum of fees related to Constant multiple since it was added (including add trigger, update trigger, override standalone triggers)
- PnL value should be calculated from CM add trigger event
> Total cost of Constant Multiple and PnL

- helpers/multiply/calculations.ts
- fixed calculations regarding Operating cost in CM and PnL, if there are events with same hash gas fee is common for them and before this fix we were cumulating them
- try to for example update CM and pay attention to Operating cost before and after this action.
> Operating cost and PnL calculations fix

- blockchain/config.ts
- added address regarding automationBotAggregator to blockchain config (mainnet)
- when cache will be updated as well it can be tested by trying to add CM trigger
> Updated automationBotAggregator mainnet address

- features/automation/optimization/controls/BasicBuyDetailsLayout.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/protection/controls/BasicSellDetailsControl.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/sidebars/SidebarAutomationFeatureCreationStage.tsx
- added missing KB links to auto buy and sell features
- check whether links to KB in auto buy and sell features are updated (banners / sidebar when creating / removing / updating)
> Added missing KB links to auto buy and sell features

- components/vault/VaultWarnings.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsLayout.tsx
- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/sidebars/SidebarAutomationFeatureCreationStage.tsx
- updated Contant Multiple KB links
- check whether link within CM banned and other links in CM sidebar are correct
> Constant Multiple KB links updated

- helpers/useFeatureToggle.ts
- Constant Multiple feature toggle set to true as default
- clear your localStorage and check whether CM will be enabled on UI
> Constant Multiple feature toggle set to true

- helpers/useFeatureToggle.ts
> cm turned off

- features/careers/listings/community-manager.mdx
- item 1
Check if Community role appears in right order, if it's properly formatted and has no grammar mistakes or typos.
> Added Community Manager role

- features/automation/protection/controls/StopLossTriggeredFormControl.tsx
- features/automation/protection/controls/StopLossTriggeredFormLayout.tsx
Slippage removed from SL executed screen 
- item 1
- step 1 ...
> removed slippage from sl executed screen as it's unknown

- components/dumb/PickCloseState.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/openFlow/openVaultStopLoss.ts
- added reset button to stop loss form
- all reset buttons in automation features are only visible when user edited something
- test reset button in automation forms
> Auto features reset button

- pages/api/user/create.tsx
- server/database/migrations/009-referral-changes.sql
- server/database/schema.prisma
modification of existing tables
```
ALTER TABLE public.merkle_tree
ADD COLUMN start_block decimal(78, 0);
ALTER TABLE public.merkle_tree
ADD COLUMN end_block decimal(78, 0);
ALTER TABLE public.user
RENAME COLUMN "createdAt" TO timestamp;
ALTER TABLE public.user DROP COLUMN total_amount;
ALTER TABLE public.merkle_tree
ADD COLUMN timestamp TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.weekly_claim
ADD COLUMN timestamp TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE public.merkle_tree
ADD COLUMN snapshot text;
```
- change in referral user creation - no need to provide the timestamp, it's added by default
- the `total_amount` column has been depreciated
- 
test if it doesn't break anything
> Automate the weekly referral data creation step - Borrow database refinement and testing

- package.json
- yarn.lock
> Bump @oasisdex/oasis-actions to ^0.0.4

- package.json
- yarn.lock
> Bump @oasisdex/automation from 1.1.10 to 1.1.11

- server/services/getOasisStats.ts
> Fix homepage stats

- features/careers/listings/community-manager.mdx
Request from Maria
- Updated the role in the description from part-time to full time
- see if the file still contains references to part-time
> updated community manager to full-time

- public/locales/cn/common.json
- Updated the Chinese translations
- Change the language to Chinese and go around in the application
> Update the chinese translations

- features/termsOfService/jwt.ts
- handlers/signature-auth/signin.ts
- package.json
- yarn.lock
> Gnosis Signing (#1415)

- package.json
- yarn.lock
> updated common

- package.json
- yarn.lock
> new package version

- features/automation/protection/openFlow/openVaultStopLoss.ts
- fixed issue with execution price calculations in open vault / open multiply stop loss flow
- try to open borrow and multiply vault with stop loss setup
> Stop loss open flow execution price calc fixed

- components/AutomationContextProvider.tsx
- components/vault/GeneralManageControl.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/OptimizationControl.tsx
- components/vault/ProtectionControl.tsx
- components/vault/commonMultiply/ManageMultiplyVaultContainer.tsx
- components/vault/detailsCards/VaultDetailsCardLiquidationPrice.tsx
- components/vault/detailsSection/ContentCardLiquidationPrice.tsx
- components/vault/stories/VaultDetailsCard.stories.tsx
- features/automation/common/basicBSTriggerData.ts
- features/automation/optimization/common/constantMultipleTriggerData.ts
- features/automation/optimization/controls/OptimizationDetailsControl.tsx
- features/automation/optimization/controls/OptimizationFormControl.tsx
- features/automation/protection/controls/GetProtectionBannerControl.tsx
- features/automation/protection/controls/ProtectionDetailsControl.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/StopLossBannerControl.tsx
- features/automation/protection/triggers/AutomationTriggersData.ts
- features/automation/protection/useBasicSellStateInitializator.ts
- features/automation/protection/useConstantMultipleStateInitialization.ts
- features/automation/protection/useStopLossStateInitializator.ts
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
- created automation context provider which is used on the top level of mange vault view. 
- automation context provider contains decoded triggers data per each automation feature so its calculated only once not many times in different places as before
- do round of adding / updating / removing auto triggers, everything should work as intended as this PR is purely about refactor
> Automation context provider

- components/vault/detailsSection/ContentCardLiquidationPrice.tsx
- fixed issue with automation context within liquidation price detail card
- try to open multiply / borrow vault and see if error about automation context occur
> Liquidation price detail card fix

- features/termsOfService/jwt.ts
- handlers/signature-auth/challenge.ts
- handlers/signature-auth/signin.ts
- package.json
- yarn.lock
- synced hotfixes from main to dev
- app shouldn't brake
> Sync hotfixes from main to dev

- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
Check if formatting is like mentioned in comment here https://app.shortcut.com/oazo-apps/story/5935/when-sl-is-close-to-max-ab-as-show-up-with-illegal-values-by-default#activity-5966
- item 1
Check if formattings of sl-too high and c-ratio too high messages are correct.
> fixed message formatting

- public/locales/en/common.json
Fixes a comma in translations.
> FIX: Translations

- features/careers/listings/developer-advocate.mdx
The developer Advocate role had the wrong email address
> update email for developer advocate

- .mocharc.js
- locales.test.ts
- Added tests to validate locale files.
Run `yarn test` with proper JSON locale and with broken one. Refer to image below (first is proper JSON locale and the second one has missing comma).
> Added locale testing

- .github/workflows/aws-prod.yaml
- .github/workflows/aws-staging.yaml
Fixes the env (not a secret) done in https://github.com/OasisDEX/oasis-borrow/pull/1456
Look https://github.com/OasisDEX/oasis-borrow/pull/1449
> Changed secrets.APP_FULL_DOMAIN to env.APP_FULL_DOMAIN in the aws config

- features/automation/protection/stopLoss/controls/GetProtectionBannerControl.tsx
- features/automation/protection/stopLoss/controls/StopLossDetailsControl.tsx
- public/locales/en/common.json
- updated automation features banners titles and copy,
- removed distinction in overview tab on protection banner whenever autoBS feature flag is on or off.
Compare banner content on site with copy from shortcut story.
> Update Automation Banner Copy

- public/locales/cn/common.json
> updated Chinese language file

- .github/workflows/aws-prod.yaml
- .github/workflows/aws-staging.yaml
- adjusted notification env variables to be defined separatly per staging / prod
- correct notification host on staging and prod
> Notification host per env

- components/NotificationSocketProvider.tsx
- set up transports explicitly in socket io config
- notifications should work on staging
> Hardcoded socket io transports

- helpers/useFeatureToggle.ts
> re-enable proxy creation

- features/automation/common/consts.ts
- features/automation/common/sidebars/SidebarAutomationFeatureCreationStage.tsx
- features/automation/common/sidebars/getAutoFeaturesSidebarDropdown.ts
- features/automation/common/sidebars/getAutomationFormTitle.ts
- features/automation/common/sidebars/getAutomationPrimaryButtonLabel.ts
- features/automation/common/sidebars/getAutomationStatusTitle.ts
- features/automation/common/state/automationFeatureChange.ts
- features/automation/common/types.ts
- features/automation/optimization/autoBuy/controls/AutoBuyDetailsLayout.tsx
- features/automation/optimization/autoBuy/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/optimization/autoBuy/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitDetailsLayout.tsx
- features/automation/optimization/common/controls/OptimizationFormControl.tsx
- features/automation/optimization/common/helpers.ts
- features/automation/optimization/constantMultiple/controls/ConstantMultipleDetailsLayout.tsx
- features/automation/optimization/constantMultiple/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/optimization/constantMultiple/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/protection/autoSell/controls/AutoSellDetailsLayout.tsx
- features/automation/protection/autoSell/sidebars/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/autoSell/sidebars/SidebarSetupAutoSell.tsx
- features/automation/protection/common/controls/ProtectionFormControl.tsx
- features/automation/protection/common/helpers.ts
- features/automation/protection/stopLoss/controls/StopLossDetailsControl.tsx
- features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
- features/notifications/handlers.ts
- public/locales/en/common.json
- adjusted automation features enum so we can reuse it in many places
- all auto features should work as usually (search for potential issues with copies inside sidebar or state management when switching features using dropdown)
> Adjusted automation features enum

- features/notifications/helpers.tsx
- features/notifications/types.ts
- changed `nextPrice` to `usdPrice`
- price should be visible in notifications
> Adjusted notifications additional data property name again

- public/locales/cn/common.json
Hazel updated the chinese translations
> updating chinese keys

- features/earn/aave/AaveContext.ts
- features/earn/aave/open/components/AaveOpenHeader.tsx
- fixes typings
- expect zero errors
> Type fixes for aave steth/eth product header

- components/Toggle.tsx
- components/notifications/NotificationCard.tsx
- components/notifications/NotificationPreferenceCard.tsx
- components/notifications/NotificationsCenter.tsx
- components/notifications/NotificationsCenterContent.tsx
- components/notifications/NotificationsCenterHeader.tsx
- components/notifications/NotificationsIconButton.tsx
- components/notifications/NotificationsPrefrenceCardWrapper.tsx
- Some general look & feel fixes in notifications UI,
- updated some animations for notifications panel and toggle in settings,
- polished styling to be more accurate to figma designs.
> Notification UI improvements

- features/automation/common/controls/AddAndRemoveTriggerControl.tsx
> any is not allowed anymore

- helpers/useFeatureToggle.ts
🚀🚀🚀
Set `Notifications` feature flag to `true` by default.
Check out if notifications panel is visible even if `Notifications` feature flag is set to `false`.
> Enable notifications

- handlers/risk/get.ts
> improved logging of TRM sanctioned responses

- handlers/risk/get.ts
> Fix /handlers/risk/get.ts prettier error

- blockchain/calls/aave/aaveLendingPool.ts
- blockchain/calls/aave/aaveProtocolDataProvider.ts
- blockchain/config.ts
- features/aave/index.ts
- features/earn/aave/AaveContext.ts
- features/earn/aave/manage/services/getClosePositionParametersStateMachine.ts
- features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
- features/earn/aave/manage/services/getManageAaveStateMachine.ts
- features/earn/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/earn/aave/manage/state/closePositionParametersStateMachine.ts
- features/earn/aave/manage/state/manageAaveStateMachine.ts
- runtime.config.js
- Newest library
- Transaction with closing position
> AAVE: Closing position

- helpers/api/tokenTickers.ts
- server/services/coinPaprika.ts
Only one batch request to coinpaprika instead of requesting each token separately
> one batch request to coinpaprika

- features/earn/aave/open/services/stEthYield.ts
- schema.graphql
- changed the query responsible for yields in AAVE
- no UI changes
- data in AAVE product card and product header should load faster
> Change AAVE yields query

- features/earn/aave/open/services/stEthYield.ts
> fixes the yield query name

- features/careers/listings/developer-advocate.mdx
- features/careers/listings/full-stack-developer.mdx
- features/careers/listings/product-marketing-manager.mdx
- features/careers/listings/smart-contract-developer.mdx
- Added new about text to roles
- Added new Product Marketing Manager role
> add new product manage position to carers page.

- features/notices/VaultsNoticesView.tsx
> Vault notices locale fix

- features/earn/aave/common/components/informationContainer/OutstandingDebtInformation.tsx
- features/earn/aave/manage/sidebars/SidebarManageAaveVault.tsx
- package.json
- yarn.lock
- Current debt on manage page is now correct value.
- Only showing ETH getting from position close.
> Order Information Fixes

- package.json
- yarn.lock
Update of common package that allows to test Auto Take Profit on mainnet
> Auto Take Profit on mainnet

- public/locales/en/common.json
Minor copy changes for stETH 
- removed Maker in the proxy creation
- Updated knowledge centre to Knowledge base
- Updated the validation message
- step 1 ...
> Minor copy changes

- components/vault/VaultWarnings.tsx
- features/automation/common/sidebars/SidebarAutomationFeatureCreationStage.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitDetailsLayout.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
- public/locales/en/common.json
- updated take profit links with correct urls
- added description in take profit form (below close to buttons)
- verify if all links in scope of take profit have correct urls
> Take profit links update

- features/content/faqs/aave/en.mdx
- helpers/productCards.ts
- Updated AAVE KB links
- Updated AAVE KB links on product card and in faq tab on open view
> Update AAVE KB links

- features/earn/aave/manage/services/getManageAavePositionStateMachineServices.ts
- features/earn/aave/manage/state/manageAaveStateMachine.ts
- package.json
- yarn.lock
Moves to observable to do gas estimation in a separate async.  Updates the UI with all the values before doing gas estimation.
> Improve performance when adjusting positon

- features/aave/index.ts
- features/earn/aave/open/services/getParametersStateMachineServices.ts
> changed ETH address and add proper name to gas estimation.

- analytics/analytics.ts
- components/Header.tsx
- components/NotificationSocketProvider.tsx
- components/notifications/NotificationCard.tsx
- components/notifications/NotificationCardsWrapper.tsx
- components/notifications/NotificationsCenter.tsx
- components/notifications/NotificationsCenterContent.tsx
- components/notifications/NotificationsIconButton.tsx
- components/notifications/NotificationsPrefrenceCardWrapper.tsx
- features/notifications/types.ts
- helpers/functions.ts
- added analytics to notification events
- if tested locally events will be displayed in console, verify it with spreadsheet from story
> Notifications analytics

- helpers/useFeatureToggle.ts
- package.json
- yarn.lock
enabled atp, updated common  
- item 1
- step 1 ...
> enabled atp, updated common

- package.json
- yarn.lock
> updated common to 1.2.3

- features/earn/aave/components/PositionInfoComponent.tsx
- fixes mixed up labels on viewing position
> Fixes aave position labels

- features/automation/api/automationTxHandlers.ts
- changed `send` to `sendWithGasEstimation` in remove trigger method
- remove previously added trigger
> Trigger removal method switch

- components/DomainBanner.tsx
- features/homepage/HomepageView.tsx
> Add button to domain landing page to home page

- helpers/useFeatureToggle.ts
> added follow vaults flag

- features/aave/common/components/informationContainer/TransactionTokenAmount.tsx
- features/aave/manage/services/getAaveProtocolData.ts
- features/earn/aave/components/PositionInfoComponent.tsx
- package.json
- yarn.lock
- shows `selling` when the user is selling eth
- fixes collateral amount in the position info page
To test:
- ensure that buying steth when opening position
- ensure that selling when reducing risk, buying when increasing risk
- ensure that selling when closing
Related PR: https://github.com/OasisDEX/oasis-earn-sc/pull/116
> fix selling steth bug

- handlers/discover/helpers.ts
> FIX - fix coll ratio in discovery

- features/discover/common/DiscoverError.tsx
- features/discover/common/DiscoverTableDataCellContent.tsx
- features/discover/filters.ts
- handlers/discover/getDiscoveryData.tsx
- handlers/discover/helpers.ts
- public/locales/en/common.json
Follows list from https://www.notion.so/oazo/Discover-Oasis-app-55d4f52280c242ca9d2182f97f51db0a?d=0d8568d261424056b1f5de8576ee8d01#a48be511c4cb4894800215b5d5b646e5.
- Changed API unknown error message and message color,
- position buttons now opens in new tab,
- added "All" options to multiple and vault size filters,
- added sorting to "Largest Debt".
> 🧭 Discover bugfixes and refinements

- handlers/discover/getDiscoveryData.tsx
- handlers/discover/helpers.ts
> FIX - Add decimals to discover values

- handlers/discover/getDiscoveryData.tsx
> FIX - Discover improvements

- components/GenericSelect.tsx
- components/Tooltip.tsx
- components/vault/DefaultVaultHeadline.tsx
- components/vault/VaultChangesInformation.tsx
- components/vault/VaultHeader.tsx
- components/vault/VaultHeaderContainer.tsx
- components/vault/VaultHeadlineDetails.tsx
- helpers/isTouchDevice.ts
- public/locales/en/common.json
- added current/next token price on opening maker positions
- go to any maker vault opening page
- there should be current/next token price in the header
> Add Oracle prices to opening of Maker positions

- blockchain/tokensMetadata.ts
- components/productCards/ProductCardsContainer.tsx
- features/aave/common/StrategyConfigTypes.ts
- features/aave/strategyConfig.ts
> fixes aave product card list

- server/database/migrations/014-update-liquidation-proximity.sql
- item 1
migrate the database - check the difference
> FEAT - change liquidation proximity calc

- handlers/discover/helpers.ts
- item 1
- go to Discover
- check the SL distance
- open vault and calc by hand `( current price - dynamic SL price) / current price`
> FEAT - Change Discover SL calc

- public/locales/en/common.json
- Updated intro text in hero,
- updated "Largest Debt" banner description.
> 🧭 Final (hopefully) update to Discover copy 

- components/AutomationContextProvider.tsx
- features/automation/contexts/AutomationContextInput.tsx
- fixed issue with guni vault overview
- using localhost go to vault 27849
> Auto context guni issue

- features/discover/common/DiscoverTableDataCellContent.tsx
- handlers/discover/getDiscoveryData.tsx
- server/database/migrations/015-discover-new-columns.sql
- server/database/schema.prisma
> FEAT - decouple pnl and net earning

- features/discover/common/DiscoverWrapperWithIntro.tsx
- Updated link to Knowledge Base in Discover intro.
> 🧭 Discover Knowledge Base link

- server/database/migrations/016-update-discover.sql
```diff
- "vault_collateral" * "current_price" AS "liquidation_value",
+ ("vault_normalized_debt" * "rate") * "liquidation_penalty" AS "liquidation_value",
```
- step 1 ...
> FIX - Update high risk table

- components/dumb/PickCloseState.tsx
- features/automation/common/consts.ts
- features/automation/metadata/aave/stopLossMetadata.ts
- features/automation/metadata/maker/stopLossMetadata.ts
- features/automation/metadata/types.ts
- features/automation/optimization/autoTakeProfit/state/autoTakeProfitStatus.ts
- features/automation/protection/stopLoss/controls/StopLossCompleteInformation.tsx
- features/automation/protection/stopLoss/controls/StopLossDetailsControl.tsx
- features/automation/protection/stopLoss/openFlow/openVaultStopLoss.ts
- features/automation/protection/stopLoss/sidebars/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
- Updated metadata type structure.
> Automation metadata refinements

- features/follow/common/FollowButton.tsx
- Minor css changes that helps button to be more in line with figma.
> Follow button css refinements

- features/aave/AaveContext.ts
> Fixes an issue with too many calls for getAssetsPrices

- features/multiply/aave/components/AaveMultiplyHeader.tsx
> aave header fix 2

- components/AutomationContextProvider.tsx
- features/automation/metadata/aave/stopLossMetadata.ts
- features/automation/metadata/helpers.ts
- features/automation/metadata/maker/autoBSMetadata.ts
- features/automation/metadata/maker/autoTakeProfitMetadata.ts
- features/automation/metadata/maker/constantMultipleMetadata.ts
- features/automation/metadata/maker/stopLossMetadata.ts
- features/automation/metadata/maker/takeProfitMetadata.ts
- features/automation/metadata/types.ts
- features/automation/protection/stopLoss/controls/StopLossCompleteInformation.tsx
- features/automation/protection/stopLoss/controls/StopLossDetailsControl.tsx
- features/automation/protection/stopLoss/controls/StopLossFormControl.tsx
- features/automation/protection/stopLoss/openFlow/openVaultStopLoss.ts
- features/automation/protection/stopLoss/sidebars/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
- features/automation/protection/stopLoss/state/useStopLossStateInitialization.ts
Covers partialy:
https://app.shortcut.com/oazo-apps/story/6904/metadata-for-automation-structure-refinements
https://app.shortcut.com/oazo-apps/story/6905/metadata-for-automation-common-interface-for-all-features
- Minor and major changes to automation metadata interface structure,
- split interface into nested categories,
- merged common interfaces into single type with generic,
- etc.
See if it even works anymore 😶
> Nested interface structure for metadata

- features/automation/contexts/MakerAutomationContext.tsx
- fixed typo in interface name
- nothing to test here
> Changed maker automation interface name

- features/content/faqs/guni/en.mdx
Update the fee to the actual fee
> Fix fee copy

- blockchain/calls/operationExecutor.ts
- features/aave/common/BaseAaveContext.ts
- features/aave/common/components/informationContainer/LtvInformation.tsx
- features/aave/common/components/informationContainer/MultiplyInformation.tsx
- features/aave/common/components/informationContainer/PriceImpact.tsx
- features/aave/common/components/informationContainer/StrategyInformationContainer.tsx
- features/aave/common/components/informationContainer/TransactionTokenAmount.tsx
- features/aave/helpers/getStrategyConfig.ts
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/oasisActionsLibWrapper.ts
- features/aave/open/state/openAaveStateMachine.ts
- features/earn/aave/components/SimulateSectionComponent.tsx
- features/multiply/aave/components/AaveMultiplyPositionData.tsx
- features/shared/liquidationPrice.ts
- features/stateMachines/transactionParameters/transactionParametersStateMachine.stories.tsx
- features/stateMachines/transactionParameters/transactionParametersStateMachine.ts
- package.json
- yarn.lock
- Revert library to last working version on production
- Revert the address of the operation executor.
> [SC-7015] Working transaction AAVE Earn

- components/productCards/ProductCard.tsx
> Removed the protocol in brackets

- components/connectWallet/ConnectWallet.tsx
- features/aave/helpers/useAaveRedirect.ts
- helpers/getCustomNetworkParameter.ts
- added preserving network parameter on connecting wallet
- go to `/connect?network=hardhat`, connect your wallet
- the `network=hardhat` parameter should stay where it was
> Added preserving network parameter on connecting wallet

- pages/api/rpc.tsx
Adds loging to RPC endpoint in order to understand what happens on a server.
> add logging

- blockchain/tokensMetadata.ts
- changed ticker of RETH token
- ticker should return correct market price of rocket pool eth
> Change RETH ticker

- components/AppContext.ts
use the `lean` data source to get data once instead of each block
- step 1 ...
> FIX - Oracle page rpc calls

- pages/api/rpc.tsx
> Add caching to rpc

- pages/api/rpc.tsx
> FIX - add total calls

- pages/api/rpc.tsx
> FIX - tryAggregate filter

- pages/api/rpc.tsx
> FIX - fix chainId call on each rpc call

- features/dsr/containers/DsrView.tsx
- features/dsr/containers/DsrViewContainer.tsx
- helpers/useFeatureToggle.ts
- `DaiSavingsRate` feature flag has been set to `true` as default
- DSR should be available on UI without playing with feature toggles
> Set DaiSavingsRate feature toggle to true

- features/aave/helpers/getStrategyConfig.ts
> Missing Strategies

- features/dsr/helpers/dsrHistory.ts
Use data fetch from cache instead of raw bc calls - to save on rpc calls.
- instead of directly calling the bc with `context.web3.eth.getBlock(blockNumber)`
the graphQl endpoint is queried to get the given blocks timestamp
```graphql
query timestamp(
$blockNumber: Number
) {
allHistoricBlocks(
first: 1
filter: { id: { equalTo: $blockNumber } }
) {
nodes {
timestamp
}
}
}
```
```ts
async function getBlockTimestamp(context: Context, blockNumber: number): Promise<number> {
const apiClient = new GraphQLClient(context.cacheApi)
const block = await apiClient.request(historicalBlockNumbers, {
blockNumber,
})
return new Date(block.allHistoricBlocks.nodes[0].timestamp).getTime() / 1000
}
``` 
go to dsr subpage anch check dates on historical events
> FEAT - use cache instead of raw bc call

- components/AppContext.ts
- features/account/AccountData.ts
- features/vaultsOverview/pipes/positions.ts
- added number of dpm positions to total count of user positions in header
- add positions through dpm, check number of positions in header
> Display number of DPM positions in header

- features/aave/oasisActionsLibWrapper.ts
- package.json
- yarn.lock
> fix: update library consumption to use token not address

- .env
- server/services/coinPaprika.ts
> [SC-7285] Coinpaprika account

- features/aave/common/BaseAaveContext.ts
- features/aave/helpers/getTxTokenAndAmount.ts
- features/aave/manage/services/getManageAavePositionStateMachineServices.ts
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/open/services/getOpenAaveStateMachine.ts
- features/aave/open/state/openAaveStateMachine.stories.tsx
- features/aave/open/state/openAaveStateMachine.ts
- features/earn/aave/riskSliderConfig.tsx
- package.json
- yarn.lock
- Simplify amount and token transaction 
- Add balances for all strategy tokens
- Add max amount to manage debt and manage collateral.
> [SC-7003] Fix bugs in AAVE earn

- features/aave/helpers/getTxTokenAndAmount.ts
- fix for providing amount in the transaction
- try paying back debt in the steth/eth position
> Fixes for debt payback

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- Fixed button on closing steth/eth  
- close steth/eth position
- click on CTA button
- you should be on opening new steth/eth view
> Fixed button on closing steth/eth

- package.json
- yarn.lock
- New package (fix order information)
> [SC-7355] Update package to fix order information

- next.config.js
removed unsupported value from the config
> removed unsupported value from the config

- components/vault/detailsSection/ContentCardLtv.tsx
- features/multiply/aave/components/AaveMultiplyManageComponent.tsx
- features/multiply/aave/components/AaveMultiplyPositionData.tsx
- public/locales/en/common.json
- added tooltips to the Overview component on Aave multiply views
> feat: [sc-7177] Added missing tooltips for the Aave multiply

- features/aave/AaveContext.ts
- features/aave/manage/state/manageAaveStateMachine.ts
- Missing token balances
- After setting allowance request parameters from the library
> Request Parameters after allowance setting

- components/AppContext.ts
- features/aave/helpers/getStrategyConfig.ts
- features/aave/services/readPositionCreatedEvents.ts
- After closing, we show the correct manage view.
- to load strategy we are using the events from MPA.
> [SC-7395] Showing good position overview after closing the position.

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- Max borrow amount from `Buying Power` from overview
> [SC-7415] Max Borrow Amount

- public/locales/en/common.json
- updated product cards labels
- cross check the product cards with the design link in the story
> Update product cards labels

- features/aave/oasisActionsLibWrapper.ts
- We have some isssue with locked collateral amount. When we substact 1 wei it is working 🙉
> [SC-7368] Subtract 1 wei from locked amount

- features/homepage/HomepageView.tsx
- features/multiply/MultiplyView.tsx
> Updated Aave Multiply links

- helpers/useFeatureToggle.ts
- Visiblity of Multiply Cards using Aave
- New earn & multiply positon created with Aave will be using DPM Account
> [SC-7549] Release Oasis Multiply

- features/aave/common/BaseAaveContext.ts
- features/aave/manage/containers/AaveManageStateMachineContext.tsx
- features/aave/manage/containers/AaveManageView.tsx
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- public/locales/en/common.json
Changes made on call with Frank:
- Aave Multiply close position - dont show the position _change_ unless user chooses the token (debt or collateral)
> Fixes to close position view

- features/homepage/HomepageView.tsx
- features/multiply/MultiplyView.tsx
> Fix blog link

- public/locales/cn/common.json
- adds chinese DPM flow translations
- go through flow in chinese. observe the translations are present
> add cn dpm translations

- features/stateMachines/dpmAccount/CreateDPMAccountView.tsx
- features/stateMachines/dpmAccount/state/createDPMAccountStateMachine.ts
- public/locales/en/common.json
- We show a success view after creating DPM
- View adjusted to a design.
> [SC-7368] Show success view after creating DPM Account

- features/discover/common/DiscoverData.tsx
Not all parts of follow UI were hidden behind `FollowVaults` flag. This PR fixes that.
> Follow button on discover table

- components/productCards/ProductCardEarnAave.tsx
- components/productCards/ProductCardMultiplyAave.tsx
- next.config.js
- pages/aave/v2/[vault].tsx
- pages/aave/v3/[vault].tsx
- pages/borrow/[protocol]/[version]/open/[collateralToken].tsx
- pages/earn/[protocol]/[version]/open/[strategy].tsx
- pages/multiply/[protocol]/[version]/open/[strategy].tsx
> [SC-7718] Fix the urls for aave positions

- components/DetailsSectionFooterItem.tsx
- features/multiply/aave/components/AaveMultiplyPositionData.tsx
- Total exposure in collateral token
> [SC-7780] Wrong token in total exposure

- public/locales/en/common.json
> Change the copy on the front page

- components/HomePageBanner.tsx
> home ref banner width fix

- components/vault/VaultHeadline.tsx
- Added couple of CSS properties to make headline more flex like in design https://www.figma.com/file/XeMo7s0ZJgXgCHmOd588QY/Discover-Oasis-%235366?node-id=2904%3A16028&t=vGcRRXMM8TnPPiGp-0
- 
- Here's short video that tests multiple cases and all are fine IMHO
https://user-images.githubusercontent.com/6871923/216317831-f786001c-242a-428d-9dbd-0124cbb7a217.mp4
- This is longer version with more extreme trials, mobile issues found during this recording are fixed, but you can test it too, try think of even more unusual edge cases
https://user-images.githubusercontent.com/6871923/216317995-ab57c342-7cac-4557-9965-fbaa4ac0ecf3.mp4
> FLEX HEADLINE

- blockchain/calls/oasisActions.ts
- features/ajna/borrow/useAjnaTxHandler.ts
- package.json
- yarn.lock
- adjusted Ajna tx handling
- added handling for other actions
- currently not testable until we will have manage view
> Adjusted Ajna tx handling

- features/aave/services/readPositionCreatedEvents.ts
- open http://localhost:3000/owner/0x165d0df29d9262f8ee9e9874c906eab706a05c2c
- observe Aave DPM position not flickering in and out every few seconds
> fix flickering DPM positions position overview

- features/aave/common/services/getParametersMachines.ts
- features/aave/manage/containers/AaveManageTabBar.tsx
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/oasisActionsLibWrapper.ts
- package.json
- pages/api/tokensPrices.tsx
- yarn.lock
Story details: https://app.shortcut.com/oazo-apps/story/7925
> chore: [sc-7925] Add new Aave closing options

- components/AppContext.ts
- features/ajna/common/observables/getAjnaPosition.ts
- features/ajna/contexts/AjnaProductContext.tsx
- added onEveryBlock to ajna position observable
- when you modify position, position data should automatically refresh on new block
> 🧿 Ajna position data refresh

- actions/ajna/index.ts
- actions/ajna/oasisActionsLibWrapper.ts
- actions/ajna/types/index.ts
- features/ajna/borrow/useAjnaTxHandler.ts
Change in file structure per Jacob request
- move function responsible for switching between actions into the library wrapper as earn team with aave
- feature should work as expected
> 🧿 Ajna library wrapper

- blockchain/aave-v3/aaveV3PoolDataProvider.ts
- blockchain/aave/aaveV2ProtocolDataProvider.ts
- components/AppContext.ts
- components/vault/VaultHeadline.tsx
- features/aave/services/readPositionCreatedEvents.ts
- features/vaultsOverview/pipes/positions.ts
- Fixing owner page when displaying Aave V3 position
- `/owner/0x165d0df29d9262f8ee9e9874c906eab706a05c2c` - this has Aave V3 position
> Fixing owner page after adding a new position

- actions/ajna/oasisActionsLibWrapper.ts
- blockchain/config.ts
- components/Skeleton.tsx
- components/infoSection/Item.tsx
- components/vault/VaultChangesInformation.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentGenerate.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentManage.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentPayback.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentWithdraw.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormWrapper.tsx
- features/ajna/borrow/state/ajnaBorrowFormReducto.ts
- features/ajna/borrow/useAjnaTxHandler.ts
- features/ajna/common/observables/getAjnaPosition.ts
Fixed some major and minor bugs related to flow component and order information.
- Fixed issue where order information was shown with delay, only after initial data was loaded,
- fixed issue where primary button was disabled and put into loading state with a debounce,
- fixed issue with existing position where there was no dpm address provided for simulation,
- fixed issue with refreshing simulation data after rpm is created.
See if issue mentioned above no longer occur.
> 🧿 Ajna flow & order bugfixes

- features/aave/services/readPositionCreatedEvents.ts
- features/vaultsOverview/pipes/positions.ts
- lendingProtocols/LendingProtocol.ts
- added Ajna to lending protocols and therefore fixed issue when opening / managing ajna positions
- user should be able to open / manage ajna positions
- everything else related to aave should work as expected
> Add Ajna to lending protocols

- components/sidebar/SidebarSectionContent.tsx
Before:
https://user-images.githubusercontent.com/16230404/218486678-b134f771-9020-497d-be84-6c8074c2b1b1.mp4
After:
https://user-images.githubusercontent.com/16230404/218486643-0d17cdb7-7491-4ca9-b23e-0ff84fff3536.mp4
- Fixed an issue where for a moment whole sidebar was jumping when scroll was supposed to be shown.
Go to any form and see if layout shift still occurs.
> Fix jumping scroll in sidebar

- features/earn/aave/components/ViewPositionSectionComponent.tsx
> remove unnecesary value

- features/aave/manage/containers/AaveManageStateMachineContext.tsx
- features/aave/manage/services/aave-v2/getManageAaveV2PositionStateMachineServices.ts
- features/aave/manage/services/aave-v3/getManageAaveV3PositionStateMachineServices.ts
- features/earn/aave/riskSliderConfig.tsx
- Default LTV for new earn strategy: **75%**
> [SC-7988] Default risk ratio for wstETH/ETH strategy

- features/ajna/borrow/helpers.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContent.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormWrapper.tsx
- features/ajna/common/types.ts
- features/ajna/contexts/AjnaProductContext.tsx
- cleaned up conditions in sidebar by extracting it to separate methods and handlers
- app should work as usual
> Ajna sidebar props adjustment

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
> disable close to colalteral

- blockchain/utils.ts
- features/aave/common/BaseAaveContext.ts
- features/aave/common/components/informationContainer/PriceImpact.tsx
- features/aave/common/components/informationContainer/StrategyInformationContainer.tsx
- features/aave/common/components/informationContainer/TransactionTokenAmount.tsx
- features/earn/aave/components/ManageSectionComponent.tsx
- features/earn/aave/components/PositionInfoComponent.tsx
- features/earn/aave/components/ViewPositionSectionComponent.tsx
- APY from a position
- NET value in debt (for Earn is ETH)
- Liquidation price based on the exchange rate in the position
> [SC-8055] APY & Net value on manage page

- features/automation/protection/stopLoss/state/stopLossTriggerData.ts
- adjusted aave SL decimals after decoding
- once user add SL trigger on aave, correct values should be displayed in the SL form
> Aave SL decimals adjustment

- blockchain/aave-v3/aaveV3Pool.ts
- show liquidation bonus as a percentage on the slider
> show correct liquidation bonus on risk slider

- features/exchange/exchange.ts
- use default 1inch protocol list - list changed to `[]`
> [SC-8060] - use 1inch defaults

- features/aave/AaveContext.ts
- features/aave/SetupAaveV3Context.ts
- features/aave/services/getAaveSupportedTokenBalances.ts
- `TokenBalances` returns the price and 0 as the balance when the user is disconnected. 
- We probably need to change its name or split prices and balances into separate objects.
> [SC-7719] Blank page when simulating on disconnected page.

- components/HomePageBanner.tsx
- features/homepage/HomepageView.tsx
- public/locales/en/common.json
https://app.shortcut.com/oazo-apps/story/8081/aave-v3-update-marketing-banner
- replace URL and string, minor tweak to handle longer texts
> homepage banner aave v3

- components/HomePageBanner.tsx
- components/productCards/ProductCardEarnAave.tsx
- public/locales/en/common.json
Copy changes from the channel.
> wstETH copy changes

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- It's working for me with that change. I don't know why...
> [SC-8079] Closing do collateral

- components/AjnaEarnSlider.tsx
- components/dumb/SliderValuePicker.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentGenerate.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormFields.tsx
- features/ajna/borrow/state/ajnaBorrowFormReducto.ts
- features/ajna/common/components/AjnaFormFieldDeposit.tsx
- features/ajna/controls/AjnaFormWrapper.tsx
- features/ajna/controls/AjnaProductController.tsx
- features/ajna/earn/components/AjnaEarnSlider.tsx
- features/ajna/earn/overview/AjnaEarnOverviewWrapper.tsx
- features/ajna/earn/overview/ContentFooterItemsEarn.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContent.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContentDeposit.tsx
- features/ajna/earn/sidebars/AjnaEarnFormWrapper.tsx
- features/ajna/earn/views/AjnaEarnView.tsx
- public/locales/en/common.json
- added ajna earn ui skeleton
- added 3x sliders with different ranges to show how behavior in different scenarios
- use url for opening ajna position, you should see mocked overview section and form with sliders and input
- handling for input and slider, tx handling etc. are not in the scope of this PR
> 🧿 Ajna earn ui skeleton and slider

- features/multiply/aave/components/AaveMultiplyPositionData.tsx
- features/vaultHistory/vaultHistory.ts
- features/vaultHistory/vaultHistoryEvents.ts
-adjusted aave SL executed banner handling
- visit locally following position `aave/v2/71`, you should see SL executed banner
> Adjust aave SL executed banner handling

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/vaultsOverview/pipes/positions.ts
- helpers/getAaveStrategyUrl.ts
- link should now point to opening new position (correctly)
> Fixed links on closing Aave position view

- features/automation/protection/stopLoss/state/stopLossTriggerData.ts
- package.json
- yarn.lock
- package version update
- based on new version removed unnecessary param when creating trigger
- create / update / remove trigger on aave, everything should work without any issue
> Update automation lib, remove max gas fee param

- features/ajna/common/controls/AjnaProductController.tsx
- pages/ajna/[product]/index.tsx
- public/locales/en/common.json
Titles redone according to changes made this week by Marcin on entire page, excluding Ajna.
- Updated titles for pool selector, opening and position pages.
> 🧿 Ajna SEO appropriate titles

- .github/workflows/release.yaml
> Add node setup to release.yaml

- actions/ajna/index.ts
- actions/ajna/oasisActionsLibWrapper.ts
- actions/ajna/types/index.ts
- features/ajna/borrow/controls/AjnaBorrowFormController.tsx
- features/ajna/common/contexts/AjnaProductContext.tsx
- features/ajna/common/hooks/useAjnaTxHandler.ts
- features/ajna/common/observables/getAjnaPosition.ts
- features/ajna/common/sidebars/AjnaFormContentTransaction.tsx
- features/ajna/earn/components/AjnaEarnSlider.tsx
- features/ajna/earn/controls/AjnaEarnFormController.tsx
- features/ajna/earn/fakePosition.ts
- features/ajna/earn/sidebars/AjnaEarnFormContentAdjust.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContentDeposit.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContentOpen.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContentWithdraw.tsx
- package.json
- yarn.lock
- added dummy handling for ajna earn open, dummy because we still need to adjust used tokens
- all beside ajna earn should work as usual
> Ajna dummy earn open

- features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentGenerate.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentPayback.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentWithdraw.tsx
- features/ajna/common/helpers/getFlowStateConfig.ts
- features/ajna/common/sidebars/AjnaFormFields.tsx
- features/ajna/common/validation.ts
- features/ajna/earn/components/AjnaEarnSlider.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContentDeposit.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContentOpen.tsx
- features/ajna/earn/sidebars/AjnaEarnFormContentWithdraw.tsx
- public/locales/en/common.json
- added handling which maps quote or collateral token depends on ajna product
- ajna borrow should remain the same, in ajna open earn user should be able to deposit quote token and set allowance
> Ajna tokens handling per product

- pages/discover/[slug].tsx
- Added ToS and Risk verification to discovery page
- connect new wallet address on discovery page, you should be prompted to sing ToS and your address should be verified
> Add ToS and Risk to discovery page

- components/Header.tsx
- features/ajna/controls/AjnaNavigationController.tsx
> Hide uniswap widget

- handlers/subgraph/get.ts
- pages/api/subgraph/index.tsx
- added subgraph proxy template
- will be generalized in next iteration
- nothing to test right now
> Subgraph proxy

- features/content/faqs/dsr/en.mdx
> fix broken mdx

- .prettierignore
- components/Header.tsx
- components/LanguageSelect.tsx
- components/vault/VaultActionInput.tsx
- components/vault/VaultProxy.tsx
- components/vault/detailsCards/VaultDetailsCardLiquidationPrice.tsx
- components/vault/sidebar/SidebarVaultProxyStage.tsx
- features/ajna/positions/common/sidebars/AjnaFormContentRisk.tsx
- features/stateMachines/dpmAccount/CreateDPMAccountView.tsx
- features/stateMachines/proxy/ProxyView.tsx
- i18next.d.ts
Remake of https://github.com/OasisDEX/oasis-borrow/pull/1761 but less insane.
> TS module which suggests translation keys

- blockchain/config.ts
- updated ajna contracts to rc3
- try to open borrow / earn positon
> Ajna contracts rc3

- helpers/api/tokenTickers.ts
- helpers/types.ts
- server/services/coinbase.ts
- server/services/coingecko.ts
- Ensure resolved prices are matched to the correct ticker
- Ensure unresolved ticker prices do not throw errors
> Fix issue with out of sequence tickers and unresolved prices

- analytics/analytics.ts
add `currentUrl` to all mp events
- step 1 ...
> FIX - add currentUrl to mp events

- features/ajna/positions/common/components/AjnaValidationMessages.tsx
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/helpers/getFlowStateConfig.ts
- features/ajna/positions/common/views/AjnaFormView.tsx
- public/locales/en/common.json
https://app.shortcut.com/oazo-apps/story/8307/validation-position-not-earning-yield
https://app.shortcut.com/oazo-apps/story/8302/validation-slider-lower-limit
https://app.shortcut.com/oazo-apps/story/8300/validation-slider-upper-limit
- added handling to validations from library
In general to test you will need library part as well
- when user will try to go above momp should receive error
- when user will try to go below htp should receive warning
> Ajna earn partial validation handling

- actions/ajna/oasisActionsLibWrapper.ts
- blockchain/config.ts
- features/ajna/positions/common/components/AjnaValidationMessages.tsx
- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/helpers/getFlowStateConfig.ts
- features/ajna/positions/common/hooks/useAjnaTxHandler.ts
- features/ajna/positions/common/observables/getAjnaPosition.ts
- features/ajna/positions/common/views/AjnaFormView.tsx
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- features/ajna/positions/earn/helpers/getAjnaEarnData.ts
- features/ajna/positions/earn/helpers/getEarnDefaultPrice.ts
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentAdjust.tsx
- features/subgraphLoader/types.ts
- features/subgraphLoader/useSubgraphLoader.ts
- package.json
- public/locales/en/common.json
- yarn.lock
- adjusted `price` handling in ajna earn scope so we will use 18 decimals
- typescript improvements
- udpated library version
- try to open / adjust ajna earn position
> Ajna earn methods adjustment

- components/AppContext.ts
- features/earn/guni/manage/pipes/manageGuniVault.ts
- helpers/multiply/calculations.ts
- Default Slippage for GUNI -> 0.01%
- No specific protocols on 1inch calls with GUNI
>  [SC-8390] GUNI default slippage to 0.01%, no default protocols for swap

- components/AppContext.ts
- adjusted resolver of `ajnaPosition$` memoized observable
- when idling on risk form step, within within 10 minutes number of rpc calls should be below 500
> Fix issue with rpc calls on Ajna pages

- actions/ajna/oasisActionsLibWrapper.ts
- adjusted price decimals
- you should be able to open ajna borrow position
> Ajna borrow price fix

- blockchain/calls/operationExecutor.ts
- features/aave/open/containers/AaveOpenStateMachineContext.tsx
- features/stateMachines/transaction/transactionStateMachine.ts
Reverts OasisDEX/oasis-borrow#2156
> Revert "[SC-8391] Gnosis Safe Closing issue"

- .prettierignore
- actions/ajna/oasisActionsLibWrapper.ts
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/helpers/isFormEmpty.ts
- features/ajna/positions/common/hooks/useAjnaTxHandler.ts
- features/ajna/positions/common/notifications.ts
- features/ajna/positions/common/validation.ts
- features/ajna/positions/earn/helpers/areEarnPricesEqual.ts
- features/ajna/positions/earn/overview/AjnaEarnOverviewManage.tsx
- features/ajna/positions/earn/overview/ContentPositionLendingPrice.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentAdjust.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentDeposit.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentOpen.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentWithdraw.tsx
- package.json
- public/locales/en/common.json
- yarn.lock
- updated library version
- adjusted common methods
- replaced conditions with `isFormValid` flag
- used available data from `AjnaEarnPosition` in details section
- fixed issues with form default stan in earn view
- fixed issue with earn simulation
- fixed issue when simulation were done while form wasn't valid or was in `risk` step and therefore reduced number of unnecessary RPC calls
- test things according to what was changed
> Ajna earn and common issues resolved 

- theme/tokenIcons.tsx
Story details: https://app.shortcut.com/oazo-apps/story/7225
> chore: [sc-7225] Fix SVG warnings

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- On change risk on manage (Earn/Mutliply aave positions), the order information shows
> [SC-8323] Show order information on adjust risk on manage

- helpers/api/cacheObject.tsx
Relates to this https://discord.com/channels/837076147694207067/839088233353576468/1083456895542628444
> Remove .on expiry handler from cacheObject 

- actions/ajna/oasisActionsLibWrapper.ts
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/validation.ts
- features/ajna/positions/earn/sidebars/AjnaEarnFormOrder.tsx
- package.json
- yarn.lock
- updated lib version
- fixed earn payload
- adjusted validations
- user should be able to perform all actions in borrow and earn
> Ajna small logic adjustments

- package.json
- yarn.lock
- Updated actions poc library
- withdraw aciton in ajna form should eventually use correct precision
> Updated actions poc library

- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/helpers/getAjnaSidebarButtonsStatus.tsx
- features/ajna/positions/common/validation.ts
- features/ajna/positions/common/views/AjnaFormView.tsx
- fixed issue when error occurs and order informations are not displayed
- while error is active, order informations should be visible
> Ajna error state adjusted

- features/aave/common/services/getParametersMachines.ts
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/stateMachines/transactionParameters/transactionParametersStateMachine.ts
- package.json
- yarn.lock
- updated lib
- enabled close to collateral
- disabled library call when theres not enough parameters
- go do aave position
- try to close to collateral
> Update the lib version, enable close to collateral

- blockchain/aave-v3/aaveV3Liquidations.ts
- blockchain/aave/aaveV2Liquidations.ts
- blockchain/dpm/accountFactory.ts
- blockchain/dpm/accountGuard.ts
- blockchain/network.ts
- blockchain/networkIds.ts
- blockchain/userDpmProxies.ts
- components/NotificationSocketProvider.tsx
- features/automation/common/helpers.ts
- features/discover/common/DiscoverData.tsx
- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- features/subgraphLoader/useSubgraphLoader.ts
- features/vaultsOverview/pipes/positions.ts
- features/vaultsOverview/vaultsOverview.ts
- handlers/follow/follow.ts
- pages/api/subgraph.tsx
- fixed circular dependency
- app should work as usual
> Fix circular dependency

- public/locales/en/common.json
> updated subheader per request of Henry

- public/locales/en/common.json
removed unrealised + subheader to maria's suggestion
> removed unrealised + subheader to maria's suggestion

- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/termsOfService/termsAcceptance.ts
- features/web3Context/types.ts
- features/web3Context/web3_context.ts
- helpers/checkIfGnosisSafe.ts
- helpers/mocks/web3Context.mock.ts
- One function which checks if the user is connected with Gnosis
- Refactor code - in all places, we use one function.
> [SC-8520] Checing if connected wallet is Safe

- actions/ajna/oasisActionsLibWrapper.ts
- blockchain/abi/rewards-manager.json
- blockchain/config.ts
- features/ajna/positions/common/helpers/getAjnaPoolData.ts
- features/ajna/positions/common/observables/getAjnaPosition.ts
- features/ajna/positions/earn/overview/AjnaEarnOverviewManage.tsx
- features/subgraphLoader/consts.ts
- package.json
- yarn.lock
- added data with Ajna token rewards in oveview
- Ajna Token rewards in overview footer should display correct number (currently 0 for all positions)
> Ajna token rewards

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- patches/@oasisdex+oasis-actions+0.2.16.patch
Temporary patch for oasis-action to fix post swap fee amt returned when closing to collateral.
> FIX patch oasis-actions to fix swap fee amt on close to coll

- features/earn/guni/manage/pipes/guniActionsCalls.ts
- features/earn/guni/open/pipes/guniActionsCalls.ts
- changed `functions` to `methods` when we are calling methods on guni contract
- guni positions, for example 29929 should load correctly
> Use methods property guni

- features/earn/guni/manage/pipes/guniActionsCalls.ts
- features/earn/guni/open/pipes/guniActionsCalls.ts
- adjusted imports
- position from story should load correctly
> Guni calls type adjustment

- features/ajna/positions/earn/overview/AjnaEarnOverviewManage.tsx
- features/ajna/positions/earn/overview/ContentCardCurrentEarnings.tsx
- features/ajna/positions/earn/overview/ContentCardMaxLendingLTV.tsx
- features/ajna/positions/earn/overview/ContentCardTokensDeposited.tsx
- features/ajna/positions/earn/overview/ContentPositionLendingPrice.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormOrder.tsx
- public/locales/en/common.json
- added 4x modals to detail cards inside Ajna Earn overview section
- visit Ajna earn position, check whether modals with correct content are available
> Ajna earn overview modals

- package.json
- yarn.lock
Bump down the usehooks-ts version, cause the higher version caused incopatibility.
> Bump down the usehooks-ts version

- features/web3OnBoard/useBridgeConnector.tsx
- features/web3OnBoard/useWeb3OnBoardConnection.tsx
- helpers/networkIconMap.ts
Missing review fixes for: https://github.com/OasisDEX/oasis-borrow/pull/2179
> Review fixes: Switching networks header component

- features/ajna/common/controls/AjnaNavigationController.tsx
- added pick network orb to ajna header
- turn on pick network feature toggle and go to ajna landing page
> Ajna pick network orb

- features/aave/open/sidebars/SillyVideo.tsx
> fixes tomfoolery

- features/content/faqs/dsr/en.mdx
- fixed link import in dsr
- open FAQ tab in DSR view and see if error occur
> Fixed link import in dsr

- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/borrow/overview/ContentCardLiquidationPrice.tsx
- features/ajna/positions/common/helpers/getAjnaPoolData.ts
- features/subgraphLoader/consts.ts
- package.json
- yarn.lock
- Added `PendingInflator` to subgraph `getPool` method,
- displayed proper liquidation price on UI as current value and afterpill,
- fixed "below current price" prop.
> 🧿 Liquidation price on Borrow

- helpers/useTomfoolery.ts
> foolishness fix

- components/connectWallet/Connection.tsx
- features/web3OnBoard/useBridgeConnection.tsx
Current Staging: Can't do anything without a wallet connection.
> Fix not connected issue

- components/vault/detailsSection/ContentCardNetValue.tsx
- adjusted Net Value card in position overview so it uses tickers to get market price as default and values from quote and swap as fallback
- visit multiply position and check net value card (in modal current market price should be +/- in line with market price (due to caching))
> User tickers prices as default when calculating net value on UI

- components/connectWallet/Connection.tsx
- features/web3Context/types.ts
- features/web3Context/web3_context.ts
- features/web3OnBoard/useBridgeConnection.tsx
- features/web3OnBoard/useWeb3OnBoardConnection.tsx
- features/web3OnBoard/web3OnBoardConnectorProvider.tsx
- helpers/mocks/web3Context.mock.ts
- pages/_app.tsx
> 🐛  Wallet Connect 

- patches/@oasisdex+oasis-actions+0.2.16.patch
- restore previously removed patches
- step 1 ...
> Restore patches

- README.md
Story details: https://app.shortcut.com/oazo-apps/story/8767
> chore: [sc-8767] Fix the hardhat workflow

- package.json
- public/locales/en/common.json
- yarn.lock
https://app.shortcut.com/oazo-apps/story/8295/ajna-warning-handling-withdraw-collateral-resulting-in-ltv-within-5-of-max-ltv
https://app.shortcut.com/oazo-apps/story/8294/ajna-warning-handling-generate-debt-resulting-in-ltv-within-5-of-maximum-ltv
- added copies to handle new validations
- on borrow position try to push position ltv close to max ltv (must be withing 5%), check if validation is displayed (use generate and withdraw actions)
> Ajna borrow max ltv validations

- features/web3OnBoard/BridgeConnector.ts
- features/web3OnBoard/useBridgeConnector.tsx
Can't reconnect after disconnecting.
- Proper disconnecting using web3-OnBoard
- It also resolved bug disconnecting WalletConnet
> Proper disconnecting

- package.json
- yarn.lock
- updated lib version
- max generate in ajna borrow should cover all weird cases
> Ajna max generate lib update

- public/locales/en/common.json
- fixed validation param in ajna borrow form
- in ajna borrow, error message regarding dust limit should display number instead of `{{amount}}`
> Fixed validation param

- blockchain/abi/ajna-pool-info.json
- blockchain/abi/ajna-pool.json
- blockchain/abi/ajna-proxy-actions.json
- blockchain/abi/ajna-rewards-manager.json
- blockchain/contracts/goerli.ts
- blockchain/contracts/mainnet.ts
- package.json
- yarn.lock
- updated ajna addresses to rc4
- updated abis to the newest interfaces
- user should be able to perform all actions in scope of borrow and earn
> Ajna RC4 configuration

- features/ajna/common/components/AjnaPoolsTable.tsx
- features/ajna/common/content.ts
- features/ajna/common/controls/AjnaSelectorController.tsx
- features/ajna/common/helpers/filterPoolData.tsx
- features/ajna/common/types.ts
- features/ajna/positions/common/observables/getAjnaPoolsTableContent.ts
- features/discover/common/DiscoverTable.tsx
- public/locales/en/common.json
- Parsed pool data into Ajna Multiply pool selector,
- added missing translations.
Go to `/ajna/multiply`.
> 🧿 Ajna Multiply pool selector

- next.config.js
The main page was redirected to a page not found.
> :bug: Fix Maker Routing

- actions/ajna/types/index.ts
- features/ajna/common/types.ts
- features/ajna/positions/common/components/AjnaValidationMessages.tsx
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/sidebars/AjnaFormContentSummary.tsx
- features/ajna/positions/common/validation.tsx
- public/locales/en/common.json
- added handling for liquidations in borrow form (should work for multiply as well)
- refactored validations handling in the scope of ajna so it's possible to use components
- warnings messages should be displayed when position is during grace periond or is being in liquidation process (you will need to tweak flags in validations.tsx or ask Konrad to trigger liquidation on your position)
> Ajna borrowish form liquidation handling

- features/homepage/HomepageView.tsx
This fixes dev after a hotfix.
> Create a yields info banner for Aave [dev fix]

- features/homepage/HomepageView.tsx
Removes the https://github.com/OasisDEX/oasis-borrow/pull/2285
> Remove the announcement

- helpers/useLocalStorage.ts
Quick fix for default value with no isValid method passed.
> useLocalStorage fix

- components/ListWithIcon.tsx
- features/ajna/positions/common/sidebars/AjnaFormContentRisk.tsx
- helpers/applicationLinks.ts
- public/locales/en/common.json
Covers:
https://app.shortcut.com/oazo-apps/story/8947/borrow-ajna-disclaimer-copy
https://app.shortcut.com/oazo-apps/story/9033/earn-disclaimer-copy-change
- Updated copies separately in Borrow and Earn product (Lorem ipsum for Multiply),
- added `components` prop to `ListWithIcon` component to make it more versatile.
> 🧿 Update Ajna risk content

- features/ajna/common/components/AjnaRewardCard.tsx
- features/ajna/common/controls/AjnaRewardsController.tsx
- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/common/controls/AjnaTokensBannerController.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewController.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewOpenController.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- public/locales/en/common.json
https://app.shortcut.com/oazo-apps/story/9133/earn-change-earning-after-fees-titles
https://app.shortcut.com/oazo-apps/story/9137/typo-in-ajna-tokens-card
https://app.shortcut.com/oazo-apps/story/9154/earn-position-lending-price-copy-adjustment
https://app.shortcut.com/oazo-apps/story/9088/update-copy-in-the-this-positions-earns-ajna-tokens
https://app.shortcut.com/oazo-apps/story/9291/ajna-rewards-box-copy-update-box-needs-to-be-configurable-per-pool
https://app.shortcut.com/oazo-apps/story/8954/general-token-reward-box
https://app.shortcut.com/oazo-apps/story/9276/update-ajna-rewards-page-copy
- updated copies in bunch of different places according to tidy up stories
- suppressed ajna rewards in usd since it will …
> Tidy up tasks - copies update

- actions/aave/oasisActionsLibWrapper.ts
- blockchain/calls/proxyActions/proxyActions.ts
- blockchain/networksConfig.ts
- blockchain/userDpmProxies.ts
- components/vault/VaultForm.tsx
- features/aave/services/readPositionCreatedEvents.ts
- features/ajna/positions/common/hooks/useAjnaTxHandler.ts
- features/ajna/positions/common/observables/getAjnaPosition.ts
- features/borrow/open/sidebars/SidebarOpenBorrowVault.tsx
- features/earn/guni/open/sidebars/SidebarOpenGuniVault.tsx
- features/multiply/open/sidebars/SidebarOpenMultiplyVault.tsx
- features/vaultsOverview/parsers.tsx
- features/vaultsOverview/pipes/positions.ts
- helpers/get-rpc-provider.ts
- lendingProtocols/aave-v3/index.ts
- lendingProtocols/aave-v3/pipelines/get-on-chain-position.ts
- lendingProtocols/pipelines/observable-helpers.ts
- Proper links to maker positions
- Fix `readProvider` of undefined. 
- Removed unused component.
> :bug: openning maker positions

- actions/ajna/oasisActionsLibWrapper.ts
- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
- features/ajna/positions/multiply/components/ContentFooterItemsMultiply.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- package.json
- yarn.lock
- added handling for buying power
- fixed issue with slider on manage position view
- go to ajna open multiply / manage view and verify if buying power is calculated
> Ajna buying power

- blockchain/aave-v3/aaveV3Oracle.ts
- blockchain/aave-v3/aaveV3PoolDataProvider.ts
- blockchain/aave-v3/utils/index.ts
- blockchain/aave/aaveV2ProtocolDataProvider.ts
- features/aave/strategy-config.ts
- features/vaultsOverview/helpers.tsx
- lendingProtocols/aave-v2/pipelines/prepare-aave-total-value-locked.ts
- theme/tokenIcons.tsx
- coupla fixes, check the task
> 🐛 Staging Bugfixes

- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
- adjusted max ltv so it's calculated based on user max generate amount
- max slider value shouldn't change while changing slider value
> Ajna multiply max ltv adjustment

- package.json
- yarn.lock
- update of lib version which contain fixes for ajna max generate calculations and validations
- max generate should be equal to real max generate amount available per specific position and pool
- when trying to generate more than max generate error should appear with correct max generate amount
> Dma library bump 0.3.14

- blockchain/calls/ilkToToken.ts
> :bug: return ETH instead of WETH in ilkToToken$

- actions/ajna/oasisActionsLibWrapper.ts
- components/ListWithIcon.tsx
- components/Toggle.tsx
- features/ajna/common/consts.ts
- features/ajna/common/types.ts
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/common/contexts/AjnaGeneralContext.tsx
- features/ajna/positions/common/contexts/ajnaStepManager.ts
- features/ajna/positions/common/helpers/getAjnaSidebarButtonsStatus.tsx
- features/ajna/positions/common/helpers/getPrimaryButtonLabelKey.ts
- features/ajna/positions/common/helpers/isFormEmpty.ts
- features/ajna/positions/earn/controls/AjnaEarnFormController.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentNft.tsx
- features/ajna/positions/earn/state/ajnaEarnFormReducto.ts
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
- public/locales/en/common.json
- added nft step to ajna earn open flow where user can opt in/out from staking nft
- in ajna open flow verify whether new step works as expected as well as all transitions (go back to editing, when dpm & allowance is ready, when only dpm  is ready etc.)
- double check if manage earn flow remain untouched
> Ajna nft opt in/out

- pages/api/rpc.tsx
- We are checking if we have defined endpoints for L2 RPC; if not, we are using our Infura project.
> change rpc endpoints

- actions/ajna/oasisActionsLibWrapper.ts
- features/ajna/positions/common/components/contentCards/ContentCardNetValue.tsx
- features/ajna/positions/common/helpers/isFormEmpty.ts
- features/ajna/positions/common/validation.tsx
- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- package.json
- yarn.lock
- added handling for `adjust` method from library
- fixed issue with max slider value
- added handling for position net value
- position net value should be calculated based on position state
- `adjust` method should be used when increasing / decreasing risk
> Ajna adjust dummy method

- features/productHub/hooks/useProductHubData.ts
Small fix for useProductHubData re-render issue.
> useProductHubData re-render fix

- features/productHub/hooks/useProductHubData.ts
- features/productHub/views/ProductHubView.tsx
- handlers/product-hub/index.ts
- dummy data endpoint `/api/product-hub` now has promoCardsCollection and protocol types
> 🧬 Added PromoCardsCollection + protocol to handleProductHubData

- actions/ajna/oasisActionsLibWrapper.ts
- features/ajna/positions/common/helpers/isFormEmpty.ts
- features/ajna/positions/common/validation.tsx
- package.json
- yarn.lock
- added handling for ajna `close` multiply dummy method
- added handling for basic actions like generate, payback, withdraw and deposit while using multiply interface
- when user tries to close position, a correct order information should be displayed (except for few mocks)
- user should be able to use basic actions while in multiply view
> Ajna close dummy method

- actions/ajna/borrow.ts
- actions/ajna/earn.ts
- actions/ajna/multiply.ts
- actions/ajna/oasisActionsLibWrapper.ts
- package.json
- yarn.lock
- extracted methods responsible for blockchain calls to separate, dedicated files
- no regression expected
> Ajna call methods extraction

- actions/better-aave/oasisActionsLibWrapper.ts
- blockchain/better-calls/dpm-account.ts
- features/aave/common/services/getParametersMachines.ts
- features/aave/common/services/state-machines/get-open-multiply-aave-parameters-machine.ts
- features/aave/strategy-config.ts
- features/stateMachines/transactionParameters/transactionParametersStateMachine.ts
- helpers/swap.ts
- package.json
- yarn.lock
- 1inch call `v5.0` for L2 positions,
- update library 
- some changes which can help us with moving from web3 to ethers completely. 
- strategies name without optimism prefix.
> 🚧 Possibility to Open Aave v3 Position on Optimism.

- features/ajna/common/consts.ts
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- features/ajna/positions/earn/helpers/getEarnDefaultPrice.ts
- adjusted min max values for empty pools
- empty pool earn slider min value will be 0.5 of market price, max market price
> Ajna earn slider range adjust v2

- package.json
- yarn.lock
- updated dma-library version
- when trying to open position on fresh ajna pool there should be no information about fees
> Bump lib version 0.3.21

- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/earn/controls/AjnaEarnFormOrderInformation.tsx
- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- normalized ajna values to avoid showing infinity etc.
- ajna UI shouldn't contain values represented as `infinity`
> Normalize ajna values

- features/ajna/positions/borrow/components/ContentFooterItemsBorrow.tsx
- public/locales/en/common.json
https://app.shortcut.com/oazo-apps/story/9453/liquidation-price-tooltip-text-error
https://app.shortcut.com/oazo-apps/story/9448/dust-limit-text-needs-to-be-updated
https://app.shortcut.com/oazo-apps/story/8964/general-change-net-borrow-cost-to-borrow-rate
- updated few copies according to designs
- verify whether copies are in line with designs
> Ajna copies update

- components/vault/VaultHeadline.tsx
- features/ajna/positions/common/views/AjnaPositionView.tsx
- helpers/useFeatureToggle.ts
- when feature toggle enabled, click on heading in manage position will reveal underlying position proxy
- currently implemented only in the scope of ajna, enable feature toggle, visit ajna position, click on position heading and check if proxy is logged in console
> Proxy reveal

- features/ajna/positions/common/observables/getAjnaPosition.ts
- fixed ajna owner page positions
- positions ajna on owner page should work
> Fix ajna owner page positions

- features/ajna/positions/common/observables/getAjnaPosition.ts
- ajna position infinite loading fixed
- try to visit any ajna position
> Ajna position infinite loading fix

- .github/workflows/new-aws-staging.yaml
> GHA workflow for new domain

- features/ajna/positions/common/helpers/getAjnaPoolData.ts
- features/ajna/positions/common/helpers/getAjnaPoolsTableData.ts
Not the most verbosest, just a little verboser 🤡
> getAjnaPools throws verbose(st) errors

- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- public/locales/en/common.json
> Earn slider copy update

- features/ajna/common/components/AjnaHaveSomeQuestions.tsx
- features/ajna/common/components/AnjaFooter.tsx
- helpers/applicationLinks.ts
- public/locales/en/common.json
- updated styling, links and translations
> Ajna footer update

- features/ajna/positions/common/helpers/isYieldLoopPool.ts
- features/productHub/helpers/getActionUrl.ts
- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
- Updated Ajna Product Hub handler to parse Yield Loop type of products into Earn category.
Run PATH API and check if there are any Ajna Earn Yield Loop products.
> 🧬/🧿 Add yield loop products to Ajna product hub

- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/common/validation.tsx
- package.json
- public/locales/en/common.json
- yarn.lock
- origination fee is subtracted on UI from max generate value
- don't show warnings if error exist
- when user tries to generate max, after generate should be ~0
- warnings shouldn't be visible when error exist
> Ajna max generate origination fee subtraction on UI

- features/ajna/common/components/AjnaHaveSomeQuestions.tsx
- features/follow/common/ShareButton.tsx
- helpers/applicationLinks.ts
Revert the twitter handle change
> Revert the twitter handle change

- features/ajna/positions/common/contexts/AjnaGeneralContext.tsx
- features/ajna/positions/common/controls/AjnaProductController.tsx
- add slippage to ajna env context
- slippage value should be available in ajna env config and should update when user change it in settings
> Add slippage to ajna env context

- theme/index.tsx
- changed the font on Homepage Hero stats to FT Polar
> Change the font on Homepage Hero stats to FT Polar

- pages/api/rpc.tsx
> fix: rpc endpoint

- blockchain/better-calls/account-factory.ts
- blockchain/better-calls/dpm-account.ts
- blockchain/better-calls/utils/index.ts
- Set GasLimit on ethers Transactions. 
- Mutiplier 1.5
> Gas Multiplier for Optimism
