- features/openVault/tests/openVault.test.ts
Improving tests to cover following scenarios from Notion:
- `generate max`
- `back to editing` on failed proxy deploy
- `progress proxy` on success proxy deploy
- Select `unlimited allowance`
- Regress allowance
- Back to editing on allowance success
- Back to editing on open vault failure
- Back to editing on open vault success
> Improve open vault tests

- features/openVault/tests/openVault.test.ts
- package.json
Improving tests to cover following scenarios from Notion:
- Test validation of open vault - multiple branches
- Added script to omit uploading `codecov` report on local run
> Add tests for open vault validation messages

- features/manageVault/manageVaultAllowances.ts
- features/manageVault/tests/manageVault.test.ts
Improving tests to cover following scenarios from Notion:
- Generate | deposit | payback | withdraw max
- Test regress functions
- Test setting allowance
Removed `allowancesReset` as it wasn't used in any other file/interface
> Improve manage vault tests

- blockchain/calls/erc20.ts
<please insert a clubhouse link abowe>
- add `0` as precision to `toFixed()` call - issue was that without it casted BN was having decimal places
- open any of your existing vaults
- revoke daiAllowance in console, by typing 'dissaproveToken('DAI') and submitting transaction
- click Dai to and set Payback Amount to max, you should be asked to Set DAI Allowance
- set DAI Allowance to PaybackAmount - trigger tx
> Set Dai Allowanc for Payback Amount

- features/manageVault/manageVaultConditions.ts
- features/manageVault/manageVaultTransitions.ts
- features/manageVault/tests/manageVaultValidations.test.ts
<please insert a clubhouse link abowe>
- account for `debtOffset` in calculations for enough of `daiAllowance` for user
- add test scenario for setting values + input
- open any of your existing vaults
- revoke daiAllowance in console, by typing `'dissaproveToken('DAI')` and submitting transaction
- click `Dai` to and set `Payback Amount` to max, you should be asked to `Set DAI Allowance`
- set `Custom DAI Allowance` it will have to be bigger than `PaybackAmount` and `debtOffset`
> Account for debtOffset for insufficient dai allowance

- components/connectWallet/ConnectWallet.tsx
- features/account/Account.tsx
- features/termsOfService/TermsOfService.tsx
- remove `walletconnect` from Local Storage. It is injected by Wallet Connect library, upon disconnecting and connecting library was trying to restore connection to previous wallet without asking for QR prompt
- go to `/connect` scan Wallet Connect QR of your choice
- connect with wallet, then disconnect from Account Modal or ToS sign prompt
- try to connect again via QR with same or new wallet - it should show up it again, rather than reestablishing previous connection
> Fix wallet connect QR prompt on reconnecting

- analytics/analytics.ts
- components/Header.tsx
- features/manageVault/manageVaultAnalytics.ts
- features/openVault/OpenVaultButton.tsx
- features/openVault/openVaultAnalytics.ts
- fixed issue on staging, we had env set to `staging` and events were not sent but logged into console
- fixed issue, which already existed, with `PickAllowance` being sent every 10 sec, even if user haven't set allowance
- firstCDP had default value for boolean, even if we haven't yet fetched number of vaults. Agreed with Frank to sent `undefined` as a value in case we haven't yet fetched user's vaults
- fixed issue caused by adding `accountDetails$` at the top of `openVaultAnalytics` resulted in duplicated events being sent if user was in some state for more that 10 sec, as it was refetching numberOfVaults
- change occurences of `new BigNumber(0)` to `zero`
- step 1 ...
> Fix analytics bugs

- features/manageVault/ManageVaultErrors.tsx
- features/manageVault/manageVaultConditions.ts
- features/manageVault/manageVaultValidations.ts
- features/manageVault/stories/ManageVaultErrors.stories.tsx
- features/manageVault/tests/manageVaultValidations.test.ts
- public/locales/en/common.json
- Added new message with information about dust limit when user tries to deposit below it
- added new state which happens when user tries to deposit below dust limit
- added tests and modified also test for `it validates if generate doesn't exceeds debt ceiling, debt floor` because it started to fail as it had also condition for deposit-collateral-on-vault-under-debt-floor I added which was not scope of this test
- added story example to storybook
- Have a vault below the debt floor
- Try to add collateral without generating dai to get above the debt floor
- The UI will allow you to continue, while the transaction will get reverted
- [✔️ ] Unit tests written where needed and passing
- [ ✔️] End-to-end tests for happy path
- [ ✔️] Documentation updated <When applicable> (given the fact …
> Story 2256 inform user about dust limit when trying to deposit below it

- next.config.js
- pages/owner/[address]/index.tsx
- If one will enter url with /owner/$address and addres has incorrect checksum checksum will be corrected by app
- Everywhere in oasis.app address is passed with correct checksum butt this issue occurs when redirected from other apps to oasis or when sb pastes adress into browser with wrong checksum
Take any Ethereum address paste it into app url /owners endpoint for example:
https://staging.oasis.app/owner/0x81c8d249f2beEeAbdBd167b13aC94Ea2da4f4a61?network=kovan
https://localhost:3443/owner/0x81c8d249f2beEeAbdBd167b13aC94Ea2da4f4a61?network=kovan
Change some letters in addres from lowercase to upper case etc. to make incorrect checksum and it doesn't matter app will correct it out of box
> Fixed address if one paste url with addres with incorrect checksum

- features/manageMultiplyVault/manageMultiplyVaultConditions.ts
- features/manageMultiplyVault/manageMultiplyVaultForm.ts
- features/manageMultiplyVault/manageMultiplyVaultInput.ts
Fixes:
```
Reported issue: When adjusting position the value set in "adjust position" doesn't reset when changing to "other actions". 
```
- reset default values properly,
- rename const with defaults
- remove redundant resetting
- test in UI toggling between states
> Reset default states for inputs on toggling

- blockchain/calls/proxyActions.ts
When I try to create a Vault with 20,000 USD and 200% coll. ratio, I receive this error. But then, when I try to use a ETH value directly, it goes trough. It seems to be an error related to the ETH calculation when I use USD.
changed BigNumber formatting from `.toString()` to `toFixed(0)` to avoid any decimals after conversion.
Try opening new vault and enter amount in USD not in collateral (e.g. $50,000). New vault should be created
> Fix BigNumber decimals issue when opening new multiply vault

- components/Modal.tsx
- components/vault/VaultFormContainer.tsx
- features/account/Account.tsx
- features/openVaultOverview/SelectVaultTypeModal.tsx
https://www.notion.so/oazo/Multiply-MVP-tests-Feedback-bugs-2a776db8d0cf4acdb42717c96ccdf9d2#b0d8445e1ac34e2197147c5154cab5d2
The modal windows `MUST BE` closed:
- Clicking outside the modal container itself
- Pressing `ESC` button
- Clicking `close` button in the top right corner.
The modal windows `MUST NOT BE` closed:
- Click inside on any part of the modal itself.
Modals to test:
- `Error`
- `Account`
- `Selecting Vault Type`
- `Signing ToS`
> Close modal window only when you click outside of it and not inside.

- features/manageMultiplyVault/components/ManageMultiplyVaultButton.tsx
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
https://www.notion.so/oazo/Multiply-MVP-tests-Feedback-bugs-2a776db8d0cf4acdb42717c96ccdf9d2#9cc7609c2a2248938ed81fcd9bfbf0f7
My understanding of the expected version:
- `Adjust your position` label **MUST BE** only on existing multiply vaults.
- `Enter an amount` label **MUST BE** visible when the user creates new multiply vault
- `Enter an amount` label **MUST BE** visible when the user manages an existing multiply vault through `Other Actions` tab.
- `Enter an amount` label **MUST BE** visible when the user creates new  ordinary vault
- `Enter an amount` label **MUST BE** visible when the user manages an existing ordinary vault ( all operations )
> Change button label

- features/manageMultiplyVault/manageMultiplyVaultConditions.ts
- hide 1inch data only on relevant summary screens, not all of them
> Fix displaying 1inch data on summary screen

- blockchain/utils.ts
https://app.shortcut.com/oazo-apps/story/2686/precision-error-sets-a-vault-into-limited-mode-when-the-vault-is-not-under-the-dust-limit-this-breaks-current-standard-vaults
`rate` is of 'type' `RAY` which is `1e27` so
So let's say the current `ilk.rate` is `1064998962605983256332145468` which is `28 digits` long.
Now by `default` the `DECIMAL_PLACES` for `BigNumber` is `20`  - taken from the documentation  - https://mikemcl.github.io/bignumber.js/#decimal-places
If you check the code  where we fetch the needed information `ilk.rate` and `urn.art`  which is respectively in `vatUrns` and `varIlk` which is in the file `vat.ts` we use the utility functions `amountTFromRay` and `amountFromWei`.
When we parse the numbers for the rate used in this example we get the following value: …
> Increase DECIMAL_PLACES for RAY and RAD numbers

- analytics/analytics.ts
- components/AppContext.ts
- features/manageMultiplyVault/components/ManageMultiplyVaultView.tsx
- features/manageMultiplyVault/manageMultiplyVaultAnalytics.ts
- features/openMultiplyVault/components/OpenMultiplyVaultView.tsx
- features/openMultiplyVault/openMultiplyVaultAnalytics.ts
Spreadsheet with agreed events:
https://docs.google.com/spreadsheets/d/1Jie1SX_5i4-jDZLMKnCUkq4lhchkPKonIOVPNNJtsA8/edit#gid=149360134
- add events to track confirm and confirm transaction for opening and managing multiply vault
- toFixed(3) for `multiply` and `debt` are used to prevent resending multiple events if user eg left browser open for longer time. Those values are dynamic, small fluctuations of marketPrice or calling `drip` by someone were causing small differences at 5+ decimal places on those 2 values and events were resent as `distincUntilChange(isEqual)` wasn't applied due to those differences
- test in UI (hardhat) opening and managing multiply vault and see events in console on confirm button click and confirm tx in wallet
eg:
on confirm button click on Confirm screen:
on …
> Add multiply confirm button and transaction events

- features/exchange/exchange.ts
Before change it is possible to check whether the quote is defined and Typescript will allow us to read all properties even though they might be not there, e.g. in case of error
After the fix developer needs to check also the status of the quote in order to read it.
> Increase type safety 

- blockchain/config.ts
Removed GUNI config from hardhat to allow for hardhat staging/prod testing.
> Removed GUNI config from hardhat config

- features/manageVault/ManageVaultFormHeader.tsx
- features/openGuniVault/guniActionsCalls.ts
- GUNI vault is saved as multiple vault
- removed condition that causes that multiple button is not visible for guni in manage vault
- test using hardhat
> saving guni as multiply vault

- features/openGuniVault/openGuniMultiplyVaultTransactions.ts
- features/openGuniVault/openGuniVault.ts
- helpers/multiply/calculations.ts
Fee tier hotfix for Guni - use 0.04% for frontend calculations.
> Release 2.8.1 

- features/openGuniVault/openGuniVault.ts
Due to the failing open Guni vault transactions buffer is increased from `0.001` to `0.002`
> Increase calculation buffer for Guni

- components/vault/DefaultVaultLayout.tsx
- features/automation/common/enums/TriggersTypes.ts
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/AdjustSlFormLayout.tsx
- features/automation/controls/ProtectionFormControl.tsx
- features/automation/controls/ProtectionFormLayout.tsx
- pages/[vault]/index.tsx
- public/locales/en/common.json
- Added functionality to switch forms
- Go to protection tab 
- You should be able to switch between implemented adjust form and mocked cancel form (to be implemented in separate PR)
> Form switch

- features/manageGuniVault/manageGuniVault.ts
- features/openMultiplyVault/variants/guni/manage/GuniManageMultiplyVaultEditing.tsx
- features/openMultiplyVault/variants/guni/manage/GuniManageMultiplyVaultForm.tsx
- user has to click on close to dai button in order to see changes information
- heroku
> guni - close to dai click triggers form update

- helpers/useFeatureToggle.ts
- pages/borrow.tsx
- pages/multiply.tsx
- removes feature toggle and uses `AssetLandingPages` feature toggle
- AssetsLandingPages feature toggle enabled - expect to see borrow and multiply pages
- AssetsLandingPages feature toggle disabled - borrow doesn't display and redirects to /, multiply doesn't display
> removing feature toggle

- components/Header.tsx
- features/earn/EarnView.tsx
- features/multiply/MultiplyView.tsx
- helpers/productCards.ts
- helpers/useFeatureToggle.ts
- pages/earn.tsx
- sitemapGenerator.js
- added new /earn page
- new tab in menu
- tidied up mobile header a little
- 
1. enable feature `EarnPages`
2. observe Earn tab in menu bar (mobile & desktop; connected & disconnected)
3. Navigate to /earn page and observe GUNI card
4. Navigate to /multiply page and observe UNI LP filter not present.
1. disable feature `EarnPages`
2. observe missing Earn tab in menu bar (mobile & desktop; connected & disconnected)
3. Navigate to /earn page and observe redirect to /
4. Navigate to /multiply page and observe UNI LP filter is present and shows GUNI card
> Add /earn page behind feature toggle

- components/AppContext.ts
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/triggers/AutomationTriggersData.ts
- Protectred vault details can be viewed when vault owner is not connected
- Go to any protected vault for ex. 55 on goerli
- View it in incognito mode or when connected with another wallet which is not owner of this one
- See some details about this vault's stoploss etc
- also try for vault that don't have protection
- [x ] End-to-end tests for happy path
- [x ] Project builds without errors
- [ x] Non-functional requirements met
> added readonly view of protection for vaults

- components/Banner.tsx
This PR fixes issue with banners with long strings (hashes) on mobile  
- added wordBreak for Banner component
- heroku / locally, use `54?network=goerli`
> Added wordBreak for Banner component

- .github/workflows/aws-prod.yaml
- Adding `NODE_ENV=production` to `docker build`, for generating some of the static assets at build time instead of on-demand
> adding NODE_ENV as build arg for docker build

- components/vault/detailsCards/VaultDetailsCardMaxTokenOnStopLossTrigger.tsx
- components/vault/stories/VaultDetailsCard.stories.tsx
- features/automation/controls/AdjustSlFormControl.tsx
- features/automation/controls/AdjustSlFormLayout.tsx
- features/automation/controls/ProtectionDetailsControl.tsx
- features/automation/controls/ProtectionDetailsLayout.tsx
- added distinction between closing to dai and collateral on ui
- heroku / goerli
> Added distinction between closing to dai and collateral on ui

- components/AppContext.ts
- components/vault/VaultErrors.tsx
- features/automation/triggers/AutomationTriggersData.ts
- features/borrow/manage/pipes/manageVault.ts
- features/borrow/manage/pipes/manageVaultValidations.ts
- features/borrow/manage/pipes/viewStateProviders/standardBorrowManageVaultViewStateProvider.ts
- features/borrow/manage/pipes/viewStateTransforms/manageVaultConditions.ts
- features/borrow/manage/pipes/viewStateTransforms/manageVaultEnvironment.ts
- features/borrow/manage/tests/manageVaultValidations.test.ts
- features/form/commonValidators.ts
- features/form/errorMessagesHandler.ts
- features/multiply/manage/pipes/manageMultiplyVault.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultEnvironment.ts
- features/multiply/manage/pipes/manageMultiplyVaultValidations.ts
- features/multiply/manage/tests/manageMultiplyVaultAdjustPositionValidations.test.ts
- features/multiply/manage/tests/manageMultiplyVaultOtherActionsValidations.test.ts
- helpers/mocks/manageMultiplyVault.mock.ts
- helpers/mocks/manageVault.mock.ts
- helpers/mocks/stopLoss.mock.ts
- public/locales/en/common.json
- added stop loss validation to borrow and multiply flows
> added stop loss validation to borrow and  multiply vaults

- .github/workflows/aws-prod-rollback.yaml
CICD to allow Devs to roll production back to a previously released version.
This is a **manual** trigger job, and requires the user to input the short commit hash, of a previously released tag.
The docker image will then be re-tagged as **_latest_**, and deployed to prod.
This way dev's can deploy any release tag that they choose, and not disrupt normal workflows, as all deployed images will be tagged with **_:latest_** .
cc: @peculiarity
> Add rollback GHA

- .github/workflows/aws-prod-rollback.yaml
Workaround for GHA bug.
GHA only shows workflows from the "default" branch, which in this case is **dev**, so when the new GHA WF was merged to main branch, it did not show up in the Actions Tab.
Adding the new "rollback" workflow to DEV branch.
> Add GHA WF to dev branch

- features/careers/listings/full-stack-developer.mdx
- features/careers/listings/smart-contract-developer.mdx
- features/careers/listings/software-Engineer-in-test.mdx
- pages/careers/index.tsx
Two stories on one branch:
- https://app.shortcut.com/oazo-apps/story/3986/careers-add-software-engineer-in-test-job-ad-to-careers
- https://app.shortcut.com/oazo-apps/story/3987/careers-update-the-about-us-section-in-the-full-stack-job-ad
- Add mechanism for manually sorting offers,
- Add new offer: **Software Engineer in Test**,
- Update **About us** section for **Full-Stack Developer**.
- See if sorting works and how its behave when e.g. there are more than one offers category or some offer doesn't have `order` field filled.
- No need to test content changes.
> Career offers manual order and new offer

- blockchain/config.ts
oasis-borrow point 1/Staging
should be sufficient to register triggers in new bot
> goerli adresses update

- features/borrow/open/containers/OpenVaultView.tsx
- features/earn/guni/open/containers/GuniOpenVaultView.tsx
- features/generalManageVault/GeneralManageVaultView.tsx
- features/survey/SurveyButtons.tsx
- features/survey/index.tsx
- features/survey/surveysConfig.json
- pages/borrow.tsx
- pages/earn.tsx
- pages/index.tsx
- pages/multiply.tsx
- pages/vaults/open-multiply/[ilk].tsx
- public/locales/en/common.json
- Add `features/survey/surveysConfig.json` to configure surveys that would appear on the site.
- Add surveys in earn, borrow (main, open and manage) and the homepage. They are currently disabled by not setting an ID on the config file.
- In `features/survey/surveysConfig.json`, copy the id from multiply page to other surveys and watch it appear on other pages.
> Add configurable Typeforms

- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- adjusted condition for checking if generate amount is less than debt flow
- test it using multiply vault, try to deposit collateral / dai when debt is above dust limit and see if this warning will popup (should not)
> Fixed warning with potential debt less than debt floor

- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- in calculations in stop loss summary section we will now use value from slider as it has the same value as stop loss level which is available after some delay. This delay led to situation where in summary for couple of seconds zeros and inifity values were present (not always but from time to time).
- using vault on goerli network add stop loss trigger for couple of times and check whether summary section has zero / infinity values.
> Fixed issue with stop loss summary section

- package.json
- yarn.lock
Removed nodemailer
- item 1
- step 1 ...
> only removed nodemailer

- features/automation/protection/controls/GetProtectionBannerControl.tsx
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
Added checking debt value in `GetProtectionBannerControl` component.
Check if this banner:
is visible on vaults with generated debt and is not visible on those without.
> Hide stop-loss banner setup on zero debt vaults

- features/vaultsOverview/VaultsOverviewView.tsx
Added checking debt value in `vaultsColumns` in vaults list. Vaults with SL enabled, but no debt shouldn't have SL pill visible.
Test it on your own vaults OR go to `/owner/0xd0612c759fC6C512B7C3abceB2366C4f4096451C`/ on mainnet and check vault `27644` and vaults above. `27644` has SL enabled and zero debt.
> Hide stop-loss pill on zero debt vaults in vaults list

- components/vault/ProtectionControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/CancelSlFormLayout.tsx
Updated link from general https://kb.oasis.app/help to https://kb.oasis.app/help/stop-loss-protection into below places:
> Update stop-loss related links to knowledge base

- components/vault/GeneralManageLayout.tsx
- components/vault/ProtectionControl.tsx
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- public/locales/en/common.json
Added box with warning when SL ratio is set in range between (NEXT_COLL_RATIO - 3) and (MAX_COLL_RATIO).
Try setting up SL in vault and check if warning is visible. Ideal conditions are when next price is different than current, because in that case gap on which warning is displayed is different than three.
> Add Warning when Stop loss is set to 3% of current collateral Ratio based on next price

- components/vault/ProtectionControl.tsx
- features/automation/protection/common/components/AutomationFormButtons.tsx
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
- helpers/useFeatureToggle.ts
Some of the changes are made dirty like commenting or disabling eslint lines, but that was faster and it's just temporary.
SL UI is available only for users that already have any triggers.
In other cases users will see banner with proper message.
Also removed banner from overview tab that is suppose to encourage to set up new SL, because there's no point in it right now.
> Temporary remove SL UI changes

- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
Follow up to https://github.com/OasisDEX/oasis-borrow/pull/1017.
Hide get protection banner from multiply vault overview tab.
Check if you can see this banner anywhere on vault pages. If not, then it's all good.
> Hide "Get protection" banner from multiply vault page

- components/VaultTabSwitch.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/VaultHeaderContainer.tsx
- features/automation/protection/controls/GetProtectionBannerControl.tsx
- features/automation/protection/controls/ProtectionDetailsLayout.tsx
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/borrow/open/containers/OpenVaultDetails.tsx
- features/earn/guni/manage/containers/GuniManageMultiplyVaultDetails.tsx
- features/earn/guni/open/containers/GuniOpenMultiplyVaultDetails.tsx
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
- features/multiply/open/containers/OpenMultiplyVaultDetails.tsx
- features/vaultHistory/VaultHistoryView.tsx
- helpers/useFeatureToggle.ts
- added NewComponents feature toggle key
- replaced usage of AutomationBasicBuyAndSell to NewComponents key 
- in order to see new designs use new feature toggle key `NewComponents`
> Added newComponents feature toggle key

- components/AppContext.ts
- features/earn/guni/manage/pipes/manageGuniVault.ts
- hardcode slippage to zero
- try to close your multiply vault and look at slippage
> set slippage to zero

- components/vault/VaultAllowance.tsx
- components/vault/sidebar/SidebarOpenBorrowVault.tsx
- components/vault/sidebar/SidebarOpenVaultAllowanceStage.tsx
- components/vault/sidebar/SidebarOpenVaultProxyStage.tsx
- features/multiply/open/containers/OpenMultiplyVaultForm.tsx
- features/multiply/open/containers/sidebar/SidebarOpenMultiplyVault.tsx
- features/multiply/open/containers/sidebar/SidebarOpenMultiplyVaultEditingState.tsx
- features/multiply/open/containers/sidebar/SidebarOpenMultiplyVaultOpenStage.tsx
- features/multiply/open/pipes/openMultiplyVaultConditions.ts
- features/sidebar/getSidebarProgress.ts
- features/sidebar/getSidebarSuccess.ts
- features/sidebar/getSidebarTitle.ts
- features/sidebar/trackingEventOpenVault.ts
- helpers/extractSidebarHelpers.ts
- helpers/isFirstCdp.ts
- public/locales/en/common.json
- implemented new sidebar design in open multiply vault flow (behind feature toggle)
- enable NewComponents feature toggle and test it using goerli / hardhat
> Open multiply new design sidebar

- features/form/commonValidators.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- added afterCollRatio check
- open multiply or borrow vault, close it and then try to deposit collateral without generating debt, following issue with error shouldn't occur now
> Stop loss validation fix when vault has 0 debt

- components/vault/sidebar/SidebarOpenBorrowVault.tsx
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLoss.tsx
- features/borrow/open/containers/OpenVaultChangesInformation.tsx
- features/borrow/open/pipes/openVault.ts
- features/borrow/open/pipes/openVaultConditions.ts
- features/multiply/open/pipes/openMultiplyVault.ts
- features/sidebar/getPrimaryButtonLabel.ts
- features/sidebar/getSidebarTitle.ts
- features/vaultTransitions/openVaultTransitions.ts
- helpers/useFeatureToggle.ts
- public/locales/en/common.json
> Added stop loss step to open borrow flow including following new state variables:                       `withStopLossStage`, `isStopLossEditingStage`, `stopLossSkipped`
>  use borrow open flow and feature toggle flag `StopLossOpenFlow` and `NewComponents`
> `withStopLossStage` variable is based on list of ilks which are allowed for automation
> Added stop loss step to open borrow flow

- features/automation/protection/useStopLossStateInitializator.ts
- from now on, protection tab state will reset on coll ratio change event
- start editing something in protection tab then move to overview and change coll ratio of the vault, when coll ratio will be refreshed, protection tab should be reset to default state
> reset sl state on coll ratio change

- features/automation/protection/controls/AdjustSlFormControl.tsx
Selected slider background was calculated using unrounded values, while in the slider user can only pick rounded value at max.
> Fix stop-loss slider filling

- components/ProductCardMultiply.tsx
Should be 50x in both GUNIV3DAIUSDC1  and GUNIV3DAIUSDC2
> issue with max multiply

- components/vault/detailsSection/ContentCardTargetColRatio.tsx
- components/vault/detailsSection/ContentCardTriggerColRatio.tsx
- features/automation/optimization/controls/OptimizationDetailsLayout.tsx
- public/locales/en/common.json
Created a static details section for basic buy, don't mind the values, they are generated randomly 🤷‍♀️
I didn't add buttons next to the title, because their visibility is conditional and `DetailsSection` already allows to use them, so no point in that currently.
Turn on BasicBS feature flag and go to any vault to Optimization tab.
> Basic buy details section

- components/AppContext.ts
- components/vault/OptimizationControl.tsx
- features/automation/optimization/controls/OptimizationDetailsControl.tsx
- features/automation/optimization/controls/OptimizationDetailsLayout.tsx
- features/automation/optimization/controls/OptimizationFormControl.tsx
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/protection/common/UITypes/AutomationFeatureChange.ts
- public/locales/en/common.json
- Added Auto Buy banner when feature is on.
- Added ability to switch between context of active features.
Turn on `BasicBS` feature flag and go to any vault to Optimization tab. By default, there should be only a banner for Auto Buy. Clicking CTA should display details section and sidebar related to it.
> Feature selection in Optimization tab

- public/locales/en/common.json
`insufficient-eth-balance`: "Your ETH balance is potentially too low to pay for transaction" -> "Your ETH balance is potentially too low to pay for **this** transaction"
> Update insufficient-eth-balance translation key

- helpers/useFeatureToggle.ts
Reverted because GUNI Vault sidebar layout needs to be updated ¯\\_(ツ)_/¯
See if new components aren't visible unless feature `NewComponents` set up as `true`.
> Set NewComponents to false by default

- components/vault/VaultActionInput.tsx
- components/vault/sidebar/SidebarFields.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLoss.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLoss.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLossEditingStage.tsx
- features/borrow/manage/sidebars/SidebarManageBorrowVault.tsx
- features/borrow/manage/sidebars/SidebarManageBorrowVaultEditingStage.tsx
- features/borrow/open/sidebars/SidebarOpenBorrowVault.tsx
- features/borrow/open/sidebars/SidebarOpenBorrowVaultEditingStage.tsx
- features/earn/guni/manage/sidebars/SidebarManageGuniVault.tsx
- features/earn/guni/manage/sidebars/SidebarManageGuniVaultEditingState.tsx
- features/earn/guni/open/sidebars/SidebarOpenGuniVault.tsx
- features/earn/guni/open/sidebars/SidebarOpenGuniVaultEditingState.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVault.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVaultEditingStage.tsx
- features/multiply/open/sidebars/SidebarOpenMultiplyVault.tsx
- features/multiply/open/sidebars/SidebarOpenMultiplyVaultEditingState.tsx
- public/locales/en/common.json
- Hide afterpills on manage multiply when you switch from close vault to transfrom to borrow,
- bring back `not-allowed` cursor on disabled fields,
- move general validations above vault changes list,
- final UI fixes to SL sidebar according to new sidebar layouts.
> Sidebars UI fixes

- helpers/multiply/calculations.ts
Vaults https://oasis.app/27394#History and https://oasis.app/27351#Overview seem to have PnL way off due to Move events not aggregated correctly. 
- Account MOVE_SRC as payback the debt
- Account MOVE_DEST as generating debt 
- Checkout 27394 and 27351
> Fix move events

- components/DetailsSection.tsx
- components/sidebar/SidebarSectionHeader.tsx
According to comment from Anna: all new components in details section and in sidebar should have header border with margins and footer border from side to side.
> New components headers with spacing

- components/VaultTabSwitch.tsx
- features/automation/common/basicBSTriggerData.ts
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/protection/common/UITypes/basicBSFormChange.ts
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- features/automation/useBasicSellStateInitializator.ts
- public/locales/en/common.json
- added add / remove form switch
- added possibility to remove basic buy / sell trigger
- using BasicBS feature toggle try to add and remove basic buy / sell triggers
> Basic BS remove trigger handlers

- components/vault/ProtectionControl.tsx
- components/vault/VaultErrors.tsx
- features/automation/common/validators.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AutoSellFormControl.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/StopLossFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- features/form/errorMessagesHandler.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
- added validation to basic sell and stop loss form to verify whether triggers are in correct state
- when SL is enabled a basic sell trigger has to be higher
- when basic sell is enabled, SL has to be lower
> Basic sell trigger always higher than SL trigger

- content/assets.ts
> Move GUNI products to Earn tab.

- components/vault/MultipleRangeSlider.tsx
- components/vault/VaultErrors.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/protection/controls/AutoSellFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/triggers/AutomationTriggersData.ts
- features/borrow/manage/pipes/adapters/standardBorrowManageAdapter.ts
- features/borrow/manage/pipes/manageVault.ts
- features/borrow/manage/pipes/manageVaultValidations.ts
- features/borrow/manage/pipes/viewStateTransforms/manageVaultConditions.ts
- features/borrow/manage/pipes/viewStateTransforms/manageVaultEnvironment.ts
- features/form/commonValidators.ts
- features/form/errorMessagesHandler.ts
- features/multiply/manage/pipes/manageMultiplyVault.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultEnvironment.ts
- features/multiply/manage/pipes/manageMultiplyVaultValidations.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
#[Added basic buy overview validation](https://app.shortcut.com/oazo-apps/story/4994/overview-validation-for-basic-buy)
- added basic sell validation to overview view (both borrow and multiply)
- added basic buy validation to overview view (both borrow and multiply)
- when basic sell trigger is enabled try to push vault to the state where next coll ratio will be below basic sell trigger coll ratio (you should get error and button should be blocked)
- when basic buy trigger is enabled try to push vault to the state where next coll ratio will be above basic buy trigger coll ratio (you should get error and button should be blocked)
> Added basic sell and buy overview validation

- components/vault/VaultWarnings.tsx
- features/automation/common/validators.ts
- features/automation/protection/common/validation.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- features/automation/protection/openFlow/openVaultStopLoss.ts
- features/form/warningMessagesHandler.ts
- public/locales/en/common.json
- added min / max slider value warnings to basic sell form when stop loss or basic buy is enabled
- added max slider value warning to stop loss form when basic sell is enabled
- enable stop loss and basic buy, verify if warnings are present when you try to set target coll ratio to max and trigger coll ratio to min (do the same with stop loss trigger and basic buy trigger disabled, warnings should be there in that case)
- in stop loss form verify whether warning is shown when use move slider to max value (basic sell has to be enabled but test also when is disabled (no warning in that case))
> Basic sell warnings on min / max slider value

- helpers/multiply/calculations.ts
- Account for oasis fee in earnings
- Display earnings as zero when we get negative value, (due to osm price updates being only once a day)
- checkout some vaults: 28921, 28888, 27351
> adjust calculations for earnings

- components/vault/detailsSection/ContentCardStopLossCollateralRatio.tsx
- components/vault/sidebar/SidebarSliders.tsx
- features/automation/protection/controls/StopLossDetailsControl.tsx
- features/automation/protection/controls/StopLossDetailsLayout.tsx
- public/locales/en/common.json
- added current coll ratio to sl details and multiply slider
- when changing coll ratio in multiply vault using slider a current coll ratio should be showed (with arrow) next to next coll ratio
- in stop loss details section card with current coll ratio should be present
> Added current coll ratio to sl details and multiply slider

- features/automation/optimization/controls/AutoBuyFormControl.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- public/locales/en/common.json
<please insert a shortcut link above>  
- notice explanation next to slider in autobiy
- check if values are correct and if values change properly when one interacts with ui
> added explanation for basic buy

- components/vault/GeneralManageLayout.tsx
- components/vault/GeneralManageTabBar.tsx
- optimization tab will be visible only for specific ilks
- use ilk which is not on following list (goerli) ['ETH-A', 'ETH-B', 'ETH-C', 'WSTETH-A', 'WBTC-A', 'WBTC-B', 'WBTC-C'] or just remove ilk for this list in code and check whether optimization & protection tab will be visible (shouldn't be visible)
> Show optimization tab for specific ilks

- features/automation/protection/controls/StopLossDetailsLayout.tsx
- public/locales/en/common.json
- Protection tab details section titles update
- go to protection tab with enabled BasicBS feature toggle, details section tiles should be Stop-Loss and Auto-Sell
> Protection tab details section titles update

- components/vault/VaultErrors.tsx
- features/automation/common/validators.ts
- features/automation/optimization/controls/AutoBuyFormControl.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/optimization/validators.ts
- features/automation/protection/common/UITypes/basicBSFormChange.ts
- features/automation/protection/common/validation.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/AutoSellFormControl.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/StopLossFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLoss.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- features/automation/protection/openFlow/openVaultStopLoss.ts
- features/form/errorMessagesHandler.ts
- public/locales/en/common.json
- added missing validation to auto buy and auto sell form
- check story description
> Added missing Basic Buy and Sell validations

- features/automation/protection/common/validation.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- due to potential network lag it was possible to click the button several times before it was blocked. Added handling for instant stop loss button disable when tx is submitted
- using hardhat try to add stop loss and observe whether button is disabled right after click
> Instant stop loss button disable and validation fix

- features/automation/optimization/controls/ConstantMultipleControl.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsControl.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsLayout.tsx
- features/automation/optimization/controls/OptimizationDetailsControl.tsx
- features/automation/protection/common/UITypes/AutomationFeatureChange.ts
- helpers/useFeatureToggle.ts
- public/locales/en/common.json
not sure if it makes sense to re-use details cards from auto buy and auto sell, it has more fields than in designs for cm
- item 1
- step 1 ...
> constant multiple banner, no details yet

- features/termsOfService/TermsOfService.tsx
- supply `userReferral` to `TermsOfService` when not on homepage
1. land with a referral link
2. manually change the url to `/referrals`
3. try `accept` or `decide later`
> Modal not closing on /referrals

- components/vault/OptimizationControl.tsx
- components/vault/ProtectionControl.tsx
- features/automation/common/validators.ts
- features/automation/optimization/controls/AutoBuyFormControl.tsx
- features/automation/optimization/controls/OptimizationFormControl.tsx
- features/automation/optimization/validators.ts
- features/automation/protection/controls/AutoSellFormControl.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- calculation used to get debt delta now using execution price
- in auto buy and auto sell form information section should contain calculation based on execution price
- in auto sell form error validation regarding dust limit should take into account correct debtDelta (based on executionPrice)
> Use execution price in calcs

- blockchain/vault.maths.ts
- features/automation/common/helpers.ts
- features/automation/optimization/controls/AutoBuyFormControl.tsx
- features/automation/protection/controls/AutoSellFormControl.tsx
- we no longer pass zero as execution price for multiply calcs method
- with zero debt o zero collateral and enabled auto buy or sell trigger go to optimization tab
> Fixed issue with 0 execution price

- features/automation/common/helpers.ts
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- cancel form button for basic buy and sell shouldn't be disabled by errors regarding add form inputs
- add triggers in different combinations and check whether button in cancel for is disabled (shouldn't be)
> Adjusted isDisabled method for basic buy and sell

- features/borrow/manage/sidebars/SidebarManageBorrowVaultEditingStage.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVaultEditingStage.tsx
- handled case when user is not the owner and tries to generate dai (button / input has to be disabled in that case)
- try deposit and generate in multiply / borrow vault which is not yours and additionally verify whether you can perform these actions on your vault
> Fixed issue with generating when user is not the owner

- features/vaultHistory/vaultsHistory.ts
](https://app.shortcut.com/oazo-apps/story/5255/bug-when-the-user-has-set-1-stop-loss-all-other-vaults-look-like-they-have-it-active-on-the-owner-page)
> [SC-5255] Fix showing stop loss info on all vaults.

- features/vaultHistory/VaultHistoryEntry.tsx
- features/vaultHistory/VaultHistoryView.tsx
- features/vaultHistory/vaultHistory.ts
- features/vaultHistory/vaultHistoryEvents.ts
- public/locales/en/common.json
- automation events with same txHash has been wrapped into single history event
- history should contain update events (when stop loss / auto sell or buy are updated), execution events with detailed informations
> Wrapped automation history events

- components/dumb/PositionList.tsx
- features/vaultHistory/vaultsHistory.ts
- features/vaultsOverview/vaultsOverview.ts
https://app.shortcut.com/oazo-apps/story/5319/show-protection-active-when-auto-sell-has-been-added
https://app.shortcut.com/oazo-apps/story/5323/protection-column-on-my-positions-is-inconsistent-between-borrow-and-multiply
- When vault has auto sell enabled, its value should be visible in its row on vaults overview page,
- Multiply vaults should display protection values, not just simple "On".
Add SL and auto-sell to both borrow and multiply vault, check if their values are correctly reflected in vaults overview page.
> Display proper protection values on vaults overview page

- features/termsOfService/termsAcceptance.test.ts
- features/termsOfService/termsAcceptance.ts
added the 
```
if (updated) {
return jwtAuthSetupToken$(web3, account).pipe(
switchMap((token) => {
return checkAcceptance(token, version, magicLinkEmail)
}),
catchError(() => {
return withClose({ stage: 'jwtAuthFailed' })
}),
startWith({
stage: 'jwtAuthInProgress',
}),
)
}
```
to force the `acceptanceWaiting4TOSAcceptance` stage when user has jwt in local storage and the TOS has been updated.
Removed the `;(state() as any).acceptJwtAuth()` in `termsAcceptance.test.ts` - as the JWT accpetance is not required.
remove the latest TOS signature from the DB, so only the previous one is left  (`version-1.06.2021`)
remove the latest TOS signature and jwt token from local storage from the DB, so only the previous one is left  (`version-1.06.2021`)
remove all …
> Do not show the JWT modal when TOS is updated

- handlers/vault/createOrUpdate.ts
Fix inability to switch from borrow to multiply (and vice versa) for vaultId on many networks
> fix duplicated chainId

- components/vault/sidebar/SidebarVaultSLTriggered.tsx
- amountFromWei method was using wrong precision based on token, ETH should be hardcoded there
- go to https://oasis.app/28944#overview totalCost in Stop-Loss executed summary should be equal to total cost in history event
> Fixed total cost issue in stop loss executed summary

- components/vault/VaultWarnings.tsx
- features/automation/optimization/controls/ConstantMultipleFormControl.tsx
- features/automation/optimization/controls/OptimizationFormControl.tsx
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/optimization/validators.ts
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- features/form/warningMessagesHandler.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
- added validation to CM form which checks if user moved sell trigger ratio to min value when SL is enabled
- enable SL on vault, move sell trigger ratio in constant multiply form to min value, warning should appear and min value should be equal to stop loss trigger ratio + 5%
> CM sell trigger above stop-loss trigger validation

- components/vault/VaultWarnings.tsx
- features/automation/protection/common/validation.ts
- features/automation/protection/controls/AdjustSlFormControl.tsx
- features/automation/protection/controls/AdjustSlFormLayout.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/StopLossFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarAdjustStopLoss.tsx
- features/form/warningMessagesHandler.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
- added validation to stop loss when CM is enabled and user will set maximum value using slider
- add CM trigger, in stop loss form move slider to max, warning should appear (currently not testable due to missing data from cache)
> Prevent Stop Loss trigger to set above CM sell trigger

- components/infoSection/Item.tsx
- features/automation/basicBuySell/InfoSections/ConstantMultipleInfoSection.tsx
- features/automation/common/helpers.ts
- features/automation/optimization/controls/AutoBuyFormControl.tsx
- features/automation/optimization/controls/ConstantMultipleFormControl.tsx
- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/protection/controls/AutoSellFormControl.tsx
- public/locales/en/common.json
- Connected changes information to `constantMultipleState`,
- updated `getBasicBSVaultChange` method to accept constant multiple values.
To do in the future, in next PR:
- Decide if `slippage` needs to be removed.
- Check if changes information are updating in constant multiple form.
> Constant multiple changes information data

- components/vault/VaultErrors.tsx
- features/automation/common/validators.ts
- features/automation/optimization/controls/AutoBuyFormControl.tsx
- features/automation/optimization/controls/OptimizationFormControl.tsx
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/optimization/validators.ts
- features/automation/protection/controls/AutoSellFormControl.tsx
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- features/form/errorMessagesHandler.ts
- public/locales/en/common.json
- added error to auto buy and sell forms when user tries to add trigger when CM is enabled
- enable CM and then try to add auto sell or buy trigger, you should get error (not testable due to lack data from cache)
> Auto BS error when CM enabled

- components/vault/VaultWarnings.tsx
- features/automation/optimization/validators.ts
- features/form/warningMessagesHandler.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
- added validation to check whether trigger that is being added will result in immediate execution
- try to setup CM sell trigger ratio in buy trigger ratio in the range that will result in immediate execution
> Added warning message if CM would be executed immediately

- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
`estimatedGasCostOnTrigger` went missing during some of the refactors and prop drilling during changing files structure in CM.
- Passed `estimatedGasCostOnTrigger` value down to the `ConstantMultipleEditingStage` component.
- Go to CM and check if "Estimated transaction cost per adjustment" is displaying properly.
> Missing estimatedGasCostOnTrigger

- blockchain/calls/observe.ts
- components/AppContext.ts
Stops loading product card data on everyblock for landing pages
- Creates lean versions of all the pipes for the product card data so it is not refreshed on every block.
- open and close a few positions on hardhat.
> only load product card data once for landing pages, not on every block

- components/vault/detailsSection/ContentFooterItemsEarnSimulate.tsx
- features/earn/guni/open/containers/GuniOpenMultiplyVaultDetails.tsx
- public/locales/en/common.json
- Update breakeven to use 30 day APY on simulate page.
- Go to earn simulate view and plug in a various DAI amounts. Confirm that the estimated breakeven 'makes sense' in the context of 30 day earnings after fees
> Bug: Align breakeven with 30 day returns on Simulate page

- components/infoSection/Item.tsx
- features/automation/basicBuySell/MaxGasPriceSection/MaxGasPriceSection.tsx
- features/automation/optimization/sidebars/ConstantMultipleEditingStage.tsx
- added max gas price section in constant multiply form
- use feature toggle `ConstantMultiple` and go to CM form. Expand max gas price section and play with buttons. For now to test it it is recommended to console log either `constantMultipleState` or verify transaction payload
> Max gas price section in CM

- components/Table.tsx
- fixed issue with broken styling in oracles table header
- visit oracles page using our app, check whether styling in header is fine
Before fix it looked like this
> Oracles table header buttons fix

- pages/_app.tsx
- removed unnecessary styling of div (first of type) in body
- if you are using last-pass plugin do the hard refresh of page and check whether landing page is displayed correctly
This is how it looked like before fix
> Last pass issue fix

- components/ActionPills.tsx
- features/automation/optimization/common/multipliers.ts
- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- public/locales/en/common.json
- Updated list of multipliers for selected ilks,
- added option to `ActionPills` to disable single item,
- added validation to multipliers list so user can't choose value that would push his collateral ratio above or below slider min or max values.
- Try setting constant multiple on vaults with different types of ilks.
> Constant multiple available multipliers validation

- components/vault/MultipleRangeSlider.tsx
- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/protection/common/UITypes/constantMultipleFormChange.ts
- features/automation/protection/useConstantMultipleStateInitialization.ts
- scripts/docker/launch.sh
Added extra isResetAction to prevent recalculation slider values (dependent on multiple variables) when one hits reset button, to make it behave in more predictable way, reset the initial state
- Have a vault with constant multiple trigger enabled
- view details of cm trigger, memorize initial state on slider values
- edit slider or multiplier
- hit reset button, it should bring slider to same state as when initially displayed
> fixed reset button for constant multiple form

- components/vault/detailsSection/ContentCardTargetColRatioAfterBuy.tsx
- components/vault/detailsSection/ContentCardTargetColRatioAfterSell.tsx
- components/vault/detailsSection/ContentCardTargetMultiple.tsx
- features/automation/optimization/controls/BasicBuyDetailsControl.tsx
- features/automation/optimization/controls/BasicBuyDetailsLayout.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsControl.tsx
- features/automation/optimization/controls/ConstantMultipleFormControl.tsx
- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/protection/controls/BasicSellDetailsControl.tsx
- features/automation/protection/controls/BasicSellDetailsLayout.tsx
- features/automation/protection/useConstantMultipleStateInitialization.ts
- Changed condition when to show afterpills in BS,
- fixed afterpills calculations for removal state in Constant Multiple,
- hidden removal button from Constant Multiple on success stage.
- Try editing BS features and see if after pills behavior is correct,
- Try removing CM trigger and see if afterpills are set on 0.
> Afterpills tweaks in BS and CM

- components/vault/GeneralManageTabBar.tsx
- components/vault/OptimizationControl.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsControl.tsx
- features/automation/optimization/controls/ConstantMultipleDetailsLayout.tsx
- features/automation/optimization/controls/OptimizationDetailsControl.tsx
- public/locales/en/common.json
https://app.shortcut.com/oazo-apps/story/5704/cm-banner-on-borrow-vault
https://app.shortcut.com/oazo-apps/story/5675/bug-remove-constant-multiple-from-borrow-vaults
https://app.shortcut.com/oazo-apps/story/5726/update-copy-cm-banner
Changed Constant Multiple banner on non-multiply vaults:
- different text,
- CTA doesn't open Constant Multiple form, instead it moves user to overview tab.
Constant Multiple enabled in multiply vault that was switched to borrow stays intact, but after user removes it he can't set it up anymore until they go back to mutliply interface.
Important note: in MVP we are only moving user to overview tab, later on we should update the button so it would also chose "Switch to multiply" option in dropdown.
- Try opening Constant Multiple in both multiply and borrow …
> Constant Multiple on non-multiply vaults

- features/automation/optimization/common/multipliers.ts
- features/automation/protection/useConstantMultipleStateInitialization.ts
Fixed an issue where default multiplier was selected without considering if it's eligible in current vault state.
Does not contain fix an issue where all multipliers are disabled, that one is still waiting to be decided how are we going to handle it.
On the side note - if no multiplier is acceptable, the method will return the middle one as without any multiplier selected whole Constant Multiple state is breaking. But that is going to be addressed (or not if we are going to hide form) along with issue mentioned above.
Set up Stop-Loss above the level of middle multiplier in any vault and check if it's selected as default.
> Disable selecting ineligible multiplier in CM

- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/optimization/validators.ts
- added the same validation to constant multiple form as in auto-buy form when max buy price is not set 
- use CM feature toggle and click on `Set No Threshold` next to max buy price input. Warning should pop up.
> CM max price input warning when no threshold

- features/automation/optimization/common/helpers.ts
- features/automation/optimization/common/multipliers.ts
- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/protection/common/UITypes/constantMultipleFormChange.ts
- features/automation/protection/useConstantMultipleStateInitialization.ts
- public/locales/en/common.json
- Display appropriate message for user if their Stop-Loss* is causing no multiplier to be legal in current state of the vault,
- Changed max slider value to be hardcoded at 500%, no longer calculated based on vault debt.
\*Stop-Loss is the only reason why multiplier may be disabled, so currently there is only one message.
- Set up Stop-Loss to 500%+ in any vault and see if Constant Multiple vault is hidden.
> Disable Constant Multiple form if there are no eligible multipliers

- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
- `minMultiplier` for multipliers eligibility is calculated in a same way as max col ratio in multiple vault, not set as const `500`.
- Test vault with low debt to see if you can select multiplier that would push vault below ilks dust limit.
> Disable multipliers that would push vault below dust limit

- components/vault/OptimizationControl.tsx
- features/automation/optimization/controls/AutoBuyFormControl.tsx
- features/automation/optimization/controls/OptimizationFormControl.tsx
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
User should not be able to enable Constant Multiple in non multiply vaults, but it was possible to change context of optimization form from sidebar. Removed that option.
Check if you can switch form context in optimization in both borrow and multiply vaults.
> Remove sidebar dropdown on non-multiply vaults

- features/automation/common/helpers.ts
- features/automation/common/validators.ts
- features/automation/optimization/common/multipliers.ts
- features/automation/optimization/controls/ConstantMultipleFormControl.tsx
- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/optimization/validators.ts
- features/automation/protection/common/UITypes/constantMultipleFormChange.ts
- features/automation/protection/controls/AutoSellFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- features/automation/protection/useConstantMultipleStateInitialization.ts
- immediately validation in Auto Sell and Constant Multiply form now takes into account current vault state
- added validation to Constant Multiply regarding dust limit
- try to setup (both in Auto Sell form and in CM form) trigger that would hit dust limit at current vault state or in future (error message should be visible)
- warning regarding immediately execution in both form should be displayed only if trigger is eligible based on current vault state
> Adjusted auto sell immediately validation

- components/vault/sidebar/SidebarVaultSLTriggered.tsx
- features/automation/common/helpers.ts
- features/automation/optimization/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupConstantMultiple.tsx
- helpers/arrayRange.ts
- helpers/useFeatureToggle.ts
- public/locales/en/common.json
- added sell execution range simulation to get eligible multipliers
- test it using different vaults in different state, there shouldn't be a case when multiplier is enabled but user is not able to create trigger using it
> Added sell execution range simulation to get eligible multipliers

- components/sidebar/SidebarSectionContent.tsx
- helpers/useFeatureToggle.ts
`DisableSidebarScroll` feature flag allows to display whole sidebar without internal scroll that makes testing a little bit easier.
`DisableSidebarScroll: false`
`DisableSidebarScroll: true`
- Added `DisableSidebarScroll` feature set to `false` by default.
- Compare different sidebars forms with `DisableSidebarScroll` flag set to `true` and to `false`.
> Add DisableSidebarScroll feature flag

- pages/api/sentry.tsx
- sentry.base.config.ts
`/api/sentry` endpoint added
- change the following lines in `.env.local` :
```
NEXT_PUBLIC_SENTRY_ENV="pullrequest"
SENTRY_RELEASE="pullrequest"
```
- go to a page that would generate sentry event eg your owner page 
- check for calls to `/api/sentry` 
- 
- check if response === `tunnel/ok`
- check sentry dashboard
> Prevent uBlock from blocking sentry analytics

- analytics/analytics.ts
- analytics/mixpanel.ts
- pages/_app.tsx
- pages/api/t.tsx
- remove double tracking (directly from FE + proxied) for FE events
- proxy all tracked events through mixpanel endpoint (`/api/t`)
- added `$current_url` , `$initial_referrer` and `$initial_referring_domain` as per `https://help.mixpanel.com/hc/en-us/articles/115004613766-Default-Properties-Collected-by-Mixpanel` to supplement the data forwarded by proxy
- moved ` mixpanelInit()` in `_app.tsx` to the `useEffect` so `window` object  is visible ( we can get current URL)
-  removed `be-` prefix to keep the current data format
- if the user opted out (cookie settings) track only `AccountChange` address and `ConfirmTransaction`
- change `MIXPANEL_ENV` to `production`
- remove `if (process.env.NODE_ENV !== 'development') {` in `_app.tsx` to track route changes
- check if the calls to `/api/t` …
> Prevent uBlock from blocking mixpanel analytics

- features/vaultsOverview/pipes/positions.ts
- Disabled the aave positions.   
- Go to the overview page.
> disabled aave positions on position overview.

- components/notifications/NotificationsPrefrenceCardWrapper.tsx
- email notification config hidden
- using feature toggle `Notifications`, e-mail config section shouldn't be visible
> Hide email notification config

- features/notifications/consts.ts
- public/locales/cn/common.json
- public/locales/en/common.json
- hidden unused subscription types
- use feature toggle `Notifications`, only `Vault action notifications` and `Vault info notifications` in notification config should be visible
> Hide unused subscription types

- features/automation/common/helpers.ts
- features/automation/optimization/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/optimization/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/protection/controls/sidebar/SidebarAutoSellAddEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarSetupAutoSell.tsx
- public/locales/en/common.json
- scripts/docker/launch.sh
- item 1
- Case coll ratio too high in AB:
click redirects, if c-ratio is lower than slider max user is able to set trigger
AB - check for sl too high
redirects to protection 
disappears after adjusting 
SL too high for AS example
coll ratio too high example
> handled too high c-ratio for ab

- blockchain/vault.maths.ts
- components/vault/detailsSection/ContentCardEstTokenOnTrigger.tsx
- features/automation/protection/common/helpers.ts
- features/automation/protection/controls/ProtectionFormControl.tsx
- features/automation/protection/controls/StopLossDetailsControl.tsx
- features/automation/protection/controls/StopLossFormControl.tsx
- features/automation/protection/controls/sidebar/SidebarCancelStopLossEditingStage.tsx
- features/automation/protection/controls/sidebar/SidebarSetupStopLoss.tsx
- updated afterpills on trigger removal in stop loss details section
- fixed issue when SL has been deleted and SL form and details section lost their active status
- add stop loss trigger then try to remove it -> after pills with zeros should be visible in details section
- after SL removal form and detail section shouldn't lose active status
> Update afterpills on trigger removal

- components/vault/VaultWarnings.tsx
- features/borrow/manage/containers/ManageVaultDetails.tsx
- features/form/warningMessagesHandler.ts
- features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx
- removed banner saying that users should recreate auto sell trigger due to contract change
- vaults 1935 and 28734 shouldn't have banner in overview details section
> Undo banner for vaults affected by latest Auto-Sell SC change

- components/HeadTags.tsx
- runtime.config.js
- this fixed the twitter share OG image which requires an absolute path to the image (publicRuntimeConfig.basePath change) and twitter:creator tag
- publicRuntimeConfig.basePath now pulls value from env `APP_FULL_DOMAIN`
Go to twitter.com and share `https://oasis.app/` or `https://oasis.app/borrow`, there should be a matching image
> Changed the OG images path to absolute + added twitter:creator

- features/automation/optimization/autoBuy/sidebars/SidebarAutoBuyEditingStage.tsx
- features/automation/protection/autoSell/sidebars/SidebarAutoSellAddEditingStage.tsx
- updated color of slider dots and values in auto buy and sell forms
- go to auto sell and auto buy sidebars, verify whether slider dot and value colors (target coll ratio) are as described in story (both for auto buy and sell target coll ratio value and dot should be black)
> Updated AB / AS target ratio color (slider)

- public/locales/en/common.json
- changed `confirmed` to `completed` in status card during open flow with SL
- open vault with SL, verify status card copy
> Updated open SL status card copy

- components/vault/detailsSection/ContentCardTargetColRatioAfterBuy.tsx
- components/vault/detailsSection/ContentCardTargetColRatioAfterSell.tsx
- features/automation/optimization/autoBuy/controls/AutoBuyDetailsControl.tsx
- features/automation/optimization/autoBuy/controls/AutoBuyDetailsLayout.tsx
- features/automation/protection/autoSell/controls/AutoSellDetailsControl.tsx
- features/automation/protection/autoSell/controls/AutoSellDetailsLayout.tsx
- details cards in automation scope will show `-` instead of `0` when trigger is not enabled
- go to auto buy and sell forms and check whether detail cards show `-` as value
> Unified default values in details section

- components/notifications/NotificationsPrefrenceCardWrapper.tsx
- removed emit which was responsible for generating dummy notifications
- setting up preferences in notifications config should no longer generate dummy notifications (test using notification feature toggle, use staging)
> Remove dummy notifications emit

- features/automation/optimization/constantMultiple/controls/ConstantMultipleDetailsLayout.tsx
- public/locales/en/common.json
As in title.
See a protection tab in both borrow and multiply vaults and confirm if banner is visible. If Constant Multiple was enabled on multiply vault and then vault was transformed into borrow, Constant Multiple UI should still be available.
> Remove Constant Multiple banner from non-multiply vaults

- components/Banner.tsx
- features/automation/common/sidebars/getAutoFeaturesSidebarDropdown.ts
- features/automation/optimization/autoBuy/controls/AutoBuyDetailsControl.tsx
- features/automation/optimization/autoBuy/controls/AutoBuyDetailsLayout.tsx
- features/automation/optimization/common/controls/OptimizationDetailsControl.tsx
- features/automation/protection/autoSell/controls/AutoSellDetailsControl.tsx
- features/automation/protection/autoSell/sidebars/SidebarSetupAutoSell.tsx
- features/automation/protection/common/controls/ProtectionDetailsControl.tsx
- features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
- public/locales/en/common.json
- Updated `Banner` component so it accepts more than one paragraph of text with nice spacing between then,
- updated `getAutoFeaturesSidebarDropdown` method to not display Auto-buy and Auto-sell options if Constant Multiple is enabled, also do not display any dropdown if it would have only one item,
- disabled CTA buttons in Auto-buy and Auto-sell banners and added explanation messages to them why they are disabled.
Test on a vault with and without Constant Multiple enabled if you can get access to Auto-sell and Auto-buy UI.
> Disable access to Auto-sell and Auto-buy UI when Constant Multiple is enabled

- helpers/useFeatureToggle.ts
disables proxy creation - used to prevent reorg consequences with transactions send to new proxys that later end up being someone else's around merge time
> disable proxy creation

- components/vault/VaultErrors.tsx
- features/automation/optimization/autoBuy/controls/AutoBuyFormControl.tsx
- features/automation/optimization/autoBuy/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/optimization/autoBuy/validators.ts
- features/automation/optimization/constantMultiple/sidebars/SidebarConstantMultipleEditingStage.tsx
- features/automation/optimization/constantMultiple/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/optimization/constantMultiple/validators.ts
- features/automation/protection/autoSell/controls/AutoSellFormControl.tsx
- features/automation/protection/autoSell/sidebars/SidebarSetupAutoSell.tsx
- features/automation/protection/autoSell/validators.ts
- features/form/errorMessagesHandler.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
- added validation to AutoBS and CM forms for max buy price and min sell price inputs which verify whether trigger will be eligible for execution 
- in AutoBS and CM forms try to setup different values in inputs and see wether errors about eligibility are shown
> Added AutoBS and CM validation for inputs

- components/dumb/SliderValuePicker.tsx
- features/automation/protection/stopLoss/openFlow/openVaultStopLoss.ts
- features/automation/protection/stopLoss/sidebars/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
- features/automation/protection/stopLoss/sliderConfig.ts
- features/earn/aave/open/sidebars/SidebarOpenAaveVault.tsx
- public/locales/en/common.json
Before:
After:
- Brought back previous html structure as it is the same in rest of the sliders used in automation features,
- marked `leftBoundryStyling` and `rightBoundryStyling` as optional and removed its usage as all of them were already redundant and duplicated default slider styles,
- added `as` props to `theme.ui` components to fix semantics of slider component,
- fixed styling of a slider so it could be used without right label.
Check out pages that uses `SliderValuePicker` component:
- Any vault on Protection tab,
- AAVE stETH: `/earn/open/aave-steth`.
> Fix Stop-loss UI display

- components/vault/detailsSection/ContentCardTriggerColPrice.tsx
- components/vault/detailsSection/ContentCardTriggerColRatio.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitDetailsControl.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitDetailsLayout.tsx
- public/locales/en/common.json
Does not include getting data from any data source since none of them exist at this point, but already assumes some logic that could be used when data is available.
Does not include popups, they are in the scope of different story.
- Created `ContentCardTriggerColPrice` and `ContentCardTriggerColRatio` components,
- added some boilerplate logic to Auto take profit details controller.
Check out Optimization tab on vault page with `AutoTakeProfit` feature flag enabled.
> Auto-Take Profit Overview Box

- blockchain/tokensMetadata.ts
- features/notifications/types.ts
Automation is now not on for wstETH-B vaults, see: https://oasis.app/29519#overview
It does work (and is on) for wstETH-A vaults, see: https://oasis.app/27564#overview
Automation is now also on for wstETH-B vaults, check on staging for example: https://staging.oasis.app/29519#overview
> fix wstETH-B automation support

- components/vault/detailsSection/ContentCardTriggerColPrice.tsx
- components/vault/detailsSection/ContentCardTriggerColRatio.tsx
- public/locales/en/common.json
Added modals to both Auto Take Profit overview cards. I took the liberty of changing title a little bit from "[Col. asset] Price Trigger" to "Trigger [Col. asset] Price" so I can reuse title from the card which is basically the same.
Go to Optimization tab and see if you can open modals on overview cards.
> Auto-Take Profit Overview Box - Pop-ups

- components/EstimationOnClose.tsx
- features/earn/guni/manage/sidebars/SidebarManageGuniVaultEditingState.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVaultEditingStage.tsx
This is only creation of components that allows to display data that would be calculated somewhere later. Does not include calculations and usage of component in proper place since that place (Auto-Take Profit sidebar) doesn't exist yet.
Example usage with dummy data from Figma
Actual usage during close multiply vault feature
- Created new component `EstimationOnClose` based on something very similar that was already scattered in application,
- edited sidebars steps of closing multiply vault and GUNI vault to be using new unified component.
- Check out closing vault step,
- to see in more Auto-Take Profit like environment, use this snipped in any place in any sidebar:
```
<EstimationOnClose
iconCircle={getToken('DAI').iconCircle}
label="Estimated DAI at Trigger"
value="$3,990,402.00 DAI" …
```
> Auto-Take Profit Expected DAI/Col at trigger

- features/automation/common/sidebars/getAutoFeaturesSidebarDropdown.ts
- features/automation/optimization/autoTakeProfit/controls/AddAutoTakeProfitInfoSection.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitFormControl.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarSetupAutoTakeProfit.tsx
- features/automation/optimization/common/controls/OptimizationFormControl.tsx
- features/automation/optimization/common/helpers.ts
- public/locales/en/common.json
Does not contain actual data, left a lot of TODO comments to remind about that.
- Added component to display changes information for Auto-Take Profit,
- added empty sidebars and all wrapping components needed for final structure to ease editing that later,
- added checking for feature toggle in Optimization sidebar dropdown as currently I think you could see ATP item with Auto-Take Profit feature turned off?,
- simplified `OptimizationFormControl` method.
Compare Auto-Take Profit sidebar with figma designs.
Please note that there are some intentional changes. Numbers are displayed in full notations since we aren't using short notation anywhere, slippage is removed as it was pointed out in shortcut task and estimated transaction costs are different (see: …
> Auto-Take Profit Form Order Summary Box

- components/notifications/NotificationCardsWrapper.tsx
- features/notifications/helpers.tsx
- features/notifications/types.ts
- public/locales/en/common.json
Constant Multiple notifications were already partially handled, needed just final polish.
- Added support for additional notification types:
```
CONSTANT_MULTIPLE_TRIGGERED = 10
APPROACHING_CONSTANT_MULTIPLE = 11
```
- notification list will now ignore and skip notifications of unknown types that aren't defined in `enum`.
I don't know if testing is even possible at this state, I'm not sure if backend is already pushing CM notifications. One thing that could be done is doing a little bit of cheating to see if it's going to work.
To test Constant Multiple notification go to `components/notifications/NotificationCardsWrapper.tsx` and after line `30` add something like 
```
notificationsState.allNotifications[0].notificationType = 10
```
or
``` …
```
> Add support for additional Notifications & Ignore inrecognized Notifications

- components/notifications/NotificationCardsWrapper.tsx
- components/notifications/NotificationsEmptyList.tsx
- public/locales/en/common.json
Please note that ultimately that panel will look a little bit different when #1494 is merged.
- Added handler for empty notifications list: different message depending if user has 0 notifications because his list is empty or he has notifications disabled in settings.
- Open notifications panel with two different wallets, one that is suppose to have notifications and one without any.
> Handle empty notifications list

- helpers/productCards.ts
This is done as it confuses users about wstETH-B
> add tag to wstETH-B

- components/notifications/NotificationsCenter.tsx
- components/notifications/NotificationsCenterHeader.tsx
- public/locales/en/common.json
- Changed cross icon to arrow icon to avoid confusions - icon isn't closing panel back is getting user back to notifications main panel,
- added different notifications panel title if user is in preferences,
- preferences will now close automatically when users closes entire notifications window.
Just check out notifications preferences panel.
> Notifications preferences panel tweaks

- blockchain/tokensMetadata.ts
- blockchain/vault.maths.ts
- components/vault/OptimizationControl.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitFormControl.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarSetupAutoTakeProfit.tsx
- features/automation/optimization/autoTakeProfit/state/autoTakeProfitFormChange.ts
- features/automation/optimization/autoTakeProfit/state/autoTakeProfitStatus.ts
- features/automation/optimization/autoTakeProfit/state/useAutoTakeProfitStateInitializator.ts
- features/automation/optimization/common/controls/OptimizationFormControl.tsx
- features/tokenAth/tokenAth.ts
- features/tokenAth/tokenAthApi.ts
Min value on slider: `current collateral price * 1.05`,
Max value on slider: `all time high collateral price * 2`, or, if API is not responding, `current collateral price * 10`,
Default value on slider: price of collateral based on `current collateral ratio * 1.2`.
- created API endpoint to request for all time high price from coingecko,
- added slider min and max values to `getAutoTakeProfitStatus` method,
- forced Auto-take Profit slider to be based on potential price, not collateral ratio,
- updated `AUTO_TAKE_PROFIT_FORM_CHANGE` reduced with method that allows to set up default values and also removed `execution-coll-ratio` event and replaced it with `execution-price` since contract requires price, not col. ratio.
Check out if slider min, max and default values on Auto-take Profit are …
> Auto-take Profit min/max on slider

- components/notifications/NotificationCard.tsx
- components/notifications/NotificationCardsWrapper.tsx
- features/notifications/helpers.tsx
- features/notifications/notificationChange.ts
- features/notifications/types.ts
- Updated notifications types,
- switched usage of `lastModified` to `timestamp`,
- sorted notifications list by `timestamp`, desc.
Check out if all notifications on the list has correct dates and if they are sorted from newest to oldest.
> Use timestamp insead of lastModified in Notifications

- features/automation/optimization/autoTakeProfit/state/useAutoTakeProfitStateInitializator.ts
Optimization tab was always marked as "On", regardless of actual features state.
Changed `isAutoTakeProfitEnabled` hardcoded flag to `false` - in the future it's state is going to be loaded from cache.
Go to vault page and see if Optimization tab is marked as "On" when all features from that tab are disabled.
> Fix incorrect Optimization tab indication

- components/AppContext.ts
- components/productCards/ProductCardEarnAave.tsx
- features/earn/EarnContext.ts
- features/earn/aave/AaveContext.ts
- features/earn/aave/open/components/AaveOpenHeader.tsx
- features/earn/aave/open/services/calculateSimulation.ts
- features/earn/aave/open/services/getSthEthSimulationMachine.ts
- features/earn/aave/open/services/stEthYield.ts
AAVE stETH/ETH queries varied in response time (sometimes even timed out) so after @sennett made some tweaks on the cache side we needed some changes on the front. Now the query (if needed) takes a list of parameters, which cuts down on response time significantly. In addition to that they are memoized properly and downloaded only once (once on `/earn` page and once on the open position page).
- moved graphql query initialization to appcontext
- moved yields query to appcontext
- added opt-in option to query selected fields on stEthYields
- added proper memoization for stEthYields query
- go to `/earn` and see how fast the yields are displayed
- switch to any other page
- go to `/earn` page again - the yields should be there with no additional request needed
- same as above but on the …
> Speeds up AAVE stETH/ETH yields requests

- components/AppContext.ts
- features/earn/aave/AaveContext.ts
- features/earn/aave/constants/index.ts
- features/earn/aave/manage/containers/AaveManageStateMachineContext.tsx
- features/earn/aave/open/components/AaveOpenHeader.tsx
- features/earn/aave/open/containers/AaveOpenStateMachineContext.tsx
- features/earn/aave/open/services/getOpenAaveStateMachine.ts
- features/earn/aave/open/services/getSthEthSimulationMachine.ts
- features/earn/aave/open/state/aaveStEthSimulateStateMachine.ts
Follow up to previous PR review made by @sennett - https://github.com/OasisDEX/oasis-borrow/pull/1517
- fixes the calculation done in the simulation machine
- should show proper yields in the AAVE STETH/ETH open header
> Fixes the AAVE yield calculations in the STETH/ETH view

- components/GenericSelect.tsx
- Added support for ellipsis overflow for labels that doesn't fit in dropdown.
> Support longer labels for generic slider

- components/vault/OptimizationControl.tsx
- features/automation/common/sidebars/CancelAutoBSInfoSection.tsx
- features/automation/optimization/autoBuy/controls/AddAutoBuyInfoSection.tsx
- features/automation/optimization/autoBuy/sidebars/SidebarAutoBuyRemovalEditingStage.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitDetailsControl.tsx
- features/automation/optimization/autoTakeProfit/controls/CancelAutoTakeProfitInfoSection.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitRemovalEditingStage.tsx
- features/automation/optimization/constantMultiple/controls/AddConstantMultipleInfoSection.tsx
- features/automation/optimization/constantMultiple/controls/CancelConstantMultipleInfoSection.tsx
- features/automation/protection/autoSell/sidebars/SidebarAuteSellCancelEditingStage.tsx
- helpers/useFeatureToggle.ts
- public/locales/cn/common.json
- public/locales/en/common.json
- added `ReadOnlyAutoTakeProfit` feature flag and its handling
- ATP enabled, readonly flag enabled, vault empty - user should be able to remove ATP trigger
- ATP enabled, readonly flag enabled, vault not empty - user should be able to remove ATP trigger
- ATP not enabled, readonly flag enabled, vault not empty - user shouldn't be able to add ATP trigger
- ATP not enabled, readonly flag enabled, vault empty - user shouldn't be able to add ATP trigger
> Auto-Take Profit safety switch

- components/vault/GeneralManageTabBar.tsx
- components/vault/ProtectionControl.tsx
- features/automation/common/sidebars/getAutoFeaturesSidebarDropdown.ts
- features/automation/optimization/autoBuy/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/optimization/autoTakeProfit/controls/AutoTakeProfitFormControl.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarSetupAutoTakeProfit.tsx
- features/automation/optimization/common/controls/OptimizationFormControl.tsx
- features/automation/optimization/common/helpers.ts
- features/automation/optimization/constantMultiple/controls/ConstantMultipleFormControl.tsx
- features/automation/optimization/constantMultiple/sidebars/SidebarSetupConstantMultiple.tsx
- features/automation/protection/autoSell/controls/AutoSellFormControl.tsx
- features/automation/protection/autoSell/sidebars/SidebarSetupAutoSell.tsx
- features/automation/protection/common/controls/ProtectionFormControl.tsx
- features/automation/protection/stopLoss/controls/StopLossFormControl.tsx
- features/automation/protection/stopLoss/helpers.ts
- features/automation/protection/stopLoss/openFlow/openVaultStopLoss.ts
- features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
- features/form/commonValidators.ts
- public/locales/en/common.json
- fixed issue with slider (missing fill color)
- fixed issue with optimization dropdown in borrow vaults
- fixed issue when CM and ATP were enabled (both forms were displayed)
- ATP slider and SL slider should have correct fill color
- borrow vault should have dropdown when ATP feature toggle enabled (but without CM item to select)
- borrow vault shouldn't have dropdown when ATP feature toggle disabled
- enable ATP and CM and check if only one form is displayed
> Auto-Take Profit dropdown and slider fix

- features/discovery/common/DiscoveryTable.tsx
- features/discovery/controllers/DiscoveryControl.tsx
Added preloader to Oasis Discovery at the beginning, when there is no table to be displayed and while user changes something in filters triggering data reload.
Try to change something in filters. Since it operates on mock json, it might require setting up a throttling to see it in effect.
> Discovery table preloader

- features/discovery/common/DiscoveryTableDataCellContent.tsx
- public/locales/en/common.json
Due to rename of `cid` field to `cdpId`, vault ids weren't displayed in first column.
- Changed all `cid` field name occurrences to `cdpId`.
Check out if first column in Discovery tables contains vault id.
> Vault numbers in Discovery table

- features/earn/aave/open/services/calculateSimulation.ts
Changes from the stETH/ETH strategy release discussion.
With that change the header yields are no longer refreshed after amount change and the APY and header yields (based on minimum multiply, so the left one in Current yield) are the same.
> Changed annualisedYield1Year to annualisedYield7days

- components/GenericSelect.tsx
- helpers/useToggle.ts
Turns out `react-select` doesn't emmit focus event on mobile on DOM, so I had to add custom handling for mobile devices. Thanks to that generic select can utilize native select which makes using it on mobile much easier.
- Moved open/close state management from focus to click on custom element,
- moved borders to custom element since `react-select` rerenders whole DOM on change, so it was impossible to use smooth animations,
- added native select that covers custom on for mobile devices.
> Generic select mobile handling

- components/GenericSelect.tsx
- components/Header.tsx
- features/discovery/common/DiscoveryNavigation.tsx
- features/discovery/common/DiscoveryWrapperWithIntro.tsx
- features/discovery/helpers.ts
- helpers/useToggle.ts
- pages/discovery/index.tsx
On mobile, instead of links with icon, navigation becomes a select.
- Added select with navigation for small screens on Discovery pages,
- extracted Discovery URL as const to be reused in all places that links to it.
Check out Discovery page on smaller screens.
> navigation on mobile

- features/discovery/controllers/DiscoveryControl.tsx
- features/discovery/helpers.ts
- Added `table` param to all Discovery requests.
Check if all requests for data for Discovery contains `table` param.
> Pass table param to discovery filters query

- features/earn/aave/open/state/openAaveStateMachine.ts
- now base riskratio in open and simulate machine are the same
- go to open earn aave steth view
- input amount, there should be no change in the header yield numbers
> AAVE stETH/ETH amount input fix

- features/vaultsOverview/pipes/positions.ts
- fixed link to AAVE position (inv. changes in https://github.com/OasisDEX/oasis-borrow/pull/1564)  
- go to `My positions`
- AAVE position link should work fine 👌
> Fixes AAVE position link (on position page)

- features/content/faqs/aave/index.tsx
- features/earn/aave/manage/containers/AaveManageView.tsx
- features/earn/aave/open/components/SimulateSectionComponent.tsx
- features/earn/aave/open/containers/AaveOpenView.tsx
- rename FAQ tab to position info
- make the banner button work at the bottom of the open position page
- click the button and the position info tab top scrolls into view
> fix learn more link

- features/proxyNew/state/actions.ts
- features/proxyNew/state/machine.ts
- features/proxyNew/state/services.ts
This was supposed to be for [this issue](https://app.shortcut.com/oazo-apps/story/6375/create-proxy-does-not-go-back-to-open-position-from-end-of-create-proxy-flow) but the problem seems to be deeper inside @oasisdex/transactions somewhere, and I don't want to meddle with it as we don't see this issue with positions and on non-hardhat chains.  But I removed some vestigial code, hence the PR.
- open aave position with + without proxy
- test some non-happy paths (cancel proxy creation etc)
> delete some code

- components/EstimationOnClose.tsx
- features/automation/optimization/autoTakeProfit/controls/AddAutoTakeProfitInfoSection.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitEditingStage.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarSetupAutoTakeProfit.tsx
- public/locales/en/common.json
- updated slider right label in ATP form
- paragraph under slider shows now estimated col ratio at trigger
- removed trigger col ratio from summary information
- in places described above correct labels and values should be present
> Update ATP estimation labels

- features/discovery/common/DiscoveryCards.tsx
- features/discovery/common/DiscoveryTable.tsx
- features/discovery/helpers.ts
- Created `getRowKey` method for generating keys for tables with dynamic data.
> 🧭 Unique keys for Discovery tables

- components/vault/VaultErrors.tsx
- components/vault/VaultWarnings.tsx
- features/automation/api/automationTriggersData.ts
- features/borrow/manage/pipes/manageVault.ts
- features/borrow/manage/pipes/manageVaultValidations.ts
- features/borrow/manage/pipes/viewStateTransforms/manageVaultConditions.ts
- features/borrow/manage/pipes/viewStateTransforms/manageVaultEnvironment.ts
- features/form/commonValidators.ts
- features/form/errorMessagesHandler.ts
- features/form/warningMessagesHandler.ts
- features/multiply/manage/pipes/manageMultiplyVault.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- features/multiply/manage/pipes/manageMultiplyVaultEnvironment.ts
- features/multiply/manage/pipes/manageMultiplyVaultValidations.ts
- helpers/messageMappers.ts
- public/locales/en/common.json
- added error and warning messages to vault overview (borrow & multiply) when user tries to reopen vault when there is already ATP enabled
- setup ATP on vault, close vault, try to reopen position (generate debt) and see if warning or error (in that case you will most likely need to manually overwrite next price in code) regarding existing ATP is shown. Do it both on borrow and multiply vault. For error case user shouldn't be able to proceed without removing ATP first.
> Added Take Profit validations in vault overview

- features/earn/aave/manage/components/ManageSectionComponent.tsx
- added multiplication by 100 to the blockchain data
- go to your aave steth position, Variable annual fee should be same as on https://app.aave.com/markets/
> Fixes Variable annual fee being off 100x

- components/productCards/ProductCardEarnAave.tsx
- features/earn/aave/manage/components/ManageSectionComponent.tsx
- helpers/useSimulation.ts
- added aaveSthEthYieldsQuery call to retrieve a single 7 day yield
- see image above
> Added Net APY on current AAVE position

- features/earn/aave/common/components/SidebarAdjustRiskView.tsx
- Switched the increase and decrease labels 
- Current price was always 1.00 (due to rounding), now it has two decimals.
> Switch increase with decrease, Current price with decimals

- components/productCards/ProductCardEarnAave.tsx
- features/earn/aave/manage/components/ManageSectionComponent.tsx
- helpers/useSimulationYields.ts
- after changes in calculateSimulation the numbers weren't correct so I changed it to use raw yield numbers
- `/earn`
- should display proper 7/90 day net APY
> Reverted to use yields instead of simulation in earn AAVE product card

- features/earn/aave/common/BaseAaveContext.ts
- features/earn/aave/common/components/SidebarAdjustRiskView.tsx
- features/earn/aave/manage/services/getManageAaveStateMachine.ts
- features/earn/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/earn/aave/manage/state/manageAaveStateMachine.ts
- features/earn/aave/open/sidebars/SidebarOpenAaveVault.tsx
- features/earn/aave/open/state/openAaveStateMachine.ts
Covers https://app.shortcut.com/oazo-apps/story/6380/ok-button-from-adjust-page-does-not-reload-position and https://app.shortcut.com/oazo-apps/story/6411/no-async-feedback-on-manage-page
- OK button from manage page now goes back to the start of the machine.
- Button should be blocked when we are reading transaction data, and spinner shown.
- adjust a position - button should now redirect back to the start of the user flow.  Edit the position again without reloading the page.  It should work.
- move the slider around a bunch when we are waiting for call data from maths lib. It should show loading spinner and block the UI from progressing.  Check for race conditions.  Check on mobile also.
> Fix ok button from open position, and show loading spinner and block button

- blockchain/utils.test.ts
- blockchain/utils.ts
- features/earn/aave/open/state/openAaveStateMachine.ts
Check that entry fees includes estimated gas fees.
> convert gwei to ETH, and add to entry fees

- components/AppContext.ts
- components/productCards/ProductCardEarnAave.tsx
- features/earn/aave/helpers/hasActiveAavePosition.ts
- features/earn/aave/helpers/useAaveRedirect.ts
- features/earn/aave/open/sidebars/SidebarOpenAaveVault.tsx
- added check on open aave position page
- added check on aave product card  
- if you dont have the aave position nothing changes
- if you do have an aave position you should be redirected to it when clicking the product card on `/earn`
- if you do have an aave position you should be redirected to it when going to the open position page by hand (ie. typing the address in the browser by hand)
> Added redirection to current position if user has any 

- features/discover/common/DiscoverTableDataCellContent.tsx
- features/discover/filters.ts
If for any reason database would return asset name for which we don't have metadata, table would thrown an error. This PR fixes that issue.
- Added validation for asset returned from database.
> 🧭 Discover asset cell validation

- features/earn/aave/common/BaseAaveContext.ts
- features/earn/aave/manage/services/getManageAaveStateMachine.ts
- features/earn/aave/manage/state/manageAaveStateMachine.ts
- features/earn/aave/open/services/getOpenAaveStateMachine.ts
- features/earn/aave/open/sidebars/SidebarOpenAaveVault.tsx
- features/earn/aave/open/state/openAaveStateMachine.ts
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- Possibility to retry transaction on open/close/adujst
- Back button on sidebars
> Page does not refresh when rejecting transactions

- features/vaultsOverview/pipes/positions.ts
- have an aave position
- load positions overview page
- observe that the positions list does not flicker in and out every 10 seconds
> stop flicker positions over page with aave positions

- analytics/analytics.ts
- components/Header.tsx
- features/discover/common/DiscoverCards.tsx
- features/discover/common/DiscoverData.tsx
- features/discover/common/DiscoverNavigation.tsx
- features/discover/common/DiscoverTable.tsx
- features/discover/common/DiscoverTableBanner.tsx
- features/discover/common/DiscoverTableDataCellContent.tsx
- features/discover/controllers/DiscoverControl.tsx
- features/discover/helpers.ts
- features/discover/views/DiscoverView.tsx
All events are based on this sheet https://docs.google.com/spreadsheets/d/1Jie1SX_5i4-jDZLMKnCUkq4lhchkPKonIOVPNNJtsA8/edit#gid=308180383 with an exception of `ScrollTable` event which will be implemented differently, as a separated story.
- Added dedicated events for tracking user behavior on Discover Oasis pages.
- Try to trigger all trackable actions on Discover page UI, then look for request to `/api/t` and compare sent parameters with those required by Google sheet,
- please note that all parameters in `eventBody` were intentioanlly changed to camelCase and all event names to kebabCase.
> 🧭 Discover mixpanel analytics

- features/automation/optimization/autoTakeProfit/state/autoTakeProfitStatus.ts
- features/automation/optimization/autoTakeProfit/validators.test.ts
- features/automation/optimization/autoTakeProfit/validators.ts
Just for testing purposes, to be changed back later.
- Set min on TP slider to `1`,
- turned off `autoTakeProfitTriggeredImmediately` validation.
> Temporary allow to set Take profit trigger at $0

- features/earn/aave/components/AavePositionHeader.tsx
- features/earn/aave/open/state/aaveStEthSimulateStateMachine.ts
- Added `baseYieldsMin` to the AaveStEthSimulateStateMachine to use it in the header
- Its the same thing as `yieldsMin` on the first simulation, but `yieldsMin` changes as the user is changing the slider value
- go to aave steth open page (without active position)
- provide some ETH in the first step
- on second step change the slider value
- the header should stay the same
> Added baseYieldsMin to the AaveStEthSimulateStateMachine to use it in the header

- features/earn/aave/constants/index.ts
- features/earn/aave/open/components/SimulateSectionComponent.tsx
- features/earn/aave/open/services/getSthEthSimulationMachine.ts
- features/earn/aave/open/state/openAaveStateMachine.ts
- Lowered the default simulation amount to 100 ETH (from 100000)
- Set the default multiple for the simulation on open to 2x
- Hidden the since inception for now
- go to `earn/aave/open/stETHeth`
- it should show 100 ETH as base for calculations (before user input)
- it should show 2x multiply as default (before moving slider and after deposit input)
- it _shoudn't_ display `Since inception` simulation
> Lucian feedback on opening

- components/HomePageBanner.tsx
- components/TabBar.tsx
- features/homepage/HomepageView.tsx
- public/locales/en/common.json
- updated the referral banner copy (changed it to more generic "HomepageBanner") + change the logo to stETH + remove the 5% and link this to the opening aave steth position
- updated the homepage to default to #earn instead of #multiply.
- check the above changes on the home page, should look like this: (note the banner above headline and selected tab on the bottom):
> Marketing the product

- features/earn/aave/open/state/openAaveStateMachine.ts
- added a guard to _not_ show the spinner on AAVE steth open page before the user has created a proxy
- go to aave steth open page using a wallet with no proxy 
- there should be no spinner spinning forever when you input the deposit amount
> No spinner before user has the proxy

- features/automation/optimization/autoTakeProfit/state/autoTakeProfitStatus.ts
- features/automation/optimization/autoTakeProfit/validators.test.ts
- features/automation/optimization/autoTakeProfit/validators.ts
This reverts commit 8086b9495906bda7da7571fde5ed6731bff77288.
- reverted changes that were created to suppress FE validation of ATP
- slider min value should be set to token market price
- validations should be in place
- tests should pass
> Revert "Temporary allow to set Take profit trigger at $0 (#1609)"

- pages/discover/[slug].tsx
Due to dynamic links in Discover, any language other than default English was returning `404` error.
- Added `locale` to static path generation.
Try accessing other languages on any Discover page.
> 🧭 Support translations on Discover pages

- components/Footer.tsx
- features/discover/api.ts
- features/discover/common/DiscoverCards.tsx
- features/discover/common/DiscoverData.tsx
- features/discover/common/DiscoverError.tsx
- features/discover/common/DiscoverPreloader.tsx
- features/discover/common/DiscoverTable.tsx
- features/discover/common/DiscoverWrapperWithIntro.tsx
- public/locales/en/common.json
- Removed `zIndex` from the footer, since it was overlapping filters options in Discover (and probably some other places in edge cases that we missed),
- errors are now displayed based on message returned from API,
- tiny tweaks in Discover layout.
- To receive `UNKNOWN_ERROR` error, in `/features/discover/meta.tsx` file change `endpoint` to some gibberish,
- to receive `NO_ENTRIES` error, in one of the json files in `/public/mocks/discover` remove all data and leave empty `rows` array,
- this is already handling actual API response, so if you have seeded `discovery` table in database, you can test it changing one of meta endpoints to `/api/discover`,
- I removed `zIndex` from footer, so it would be good to do some quick smoke tests and check random pages if there isn't something funny …
> 🧭 Discover API errors handling and loader tweaks

- features/discover/common/DiscoverTableDataCellContent.tsx
- features/discover/helpers.ts
- features/discover/types.ts
- public/locales/en/common.json
- public/mocks/discover/highest-risk-positions.json
- public/mocks/discover/largest-debt.json
- Liquidated vault are displayed with pill explaining when it was liquidated.
- See for `/discover/highest-risk-positions` if liquidated row contains time ago in its pill.
> 🧭 Support timeAgo in Discovery liquidation status

- components/dumb/SliderValuePicker.tsx
- features/aave/common/components/SidebarAdjustRiskView.tsx
- public/locales/en/common.json
- Adding the units on both sides
- Moving the big word "Current" to be Current Price
- Moving the historical ratio link
- Having the color of the Liquidation price change in stead of the current Price
- slider changes color (filled from left side)
- (mine) moved the message up so the user can see it without scrolling and removed the bullet)
- see attached pictures for changes
Before:
After:
> Feedback from Chris/Barron

- blockchain/calls/aave/aaveLendingPool.ts
- blockchain/calls/aave/aaveProtocolDataProvider.ts
- features/aave/helpers/hasAavePosition.ts
- features/aave/manage/services/getAaveProtocolData.ts
- features/aave/open/services/getOpenAaveStateMachine.ts
- features/aave/view/containers/AavePositionView.tsx
- features/vaultsOverview/pipes/positions.ts
- pages/aave/[address].tsx
- Before without a connected wallet, the page displayed aave for the address, not for the proxy account connected to the address. 
- Now, if a proxy exists, the page will display the position for the proxy. If it doesn't exist, the page will display the position for the address from the URL. 
- Go to the position page without connected wallet.
> Non owner view for AAVE position.

- components/AutomationContextProvider.tsx
- features/automation/common/context/getAutomationAavePositionData.ts
- features/automation/common/context/getAutomationEnvironment.ts
- features/automation/common/context/getAutomationMakerPositionData.ts
- features/automation/common/context/getAutomationPositionData.ts
- helpers/getVaultProtocol.ts
Assuming that different protocols may need different data sources that just `generalManageVault`, I prepared dedicated methods for data extractions.
`getAutomationPositionData` doesn't have any assumptions, just simply returns entire `positionData` object.
`getAutomationEnvironment` returns only part of the data, since some of environmental information are shared between protocols (ETH market price), so `environmentData` is later merged using those partial data.
> Separated methods for position and environment data extraction

- features/discover/controllers/DiscoverControl.tsx
- features/discover/filters.ts
- features/discover/meta.tsx
- handlers/discover/getDiscoveryData.tsx
- handlers/discover/helpers.ts
"All" option used to display all available tokens, no matter what was available in dropdown. From now it will only merge those that were in options list.
- Removed generic "all" option from assets filter,
- created `getGenericArrayFilter` method for API filtering,
- removed `getAssetFilter` method as dedicated one for assets is no longer needed.
- Try using all options combinations in assets filter.
> 🧭 Auto generate "all" option in assets filter in Discover

- features/discover/common/DiscoverData.tsx
- features/discover/common/DiscoverFilters.tsx
- features/discover/common/DiscoverTable.tsx
- features/discover/controllers/DiscoverControl.tsx
- Added `isSticky` props instead of checking amount of rows.
> 🧭 Discover table uses `isSticky` prop

- pages/security.tsx
- public/locales/en/common.json
- Added link to newest audit on the `/security`
- Fixed other labels so they read `Audit Report` everywhere
- go to `/security`
- there should be a new link `Modular Proxy Actions Audit Report`
> Added Modular Proxy Actions Security Audit link to Security page

- pages/api/proxy/index.tsx
Extremely simple internal proxy for local testing API that doesn't allow for request directly from the browser.
- Created `api/proxy` endpoint.
- For example, try requesting `/api/proxy?url=https://staging.oasis.app/api/discover?asset=ETH%2CWBTC%2CMANA%2CLINK%2CGUSD%2CYFI%2CUNI%2CMATIC%2CWSTETH%2CCRVV1ETHSTETH&size=&table=highest-risk-positions`.
> Proxy for API testing

- server/database/migrations/013-add-users-who-follow-vaults.sql
- server/database/schema.prisma
- added junction table which specifies which addresses follow which vaults of what type on given chainid
- Run dev.sh
- see if migration works
- try to manually add in db records that define user following vault
- Check for edge cases like multiple users can follow the same vault of the same type
- One user can follow multiple vaults
- One user can follow vaults with the same ids on different chains
> created users_who_follow_vaults table

- features/discover/common/DiscoverFilters.tsx
- features/discover/common/DiscoverMultiselect.tsx
- features/discover/filters.ts
- features/discover/helpers.ts
- features/discover/meta.tsx
- features/discover/types.ts
- handlers/discover/getDiscoveryData.tsx
- handlers/discover/helpers.ts
- Added different types of filter types as enum: `single`, `multi`, `hidden`,
- set "size" and "multiple" as `multi`,
- set "asset" only for "Most Yield Earned" as `hidden`,
- refined API calls to accept more than one range as `where` filter.
- Firstly, you need local Discover database to test it. Since API call were altered, proxy'ing request to staging won't work ,
- after getting yourself localdatabase or connection to staging one (only connection to staging, not API proxy), just test entire filters section.
> 🧭 Discover multiselect for "size" and "multiple" filters 

- features/walletAssociatedRisk/WalletAssociatedRisk.tsx
- handlers/risk/get.ts
- removed alert and disconnect call when error occurs
- risky when risk indicator exists and totalVolumeUsd greater than zero
- use risky and non risky wallet on mainnet, connect wallet on the owner page and check response from api about risk
- when error occurs user shouldn't be disconnected and alert shouldn't pop up
> Adjusted risk handling

- features/discover/common/DiscoverMultiselect.tsx
- icons.d.ts
- theme/icons.tsx
- Changed item selection mark from standalone tick to two-state checkbox.
> 🧭 Nicer checkbox for Discover multiselect

- handlers/discover/getDiscoveryData.tsx
- Added `AND` between `OR` for "multiple" and "size" filters.
See if selecting single option in "multiple" or "size" filter on "Highest Multiply P&L" page has any effect.
> 🧭 Fix OR filter for Highest Multiply P&L in Discover

- features/discover/common/DiscoverFilters.tsx
- features/discover/common/DiscoverMultiselect.tsx
- theme/icons.tsx
Turns out the icon I've add was already available in external library and keeping it in our repo was unnecesary. Also, it broke one of the places where it was used before 🤷
- Removed local `checkmark` icon,
- sneaked tiny change in Discover UI - all filters are taking equally 1/4 of available space in width.
> 🧭 Remove checkbox icon

- features/aave/oasisActionsLibWrapper.ts
- features/earn/aave/riskSliderConfig.tsx
- CUSTOM_OPERATION instead of INCREASE_POSITION and DECREASE_POSITION
- 4 digits for stETH/ETH price
- Open position
- Try to decrease or increase risk
> Fix failing transaction for adjusting risk. 

- components/vault/GeneralManageLayout.tsx
- components/vault/VaultHeaderContainer.tsx
- changes the positioning of stuff in header
- go to any vault
- tooltip displayed on hover should not be obscured by other elements
> Fixes tooltip visibility on header

- helpers/useFeatureToggle.ts
As in title.
- Changed `DiscoverOasis` to `true`.
Open Oasis.app in incognito mode and check if main navigation contains link to Discover by default.
> 🧭 Set Discover feature flag `true` by default

- features/automation/common/sidebars/CancelAutoBSInfoSection.tsx
- features/automation/optimization/autoBuy/sidebars/SidebarAutoBuyRemovalEditingStage.tsx
- features/automation/optimization/autoBuy/sidebars/SidebarSetupAutoBuy.tsx
- features/automation/optimization/autoTakeProfit/sidebars/SidebarAutoTakeProfitRemovalEditingStage.tsx
- features/automation/optimization/constantMultiple/sidebars/SidebarConstantMultipleRemovalEditingStage.tsx
- features/automation/protection/autoSell/sidebars/SidebarAuteSellCancelEditingStage.tsx
- features/automation/protection/autoSell/sidebars/SidebarSetupAutoSell.tsx
- features/automation/protection/stopLoss/sidebars/SidebarCancelStopLossEditingStage.tsx
- public/locales/en/common.json
- fixed summary when removing Auto-(Buy/Sell) trigger and vault is closed
- prepared one copy for all automation features regarding trigger removal description
- visit vault `29833` on mainnet, go to optimization tab and to remove auto-buy trigger step, summary should show correct data
> Fix summary when removing Auto-(Buy/Sell) trigger and vault is closed

- handlers/discover/helpers.ts
Turns out timestamp in one place was mistakenly multiplied by 1000.
- Removed timestamp multiplier for liquidated vaults API handlers,
- since `DiscoverTableVaultStatus.LIQUIDATED` and `DiscoverTableVaultStatus.BEING_LIQUIDATED` now returns exactly the same thing, I moved them to single case statement.
> 🧭 Discover - incorrect timestamp in Highest-Risk Positions

- blockchain/aaveLiquidations.ts
- components/AppContext.ts
- features/aave/manage/containers/AaveManageView.tsx
- features/notices/VaultsNoticesView.tsx
- features/notices/helpers.ts
- public/locales/en/common.json
- added `AavePositionNoticesView` which provide handling for all banners within aave position view
- added `getAavePositionLiquidation$` observable which gets info about liquidation events from `aaveLendingPool` contract, if liquidation happened but later user perform deposit action banner wont be shown
- small adjustment to copies
- to test `ownership` banner just visit aave multiply position when connected / not connected
- to test `liquidated` banner you will need to mock proxy address in `AavePositionNoticesView` when assigning value to `preparedAaveLiquidations$`,  you can use following address `0xf3704de41D39688514775FD65722d346c06042aD`
- to test `aboveMaxLtv` banner …
> Aave position banners

- components/AppContext.ts
- prevents multiple calls on homepage (and probably other pages)
> Added memoization to aaveAvailableLiquidityInUSDC call

- components/FeatureToggleRedirect.tsx
- helpers/useFeatureToggle.ts
- pages/ajna/index.tsx
Covers:
https://app.shortcut.com/oazo-apps/story/7032/research-extended-theme-ui
and partialy:
https://app.shortcut.com/oazo-apps/story/7011/spike-front-end-architecture
https://app.shortcut.com/oazo-apps/story/7034/research-page-blocked-by-feature-flag
- Created empty Ajna page as a playground for testing spike features,
- Added `Ajna` feature flag,
- Created `WithFeatureToggleRedirect` component that redirects to selected page if user doesn't have required feature flag set to `true`,
- Tested partial overwriting of theme in `theme.ui`.
- Go to `/ajna` page with and without `Ajna` feature flag turned on.
> 🧿 Ajna empty page

- features/aave/common/StrategyConfigTypes.ts
- features/aave/manage/containers/AaveManageView.tsx
- features/automation/contexts/AaveAutomationContext.tsx
- features/earn/aave/components/ManageSectionComponent.tsx
- features/earn/aave/components/PositionInfoComponent.tsx
- features/earn/aave/components/ViewPositionSectionComponent.tsx
- uses reserve data from debt token
- renames the data passed around
- open an AAVE earn position and observe the the variable annual fee represents the debt token (eth in this case):
- variable annual fee info from aave protocol is available [here](https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts) from the `ProtocolData` contract
> Fix variable annual fee issue

- features/automation/common/state/automationFeatureChange.ts
- features/automation/common/state/automationFeatureTxHandlers.ts
- features/automation/common/types.ts
- features/automation/protection/stopLoss/controls/StopLossFormControl.tsx
- features/automation/protection/stopLoss/sidebars/SidebarAdjustStopLossEditingStage.tsx
- features/automation/protection/stopLoss/sidebars/SidebarSetupStopLoss.tsx
- features/automation/protection/stopLoss/state/stopLossTxHandlers.ts
- features/automation/protection/stopLoss/state/useStopLossReducer.ts
- helpers/useStateReducer.ts
Extracted best parts from [use-state-reducer](https://github.com/OasisDEX/oasis-borrow/tree/pk/use-state-reducer) branch to [auto-ui-changes-to-use-reducer-switch](https://github.com/OasisDEX/oasis-borrow/tree/sp/auto-ui-changes-to-use-reducer-switch). 
- Added `useStateReducer` hook as parent to to `useStopLossReducer` and to be used in all feature state reducers,
- fixed type errors.
See if Stop-loss is still working.
> Include `useStateReducer` to `useStopLossReducer`

- features/automation/protection/stopLoss/state/useStopLossReducer.ts
- helpers/useStateReducer.ts
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/iOVri1dITGg/0.jpg)](https://www.youtube.com/watch?v=iOVri1dITGg&t=72s)
Changed old and boring name `useStateReducer` to new, fancy, sexy and shiny `useReducto`.
> Rename to ⚡ `Reducto`

- features/borrow/manage/pipes/viewStateTransforms/manageVaultConditions.ts
- features/form/commonValidators.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- fixed after col ratio below trigger ratio validation
- if SL is enabled and current col ratio is close to SL ratio error shouldn't be visible when user try to deposit (basically when `afterCollateralizationRatioAtNextPrice` is greater than `collateralizationRatioAtNextPrice` error shouldn't be displayed)
> Fixed after col ratio below trigger ratio

- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/open/sidebars/SidebarOpenAaveVault.tsx
- features/aave/open/state/openAaveStateMachine.ts
- recalc proxy things when web3 context is changed
1. Step 1 - open Maker ETH position (borrow or multiply) using first account on HH
2. Step 2 - open an aave position
3. Step 3 - go to the position at the end of the flow by clicking the button, or click action on Earn product card (hitting URL directly doesn't reproduce)
- Expected: navigate to the position
- Actual: it redirects to /aave/undefined when clicking the opening link and shows a client-side error <- ensure this doesn't happen.
- ensure that a previously-created DS proxy is reused.
- closing position puts funds back in the wallet
> fix load manage vault

- components/productCards/ProductCardMultiplyAave.tsx
- features/aave/helpers/aavePrepareReserveData.ts
- public/locales/en/common.json
- https://app.shortcut.com/oazo-apps/story/7142/product-cards-data-liquidity-available-and-variable-annual-fee-are-looking-at-the-collateral-token-in-stead-of-the-debt-token
- https://app.shortcut.com/oazo-apps/story/7146/product-cards-on-homepage-on-multiply-tabs-have-earn-content
- uses the debt token to show the liquidity-available-and-variable-annual-fee
- updates the card banners to be the same as the other multiply cards
- go to multiply tab and see card using debt data and showing the right banner
> use debt liquidity on product cards

- features/multiply/aave/components/AaveMultiplyPositionData.tsx
- Changed the precision of the values in the overview of the multiply position (and on opening)
- check the precision of the values in the overview of the multiply position (and on opening):
- should have 2 decimals for: net value, Liquidation price, Buying power
- should have 4 decimals for: debt token amount
Old: 
New:
> Changed the precision of the values in the overview

- features/aave/open/sidebars/SidebarOpenAaveVaultEditingState.tsx
- aave multiply opening
- clicking on balance now does something
- go to aave multiply opening
- click on balance
- input should update with your balance value
> Added action handling maximum balance

- components/navigation/Navigation.tsx
- components/navigation/NavigationMenu.tsx
- components/navigation/NavigationMenuDropdown.tsx
- components/navigation/NavigationMenuDropdownContent.tsx
- components/navigation/NavigationMenuLink.tsx
- components/navigation/NavigationMenuPanel.tsx
- components/navigation/NavigationMenuPointer.tsx
- public/locales/en/common.json
Still missing right panel for wallet connection and other services.
[Tab-1671125085929.webm](https://user-images.githubusercontent.com/16230404/207927355-d9895e2c-4650-47df-ba9e-1b06459e5bd1.webm)
- Fixed issues with dropdown animation,
- split navigation component into smaller chunks to increase readability.
- Go to `/ajna` page with `Ajna` feature flag enabled. Without it there should be redirect to homepage,
- compare with figma design: https://www.figma.com/file/XAUn9bc0mlzIS63d9yDUUF/Ajna-x-Oasis?node-id=1268%3A55941&t=ZOXqgZr578kCXQWQ-0.
> 🧿 Ajna dropdown navigation

- components/Header.tsx
- components/navigation/Navigation.tsx
- components/navigation/NavigationActions.tsx
- components/navigation/NavigationMenuDropdown.tsx
- components/navigation/NavigationMenuOrb.tsx
- components/navigation/content/ConnectWalletButton.tsx
- components/navigation/content/MyPositionsLink.tsx
- components/navigation/content/NotificationsOrb.tsx
- components/navigation/content/SwapOrb.tsx
- components/notifications/NotificationsCenter.tsx
- components/notifications/NotificationsIconButton.tsx
- features/ajna/controls/AjnaNavigationController.tsx
- helpers/useAccount.ts
- theme/index.tsx
- Add wallet controllers,
- mobile support.
- Created `NavigationOrb` component which is a common component for all user actions and panels in navigation,
- implemented `SwapOrb` and `NotificationsOrb` using `NavigationOrb` so both of them can use the same styling, animation and interaction,
- added "Connect wallet" button to Ajna navigation,
- created `useAccount` hook that contains selected information about user based on global context as a shorthand; for now it's if user is connected and how many positions he has open. That should be further whenever there is opportunity for something to be moved there,
- Go to `/ajna` page with `Ajna` feature flag enabled. Without it there should be redirect to homepage,
- test if orbs behavior is similar to those on main landing page (but better 😎), …
> 🧿 User actions for Ajna navigation

- components/Header.tsx
- Fixed issue with condition that was rendering `0` when user has no open vaults next to "My positions" link in navigation.
Use two different wallets to test it. One that already has vaults and one that doesn't. When connected, check if number of vaults is displayed correctly and there's no `0` when you don't have any.
> Remove 0 showing next to my positions

- features/aave/services/readPositionCreatedEvents.ts
- create steth/eth position using DS proxy
- make sure no DPM positions
- 👉 position should be shown on overview page
- create a DPM position
- 👉 position should not be shown twice
> fix aave dsproxy positions not displaying if no dpm proxy positions

- components/vault/VaultActionInput.tsx
- features/aave/AaveContext.ts
- features/aave/common/BaseAaveContext.ts
- features/aave/common/components/SidebarAdjustRiskView.tsx
- features/aave/common/components/informationContainer/FeesInformation.tsx
- features/aave/common/components/informationContainer/PriceImpact.tsx
- features/aave/common/components/informationContainer/TransactionTokenAmount.tsx
- features/aave/common/services/getParametersMachines.ts
- features/aave/helpers/getTxTokenAndAmount.ts
- features/aave/manage/containers/AaveManageStateMachineContext.tsx
- features/aave/manage/services/getManageAavePositionStateMachineServices.ts
- features/aave/manage/services/getManageAaveStateMachine.ts
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/oasisActionsLibWrapper.ts
- features/aave/open/services/getOpenAaveStateMachine.ts
- features/aave/strategyConfig.ts
- helpers/api/tokenTickers.ts
- package.json
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- yarn.lock
- added Payback debt, withdraw collateral, deposit collateral, borrow debt to the sidebar in the Aave multiply positions
- should work with aave steth/eth position
- go to any Aave position and try to do any above actions using the sidebar
> [UI] AAVE Multiply adjusting UI

- features/aave/manage/state/manageAaveStateMachine.ts
- changed how and when the borrowDeposit machine is spawned and killed
- go to your steth/eth position
- while switching tabs in the sidebar there should be no error
> Fixed an error while switching tabs on sidebar

- features/aave/open/containers/AaveOpenView.tsx
- Only show after t/x pills once the user hits the review step
- Open an aave multiply position and double check pills only appear in the last step before submitting the t/x can use url like:  `http://localhost:3000/multiply/aave/open/stETHusdc?network=hardhat#simulate`
> Show pill only on reviewing step before tx is executed

- features/borrow/manage/pipes/viewStateTransforms/manageVaultConditions.ts
- features/form/commonValidators.ts
- features/multiply/manage/pipes/manageMultiplyVaultConditions.ts
- removed unnecessary margin from method which validates col ratios and given threshold
- users should be always able to deposit to vault when SL is enabled
- user shouldn't be able to reopen vault when SL is active and new col ratio will be below SL trigger ratio
> Automation validation update

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- fixed dot notation
- to payback debt tab on Aave multiply position
- app should'nt crash
> Fixed app crashing when going to payback debt tab on Aave multiply position

- features/aave/open/containers/AaveOpenView.tsx
- features/aave/open/sidebars/SidebarOpenAaveVaultEditingState.tsx
- features/aave/open/state/openAaveStateMachine.ts
- pages/api/t.tsx
- Resetting the form value when removing the amount or switching tabs on earn steth/eth open view  
- go to earn steth/eth open view
- input an amount
- delete it, transaction info should dissapear
- input some amount again
- switch tabs to Position info (on the left)
- switch back to Overview tab
- value and transaction info should be gone
> Resetting the form value when removing the amount or switching tabs

- features/aave/open/sidebars/SidebarOpenAaveVaultEditingState.tsx
- added a loader which prevents displaying value input before the token price is known
- go do Aave multiply (any kind)
- you should be able to input a precise amount of chosen token (down to ~0.01 USD in auxiliary)
> Fixed decimal places input on Aave multiply

- components/vault/detailsSection/ContentCardLtv.tsx
- changed how the Liquidation Threshold in Aave multiply overview is displayed
- go to your Aave multiply position
- Liq Threshold should be (for example) 80% instead of 0.8
> Changed how the Liquidation Threshold in Aave multiply overview is displayed

- components/productCards/ProductCardsContainer.tsx
- components/productCards/ProductCardsFilter.tsx
- features/asset/AssetView.tsx
- helpers/productCards.ts
- pages/asset/[asset].tsx
- Added Aave Earn and Multiply cards on the assets page
- Removed AAVE multiply cards in all assets
- go to `/asset/eth` or `/asset/btc`
- there should be Aave product cards on the bottom
- go to `/multiply` page, the cards should respect the current filter
> Added Aave Earn and Multiply cards on the assets page

- features/aave/helpers/getTxTokenAndAmount.ts
- package.json
- yarn.lock
- Library version bump (skipped one action (`SendToken`). With new DPM Implementation we can use `ReturnFunds`).
- Fix the transaction amount for withdrawing.
> [SC-7392] Fix withdrawing ETH collateral

- features/aave/common/components/SidebarAdjustRiskView.tsx
- features/aave/common/components/informationContainer/StrategyInformationContainer.tsx
- multiple was missing from order info here: https://app.shortcut.com/oazo-apps/story/7243/inconsistent-information-in-order-vs-tvl-selected
- reset button moved up: https://app.shortcut.com/oazo-apps/story/7307/reset-text-button-needs-to-be-moved-up
> [7243] re add multiple value to order info, move slider button

- features/aave/common/components/SidebarAdjustRiskView.tsx
- package.json
- yarn.lock
- consumes new version of library
- go to open a steth/eth, wbtc/usdc, and eth/usdc aave position
- observe that price movement is calculated correctly, along with warning threshold when movement is <= 20%
- check open and manage
Related PR: https://github.com/OasisDEX/oasis-earn-sc/pull/165
> 7260 - price movement is incorrect

- components/vault/VaultActionInput.tsx
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- `VaultActionInput` has optional `currencyDigits` in props 
- On manage AAVE position we can specify amount with full precision.
> [SC-7451] Possibility to payback all

- features/aave/common/stEthYield.ts
- quick fix which prevents an error when displaying steth/eth earn product page on goerli (which does not support it fully)
- go to a page which displays steth/eth product card (eg. `/earn`) using hardhat
- everything should work just fine
- switch network to goerli (`/earn?network=goerli`)
- everything should work fine, except the yields are not loading (but not crashing the app)
> Fixes error when there's no yields available for steth/eth (eg. goerli net)

- helpers/useReducto.ts
Extracted just `useReducto` hook from bigger PR that might not get merged soon: https://github.com/OasisDEX/oasis-borrow/pull/1786.
- Added `useReducto` hook.
> Add useReducto independently 🪄

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- public/locales/en/common.json
- changed the copy in the sidebar on Close to collateral/debt view
- go to your position
- select Close position
- the copy should mention the position and not the vault
> Changed Aave multiply close to X copy

- components/productCards/ProductCardMultiplyAave.tsx
- components/productCards/ProductCardsContainer.tsx
- public/locales/en/common.json
- changed Aave Multiply product cards order
- tagged them as New
- view the changes on the home page and on `/multiply` or `/assets` page
> Fixed Aave Multiply product cards order + tagged as New

- features/homepage/HomepageView.tsx
- features/multiply/MultiplyView.tsx
- public/locales/en/common.json
- aave marketing mentions behind feature flag. 
- change AAVE to Aave.
- set AaveDpm feature flag to false
- observe no aave-related copy on homepage or multiply page
- enable feature flag
- observe copy displays on homepage or multiply page
> aave marketing mentions behind feature flag.  change AAVE to Aave.

- features/aave/open/state/openAaveStateMachine.ts
- fixed one comparison which blocked providing all of your funds
- go to opening eg. wbtc/usdc position
- click on `Balance` in the sidebar to deploy all of your tokens
- all should be fine
> Fixed the comparison on canOpenPosition guard

- features/aave/open/state/openAaveStateMachine.ts
- We are blocking the proxy address and the redirection URL when the transaction is starting
> [SC-7551] Wrong redirection on aave positions

- features/aave/helpers/getStrategyConfig.ts
- only attempts to read position created events when DPM proxy is used
- ensure overview can be loaded: http://localhost:3000/owner/0x0F8C58eDf65cbD972D175bFE481bc16fA8dEee45?network=hardhat#simulate
- ensure ds proxy position can be loaded
- local HH: steal steal proxy `0x1182CB8f6F83b76109cCA9A2ED0748390D7fB508` (for wallet `0x0F8C58eDf65cbD972D175bFE481bc16fA8dEee45` above)
- ensure that the position can be changed and closed
> DS proxy steth/eth positions don't display

- features/aave/common/components/SidebarAdjustRiskView.tsx
- features/aave/helpers/aaveAutomationHelpers.tsx
- features/aave/manage/components/StopLossAaveErrorMessage.tsx
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- public/locales/en/common.json
- added error when user have active stop loss trigger on aave multiply position and tries to change ltv to value greater than stop loss ltv
- in order to test it you will need local deployment of automation v2 using hardhat and local instance of cache (ping me if you need help)
- enable `AaveProtection` feature toggle, add stop loss trigger and then try to change your postion (adjust ltv, withdraw collateral, borrow debt) so the ltv will be above stop loss ltv (error should popup and button should be disabled)
> Aave SL overview validation

- features/aave/oasisActionsLibWrapper.ts
- package.json
- yarn.lock
- Collecting fee is calculated in the library
- In the library (done in [PR](https://github.com/OasisDEX/oasis-earn-sc/pull/168)) we have a hierarchy in which token we want to get a fee. In that order: `USDC`, `DAI`, `WETH`, `ETH`, `STETH`, `WBTC`. 
How to test:
- Ensure on the FE in its current state multiply fee should always be in USDC, for earn in ETH.
> [SC-7574] Collecting fee in the library (package version bump)

- components/AppContext.ts
- features/vaultsOverview/pipes/positions.ts
- features/vaultsOverview/vaultsOverview.ts
- added handling of protection indication for aave multiply positions on owner page
- `AaveProtection` feature toggle on, local instance of hardhat and cache, manually deploy automation v2 using hardhat commands
- create Aave multiply postion, add / remove stop loss trigger and verify if it's handled properly on owner page
> Aave protection indication owner page

- blockchain/config.ts
- components/dumb/SliderValuePicker.tsx
- components/vault/detailsSection/ContentCardLtv.tsx
- features/aave/AaveContext.ts
- features/aave/common/BaseAaveContext.ts
- features/aave/common/components/SidebarAdjustRiskView.tsx
- features/aave/helpers/hasUserInteracted.ts
- features/aave/helpers/isUserWalletConnected.ts
- features/aave/oasisActionsLibWrapper.ts
- features/aave/open/containers/AaveOpenView.tsx
- features/aave/open/services/getOpenAaveStateMachine.ts
- features/aave/open/sidebars/SidebarOpenAaveVault.tsx
- features/aave/open/sidebars/SidebarOpenAaveVaultEditingState.tsx
- features/aave/open/state/openAaveStateMachine.ts
- features/multiply/aave/components/AaveMultiplyPositionData.tsx
- features/stateMachines/transactionParameters/transactionParametersStateMachine.ts
- pages/api/tokensPrices.tsx
- pages/earn/[protocol]/open/[strategy].tsx
- pages/multiply/[protocol]/open/[strategy].tsx
- moved the risk adjustment to the first step, available immediately after inputting the amount
- moved the wallet requirement further down the flow so the user is able to simulate the position without wallet connection
- go to any aave (earn or multiply) view with no wallet connection
- deposit amount and risk adjustment should be on one view
- you should be able to simulate the position
- you should be redirected to `/connect` when it's necessary
> Aave Open flow in 1 step (deposit + adjust) + simulation w/no wallet

- components/vault/DefaultVaultHeadline.tsx
- components/vault/EarnVaultHeadline.tsx
- components/vault/GeneralManageControl.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/VaultHeadline.tsx
- features/discover/common/DiscoverCards.tsx
- features/discover/common/DiscoverData.tsx
- features/discover/common/DiscoverResponsiveTable.tsx
- features/discover/common/DiscoverTable.tsx
- features/discover/common/DiscoverTableDataCellContent.tsx
- features/discover/filters.ts
- features/discover/meta.tsx
- features/earn/guni/common/GuniVaultHeader.tsx
- features/follow/common/FollowButton.tsx
- features/follow/common/FollowButtonControl.tsx
- features/vaultsOverview/containers/FollowedTable.tsx
- pages/discover/[slug].tsx
Covers:
https://app.shortcut.com/oazo-apps/story/7598/add-follow-unfollow-button-to-followed-vaults-list
https://app.shortcut.com/oazo-apps/story/7597/add-follow-unfollow-button-to-discover-oasis-table
- Added props to discover table component for vault following support,
- added short and mobile versions for follow vault button,
- added follow vault buttons to discover table,
- added follow vault buttons to table with positions that user is already following.
- Check if follow vault button in short version is available in two tables mentioned above.
Additional notes:
- Discover has `chainId` hardcoded to mainnet, since it doesn't support any other chain.
- Table with users followed vault does not automatically remove record when you decide to unfollow, that will happen only on reload. …
> Follow vault buttons on discover table

- components/productCards/ProductCardsFilter.tsx
[shortcut](https://app.shortcut.com/oazo-apps/story/7596/update-the-featured-product-cards-on-multiply-in-line-with-the-homepage)
- added the cards
- ensure the cards appear under /multiply#featured
> Add Aave product cards to multiply page, featured cards

- features/aave/common/StrategyConfigTypes.ts
- features/aave/open/containers/AaveOpenStateMachineContext.tsx
- features/aave/strategyConfig.ts
- features/asset/AssetView.tsx
- features/homepage/HomepageView.tsx
- features/multiply/MultiplyView.tsx
- helpers/productCards.ts
- helpers/useFeatureToggle.ts
- Remove AAVE Multiply and DPM Proxy feature flags
- Add AAVE Borrow flag
- Ensure all helpers connected with strategy config continue work correctly when no feature flag is specified
- step 1 ...
> Remove AAVE Multiply feature flags and add AAVE Borrow flag

- features/aave/common/StrategyConfigTypes.ts
- features/aave/common/components/AaveHeader.tsx
- features/aave/services/readPositionCreatedEvents.ts
- features/aave/strategyConfig.ts
- features/vaultsOverview/pipes/positions.ts
- next.config.js
- pages/borrow/[protocol]/open/[collateralToken].tsx
- pages/earn/[protocol]/open/[strategy].tsx
- adds base page for Aave borrow
- includes list of allowed collaterals (only eth for now)
- adds borrow strategy config
- open, manage, close Earn and Multiply positions to ensure no regression.
> aave borrow base page

- features/aave/open/state/openAaveStateMachine.ts
- features/aave/strategyConfig.ts
- features/earn/aave/components/SimulateSectionComponent.tsx
- the default value for the Aave Earn APY is based on the maximum risk possible (same as default simulation)
> Fixed aave earn default APY

- features/automation/common/consts.ts
- features/automation/optimization/autoBuy/controls/AutoBuyDetailsLayout.tsx
- public/locales/en/common.json
- adjusted banner copy
- banner is visible in auto-buy details section 
- visit one of the vaults from story, banner should be visible in overview and auto-buy details section
- copy should be updated
> Auto-buy override banner in AB details section

- features/automation/common/state/autoBSTxHandlers.ts
- added missing item to dependency array
- click on `Set Threshold` `Set No Threshold` button in auto buy or sell form should refresh tx data
> AutoBS tx handlers dependency array fix

- components/vault/DefaultVaultHeadline.tsx
- components/vault/EarnVaultHeadline.tsx
- components/vault/GeneralManageLayout.tsx
- components/vault/VaultHeadline.tsx
- features/aave/common/components/AaveHeader.tsx
- features/dsr/containers/DsrView.tsx
- features/earn/aave/components/AavePositionHeader.tsx
- features/earn/guni/common/GuniVaultHeader.tsx
Share to twitter button was mistakenly visible not just on existing positions, but also in opening flow.
- Added `shareButton` prop to `vaultHeadline` so it's possible to turn it on and off,
- set `shareButton` to true on all manage positions pages.
Visit every type of position (borrow, multiply and earn for maker, multiply and earn for aave and dsr) and see if share button is not visible in open flow, just in manage.
> Share button on demand

- features/aave/common/components/informationContainer/FeesInformation.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/open/state/openAaveStateMachine.ts
- features/stateMachines/allowance/state/createAllowanceStateMachine.ts
- Now allowance machine returns the result of the transaction
- State machines update the allowance just after the transaction
- Fee information displays 0 if a token fee is zero.
> [SC-7756] Set allowance with transaction result, zero fee 

- features/vaultsOverview/pipes/positions.ts
- Filter out empty DSProxy positions that are populated because of a faked Position Created event. Defaults to stETH:ETH because that's the default strategy that's loaded from config.
- Go to -> /owner/0x58dce68cccef2cd44555da238525e69c5cc65a3e
- Check there's no stETH:ETH position visible
> fix: Empty stETH position showing on positions page

- features/follow/common/FollowButton.tsx
- features/follow/common/FollowButtonControl.tsx
- Disabled follow button when wallet not connected
- Follow button on vault overview should be disabled when wallet not connected, and enabled when wallet is connected and limitof followed vaults is not reached, and is not progressing
- Also check GUNI
> disable follow button when wallet not connected

- components/AppContext.ts
- components/FlowSidebar.tsx
- components/forms/Radio.tsx
- features/aave/AaveContext.ts
- features/aave/getCommonPartsFromAppContext.ts
- features/aave/open/containers/AaveOpenView.tsx
- features/stateMachines/allowance/AllowanceView.tsx
- features/stateMachines/allowance/state/createAllowanceStateMachine.ts
- features/stateMachines/dpmAccount/CreateDPMAccountView.tsx
- features/stateMachines/dpmAccount/state/createDPMAccountStateMachine.ts
- helpers/dummyStateMachine.ts
- helpers/useFlowState.ts
- public/locales/en/common.json
- added new hook - `useFlowState`. The purpose of this hook is to provide access to internals of handling flow states: creating DPM proxy and allowance.
- added new component `FlowSideBar` which can consume `flowState` from the hook above. This provides UI needed for proxy and allowance states.
Typical use case:
```
const flowState = useFlowState({
amount: yourDataSource.amount,
token: yourDataSource.collateral,
onEverythingReady(params) {
// we have everything we need, pick the first
// DPM proxy from "availableProxies" and proceed with your flow
console.log('onEverythingReady', params)
},
})
```
```
<FlowSidebar {...flowState} />
```
If you don't want to use `onEverythingReady` for whatever reason you can react to the hook changes:
```
{
dpmMachine, // internals
allowanceMachine, // …
```
> Component for creating DPM and Allowance flow

- components/FlowSidebar.tsx
- helpers/useFlowState.ts
Fixes for above.
- proper handling of the `''` (empty string) token as well as wrong or not provided amount
- in the above situation allowance flow is skipped and `onEverythingReady` callback is fired, but with `isAllowanceReady` set to `false`
- fixes callback handling
- added `asUserAction` to callbacks (true if user action, false if done automatically)
- I know who you are, you can test it better than me 👽
> DPM/Allowance flow helpers - fixes

- components/sidebar/SidebarSectionFooterButton.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContent.tsx
- features/ajna/common/helpers.tsx
- features/ajna/contexts/AjnaProductContext.tsx
- features/ajna/controls/AjnaProductController.tsx
🧿 Ajna form without wallet connection
You can simulate if no wallet is connected. On setup or manage steps, if wallet is disconnected, primary button will take user to `/connect` page. If users disconnects wallet while on any later step, he is going to be taken back to setup.
- Added disconnected wallet handling.
Play with form with wallet connected and disconnected and compare it it behaves like it is in description above.
> 🧿 Ajna form without wallet connection

- components/FlowSidebar.tsx
- helpers/callBackIfDefined.ts
- helpers/useFlowState.ts
If you have any questions regarding how this works - consult the ADR.
- `onEverythingReady` has been moved to the UI component - preventing it from executing until 100% necessary
- exported `callBackIfDefined` for reusability
- machines provided by the hook are now inside `internals` (since they're not really that useful for the user; minimizing the noise)
🤷
> Flow state components changes

- blockchain/aave-v3/aaveV3Oracle.ts
- blockchain/tokensMetadata.ts
- components/productCards/ProductCardEarnAave.tsx
- components/productCards/ProductCardsContainer.tsx
- components/productCards/ProductCardsFilter.tsx
- features/aave/AaveContext.ts
- features/aave/AaveContextProvider.tsx
- features/aave/SetupAaveV3Context.ts
- features/aave/strategyConfig.ts
- features/asset/AssetView.tsx
- features/earn/EarnView.tsx
- helpers/mapStrategyToToken.ts
- helpers/productCards.ts
- helpers/useFeatureToggle.ts
- lendingProtocols/aave-v2/pipelines/aavePrepareAvailableLiquidity.ts
- lendingProtocols/aave-v3/index.ts
- lendingProtocols/aave-v3/pipelines/aavePrepareAvailableLiquidity.ts
- public/locales/en/common.json
- new product card for wstETH Aave V3
- since Aave V3 oracles report prices in USD there are some changes to the current liquidity available data
- new observable called `getAaveV3OracleBaseCurrencyUnit` which gives you `BASE_CURRENCY_UNIT` (to deal with the new oracle data format)
- turn on the feature flag - `AaveV3EarnWSTETH`
- there should be a wstETH/ETH earn card on: 
- home page, Earn tab
- Products -> Earn page
> [FE] Create Product card with feature toggle

- analytics/analytics.ts
- analytics/common.ts
- features/borrow/open/pipes/openVaultAnalytics.ts
- features/multiply/manage/pipes/manageMultiplyVaultAnalytics.ts
- features/multiply/manage/utils.ts
- features/multiply/open/pipes/openMultiplyVaultAnalytics.ts
Added `oasisFee` param to following `ConfirmTransaction` events, added multiply and earn product labels
- Opening multiply vault
- adjusting multiply
- closing multiply vault
- Added 'multiply' and 'earn' products in mixpanel events
- labeled multiply related events as multiply, STETH events as earn
- Go to all possible scenarios w
https://user-images.githubusercontent.com/6871923/217224637-e995214d-06c6-4db5-a8b3-d1ec067132de.mp4
with oasisFee, check in dev tools console if it's passed correctly in below example, it's not yet for close vault
• For Multiply Actions, update the Product label from Borrow to Multiply
- Please also check if there's no regression ie. Multiply label applied to borrow events
- Besides t
https://user-images.githubusercontent.com/6871923/217244986-1044dd59-f5ce-43e …
> Added oasisFee to mixpanel events

- features/ajna/borrow/ajnaBorrowStepManager.ts
- features/ajna/borrow/sidebars/AjnaBorrowFormWrapper.tsx
Temporary workaround, `useFlowState` require `token` and `amount` in all cases.
- updated `useFlowState` handling,
- updated `isBorrowStepValid` method to disable primary button in manage flow.
See if allowance component doesn't break on of the actions in manage position.
> 🧿 Always pass data to allowance

- helpers/useFeatureToggle.ts
- Turned Follow Vaults feature flag on
Point is to make Follow Vaults turned on for everybody on staging before next release
- Turning Follow Vaults feature flag turns the follow vault feature on for Maker vaults
> turned follow vaults on to make it turned on on staging

- components/AppContext.ts
- features/ajna/borrow/sidebars/AjnaBorrowFormWrapper.tsx
- features/ajna/common/observables/getAjnaPosition.ts
- features/ajna/contexts/AjnaProductContext.tsx
- features/ajna/controls/AjnaProductController.tsx
Loads empty position state from library on open flow. Note: this breaks any Ajna position page on mainnet since there are no contacts deployed on it.
- Modified `getAjnaPosition$` observable in a way that it can return existing position when passed ID or empty position when collateral and quote tokens passed,
- fixed an issue where user was asked for DPM proxy during manage flow.
Just see if both open and manage flow views loads properly.
> 🧿 Ajna empty position

- components/vault/VaultHeadline.tsx
- Added no wrapping on follow button when disabled in Vault Headline 
- Make sure it fixes the issue on the vault overview page
- Make sure it doesn't break it on the discovery page (attempting to apply it everywhere would break it)
> fixed wrapping text for disabled follow button on vault overview

- features/ajna/borrow/overview/AjnaBorrowOverviewWrapper.tsx
- features/ajna/borrow/overview/ContentCardLiquidationPrice.tsx
- features/ajna/borrow/overview/ContentFooterItemsBorrow.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContent.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentManage.tsx
- features/ajna/borrow/state/ajnaBorrowFormReducto.ts
- features/ajna/borrow/views/AjnaBorrowView.tsx
- features/ajna/controls/AjnaSelectorController.tsx
- features/discover/common/DiscoverTableDataCellContent.tsx
- helpers/useAccount.ts
A package will small fixes for bugs found while testing open and manage flow.
- A change in manage form dropdown or pill will reset form state,
- selecting "Back to editing" won't reset selected dropdown and pill in manage form,
- removed footer in `ContentCardLiquidationPrice` when main value is equal to zero,
- added unit to `ContentCardLiquidationPrice` afterpill,
- ownership banner on manage view no longer shows for a second on users own position,
- removed afterpill in footer for "Annual net borrow cost" as it is always the same,
- updated protocol column in pool selector according to Oasis Create design.
See all changes from the above.
> 🧿 Ajna flow refinements

- features/automation/protection/stopLoss/state/useStopLossStateInitialization.ts
- fixed issue when during stop loss trigger removal, form action was switching to `add`
- remove stop loss trigger, form action should remail `remove`
> Stop-Loss form action change fix

- features/aave/common/components/SidebarAdjustRiskView.tsx
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/multiply/aave/components/AaveMultiplyPositionData.tsx
Temporary validation suppression in order to test trigger execution
- disabled validation related to stop loss in aave manage overview
- fixed issue with undefined autoKind
- despite stop loss error error user should be able to perform actions in form
> Disable stop loss aave validation

- features/discover/common/DiscoverTableDataCellContent.tsx
- Modified discovery table to display no icon when it's missing in both `asset` and `primitives`
- In `tokensMetadata` find tokens with missing `bannerIcon` for example `GNO`, `PAXUSD` etc.
- In https://tracker-vaults.makerdao.network/ find a vault with token with missing icon as a collateral for example 
- View one of vaults with missing icon, for example GNO http://localhost:3000/29954 , PAXUSD http://localhost:3000/14896 , UNIV2DAIUSDC-A http://localhost:3000/28539
- Follow that vault
- Go to my positions page
- Page should open correctly, vaults with missing icon will just have no icon displayed in DiscoverTableDataCellContent
> fix show no icon when it's missing

- features/ajna/borrow/state/ajnaBorrowFormReducto.ts
- features/ajna/contexts/AjnaProductContext.tsx
Due to the `open` state being default action, unless user didn't select something in dropdown or switched pill, simulation wasn't working.
- Default action is set depending on context `flow`.
See if simulation works on Ajna manage position page.
> 🧿 Fix Ajna simulation on manage flow

- features/automation/protection/stopLoss/state/stopLossTriggerData.ts
- stop loss value for auto v2 needs to be multiplied by `10 ** 6` (so `76 * 10 ** 6` or `0.76 * 10 ** 8`) and divided by this value during decoding
- triggers data should contain correct sl value format
- when adding and removing, on UI user should see correct numbers
> Aave SL trigger value adjustment

- features/aave/manage/state/manageAaveStateMachine.ts
- call actions when entering the closing state instead of on the transition itself
> fix closing

- features/aave/common/BaseAaveContext.ts
- features/aave/common/StrategyConfigTypes.ts
- features/aave/common/components/SidebarAdjustRiskView.tsx
- features/aave/common/components/informationContainer/OrderInformationTooltipAction.tsx
- features/aave/common/components/informationContainer/SlippageInformation.tsx
- features/aave/common/components/informationContainer/StrategyInformationContainer.tsx
- features/aave/manage/containers/AaveManageStateMachineContext.tsx
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/open/containers/AaveOpenStateMachineContext.tsx
- features/aave/open/sidebars/SidebarOpenAaveVault.tsx
- features/aave/open/state/openAaveStateMachine.ts
- features/aave/strategyConfig.ts
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/pt/common.json
- Introduce a default slippage for the strategy.
- Default slippage for Earn `wstETH/ETH` -> 0.1%.
- All transaction for `wsETH/ETH` has the default slippage set.
- User can change it to theirs (get from user settings).
- New tooltip for Order Information. The tooltip can have action and doesn't disappear after moving the mouse.
> [SC-8085] Default slippage in strategy

- actions/ajna/oasisActionsLibWrapper.ts
- features/ajna/borrow/contexts/AjnaBorrowContext.tsx
- features/ajna/borrow/contexts/isBorrowFormValid.ts
- features/ajna/borrow/helpers.tsx
- features/ajna/borrow/overview/AjnaBorrowOverviewWrapper.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContent.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentGenerate.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentManage.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentPayback.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentSummary.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentTransaction.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormContentWithdraw.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormFields.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/borrow/sidebars/AjnaBorrowFormWrapper.tsx
- features/ajna/borrow/useAjnaTxHandler.ts
- features/ajna/borrow/views/AjnaBorrowView.tsx
- features/ajna/contexts/AjnaProductContext.tsx
- features/ajna/controls/AjnaProductController.tsx
- public/locales/en/common.json
Dedicated proxy for Ajna Borrow. Does not change anything in Borrow reducto or transactions.
- Split existing context into `AjnaBorrowContext` and `AjnaProductContext`,
- adjusted existing files to accommodate this change.
See if open and manage flow are still working.
> 🧿 Separate borrow related stuff into its own context

- features/earn/aave/components/PositionInfoComponent.tsx
- features/vaultsOverview/pipes/positions.ts
https://app.shortcut.com/oazo-apps/story/8108/bug-net-value-in-usd-isn-t-showing-correct-compared-to-actual-net-value-of-eth-aave-v3-steth
- read net value from library
1. create earn v3 + v2 position
2. create aave multiply positions
3. ensure the net value matches the net value on the position page, accounting for ticker price
> position overview net value fix

- package.json
- yarn.lock
https://app.shortcut.com/oazo-apps/story/8104/add-new-fee-tier-use-it-for-wsteth-eth
- lib update
- open/mutate/close aave v3 position
- ensure low fee tier used from library
> update lib version to consume new low fee tier for aave v3 wsteth/eth

- .github/workflows/build.yml
- components/sidebar/SidebarSection.tsx
Set node to 16 for oasis-borrow https://github.com/actions/runner-images/issues/7002
> Set node version to 16 in GH actions

- features/aave/open/sidebars/SidebarOpenAaveVault.tsx
- features/stateMachines/allowance/AllowanceView.tsx
- disables main sidebar button when it is in loading state in open aave sidebar
Ensure button is disabled when in loading state (spinner) across:
- creating DPM
- loading DPM
- setting allowance
- adjusting risk (calling lib)
- confirming in metamask
> disable button when in loading state

- .github/workflows/aws-prod.yaml
- .github/workflows/aws-staging.yaml
- .github/workflows/build.yml
- .github/workflows/dockerhub.yaml
- .github/workflows/release.yaml
- .github/workflows/storybook.yml
TECH-1124 - Node.js 12 Github Actions are deprecated as Node.js 12 reached End-of-Life on April 2022. This PR upgrades them to Node.js 16
> TECH-1124 - Upgrading Node.js 12 (End-of-Life) Github Actions to Node.js 16

- features/ajna/controls/AjnaSelectorController.tsx
- For Earn, second token in pool pair goes to the selector, second token to the table,
- for Borrow nothing should change.
> 🧿 Reverse tokens i pool selector for Ajna Earn

- features/aave/common/components/SidebarAdjustRiskView.tsx
- show `-` instead of `NaN` for liquidation price when showing a position with zero collateral
- test that aave position with zero collateral shows `-` instead of `$NaN`
- ensure `hasUserInteracted` displays liquidation price correctly
> don't show nan when there is no collateral in a vault

- next.config.js
- based on error in gnosis app, adjusted origin
- using gnosis safe app it should be possible to access oasis app
> Gnosis safe origin change

- components/DetailsSectionFooterItem.tsx
- features/ajna/borrow/controls/AjnaBorrowPositionController.tsx
- features/ajna/common/observables/getAjnaPosition.ts
- features/ajna/common/views/AjnaPositionView.tsx
- features/ajna/earn/controls/AjnaEarnPositionController.tsx
- features/ajna/earn/overview/AjnaEarnOverviewManage.tsx
- features/ajna/earn/overview/ContentCardMaxLendingLTV.tsx
- features/ajna/earn/overview/ContentFooterItemsEarnManage.tsx
- features/ajna/earn/overview/ContentPositionLendingPrice.tsx
- public/locales/en/common.json
Final (?) version of UI for content cards and overview section for Earn manage page.
- Adjusted details section component so it can display properly footer with just two items,
- brought back old price format to Earn, now it's back the same as on Borrow,
- updated collateral/quote token order on Earn content cards and details section footer.
As Earn positions are not yet available anywhere, to test it you have to overwrite position's product in main product controller from "borrow" to "earn". Then open existing Borrow position, that should display Earn UI.
> 🧿 Ajna Earn manage overview changes

- components/Footer.tsx
- helpers/useFeatureToggle.ts
- added button with link to goerli network hidden behind feature toggle
- button has been added to change network when using gnosis safe app
- enable `GoerliButton` feature toggle, button should be visible in footer on homepage
> Move to goerli button

- components/DetailsSectionNotification.tsx
- features/ajna/common/contexts/AjnaProductContext.tsx
- features/ajna/common/notifications.ts
- features/ajna/common/types.ts
- features/ajna/earn/overview/AjnaEarnOverviewManage.tsx
- public/locales/en/common.json
- added handling for notifications within context
- prepared 2x notifications for earn overview
- types clean up
- manage earn view is not accessible now, if you want to test these notification add `borrow` case next to `earn` case in `features/ajna/common/notifications.ts` and visit borrow position
> 🧿 Ajna manage form notifications

- components/AnimatedWrapper.tsx
- components/navigation/NavigationMenuPanel.tsx
- components/productCards/ProductCardsWrapper.tsx
- features/ajna/components/AjnaHeader.tsx
- features/ajna/components/AjnaRewardCard.tsx
- features/ajna/controls/AjnaNavigationController.tsx
- features/ajna/controls/AjnaSelectorController.tsx
- features/ajna/views/AjnaRewardsView.tsx
- features/homepage/AjnaHomepageView.tsx
- pages/ajna/multiply.tsx
- public/locales/en/common.json
Couple QOL minor improvements to static pages for Ajna.
- Extracted `AnimatedWrapper` component to be used along all Ajna pages (and also outside of Ajna context, but this PR does not do that),
- extracted `AjnaHeaderProps` component to be used at top of all Ajna pages except HP (or maybe HP includes if it's tweak enough?),
- added support for navigation components so an item in menu can both have it's own dropdown panel and be a link at the same time - also added links for Borrow, Earn and Multiply pages in Ajna navigation,
- fixed couple small inconsistencies with design on rewards page and simplified styles a little bit,
- created empty Ajna Multiply page - this one does not contain product cards as in the light of Oasis create I'm not sure if they are in they final version.
No special …
> 🧿 Ajna content pages improvements

- features/discover/common/DiscoverTableDataCellContent.tsx
- features/vaultsOverview/containers/FollowedTable.tsx
- features/vaultsOverview/containers/PositionsTable.tsx
- features/vaultsOverview/helpers.ts
- Removed share button from my positions table on owner's page.
See if:
- Sharing button is removed from my positions table,
- sharing button is kept on followed positions table and in Discover.
> Remove share button from my positions

- features/discover/common/DiscoverTableDataCellContent.tsx
- features/vaultsOverview/helpers.ts
Context: https://discord.com/channels/837076147694207067/1078308551874846801/1078308556744446004
- All go to positions link on owner's page should open in the same tab.
> Positions links on owner's page in same window

- analytics/analytics.ts
- pages/api/t.tsx
- Added set of parameters that are passed to mixpanel endpoint: browser, browser version, if device is mobile, device os, screen width and height.
Trigger any mixpanel event and see if additional data was passed correctly.
> Track default mixpanel params on backend

- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- features/subgraphLoader/useSubgraphLoader.ts
Subgraph loader available as both hook and method.
Note: `TempGraph` and `tempMethod` are left intentionally as a hint how this method has to be extended in case someone wants to add support for more types of graphs or their methods.
- Created `useSubgraphLoader` hook,
- created `loadSubgraph` method.
As it is just a set of methods, not it's usage, you have to use one of the following:
```typescript
const { isError, isLoading, response } = useSubgraphLoader('Ajna', 'getEarnData', {
dpmProxyAddress: '0x2e86fc1cca2c22a381b3dbdcf679a23cc63ed3a2',
})
```
or
```typescript
const response = await loadSubgraph('Ajna', 'getEarnData', {
dpmProxyAddress: '0x2e86fc1cca2c22a381b3dbdcf679a23cc63ed3a2',
})
```
> Common subgraph loader

- analytics/analytics.ts
- analytics/mixpanel.ts
- pages/_app.tsx
- Added tracking fo rthe first load of Oasis.app on `/` home apge - track `utm_source`
- change api call based on user settings
add `?utm_source=xxxx` to url and check mixpanel tracking events
> FEAT - Add tracking for users on landing page that have not accepted cookies

- features/subgraphLoader/consts.ts
- features/subgraphLoader/useSubgraphLoader.ts
- pages/api/subgraph.tsx
Subgraph loader moved to the backend.
- created `/api/subgraph` endpoint utilized by previously created `useSubgraphLoader` hook and `loadSubgraph` method,
- fixed some errors with types,
As it is just a set of methods, not it's usage, you have to use one of the following:
```typescript
const { isError, isLoading, response } = useSubgraphLoader('Ajna', 'getEarnData', {
dpmProxyAddress: '0x2e86fc1cca2c22a381b3dbdcf679a23cc63ed3a2',
})
```
or
```typescript
const response = await loadSubgraph('Ajna', 'getEarnData', {
dpmProxyAddress: '0x2e86fc1cca2c22a381b3dbdcf679a23cc63ed3a2',
})
```
- Get subgraphs urls from env when https://github.com/OasisDEX/oasis-borrow/pull/2128 is merged and config is available.
> Common subgraph loader API

- blockchain/calls/callsHelpers.ts
- components/AppContext.ts
- helpers/getGasMultiplier.ts
- package.json
- yarn.lock
- removed the og multiplier from the transactions package: https://github.com/OasisDEX/common/pull/88
- added it to the frontend with the distinction: 1.5 multiplier for the HW wallets and 1 (meaning none) multiplier for the others
- connect using metamask
- simulate a transaction
- disconnect, connect using hw wallet (ledger, trezor)
- simulate a transaction
- gas estimate should be higher on the second one
> Change current behavior of gas estimation in FE app

- pages/_app.tsx
page view is now tracked when `router.isReady` is `true` since the query parameters were undefined on first render.
```ts
useEffect(() => {
if (router.isReady) {
mixpanelInit()
if (router.pathname === '/') {
const utm: { [key: string]: string | string[] | undefined } = {
utmSource: router.query.utm_source,
utmMedium: router.query.utm_medium,
utmCampaign: router.query.utm_campaign,
}
trackingEvents.landingPageView(utm)
} else {
trackingEvents.pageView(router.pathname)
}
}
}, [router.isReady])
```
go to `http://localhost:3000/?utm_source=zzzzz&utm_medium=xxxx&utm_campaign=yyyy#multiply` and check the console logs on first laod
> FIX - fix first render query

- helpers/getGasMultiplier.ts
Hotfix to revert gas estimate multiplier back to 1.5 given failing T/x for users.
> Fix - Put default gas multiplier back to 1.5 until we can revisit

- blockchain/calls/callsHelpers.ts
- components/AppContext.ts
- helpers/getGasMultiplier.ts
- package.json
- yarn.lock
Ensure the gasEstimate multiplier is being passed to the sendWithGasEstimates function not just estimateGas function
> Hotfix 2 | add gasMultiplier to sendTx function calls

- components/AppContext.ts
- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/observables/getAjnaPosition.ts
- features/ajna/positions/common/observables/getDpmPositionData.ts
Since library requires quote price, token prices has to loaded first before position is loaded, main observable had to be split into two separated ones. This PR does not pass quote price to library (library is not updated so it doesn't require it) but allows to do it in easy way.
- Remove `dpmPositionData$` observable dependency from `ajnaPosition$` and replaced it with `dpmPositionData` interface,
- created `getStaticDpmPositionData$` fakeish observable,
- updated `AjnaProductController` observable order and dependencies.
Try both open and manage flow and see if empty position and existing positions are loading correctly.
> 🧿 Split get Ajna position observable

- components/HeadTags.tsx
Little fix for this:
```
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more than a single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
at title
at head
at Head (webpack-internal:///./node_modules/next/dist/pages/_document.js:279:1)
at html
at Html (webpack-internal:///./node_modules/next/dist/pages/_document.js:678:104)
at MyDocument (webpack-internal:///./pages/_document.tsx:23:1)
```
> Get rid of title errors

- features/homepage/HomepageView.tsx
- features/stateMachines/transactionParameters/transactionParametersStateMachine.ts
- Retry getting parameters when gas estimation fails. Mostly we want to ask 1inch about the best route again. 
- Default tab on mainpage: Earn.
> [SC-8434] Retry on Getting Parameters on AAVE. Default Page - Earn

- analytics/analytics.ts
- components/AppContext.ts
- components/connectWallet/ConnectWallet.tsx
- features/aave/open/sidebars/SidebarOpenAaveVault.tsx
- features/termsOfService/termsAcceptance.test.ts
- features/web3Context/types.ts
- features/web3Context/web3_context.ts
- features/web3OnBoard/BridgeConnector.ts
- features/web3OnBoard/useBridgeConnection.tsx
- features/web3OnBoard/useBridgeConnector.tsx
- features/web3OnBoard/useNetworkConnector.tsx
- features/web3OnBoard/useWeb3OnBoardConnection.tsx
- helpers/getCustomNetworkParameter.ts
- helpers/mocks/web3Context.mock.ts
- Refactor connecting against web3-OnBoard. 
- When switching the network on connect, we reconnect the user. 
- Connecting use only `useCallback`
- Mixpanel event contains a `walletLabel` and method.
> :bug: Web3-OnBoard Brave connection, new properties in change-address event

- features/discover/common/DiscoverTableDataCellComponents.tsx
- features/discover/common/DiscoverTableDataCellContent.tsx
- Fixed issue with BAT icon not displaying,
- removed placeholder circle if icon is not showing - empty place in row with missing icon was in line with design.
Test on `0xE9c245293DAC615c11A5bF26FCec91C3617645E4` wallet.
> Fix owner's position table icon issue

- features/discover/common/DiscoverTableDataCellContent.tsx
- Token metadata is loaded from `value` field, not `label`.
Test on `0x468d1ef7a1204d592537dab35794aac640c97505` wallet as it has closed Curve LP vault and probably would be good idea to see couple more random wallets just to be sure.
> Fix missing token metadata

- blockchain/tokensMetadata.ts
- features/ajna/positions/borrow/overview/ContentCardCollateralLocked.tsx
- features/ajna/positions/borrow/overview/ContentCardPositionDebt.tsx
- features/ajna/positions/borrow/overview/ContentFooterItemsBorrow.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/earn/helpers/getAjnaSimulationRows.ts
- features/ajna/positions/earn/overview/ContentCardCurrentEarnings.tsx
- features/ajna/positions/earn/overview/ContentCardTokensDeposited.tsx
- features/ajna/positions/earn/overview/ContentFooterItemsEarnManage.tsx
- adjusted USDC digits from 6 to 2
- fixed all places in Ajna UI where quote token or collateral token wasn't displayed properly
- check ajna open & manage earn / borrow flow to see whether quote token and collateral token have correct number of decimals
> Ajna UI decimals

- components/Footer.tsx
- helpers/useFeatureToggle.ts
- removed feature toggle with goerli button which was useful for testing gnosis wallet
- GoerliButton feature toggle should not longer be available
> Remove goerli btn feature toggle

- components/vault/VaultActionInput.tsx
- features/ajna/common/consts.ts
- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/borrow/overview/ContentCardLoanToValue.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentManage.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/common/sidebars/AjnaFormFields.tsx
- public/locales/en/common.json
Some smaller updated according to latest changes in figma.
- Changed "generate" to "borrow" across Borrow UI,
- added "Liquidation Threshold" to LTV card,
- set all afterpills to warning color if user is within 5% to Max LTV (similar to Maker).
> 🧿 Liquidation threshold in Ajna Borrow 

- features/ajna/common/consts.ts
- features/ajna/common/types.ts
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/notifications.ts
- features/ajna/positions/common/observables/getAjnaPosition.ts
- features/ajna/positions/common/observables/getDpmPositionData.ts
- features/ajna/positions/common/state/ajnaFormReductoActions.ts
- features/ajna/positions/multiply/state/ajnaMultiplyFormReducto.ts
- features/ajna/positions/multiply/temp.ts
- public/locales/en/common.json
Extended `AjnaProductContext` and `AjnaProductController` to fit Multiply product. So far this is just the context, no UI changes were made.
- Created fake `AjnaMuliplyPosition` interface to be replaced in the future with one from library,
- added support for Multiply product in Ajna context,
- created `AjnaMultiplyFormReducto` for opening part of the flow.
- See if `/ajna/multiply/WBTC-USDC` doesn't break the application,
- see if Borrow/Earn flows are still working.
> 🧿 Extend Ajna Context for Multiply Product

- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/helpers/getPrimaryButtonLabelKey.ts
- features/ajna/positions/common/validation.ts
- features/ajna/positions/common/views/AjnaFormView.tsx
- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyFormController.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyPositionController.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentDeposit.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentOpen.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
- features/ajna/positions/multiply/temp.ts
Opening part of Ajna Multiply form.
- created opening form UI,
- created multiply slider,
- added additional state for primary button in form - "Set {{token}} allowance".
Check form on `/ajna/multiply/WBTC-USDC`.
- All data is fake, just some random generated placeholders,
- "Total cost" in order information is intentionally inconsistent with designs. All three products has this designed in a different way - [after this PR is merged I will created separated one that standardize displaying cost across Borrow, Earn and Multiply](https://app.shortcut.com/oazo-apps/story/8742/standardize-displaying-transaction-cost-across-borrow-earn-and-multiply).
> 🧿 Open Multiply position form

- .github/workflows/aws-staging.yaml
- .github/workflows/build.yml
The title tells us everything.
> Build workflow only on Pull Request. Use Production Cache on CI

- components/FlowSidebar.tsx
- features/ajna/positions/common/helpers/getFlowStateConfig.ts
- fixed issue where user wasn't depositing / paybacking tokens but FlowSidebar was shown anyway with fallback return of `<></>`
- on Ajna earn position go to `Manage Liquidity`, adjust lending price bucket without depositing anything and click confirm (order information should be shown instead of form disappearing)
> Flow Sidebar minor fix

- components/GasEstimation.tsx
- components/vault/VaultChangesInformation.tsx
- features/ajna/positions/borrow/components/ContentFooterItemsBorrow.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/common/contexts/AjnaGeneralContext.tsx
- features/ajna/positions/common/views/AjnaFormView.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormOrder.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
All three products had total transaction cost designed in a different way, this PR standardizes this and some other minor things.
- Standardized total cost in order information - according to newest design cost should be summed up, not displayed separately. It's already displayed separately in the dropdown.
- Added `addition` prop to gas estimation for that purpose and removed `withBrackets` as it's not used anywhere.
- Hid transaction cost until DPM and allowance flow is finished as it always fail anyway until it's that,
- Swapped available to borrow and withdraw in Borrow overview section per Luciano's request (https://www.figma.com/file/XAUn9bc0mlzIS63d9yDUUF/Ajna-x-Oasis?node-id=2071-89109&t=0VlSNEJrrx0SMmow-0#417223614).
- Fixed formatting in Borrow and Earn order information - units …
> 🧿 Standardize displaying transaction cost across Borrow, Earn and Multiply

- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/common/notifications.ts
- public/locales/en/common.json
- added handling for liquidation banners in scope of borrow and earn
- it's just UI implementation, in order to show there in file `features/ajna/position/common/notification.ts` uncomment todos
> Liquidation overview notifications

- features/shared/vaultApi.ts
- casted protocol name to lowercase when calling api
- switching maker vault type on UI should work
> Vault type switch fix

- features/homepage/HomepageView.tsx
- helpers/applicationLinks.ts
- next.config.js
- pages/[...rest].tsx
- pages/[vault]/index.tsx
- sitemapGenerator.js
- replaced obsolete links
- adjusted site map
- adjusted handling of 404
- verify 404 handling on pages like for example `/dummy/page` etc.
- contact link in info card on landing page should redirect to proper kb page
> Adjusted links and 404 handling

- features/newsletter/NewsletterView.tsx
- limit newsletter input length to 320 characters
- try to input more to newsletter input field
> Newsletter input max length

- .github/workflows/aws-prod-rollback.yaml
- .github/workflows/aws-prod.yaml
- .github/workflows/aws-staging-rollback.yaml
- .github/workflows/aws-staging.yaml
- .github/workflows/build.yml
- .github/workflows/dockerhub.yaml
TECH-1524 - Node.js 12 Github Actions are deprecated as Node.js 12 reached End-of-Life on April 2022. This PR upgrades them to Node.js 16. This PR extends previous ticket - TECH-1124
> TECH-1524 - Upgrading Node.js 12 (End-of-Life) Github Actions to Node.js 16

- .github/workflows/build.yml
It's not useful until migration from Mocha to Jest is completed.
- Commented out Codecov action.
🤷‍♂️
> Temporary disable codecov reports

- features/homepage/HomepageView.tsx
- added a banner informing about the yields UI error
- its visible on the homepage
- go to the homepage
> Create a yields info banner for Aave

- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
Bugfix.
- Reversed collateral token and quote token in liquidation price value.
> 🧿 Ajna Borrow order information liq price tokens order

- features/ajna/positions/common/hooks/useAjnaTxHandler.ts
- features/ajna/positions/common/observables/getAjnaPosition.ts
Bugfix.
- Replaced `context.rpcProvider` with `networksById[context.chainId].readProvider`.
See if Ajna positions are loading and simulations is working.
> Fix RPC Provider for Ajna

- public/locales/en/common.json
Bugfix.
- Fixed typo "comeptitive" on homepage and seo tags.
Selfexplanatory.
> 🧿 Ajna homepage typo

- components/dumb/SliderValuePicker.tsx
- features/aave/common/components/SidebarAdjustRiskView.tsx
- features/ajna/positions/common/notifications.tsx
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentOpen.tsx
- package.json
- public/locales/en/common.json
- yarn.lock
Bugfix.
- Validation of price above MOMP is now warning, not error,
- fixed visually disabling slider component,
- bonus: slider is disabled until user input something in deposit field.
> 🧿 Allow to set price above MOMP in Ajna Earn position

- package.json
- yarn.lock
- updated dma-library version which contain fix for net apy calculations when user deposits below htp
- when user tries to deposit quote tokens below htp, net apy should be 0
> Bump dma-library version 0.3.10

- features/ajna/positions/earn/components/ContentFooterItemsEarnOpen.tsx
- features/ajna/positions/earn/consts.ts
- features/ajna/positions/earn/controls/AjnaEarnOverviewOpenController.tsx
On the design, when there are two items in overview section footer, the items are starting to take a wider space, but this is inconsistent with previous designs that were applied to all the other places, so I did not change that. A single item is still taking the same amount of space, as it used to.
- Removed "Estimated break even" from open Ajna Earn flow and all its dependencies that weren't used anywhere else.
> 🧿 Remove est. break even

- components/DetailsSectionContentSimpleModal.tsx
- features/ajna/common/components/AjnaDetailsSectionContentSimpleModal.tsx
- features/ajna/positions/common/components/contentCards/ContentCardCollateralLocked.tsx
- features/ajna/positions/common/components/contentCards/ContentCardCurrentEarnings.tsx
- features/ajna/positions/common/components/contentCards/ContentCardLiquidationPrice.tsx
- features/ajna/positions/common/components/contentCards/ContentCardLoanToValue.tsx
- features/ajna/positions/common/components/contentCards/ContentCardMaxLendingLTV.tsx
- features/ajna/positions/common/components/contentCards/ContentCardPositionDebt.tsx
- features/ajna/positions/common/components/contentCards/ContentCardPositionLendingPrice.tsx
- features/ajna/positions/common/components/contentCards/ContentCardTokensDeposited.tsx
- public/locales/en/common.json
- theme/index.tsx
Only modals, no tooltips as there must have been a misunderstanding with tooltips - their content and titles doesn't match what we currently have in footer so they are probably are supposed to be in some other place, than we anticipated while estimating the story.
- Added modals to overview section cards for Ajna Borrow,
- created helper component `DetailsSectionContentSimpleModal` for all default looking modals* - that allowed to get rid of a lot of duplication previously needed to handle all modals,
- created Ajna specific helper `AjnaDetailsSectionContentSimpleModal` for `DetailsSectionContentSimpleModal` that wraps modals in Ajna theme and applies appropriate colors.
* `ContentCardPositionLendingPrice` is an example of card then modal is more complicated than default. In that case, …
> 🧿 Modals for Ajna Borrow

- analytics/analytics.ts
- components/swapWidget/SwapWidget.tsx
- helpers/hooks/useTrackSwapWidgetEvents.ts
- added useTrackSwapWidgetEvents hook to track swap widget events
- you dont need to make a swap to test this, you can just attempt and then reject
> Added tracking swap widget events

- components/PromoCard.tsx
- features/oasisCreate/types.ts
- features/oasisCreate/views/OasisCreateView.tsx
- helpers/mocks/oasisCreateData.mock.ts
[Tab-1684848152246.webm](https://github.com/OasisDEX/oasis-borrow/assets/16230404/17d63c1f-af31-4b9a-b23e-3cb59ade7389)
- Created `OasisCreateData` interface that should be used as a Oasis Create API response type,
- created mechanism for filtering promo cards on Oasis Create page,
- added some dummy data as promo cards content.
Go to `/oasis-create/borrow` and see if promo cards are updating along while natural language selector is changed.
> 🧬 Filtering promo cards on Oasis Create page

- features/aave/helpers/getStrategyConfig.ts
- lendingProtocols/aave-v2/pipelines/aave-user-configuration.ts
- lendingProtocols/aave-v3/pipelines/aave-user-configuration.ts
- lendingProtocols/aaveCommon/userConfiguration.ts
`hasAssets` now takes an array (needed for ETH/WETH comparison)
Story details: https://app.shortcut.com/oazo-apps/story/9362
> feat: [sc-9362] Staging Bugfixes

- blockchain/token-metadata-list/aave-v2.ts
- blockchain/token-metadata-list/aave-v3.ts
- features/aave/strategy-config.ts
- features/asset/AssetView.tsx
- features/earn/aave/components/AavePositionHeader.tsx
- helpers/productCards.ts
- helpers/useFeatureToggle.ts
- public/locales/cn/common.json
- public/locales/en/common.json
- public/locales/es/common.json
Every strategy has a protocol version in the name/symbol (and token def in `tokens: TokenConfig[]`), for example theres now `wBTCusdcV2` and `wBTCusdcV3`.
This fixes couple of UI bugs and clears confusion.
> Protocol versionin the name/symbol of Aave strategies/tokens

- handlers/product-hub/index.ts
- pages/api/product-hub.tsx
- instead of "Oasis Create" we choose to use "product-hub" name as more general alternative
- dummy data endpoint `/api/product-hub`
- POST `/api/product-hub`
> 🧬 [Oasis Create Data] Create a main endpoint

- components/MessageCard.tsx
- features/ajna/positions/common/components/AjnaValidationMessages.tsx
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/sidebars/AjnaFormContentSummary.tsx
- features/ajna/positions/common/validation.tsx
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- package.json
- public/locales/en/common.json
- theme/index.tsx
- yarn.lock
- Added two new types of message to `AjnaValidationMessages` component: `notice` and `success`,
- added handling to new types of validations returned from library to UI,
- added support for links in validation message for non-local Ajna validations.
Go to Ajna Earn UI (either open or manage is fine) and try putting price in all four color ranges to see different messages.
> 🧿 Ajna Earn price slider validation

- blockchain/contracts/arbitrum.ts
- blockchain/contracts/goerli.ts
- blockchain/contracts/mainnet.ts
- blockchain/contracts/optimism.ts
- features/ajna/common/helpers/filterPoolData.tsx
- features/ajna/common/types.ts
- features/ajna/positions/common/helpers/getAjnaPoolsTableData.ts
- features/ajna/positions/common/observables/getAjnaPoolsTableContent.ts
- features/subgraphLoader/consts.ts
- package.json
- yarn.lock
This PR adds general support for newly added pools and displays them in the table selector. It does not contain fixes for infinity in Multiply selector, two quadrillion max LTV etc.
- Added support for: `WSTETH/DAI`, `RETH/DAI`, `WBTC/DAI`, `USDC/WETH` and `USDC/WBTC`.
Go to Ajna pool selector and check if new pools are available across all product types.
> 🧿 Additional Ajna pools

- features/ajna/common/consts.ts
- features/ajna/positions/common/helpers/getAjnaPoolData.ts
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- added handling for case where pool is not initialized yet (there is only liquidity (or not) without borrowers)
- fixed slider step
- overwrite htpPrice when index is 7388 (from zero to minimum value from buckets price list)
- on fresh pool where  there is no liquidity or there is liquidity but without borrowers slider range should be from min price from buckets to market price
> Ajna earn slider range adjust

- blockchain/contracts/mainnet.ts
As our code doesn't support the new operation executor we need to have the old one.
> restore old operation executor address

- next.config.js
- sentry.base.config.ts
- Make smaller sampling to Sentry. Reason: we have a lot of transactions in Sentry. We don't need it so we are reducing sampling.
- `largePageDataBytes` change. Reason: Nearly all pages exceed the standard limit. We need to identify which page we should prioritize to address first.
> :loud_sound: Make smaller sample. Make larger `largePageDataBytes`

- public/locales/en/common.json
- updated copy
- use earn position ETH/USDC, try to withdraw USDC
> Max withdraw when lup above htp copy update

- blockchain/calls/proxyActions/proxyActions.ts
- Fixed the fees for closing GUNI -> should not take any fees on closing. This bug was introduced with the network configuration update
- Confirm that the address used is the noFeesExchange
> Fix the GUNI fee to use the no fee exchange

- blockchain/networks/use-custom-fork-parameter.ts
- features/web3OnBoard/useBridgeConnector.tsx
- if we are using forks and MetaMask we want to add Fork to the wallet.
- After the action we save information about fork in wallet in Local Storage to avoid re-adding that fork.
> Fork network: add to wallet only once.

- components/constants.ts
- components/vault/VaultActionInput.tsx
- features/ajna/positions/earn/components/AjnaEarnInput.tsx
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
- features/ajna/positions/earn/helpers/convertSliderThresholds.ts
- features/ajna/positions/earn/helpers/convertSliderValuesToPercents.ts
- features/ajna/positions/earn/helpers/getMinMaxAndRange.ts
- features/ajna/positions/earn/helpers/snapToPredefinedValues.ts
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentAdjust.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentOpen.tsx
- helpers/input.tsx
- public/locales/en/common.json
Added ability to manually put a desired price for Ajna Earn form.
[Tab-1686581749966.webm](https://github.com/OasisDEX/oasis-borrow/assets/16230404/624b3e22-72bc-4c16-b275-038573cf8daf)
- Created `AjnaEarnInput` and `AjnaEarnInputButton` components manually selecting price,
- extracted all helpers functions from `AjnaEarnSlider` from component file and moved them to separated directory along with other helpers as some of them were also used in `AjnaEarnInput`.
Test implementation in following scenarios:
- opening new position,
- managing existing position on Adjust step where slider is always visible,
- managing existing position on Manage quote step, where slider is initially hidden.
> 🧿 Manual price bucket selector

- features/productHub/views/ProductHubView.tsx
Whenever user clicked on a page in main navigation while being on product hub already, the whole thing wasn't updaing.
- Added `Fragment` with a `key` as wrapped for Product Hub to force refresh when `product` is changing.
> 🧬 Fix refreshing product hub via main navigation

- features/ajna/positions/borrow/controls/AjnaBorrowOriginationFee.tsx
- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/common/helpers/getOriginationFee.ts
Origination fee had to be calculated on the front-end instead of library, because library doesn't have a context of if the position is actual existing position or just a simulation.
- Created `getOriginationFee` method that is added to debt simulation in overview section and order information.
- Try simulating drawing debt in both open and manage flows for Ajna Borrow position.
> 🧿 Add origination fee to debt simulation

- features/ajna/common/components/AjnaRewardCard.tsx
- features/ajna/common/consts.ts
- features/ajna/common/controls/AjnaRewardsController.tsx
- features/ajna/positions/common/contexts/AjnaGeneralContext.tsx
- features/ajna/positions/common/contexts/ajnaStepManager.ts
- features/ajna/positions/earn/state/ajnaEarnFormReducto.ts
- Disabled NFT opt-in/out step on Ajna Earn open flow,
- replaced Ajna token amount with "coming soon" on rewards page.
- Try opening Earn position and see if NFT step is skipped,
- check if rewards page displays "coming soon" properly.
> 🧿 Delay Ajna rewards

- features/ajna/positions/common/helpers/getPrimaryButtonLabelKey.ts
- features/ajna/positions/common/views/AjnaFormView.tsx
The issue was never about asking for allowance, just about button label. By default, primary button label was set to match action of asking user for collateral token allowance.
- Added check if form is empty to `getPrimaryButtonLabelKey` method, so if form is its original state, it is displaying default label (which is "Confirm").
Go to any existing Ajna Borrow position and see if label is correct in initial state.
> 🧿 Fix repeated allowance request

- features/aave/services/readPositionCreatedEvents.ts
After connecting to Ajna RC5 contracts, protocol name in `CreatePosition` event is changed from `Ajna` to `AJNA_RC5` which made loading any new position fail.
- Added `AJNA_RC5` to acceptable protocols list in filters.
- Open new Ajna position and see if it is loading.
> 🧿 Add AJNA_RC5 to protocol types

- features/ajna/positions/common/helpers/getIsFormEmpty.ts
- features/ajna/positions/common/helpers/getPrimaryButtonLabelKey.ts
- features/ajna/positions/common/hooks/useAjnaTxHandler.ts
- fixed issue where after pills were still visible after tx was finished
- on borrow / earn positions try to send few txs and check if after pills are still visible after tx finished
> Ajna simulation reset fix

- components/PromoCard.tsx
- features/ajna/common/controls/AjnaProductHubController.tsx
- features/homepage/AjnaHomepageView.tsx
- features/productHub/controls/ProductHubNaturalLanguageSelectorController.tsx
- features/productHub/views/ProductHubView.tsx
- handlers/product-hub/helpers/parseAjnaPromoCard.ts
- handlers/product-hub/promo-card-collections-parsers/ajnaLpHandler.ts
- Modified `PromoCard` component to be entirely clickable when link is provided,
- added links to products for `ajnaLPHandler`.
Check promo cards on `/ajna`.
> 🧬/🧿 Clickable promo cards on Product Hub

- components/PromoCard.tsx
- components/Translatable.tsx
- components/assetsTable/cellComponents/AssetsTableDataCellInactive.tsx
- components/assetsTable/cellComponents/AssetsTableTooltip.tsx
- features/productHub/helpers/parseRows.tsx
- features/productHub/types.ts
- handlers/product-hub/index.ts
- server/database/migrations/024-product-hub-add-tooltips.sql
- server/database/schema.prisma
- Added migration altering Product Hub database table to add `tooltips` column,
- extracted `PromoCardTranslation` component from `PromoCards` and renamed it into `Translatable` so it can be reused anywhere else (as tooltips need it),
- added support for tooltips for columns, that doesn't have any content.
Add some tooltips to any product hub patch api handler and check if they are on the front-end.
> 🧬 Support for tooltips on Product Hub

- features/ajna/positions/earn/components/AjnaEarnInput.tsx
- added keypressed handling to ajna price input which reacts to `Enter` key
> Ajna price input enter handling

- features/ajna/common/layout.tsx
- features/homepage/AjnaHomepageView.tsx
- features/homepage/HomepageView.tsx
- features/homepage/common/Hero.tsx
- features/productHub/views/ProductHubView.tsx
Latest redesign changes broke Ajna layout, this PR brings it back.
- Updated `AjnaLayout` to use the same layout as rest of the pages (except for color scheme),
- updated `Hero` on Ajna landing page to match the one on homepage.
Check all `/ajna` pages to see if layout is updated everywhere.
> 🧿 Fix Ajna layout after redesign changes

- components/LandingBanner.tsx
- features/homepage/AjnaHomepageView.tsx
- public/locales/en/common.json
- Fixed connect button when user is disconnected,
- added "See my rewards" when user has connected wallet,
- tiny adjustments to banner styles so it matches design and utilizes theme ui predefined themes.
Use banner as connected and disconnected user.
> 🧿 Update Ajna Rewards banner

- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
Debt and bucket liquidity were returned with different precision.
- Fixed precision error.
> 🧿 Ajna Borrow liquidity available number is invalid

- components/navigation/Navigation.tsx
- components/navigation/NavigationActions.tsx
- components/navigation/NavigationBranding.tsx
- components/navigation/NavigationMenu.tsx
- features/navigation/controls/AjnaNavigationController.tsx
- features/navigation/controls/NavigationActionsController.tsx
- features/navigation/controls/NavigationController.tsx
From now on, navigation in centered relatively to the window, not in between logo and user actions.
- Centered navigation,
- fixed couple edge case rwd nav related bugs.
> Center navigation

- components/assetsTable/AssetsTable.tsx
- components/assetsTable/cellComponents/AssetsTableDataCellAction.tsx
- components/assetsTable/cellComponents/AssetsTableDataCellAsset.tsx
- components/assetsTable/types.tsx
- features/discover/common/DiscoverData.tsx
- features/discover/helpers/parseDiscoverRowData.tsx
- features/vaultsOverview/containers/FollowedTable.tsx
- features/vaultsOverview/helpers.tsx
- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
- Made entire row covered by action button,
- removed follow vault and share button from the table.
- Check if entire row is clickable in Product Finder, Discover and on owner's page,
- check if owner's page doesn't have follow and share buttons anymore.
> Assets table entire row active

- blockchain/better-calls/erc20.ts
> :bug: fix balance for ETH

- features/ajna/positions/common/helpers/getIsFormEmpty.ts
- features/ajna/positions/common/hooks/useAjnaTxHandler.ts
- adjusted conditions inside `getIsFormEmpty` method
- adjusted dependencies arrays in `useAjnaTxHandler`
- while opening earn / multiply position, after dpm. & allowance step order informations should display correct data
> Get is form empty method fix

- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/helpers/getAjnaHeadlineProps.tsx
- features/ajna/positions/common/sidebars/AjnaFormContentTransaction.tsx
- features/ajna/positions/common/views/AjnaFormView.tsx
- features/ajna/positions/common/views/AjnaPositionView.tsx
- public/locales/en/common.json
- adjusted copies and params so we no longer use long / short in the position open & manage flow
- no short / long wording
> Remove long / short wording in setup & manage flow

- features/ajna/common/controls/AjnaProductHubController.tsx
- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/helpers/getAjnaSidebarButtonsStatus.tsx
- features/ajna/positions/common/notifications.tsx
- features/ajna/positions/common/validation.tsx
- features/ajna/positions/common/views/AjnaFormView.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewOpenController.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- features/homepage/AjnaHomepageView.tsx
- features/homepage/HomepageView.tsx
- features/productHub/controls/ProductHubContentController.tsx
- features/productHub/views/ProductHubRouteHandler.tsx
- handlers/product-hub/promo-card-collections-parsers/index.ts
- handlers/product-hub/types.ts
- helpers/useFeatureToggle.ts
- public/locales/en/common.json
A safety switch that can be turn on to prevent users from dumping tokens in Ajna.
Whenever `AjnaSafetySwitch` is turned on:
- All Ajna open flow forms are locked, primary button is hidden, there is special notification displayed at the top of overview section,
- empty borrow positions are preventing user from depositing more collateral or generating or paying back debt (which isn't a case since position is empty, but still message will appear),
- empty earn positions are preventing user from depositing more quote,
- all Ajna products and promo cards are hidden from Product Finder.
Turn on `AjnaSafetySwitch` and go through the list.
> 🧿 Ajna safety switch

- features/ajna/common/components/AjnaProductHubIntro.tsx
- features/ajna/common/controls/AjnaProductHubController.tsx
- features/ajna/positions/borrow/controls/AjnaBorrowFormController.tsx
- features/homepage/AjnaHomepageView.tsx
- features/productHub/components/ProductHubIntro.tsx
- features/productHub/controls/ProductHubPromoCardsController.tsx
- features/productHub/views/ProductHubView.tsx
- handlers/product-hub/promo-card-collections-parsers/ajnaLpHandler.ts
- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
- public/locales/en/common.json
- commented out Ajna Multiply products from Ajna Product Finder handler,
- removed Ajna Multiply promo cards from Product Finder (removed, not commented out as they are going to be different than was until now anyway),
- added dedicated intro on Product Finder on Ajna pages when user selects "Multiply" in natural language selector,
- removed "Switch to multiply" from dropdown menu on manage Ajna Borrow UI.
- Patch Product Hub data with new data handler,
- go through changes list.
> 🧿 Hide access to Ajna Multiply

- pages/not-found.tsx
- fixes the layout of the 404 page (lighter instead of home page one)
- go to `/not-found`
> Fix the layout of the 404 page

- features/ajna/positions/common/notifications.tsx
- public/locales/en/common.json
- adjusted notification copy and condition
- when position have 0 quote tokens but collateral to withdraw, empty position notification shouldn't popup
> Ajna earn empty position notification adjust

- features/ajna/common/consts.ts
- changed market price offset from 45% to 25%
- on pool without borrowers when providing liquidity you should be able to set up ltv to 75%
> Empty pool slider market price offset

- package.json
- public/locales/en/common.json
- yarn.lock
- updated copy
- library version bump
- when there is no enough liquidity to move user bucket to another one, error with updated copy should popup
> After lup bigger than htp copy update

- features/ajna/common/consts.ts
- features/ajna/positions/earn/components/AjnaEarnInput.tsx
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- features/ajna/positions/earn/helpers/getMinMaxAndRange.ts
- features/ajna/positions/earn/helpers/snapToPredefinedValues.ts
- `snapToPredefinedValues` method uses predefined ajna bucket list as range
- test slider and input, simulation price should always match price from these
> Usage of buckets list in ajna earn slider

- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- set default value of earn slider to min value
- fix issue on existing earn position on pool without borrowers where slider value was updated to max even though position price existed
- on pool without borrowers earn slider default value should be set up to min value as default
- on existing position on not utilized pool, slider value should be set to position lending price
> Adjust earn slider default value on fresh pool

- package.json
- yarn.lock
- Bump dma-lib version to 0.3.28
- max available to withdraw in ajna earn positions shouldn't drop below 0
> Bump dma-lib version to 0.3.28

- features/ajna/common/types.ts
- features/productHub/helpers/parseRows.tsx
- public/locales/en/common.json
- liquidity typo fix and format negative to zero
- in product hub table liquidity shouldn't drop below 0
- typo fixed
> Liquidity typo fix and format negative to zero

- features/ajna/positions/common/helpers/getFlowStateConfig.ts
- fixed ajna flow config for payback actions
- when performing withdraw and payback action on pool i.e USDC-WBTC, when user types something into withdraw input there should be no `Set WBTC allowance` until payback input will be filled
> Fix ajna flow config for payback actions

- features/ajna/positions/earn/components/AjnaEarnInput.tsx
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- handled case for short pools
- ajna earn input should work for short pools, if user input value out of range, on enter it should snap to fallback value (lup or max)
> Partial Ajna earn input fix

- features/ajna/positions/common/components/contentCards/ContentCardPositionLendingPrice.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
- public/locales/en/common.json
- Updated `ContentCardPositionLendingPrice` content card to display properly short earn positions.
Compare this card on long and short positions, e.g.: `137` and `141`.
> 🧿 Ajna Earn short position lending price

- features/ajna/positions/earn/helpers/getMinMaxAndRange.ts
- limited max value of earn slider to value below market price
- on short earn position try to move slider to max value, user shouldn't be able to move above 100%
> Ajna earn slider max market price

- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- features/productHub/helpers/parseRows.tsx
- public/locales/en/common.json
Covers:
https://app.shortcut.com/oazo-apps/story/10302/change-max-lending-price-tooltip-text
https://app.shortcut.com/oazo-apps/story/10269/typo-on-landing-page
https://discord.com/channels/837076147694207067/1127946676783558777/1127953189568786472
https://discord.com/channels/837076147694207067/839063661884080128/1127959896193761363
- Updated Max LTV modal copy,
- fixed typos on Ajna landing page,
- removed redundant labels from Earn price slider,
- renamed "Available liquidity" to just "Liquidity" in product finder.
> 🧿 Various copy updates and typo fixes

- features/ajna/common/controls/AjnaRewardsController.tsx
Missed those two in original KB update story:
- _Updated Ajna KB/docs links._
> 🧿 Ajna rewards page links to docs

- features/ajna/common/components/AjnaRewardCard.tsx
- features/ajna/common/controls/AjnaRewardsController.tsx
- features/ajna/positions/common/helpers/getAjnaRewards.ts
- features/ajna/rewards/useAjnaRewards.ts
- features/content/faqs/ajna/borrow/en.mdx
- features/content/faqs/ajna/earn/en.mdx
- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- handlers/ajna-rewards/get.tsx
- handlers/ajna-rewards/getAjnaRewardsData.ts
- pages/api/ajna-rewards/index.tsx
- public/locales/en/common.json
- Created `/api/ajna-rewards` endpoint for loading rewards data from database,
- created `getClaimedRewards` query for loading data from subgraph,
- created `useAjnaRewards` hook for handling rewards data,
- added allowing to disable claiming button on demand,
- removed "Earning on {{amount}} of positions".
This has to be thoroughly tested when actual data is available. Currently, both database and subgraph response are empty, so some tweaking around formatting, precision etc. might be required.
> 🧿 Add balances to Ajna rewards page

- features/ajna/positions/common/observables/getAjnaPositionAuction.ts
- partially handled case from story, adjusted condition so it verify whether position is in grace period and if so, liquidation notifications are not displayed
- there should be no situation where grace period notification and notifications that position has been liquidated are visible in the same time
> Adjust Ajna liquidation condition

- features/ajna/positions/common/observables/getAjnaPosition.ts
- added condition which verifies length of position created events in ajna observable
- there should be no infinity loading on owner page when someone use dpm proxy address in url instead of wallet address
> Fix owner page if someone use dpm proxy address instead of wallet address

- features/ajna/common/consts.ts
- features/ajna/positions/earn/helpers/getMinMaxAndRange.ts
- remove ajna earn market price offset on slider for pools that are not utilized
- on stable pools it should be possible to set ltv near 100% (on slider)
> Ajna remove ajna earn market price offset

- features/ajna/positions/borrow/components/ContentFooterItemsBorrow.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
- features/ajna/positions/common/sidebars/AjnaFormFields.tsx
- features/ajna/positions/earn/components/ContentFooterItemsEarnManage.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
- package.json
- yarn.lock
- show max generate amount on ajna borrow UI + validations
- show max withdraw in earn UI
- test whether max generate amount indeed make sense for different pools scenarios (multiple buckets, single bucket, while generating moving lup below htp etc.)
> Bring back max generate validations and calculations

- features/aave/common/components/SidebarAdjustRiskView.tsx
- public/locales/en/common.json
- the warning label on adjusting position now includes proper position type
- manage aave position
- move slider to the right
- the warning label should include proper Earn/Multiply/Borrow info position
> Fix wrong label on managing Aave positions

- components/vault/VaultHeadline.tsx
- features/aave/common/components/AaveHeader.tsx
Added Protocol label to position header with responsive design support according to figma design
open the position view for each protocol and compare the view with figma design
> display a label next to the position [sc-10124]

- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/helpers/formatSwapData.ts
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
- Add in logic to determine swap direction in MultiplyForm component
- Go to close multiply position view and confirm values are displaying as expected
> [BUG] Determine Swap Direction in Side Panel on Close/Decrease

- actions/ajna/multiply.ts
- blockchain/tokens/mainnet.ts
Note: ETH_ACTUAL is an ugly solution. But, I've taken it as I'm unclear on how much other logic depends on ETH actually being WETH on mainnet
- Create a new entry in mainnet tokens for our ETH native stand-in ERC20 address that's used in our smart contracts
- Pass this address to ajna close & multiply on mainnet
- Tested on mainnet with testing wallet https://etherscan.io/tx/0x9a9f46c3f36df0eb6a14dc26885bdb17187824a3357efc5089058cda826d4ab4
> Pass correct ETH address to Ajna Multiply Close & Adjust

- components/DetailsSectionContentCard.tsx
- components/Steps.tsx
- features/ajna/positions/common/components/contentCards/ContentCardPositionLendingPrice.tsx
- features/ajna/positions/earn/components/AjnaEarnSlider.tsx
- features/ajna/positions/earn/consts.ts
- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
- features/ajna/positions/earn/helpers/getLendingPriceColor.ts
Redeploying this: https://github.com/OasisDEX/oasis-borrow/pull/2569
- Added bars that are reflecting current lending price in overview section card,
- added custom color option for content cards,
- created `Steps` component for displaying those bars,
- removed footer text from lending price overview card.
- Bars and lending price value should be similar color, as price position on the slider, but the color shouldn't update along with simulation - it is tied to current price,
- during edit mode when afterpills are displayed, the bars are hidden.
> RE: 🧿 Update Earn overview box to make clear whats the status of the user position

- components/dumb/SliderValuePicker.tsx
- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
**CHANGES**
When maxBorrow can't be determined by calls via the pool and defaults to zero. Then I've suggested a fallback of one rather than zero. So, the slider doesn't get locked at 0 and is unmovable. Equally, if the max is one we'll still show validations messages after the fact that say that the t/x will not work.
> [BUG] Improve Slider Behaviour

- features/aave/services/readPositionCreatedEvents.ts
- features/vaultsOverview/parsers.tsx
- features/vaultsOverview/pipes/positions.ts
Added chainId to the result model when parsing PositionCreated event, so I can use that chainId when creating aave positions stream and map it to the Network Name which is shown in the UI. This will allow to show the correct network icon on the positions table. Previously it was impossible as there were no network data in the position object and it was incorrectly showing ETH MAINNET network for L2's.
1) Open multiply and earn positions on the optimism for aave.
2) Check positions table if the protocol label is showing an optimism icon.
> Position label is not showing correct L2 network icon

- features/ajna/positions/common/helpers/getIsFormEmpty.ts
- features/ajna/positions/common/hooks/useAjnaTxHandler.ts
- issue in `isEmptyForm` was causing the issue with after pills when tx was successful 
- when tx on multiply position is successful, after pills should disappear
> Hide after pills when tx success

- components/AppContext.ts
- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormOrder.tsx
- features/earn/guni/manage/pipes/manageGuniVault.ts
- features/earn/guni/open/pipes/openGuniMultiplyVaultTransactions.ts
- features/exchange/exchange.ts
- features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
- features/multiply/open/pipes/openMultiplyVaultTransactions.ts
- helpers/mocks/exchangeQuote.mock.ts
- refactored `exchangeQuote$` observable to be able to use any token pairs
- added initial quote handling to Ajna multiply order information and based on that and value from swap calculated price impact
- adjusted slider logic to use prices from our price feed (maybe there is a way to base it on swap data, to be investigated) so slider works ok on short pools
- adjusted price impact label in order information to show values not in $ but in coll token / quote token
- use positions on different pools for example ETH/USDC, USDC/ETH, CBETH/ETH and verify price impact
- on short position check whether slider works as expected
> Ajna multiply price impact

- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentDepositCollateral.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentWithdrawCollateral.tsx
https://app.shortcut.com/oazo-apps/story/10552/multiply-withdrawal-ltv-increases-are-not-supported-in-operation
https://app.shortcut.com/oazo-apps/story/10553/multiply-deposit-ltv-decreases-are-not-supported-in-operation
- Temporarily disabled adjust LTV + deposit/withdrawal until these operations are updated
- Go to manage collateral in the UI
- Should not be able to see adjust LTV expander here
> Disable Withdrawal/Deposit + LTV adjustment for Ajna Multiply

- components/DetailsSectionContentCard.tsx
- features/ajna/positions/common/components/contentCards/ContentCardNetBorrowCost.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- public/locales/en/common.json
- Add simple modal and rewards icon to Net Borrow Cost on multiply
> Add Rewards + Tooltip to Multiply overview

- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentManage.tsx
- Remove buy collateral button from manage debt section of ajna multiply
- Go to /ethereum/ajna/847
- Click manage debt in dropdown
- Confirm that the buy coll action pill is not visible
> Remove buy collateral button

- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentGenerate.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentPayback.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentWithdrawCollateral.tsx
- Added missing max values to inputs in ajna multiply form
- inputs like payback, withdraw, generate etc should have max values available above input
> Add missing max values

- .github/workflows/dev-cache.yaml
Implements cache shared between `dev` and feature branches:
https://github.com/actions/cache/blob/main/tips-and-workarounds.md#use-cache-across-feature-branches
> New workflow: Create dev npm cache

- features/ajna/common/components/AjnaProductHubIntro.tsx
- features/ajna/positions/borrow/controls/AjnaBorrowFormController.tsx
- features/productHub/views/ProductHubView.tsx
- handlers/product-hub/promo-cards/ajnaLp.ts
- handlers/product-hub/promo-cards/collections/ajna.ts
- handlers/product-hub/promo-cards/homeWithAjna.ts
- handlers/product-hub/promo-cards/index.ts
- handlers/product-hub/promo-cards/parsers/getPromoCardsPills.ts
- helpers/useFeatureToggle.ts
- Added Ajna Multiply products to `homeWithAjna` and `ajnaLp` promo cards collections,
- created temporary filter that hides Ajna Multiply related stuff from Product Finder if feature flag is turned off.
- disabled possibility to switch from borrow to multiply, although multiply to borrow is still possible
- restored header with Ajna coming soon copy when flag is disabled
- Check `/multiply` and `/ajna/multiply` pages with `AjnaMultiply` flag turned on and off.
- Check possibility to switch between position types with flag turned on and off
> Ajna Multiply on Product Finder

- package.json
- yarn.lock
- bump lib version which fixes issue with zero in warning regarding ltv close to max ltv
- create either borrow or multiply position with ltv within range of 5% to dynamic max ltv. Later on try to deposit a little bit of collateral to remain within 5% range. Warning shouldn't popup
> Bump dma lib 0.4.2

- blockchain/identifyTokens.ts
- blockchain/tokensMetadata.ts
- components/AppContext.ts
- pages/api/token-identifier/index.tsx
- Created `identifyTokens$` observable for identifying provided tokens list,
- created `token-identifier` API endpoint that is utilized by observable mentioned above (mostly for error handlings and hiding json address).
Currently, there is no usage of the observable anywhere inside of the app, so if you want to test it, paste the code from below on any page:
```typescript
const { identifiedTokens$ } = useAppContext()
const [identifiedTokensData, identifiedTokensError] = useObservable(
identifiedTokens$([
'0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2',
'0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0',
'0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
]),
)
console.log('identifiedTokensData')
console.log(identifiedTokensData)
console.log('identifiedTokensError') …
```
> Token identifying by contract address

- features/ajna/positions/common/controls/AjnaProductController.tsx
- Fixed an issue where pools that aren't supported by multiple were redirecting also on borrow and earn.
> Redirect non-multiply tokens only on multiply

- analytics/analytics.ts
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
Story details: https://app.shortcut.com/oazo-apps/story/10642
Changes:
- renamed mixpanel events `stETHAdjustRiskMoveSlider` and `stETHAdjustRiskConfirmRisk` to `aaveAdjustRiskSliderAction`, to one action that handles all aave earn/multiply adjust events
- moved `riskRatioEvent` in the state machine after the debounce (so it doesn't execute like crazy)
- added `userInput` value to `stopLossError` for an instant feedback on the stop loss warning
> fix: [sc-10642] [Aave multiply] Last slider value is not neccesarily the shown order information

- components/AppContext.ts
- features/ajna/positions/common/contexts/AjnaGeneralContext.tsx
- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/observables/getDpmPositionData.ts
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- improved handling of dma multiple positions
- fixed issue with memoization
- go to `0xd790A1516F78E3FB52338084B5C5931a75BB19CF` owner page, click view next to 963 borrow position, then go back to owner, click view next to 963 earn position, correct position should be loaded
- try to go directly to `ethereum/ajna/963`, url should be updated with token pair and product
> Improve handling of dma multiple positions

- features/aave/open/state/openAaveStateMachine.ts
- features/automation/metadata/aave/stopLossMetadata.ts
- features/automation/protection/stopLoss/openFlow/openVaultStopLossAave.ts
Story details: https://app.shortcut.com/oazo-apps/story/10646
> chore: [sc-10646] [Aave multiply] Update Stop loss max offset - validate on 2.5% of liquidation threshold.

- features/aave/manage/containers/AaveManageTabBar.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
Story details: https://app.shortcut.com/oazo-apps/story/10652
> fix: [sc-10652] [Aave multiply] Order information state is not reset when switching between options

- components/AutomationContextProvider.tsx
- components/Tab.tsx
- components/TabBar.tsx
- components/vault/VaultTabTag.tsx
- features/aave/manage/containers/AaveManageTabBar.tsx
- features/automation/api/automationTriggersData.ts
- features/vaultHistory/vaultHistory.ts
- features/vaultHistory/vaultsHistory.ts
- helpers/mocks/stopLoss.mock.ts
Changes 🤺 
- added loading state to the Aave position Protection tab
Story details: https://app.shortcut.com/oazo-apps/story/10656
> fix: [sc-10656] [Aave multiply] App slow to recognize Stop Loss is active

- features/web3OnBoard/use-bridge-connector.tsx
- features/web3OnBoard/wallet-state/connecting-wallet-state-reducer.ts
- features/web3OnBoard/wallet-state/wallet-state-event.ts
- features/web3OnBoard/web3-on-board-connector-provider.tsx
Added a new `connection-cancelled` event and modified the `createConnector` function to handle cases where the connection is canceled. In addition, the return type of createConnector was changed from `Promise<void>` to `Promise<Boolean>`, with the result indicating if the connection is successful.
> Add connection-cancelled handling and correct createConnector behaviour

- components/Modal.tsx
- components/vault/VaultDetails.tsx
- components/vault/detailsSection/ContentCardLtv.tsx
- features/multiply/aave/components/AaveMultiplyPositionData.tsx
- helpers/modalHook.tsx
- public/locales/en/common.json
Changes 🕺 
- added stop loss information on the LTV block of the overview (pic 1)
- added stop loss information in the LTV modal (pic 2)
- added a way to close the modal (hacky, cause `openModal` from `useModal` now has additional `openModal.close` function, but it works and the types are there)
Story details: https://app.shortcut.com/oazo-apps/story/6940
<details>
<summary>pic 1</summary>
</details>
<details>
<summary>pic 2</summary>
</details>
> Aave Position overview Card - Add Stop Loss information

- features/ajna/positions/common/controls/AjnaTokensBannerController.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewController.tsx
- public/locales/en/common.json
- adjusted rewards banner copies in earn positions when lenders price is below lup
- when lenders price is below lup a different copies should be displayed in rewards banner
> Ajna rewards banner adjustment

- components/vault/detailsSection/ContentCardLtv.tsx
- features/aave/open/containers/AaveOpenView.tsx
- features/multiply/aave/components/AaveMultiplyManageComponent.tsx
- features/multiply/aave/components/AaveMultiplyPositionData.tsx
Couple of fixes:
- on open: do not display stop loss values
- on manage: remove hardcoded `stopLossLevelLoading={true}` and use a real value
> Aave Stop loss fixes

- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
Available to withdrawn was `NaN` because the calculation used `withdrawAmount` which is undefined by default.
- Added `zero` as fallback for `withdrawAmount`.
Check available to withdraw after pill on any Ajna Earn position.
> Fix `NaN` in available to withdraw after pill

- blockchain/contracts/index.ts
- blockchain/identifyTokens.ts
Do not prune previously identified tokens.
- Removed pruning function,
- added additional check for identifying to see if token exists in our metadata.
- Try loading couple different results in pool finder,
- open borrow UI for one of the pools,
- see if there is any error on the way.
> Secure token identifier

- handlers/product-hub/index.ts
- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
- Update and remove data for Product Finder are now done via batch update instead of two single queries,
- added additional check, data for specific protocol is going to be removed ONLY if there is new data to overwrite it - it's better to have out of date data, than no data at all,
- removed a warning about token address not found within a config for pools that we are not supporting.
Patch Product Finder and check if results looks reasonable.
> Product Finder database update security and improvement

- features/ajna/positions/earn/controls/AjnaEarnFormOrderInformation.tsx
- removed max ltv and after max ltv from ajna oracless order information section
- max ltv and after max ltv shouldn't be visible in earn order information in oracless mdoe
> Ajna oracless earn order info

- features/ajna/common/consts.ts
- features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
- handlers/product-hub/promo-cards/collections/ajna.ts
- Added `SDAI-USDC`, `TBTC-USDC` and `YFI-DAI` to array with rewards supporting pools,
- hidden rewards banner on multiply UI when pool is not supporting rewards,
- fix reward pill on promo cards.
Patch Product Hub and compare with list of the changes.
> Add new pools with rewards to config

- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/web3OnBoard/web3-on-board-connector-provider.tsx
Introduced a network check in AjnaProductController.tsx and web3-on-board-connector-provider.tsx. Modified the WithConnection component in AjnaProductController to specify MAINNET explicitly and to include TestNet. In web3OnBoard, implemented a useEffect hook to handle change of network if the network of connected wallet does not match the required networks. These changes provide the ability for the Ajna page to switch to the required network when user's wallet is connected to a different network. A proper network check and possible switch increases the seamless user experience and mitigates any contract interaction errors caused due to the wrong network.
> Implement network check in AjnaProductController and WalletManager

- features/aave/components/AaveHeader.tsx
- features/aave/strategies/arbitrum-aave-v3-strategies.ts
- features/aave/strategies/ethereum-aave-v2-strategies.ts
- features/aave/strategies/ethereum-aave-v3-strategies.ts
- features/aave/strategies/optimism-aave-v3-strategies.ts
- features/aave/types/strategy-config.ts
- public/locales/en/common.json
- On aave multiply, borrow and manage earn instead of collateral price and debt price we show ratio between those prices. In case of short position we show debt to collateral. 
- Go to open aave postion
- Go to manage aave positon.
> Show price ratio in aave headers

- features/poolFinder/helpers/getOraclessTokenAddress.ts
- features/poolFinder/types.ts
- handlers/tokens-search/get.ts
Tokens list we are using had two tokens with `RETH` symbol. Response from our API endpoint was using token symbol as key in object, so whenever duplication was found, old data was overwritten by new data. I've updated response, so it's no longer:
```
{ tokenSymbol: tokenAddress }
```
but now it's
```
{symbol: string, address: string}[]
```
- Updated API response structure, so it can handle multiply tokens with same symbol.
Try finding any `RETH` pool on pool finder.
> Handling duplicated token symbol in pool finder

- features/poolFinder/controls/PoolFinderContentController.tsx
- public/locales/en/common.json
There is YieldETH/ETH pool on mainnet (`0x25d63c91a85d0a21dc84021df01a800cd3cda797`). If you try to search for it by providing collateral address (`0xb5b29320d2dde5ba5bafa1ebcd270052070483ec`) it works as intended. Unfortunately, tokens list that we are using for identifying by name or symbol does not contain YieldETH, so by putting `yield` in search, there a no results.
I've updated error message whenever user put as a token something else than direct address, to encourage they to try again, using address, instead of giving up search.
- Added additional error message depending on what kind of input user provided.
> Extended pool finder error message

- public/locales/en/common.json
- From:
" ... You can still open a position **and in** this pool. ..."
- To:
" ... You can still open a position **in** this pool. ..."
> Fixing grammar mistake in oracle-less tooltip

- features/vaultsOverview/parsers.tsx
- added support to net value being displayed in tokens instead of dollars on owner page
- considering you have Ajna earn oracless position, on owner page net value should be displayed in quote tokens
> Owner page support net value in token

- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentGenerate.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentPayback.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentWithdraw.tsx
- features/ajna/positions/common/validation.tsx
- removed isDisabled condition for second inputs in ajna borrow actions, so it's possible to generate without depositing while being on deposit & generate form step etc.
- go through all ajna borrow actions, verify whether user is able to use only second inputs to send tx
- order information should be displayed correctly
> Ajna unblock second inputs in borrow

- features/aave/components/order-information/StrategyInformationContainer.tsx
Modified `StrategyInformationContainer` to conditionally render the `MultiplyInformation` component based on the strategy configuration. This change was made to avoid rendering `MultiplyInformation` when the product type is set to 'Borrow'.
> Add conditional rendering for MultiplyInformation component

- server/database/migrations/027-alter-referrals.sql
- server/database/schema.prisma
add tx_processed column to borrow db - is used if redeemer transaction to add weekly root fails but snapshots are added to the database.
migrate locally
> feat: add `tx_processed` to MerkleTree table

- actions/ajna/borrow.ts
- on repay only action, a withdraw of smallest possible amount of collateral based on precision is added to ensure refresh of netural price and therefore liquidation price
- do repay only action on ajna borrow / multiply position, after sending tx verify whether a small amount of collateral has been withdrawn (potentially you could also check for repay withdraw event in history)
> Ajna withdraw on repay only action

- features/vaultsOverview/parsers.tsx
- features/vaultsOverview/pipes/positions.ts
This commit modifies the risk ratio representation by multiplying loanToValue by 100 in parsers.tsx to express the ratio as a percentage for better user comprehension. Similarly, the variable borrow rate is also converted to a percentage. Additionally, the warning threshold calculation in positions.ts was adjusted by subtracting 3% of maxLoanToValue instead of 3 times maxLoanToValue. The notion of danger is also updated to compare loanToValue with maxLoanToValue instead of liquidation threshold. 
Story details: https://app.shortcut.com/oazo-apps/story/11152
> fix: Wrong values displayed in Owner page for 'Risk ratio' and 'Variable %'

- features/aave/components/DebtInput.tsx
- features/aave/open/sidebars/SidebarOpenAaveVaultEditingState.tsx
- features/aave/types/base-aave-event.ts
This commit updates the 'debt' field in 'base-aave-event.ts' to optional for better handling of missing values. In 'SidebarOpenAaveVaultEditingState.tsx', the maximum amount and price displayed are now more accurately retrieved from the deposit balance. The component 'DebtInput.tsx' has been updated to handle currency digits correctly and to ensure the debt amount is not undefined by handling optional debt amounts. These changes enhance the accuracy and resilience of the system.
> fix: Issues when typing in 'Generate <quote>' input field

- blockchain/identifyTokens.ts
- blockchain/tokensMetadata.ts
- components/SimulateTitle.tsx
- components/vault/VaultHeadline.tsx
- features/ajna/positions/borrow/controls/AjnaBorrowFormController.tsx
- features/ajna/positions/common/contexts/AjnaGeneralContext.tsx
- features/ajna/positions/common/controls/AjnaProductController.tsx
- features/ajna/positions/common/helpers/getAjnaHeadlineProps.tsx
- features/ajna/positions/common/hooks/useAjnaData.ts
- features/ajna/positions/common/views/AjnaPositionView.tsx
- features/ajna/positions/earn/controls/AjnaEarnFormController.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewOpenController.tsx
- features/ajna/positions/multiply/controls/AjnaMultiplyFormController.tsx
- features/poolFinder/helpers/parsePoolResponse.ts
- features/poolFinder/helpers/parseRows.tsx
- features/poolFinder/types.ts
- handlers/tokens-info/tokens.ts
- server/database/migrations/027-tokens-source.sql
- server/database/schema.prisma
https://app.shortcut.com/oazo-apps/story/11038/right-icon-is-shown-for-any-token-called-usdt-icon-should-only-display-based-on-tokenlist
https://app.shortcut.com/oazo-apps/story/10878/secure-token-identifier-against-scam-tokens
- added additional field in db and in tokens interface to support token `source`
- adjusted idenftifyTokens observable to handle `source` prop
- added new props to ajna environment context which are `collateralTokenIcon` and `quoteTokenIcon`
- try to use oracless pools which tokens for sure are not within our config or api token list to see if generic icons will be used
- pool finder shouldn't show token icon if token source is blockchain
- verify …
> Tokens source

- pages/ajna/pool-creator.tsx
`WithConnection` component is causing page to not update. When user clicks on the link somewhere in the UI, the URL in the browser bar is updated, but page is not refreshed. After manual reload new page is loaded. 
There is something wrong with `WithConnection` component that has to be investigated.
- Removed additional props from `WithConnection` component.
Go to pool creator and either try to create pool that already exists or create new one. In both cases there are links to borrow and earn rendered. Click on one of the urls and check if you're getting redirected.
> Pool creator redirect not updating

- features/aave/components/AaveBorrowManageComponent.tsx
- features/aave/components/AaveBorrowPositionData.tsx
- features/aave/components/AaveMultiplyManageComponent.tsx
- features/aave/components/AaveMultiplyPositionData.tsx
- features/aave/components/LiquidationPriceCard.tsx
- features/aave/components/NetValueCard.tsx
- features/aave/services/calculate-view-values-for-position.tsx
- public/locales/en/common.json
- Refactor way of displaying Liquidation Price and Net Value of the position in Aave
- New components only for `NetValue` & `LiquidationPrice` 
- In case of short position tyle we are displaying Debt/Collateral instead of Collateral/Debt
- It's a just view change without changing any significant calculations.
> Liquidation Price & Net Value - Aave Positions

- features/poolCreator/hooks/usePoolCreatorData.tsx
Context: https://discord.com/channels/837076147694207067/1138393690331680768/1142106474852646912
- Transformed token addresses provided by user in inputs into lowercase.
Use not lowercased addresses that weren't working before, but should work now:
`0x0B1ba0af832d7C05fD64161E0Db78E85978E8082` and `0xea100Bec80418680e55D28b655da6CbEF427275f`.
> Lowercase tokens for pool creator form

- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/common/helpers/getBorrowishChangeVariant.ts
- features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx
- updated method responsible for calculating change variant
- when using oracless borrow, after pills should always be green
> Oracless borrow after pills always green

- features/aave/manage/sidebars/GetReviewingSidebarProps.tsx
- features/aave/manage/sidebars/ManageAaveReviewingStateView.tsx
- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
Story details: https://app.shortcut.com/oazo-apps/story/11176
1. Back to editing button - only visible when reviewing adjusting
2. Default manage collateral operation set.
3. Disable button when no amount set.
> fix: [sc-11176] [BUG][Aave v3][Borrow] UI issue in Management block when opening an existent position's page

- features/ajna/positions/common/views/AjnaFormView.tsx
- removed useEffect which was causing unexpected update of `currentStep`
- either borrow, earn or multiply - during transaction switch between tabs (overview -> faq or history -> overview), transaction state should be persisted
> Ajna current step update adjustment

- features/ajna/common/consts.ts
- features/ajna/positions/common/contexts/AjnaProductContext.tsx
- features/ajna/positions/common/notifications.tsx
- public/locales/en/common.json
- added two notifications for ajna oracless borrow positions
- adjust ajna borrow position so threshold price will be within 5% range to LUP, orange notification should be visible in this case
- adjust ajna borrow position so threshold price will be above LUP, red notification should be visible in this case
> Oracless borrow notifications

- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/common/components/contentCards/ContentCardThresholdPrice.tsx
- public/locales/en/common.json
- Added missing values in place of brackets.
Go to any oracless borrow position and click on "Threshold Price" content card.
> Add values to TP content card

- components/AppContext.ts
In the context of resolving merge issues, the variable 'aaveV3Optimism' has been renamed to 'aaveV3'. This change ensures consistency and correctness in the usage of aaveV3 across the component."
> fix: [sc-11269] [Bug][staging] aave v3 mainnet positions aren't loading on the portfolio page

- features/ajna/positions/earn/components/ContentFooterItemsEarnManage.tsx
- when max ajna earn withdraw is below 0, convert it to 0
- negative values of max withdraw amount should be converted to 0 on UI, position WBTC-USDC, 1250 on mainnet
> Ajna earn max withdraw negative to zero

- features/aave/strategies/index.ts
- features/shared/vaultApi.ts
- pages/[networkOrProduct]/aave/[version]/[vault].tsx
Implemented the useApiVaults hook to consolidate and handle vault information in an optimized way. This simplifies the logic, reducing the need for useMemo and useObservable in several places. Adjusted retrieval of chainId to directly access the id property, removing the need for hexToDecimal helper function. The vault type check in the strategies/index.ts file was also revised to leverage the productToVaultType helper function, ensuring consistent vault type validation across the application.
> fix: [sc-11271] [Bug][staging] Aave v3 position 1015 not loading

- features/homepage/AjnaHomepageView.tsx
- features/homepage/common/Hero.tsx
- public/locales/en/common.json
- Modified `Hero` component props to allow using two cta buttons.
Check Ajna landing page and see if there is additional button leading to pool creator.
> Add Pool Creation button to Ajna landing page

- features/ajna/common/consts.ts
- Added `WSTETH` to `AJNA_TOKENS_WITH_MULTIPLY` array.
Patch Product Finder and check if multiply/earn contains WSTETH/ETH Ajna pool.
> Add AJNA WSTETH/ETH to multiply product finder

- package.json
- yarn.lock
- Bumped dma lib to 0.4.11
- claim collateral UI should be triggered on following position: `ethereum/ajna/earn/YFI-DAI/1097#overview`
> Bump dma lib 0.4.11

- package.json
- yarn.lock
- Bumped dma lib 0.4.12
- position ethereum/ajna/1223#overview max generate should be way above 0. At this moment, base on the pool state it should be ~31k
> Bump dma lib 0.4.12

- components/DetailsSectionContentCard.tsx
- components/Tooltip.tsx
- components/constants.ts
- features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
- features/ajna/positions/borrow/helpers/getAjnaBorrowDebtMax.ts
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentDeposit.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentGenerate.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentPayback.tsx
- features/ajna/positions/borrow/sidebars/AjnaBorrowFormContentWithdraw.tsx
- features/ajna/positions/common/components/contentCards/ContentCardLiquidationPrice.tsx
- features/ajna/positions/common/components/contentCards/ContentCardThresholdPrice.tsx
- features/ajna/positions/common/sidebars/AjnaFormFields.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentDeposit.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentOpen.tsx
- features/ajna/positions/earn/sidebars/AjnaEarnFormContentWithdraw.tsx
- features/ajna/positions/multiply/sidebars/AjnaMultiplyFormContentGenerate.tsx
This is probably temporary measure to solve some issues that users are having on oracless mode UI.
[Tab-1692792734724.webm](https://github.com/OasisDEX/oasis-borrow/assets/16230404/ad17f1b4-964a-4046-94f9-cd0f271f3b0c)
- Updated overview section components to allow adding tooltips to content card value, afterpill and footer,
- updated all Ajna form inputs on oracless UI so they accepts 18 decimal places.
Try on both borro oracless and earn oracless position
- check if you can input up to 18 decimal places,
- check if tooltips are available (for main values only if they are different, than zero).
> Ajna oracless full token prices

- features/ajna/positions/common/components/contentCards/ContentCardPositionLendingPrice.tsx
- features/ajna/positions/earn/components/AjnaEarnInput.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
- Added tooltip with full value for lending price content card in oracless mode,
- adjusted manual price input to accept 18 decimal places in oracless mode.
You can check both here: `/ethereum/ajna/earn/0x6982508145454Ce325dDbE47a25d4ec3d2311933-0x6B175474E89094C44Da98b954EedeAC495271d0F/1253`.
> Additional decimal adjustments for Ajna oracless Earn

- features/ajna/positions/common/components/contentCards/ContentCardLiquidationPrice.tsx
- features/ajna/positions/common/components/contentCards/ContentCardPositionLendingPrice.tsx
- features/ajna/positions/common/components/contentCards/ContentCardThresholdPrice.tsx
Tooltip on afterpill condition was not strict enough and was displayed on curated pool borrow products.
- Updated content card afterpills tooltip conditions.
Go to curated and oracless positions and check if afterpill tooltips are visible. They should be visible ONLY in oracless mode.
> Display afterpill only on oracless mode

- actions/ajna/oasisActionsLibWrapper.ts
- package.json
- yarn.lock
- Brought back `getMaxIncreasedValue` usage removed in https://github.com/OasisDEX/oasis-borrow/pull/2790,
- updated `@oasisdex/addresses` package.
Try to repay max debt in few different Ajna positions.
> Revert of a partial revert of `getMaxIncreasedValue` usage 

- middleware.ts
- next.config.js
- tsconfig.json
-  Middleware to handle `Access-Control-Allow-Origin`. If the current origin exists in the header and in the `ALLOWED_ORIGINS` environment variable, there will be an `Access-Control-Allow-Origin` header in the response.
@cristidas please add `ALLOWED_ORIGINS` to AWS.
> Middleware to handle CORS

- features/ajna/common/consts.ts
- Removed TBTC-USDC from `AJNA_POOLS_WITH_REWARDS` config.
1. Patch Product Finder data.
2. Check if sparks are gone in Product Finder TBTC-USDC row.
3. Check if rewards banner is gone on TBTC-USDC open and manage flow pages.
> Remove rewards sparks and banner from TBTC Pools

- features/aave/helpers/getStrategyConfig.ts
Refactored the handling of the vault type in Aave V2 strategy configuration. Removed the dynamic vaultType variable and replaced it with fixed values per each case of asset configurations. This was necessary as changing vault type in Aave v2 is not supported.
> fix: [sc-11664] User cannot access AAVE v2 Earn position (P2)

- features/aave/components/AavePositionHeader.tsx
- features/aave/strategies/ethereum-spark-v3-strategies.ts
- disabled the yield calcs on aave-like earn header
- changed the UI on Spark V3 Earn strats to multiply UI (because theres no yield calcs)
> feat: [sc-11192] ✨ [Frontend] Spark V3 Earn strats using multiply UI

- features/aave/components/AaveMultiplyPositionData.tsx
- features/productHub/controls/ProductHubContentController.tsx
- helpers/useFeatureToggle.ts
Also added `SparkProtocolSDAIETH` feature toggle
Story details: https://app.shortcut.com/oazo-apps/story/11795
> fix: [sc-11795] Replace deb token symbol in buying power with USD for Aave and Spark

- blockchain/networks/networks-config.ts
- features/aave/open/state/openAaveStateMachine.ts
- features/aave/strategies/arbitrum-aave-v3-strategies.ts
- features/aave/strategies/ethereum-aave-v3-strategies.ts
- features/aave/strategies/ethereum-spark-v3-strategies.ts
- features/aave/strategies/optimism-aave-v3-strategies.ts
- features/navigation/controls/NavigationActionsController.tsx
- features/productHub/controls/ProductHubContentController.tsx
- features/productHub/meta.ts
- handlers/product-hub/update-handlers/sparkV3/sparkV3Products.ts
- helpers/useFeatureToggle.ts
- Ready for release.
- Enabling all shorts for aave v3 & spark
- Enabling arbitrum (all multiply) and optimism (missing multiply pairs)
- sDAI/ETH on Spark -> it's Short ETH
- Remove some unused flags
> chore: [sc-11890] Release chores for Arbitrum Multiply   Shorting

- components/history/PositionHistoryItemDetails.tsx
- changed origination fee symbol from USD to quote token
- for example position 1311, origination fee in history should be in ETH
> Ajna history origination fee in quote token

- features/ajna/positions/common/components/contentCards/ContentCardMaxLendingLTV.tsx
- features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
- removed lending price from max lending ltv card footnote
- visit ajna earn position, max lending ltv card shouldn't have footnote
> Remove footnote from max lending ltv card

- features/ajna/positions/common/notifications.tsx
- package.json
- yarn.lock
- disabled momp warning (notification) in oracless mode
- bump dma-lib version
- find oracless earn position with lending price above momp, notification shouldn't be present
> Disable momp warning in oracless

- .env.template
- features/aave/aave-history-support.ts
- features/subgraphLoader/consts.ts
- runtime.config.js
- Adds config for aave history
- Add new env variable `AAVE_OPTIMISM_SUBGRAPH_URL` 
- You can preview example position `/optimism/aave/v3/108#overview`
> feat: enable optimism history

- features/ajna/positions/common/observables/getAjnaPositionAggregatedData.ts
- adjusted conditions regarding auctions so the last event is used to determine whether position was partially or completely liquidated
- adjusted condition regarding grace period
- search for partially / completely liquidated position to check if correct notifications are displayed or do manual testing by mocking values locally
- when user save position during grace period, warning message about grace period should no longer be visible
> Ajna partially liquidated fix

- helpers/clean-object.ts
- helpers/config/access-config-context.ts
- `ob-config` still has the current config
- `ob-config-overrides` has the current config but the new values are set to null (and then the null values are cleared when overrides are loaded, boolean values stay)
- clear you cache
- use `ob-config-overrides` to test feature toggle overriding
> Config overrides defaults to null instead of actual value

- features/automation/metadata/aave/stopLossMetadata.ts
- `createGetAaveStopLossMetadata` uses `getLocalAppConfig` instead of `getAppConfig`
- go to any aave v3 position, it should not throw errors in the console
> Fixes errors on automation context

- public/locales/en/common.json
We are using a calculation that calculates the cost to borrow based on your net value. The current wording is confusing, as it seems it is just using the borrow rate.
> Update net borrow cost to cost to borrow

- features/ajna/positions/common/helpers/getAjnaPositionAggregatedData.ts
- features/ajna/positions/common/observables/getAjnaPositionAggregatedData.ts
- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- added additional filtering of history events in order to get events per given position
- positions under the same ID should have correct, not mixed history
> Ajna history per position

- features/poolFinder/helpers/parsePoolResponse.ts
- features/poolFinder/helpers/parseRows.tsx
- features/poolFinder/types.ts
- features/productHub/helpers/getActionUrl.ts
- features/productHub/helpers/parseProduct.tsx
- features/productHub/types.ts
- handlers/product-hub/update-handlers/aaveV2/aaveV2Products.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/arbitrum-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/ethereum-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/optimims-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aaveV3Handler.ts
- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
- handlers/product-hub/update-handlers/maker/makerHandler.ts
- handlers/product-hub/update-handlers/maker/makerProducts.ts
- handlers/product-hub/update-handlers/sparkV3/sparkV3Handler.ts
- handlers/product-hub/update-handlers/sparkV3/sparkV3Products.ts
- server/database/migrations/032-product-hub-rewards.sql
- server/database/schema.prisma
- `earnStrategy` in db is now enum, values from this column copied to new column `earnStrategyDescription`
- handled change described above in all product-hub related handlers
- added `hasRewards` column
- response from db regarding product-hub should contain additional property `earnStrategyDescription` and `earnStrategy` should be an enum value
- everything should work as before, no functional changes
> Extend product finder database

- features/navigation/controls/NavigationController.tsx
Brought back links that were mistakenly removed from navigation when `NewNavigation` feature flag is off.
> Bring back link in navigation

- features/navigation/panels/getNavProtocolsPanel.tsx
- changed structure of navigation config and in this PR it's handled according to new interface
- from now nav protocol items description will be fully configurable through config
> Incorrect nav protocol items copies

- features/navigation/panels/getNavProductsPanel.tsx
- added `getTokenGroup` in places that were missed
- in nav Product -> Earn -> Yield Loop WSTETH should redirect to `earn/ETH`
> Add missing getTokenGroup mapper

- pages/_app.tsx
- public/locales/en/common.json
- Moved basic SEO tags higher in hierarchy, so they are loaded before global config is fetched.
- Updated title and description according to https://discord.com/channels/837076147694207067/839063661884080128/1157234601043963904.
Open any page and see if title is loaded while page still spins.
> Fix missing basic SEO tags

- features/ajna/positions/earn/helpers/getAjnaEarnData.ts
- helpers/context/ProductContext.ts
- added additional condition to verify whether buckets length is > 0
- visiting owner page with following address `0x10649c79428d718621821cf6299e91920284743f` shouldn't throw error regarding reading data `lps` of undefined
> Fix issue with lps on owner page

- features/navigation/helpers/getProductBorrowNavItems.ts
- features/navigation/helpers/getProductEarnNavItems.ts
- features/navigation/helpers/getProductMultiplyNavItems.ts
- features/navigation/panels/getNavProductsPanel.tsx
- links in nav Products items should redirect to open flows of specific strategy
> Add strategies specific direct links to nav

- features/subgraphLoader/useSubgraphLoader.ts
- added condition to use absolute paths when calling subgraph endpoint
- updating product hub locally should work
- calling staging / prod endpoint manually should update ajna stuff
> Subgraph calls absolute url

- handlers/product-hub/helpers/get-token-group.ts
- added STETH to token group so it maps to ETH
- when using new navigation and selections STETH token on token list, all links (borrow/earn/multiply) should base on ETH
> Add steth to token group

- handlers/product-hub/update-handlers/maker/makerHandler.ts
- handlers/product-hub/update-handlers/maker/makerProducts.ts
- helpers/productCards.ts
- public/mocks/discover/highest-risk-positions.json
- removed CRVV1ETHSTETH from product hub as this pair (CRVV1ETHSTETH-A/DAI) was offboarded from Maker
- no data about CRVV1ETHSTETH within product hub
> Remove CRVV1ETHSTETH from product hub

- pages/earn/open/[ilk].tsx
- pages/vaults/open-multiply/[ilk].tsx
- pages/vaults/open/[ilk].tsx
- removed necessity to connect wallet while being redirected to maker open borrow / multiply / earn open flows
- changes doesn't impact DSR as wallet connection is required there
- disconnect your wallet, while using new navigation, click on maker product, you should be redirected to open flow without the need for wallet connection
> Turn off force connect while redirected to maker open positions flow

- components/InternalLink.tsx
- components/Links.tsx
- components/Links.types.tsx
- components/navigation/Navigation.types.ts
- components/navigation/NavigationMenuDropdownContentList.tsx
- features/navigation/helpers/getNavTokensNestedListItem.tsx
- features/navigation/panels/getNavProtocolsPanel.tsx
Covers:
https://app.shortcut.com/oazo-apps/story/12030/default-selection-of-protocol-in-product-finder
https://app.shortcut.com/oazo-apps/story/12129/when-you-select-a-specific-protocol-for-a-specific-product-other-protocols-populate-the-dropdown-eg-select-aave-but-spark
- Added preselected protocols to protocol specific links,
- removed links to "see all" when there was no specific place that link could take an user.
Try to select any of the links from Protocols panel and check if protocol was preselected in Product Finder.
> Default selection of protocol in Product Finder

- features/navigation/helpers/getNavTokensNestedListItem.tsx
- Fixed an issue, where application was crashing when user selected combination of token and product, that is not available in Product Finder.
Check if Tokens -> BTC/USDX has hidden Earn link.
> Fix application crash with dead end routes in navigation

- features/aave/components/ErrorMessageCannotBorrowDueToProtocolCap.tsx
- features/aave/components/ErrorMessageCannotDepositDueToProtocolCap.tsx
Added utility 'amountFromWei' to convert collateral and debt values from Wei to readable format in Aave component error messages. This change provides a more user-friendly error message by displaying token amounts in their standard unit instead of Wei, which enhances user comprehension.
> AaveLike: Update conversion of collateral and debt values

- components/TopBanners.tsx
Header name is now passed to the mixpanel event instead of hardcoded 'rebranding'. Also added useWindowSize and adjusted styling in the TopBanner component to implement text truncation on small window sizes. This provides informative tracking events and improves the banner presentation on smaller screens.
> :lipstick: Update banner click tracking and add text truncation

- features/multiply/manage/sidebars/SidebarManageMultiplyVaultEditingStage.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVaultManageStage.tsx
- Displays multiply confirmation for closing operation
- Close position and verify the confirmation component
> fix: display multiply confirmation for closing action

- next-i18next.config.js
- pages/_app.tsx
- turned off language detection
- while using preferred language in system / browser as ES, visit app using es translations
> ES language redirect loop fix

- features/productHub/components/ProductHubLoadingState.tsx
- features/productHub/views/ProductHubView.tsx
- Added `useEffect` that reacts to network changes and sets initial network filter,
- removed `useMemo` for `resolvedInitialNetwork` as it wasn't doing anything, this data was loaded only once and never refreshed - it's value is not set directly as `selectedFilters` default value,
- as determining user's network is async, brought back `WithLoadingIndicator` into Product Hub that is displayed while app is checking what chain is user connected to,
- also brought back `ProductHubLoadingState` - it's not new, it was removed some time age when Product Hub data was loaded along with global config and was no longer needed at that moment.
Please test use cases below besides just checking code:
- When user opens Product Hub network filter should be preselected to the network they are connected,
- …
> Product Finder default network filter

- components/portfolio/PortfolioHeader.tsx
- components/portfolio/PortfolioOverview.tsx
- components/portfolio/PortfolioOverviewItem.tsx
- components/portfolio/PortfolioOverviewSkeleton.tsx
- components/portfolio/positions/PortfolioPositionBlock.tsx
- components/portfolio/positions/PortfolioPositionsView.tsx
- components/portfolio/wallet/PortfolioWalletView.tsx
- public/locales/en/portfolio.json
- Updated translations,
- changed Etherscan button variant to match the one in design,
- updated layout of headline items,
- removed arrow from buttons in positions - we were removing them from all places in Product Finder some time ago and we should keep it consistent,
- added blog posts to wallet tab.
> Minor Portfolio layout fixes

- .codesandbox/tasks.json
In the ".codesandbox/tasks.json" file, the "start-production" task's command was modified from "yarn start:preview" to "yarn start". Moreover, the "restartOn" property was removed as it was no longer needed under the new production environment setup resulting in a cleaner and more efficient configuration.
> Simplify production task in CodeSandbox configuration

- blockchain/contracts/arbitrum.ts
- blockchain/contracts/base.ts
- blockchain/contracts/goerli.ts
- blockchain/contracts/mainnet.ts
- blockchain/contracts/optimism.ts
- blockchain/prices.ts
- blockchain/token-metadata-list/token-configs.ts
- helpers/api/tokenTickers.ts
- server/services/cbethBaseChainlinkTicker.ts
- server/services/ethBaseChainlinkTicker.ts
- moved the `oracleTicker` in `getPrice` so it's gonna get picked first (if defined)
- added two (CBETH/USD and ETH/USD) chainlink price sources similar to `getSDaiOracleTicker`
- Go to your Aave V3 on Base position (with ETH or CBETH). The price should not fluctuate (more than the chainlink price source)
> Added chainlink oracle price as price source on BASE

- features/aave/components/AavePositionHeader.tsx
- features/aave/hooks/useAaveEarnYields.ts
- lendingProtocols/aave-like-common/yields/index.ts
This commit addresses an issue where `annualisedYield7days` and `annualisedYield90days` variables could possibly be undefined. We are now checking if these fields exist before using them to calculate yield differences and pushing them into the headline details array. This will prevent runtime errors if the said fields are unexpectedly undefined.
> :bug: chore(aave yields) Fixed possible undefined yields in Aave

- blockchain/prices.ts
- handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
- handlers/portfolio/positions/handlers/ajna/index.ts
- handlers/portfolio/positions/handlers/dsr/index.ts
- handlers/portfolio/positions/handlers/maker/helpers/getMakerPositionInfo.ts
- handlers/portfolio/positions/handlers/maker/index.ts
- handlers/portfolio/positions/helpers/getTokensPrices.ts
- handlers/portfolio/positions/helpers/index.ts
- handlers/portfolio/positions/index.ts
- handlers/portfolio/types.ts
- Replaced simple token tickers usage with price formatter that repeats loading prices as long as one of two happens:
- All prices are loaded successfully.
- Timeout 🤷‍♂️
> Retry tickers request in portfolio handlers

- handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
- Urls to Ajna positions were missing `/` at the beginning of them.
> Fix ajna url on portfolio page

- components/TokensGroup.tsx
- handlers/portfolio/positions/handlers/aave-like/helpers.ts
- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/portfolio/positions/handlers/aave-v2/ds-proxy-position.ts
- handlers/portfolio/positions/handlers/aave-v2/index.ts
- handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
- handlers/portfolio/positions/handlers/maker/helpers/getMakerPositionInfo.ts
- handlers/portfolio/positions/helpers/getTokenName.ts
- helpers/getTokenDisplayName.ts
- Added guard in `TokensList` component to display ETH instead of WETH,
- added guards in all portfolio handlers to cover WETH with ETH only in display parts, not calculations.
> Replace WETH with ETH on aave in portfolio

- features/omni-kit/types.ts
- handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
- handlers/portfolio/positions/handlers/ajna/index.ts
- handlers/portfolio/positions/handlers/maker/helpers/getMakerPositionInfo.ts
- handlers/portfolio/positions/helpers/getBorrowishPositionType.ts
- handlers/portfolio/positions/index.ts
Added default type from subgraph if position type is not found in the database.
> Missing multiply positions on portfolio

- handlers/portfolio/positions/handlers/aave-like/index.ts
Story details: https://app.shortcut.com/oazo-apps/story/12771
> fix: [sc-12771] [BUG] - Borrow cost is surfacing only Borrow APY, not cost to borrow (borrow - supply)

- components/BannerTransparent.tsx
- components/portfolio/PortfolioNonOwnerNotice.tsx
- pages/portfolio/[address].tsx
- public/locales/en/portfolio.json
- Extracted banner to external parameterized component `BannerTransparent`,
- created separated displaying variant for different cases:
- Disconnected user, owner has assets,
- disconnected user, owner has no assets,
- connected user, connected wallet has assets,
- connected user, connected wallet has no assets.
> Non owner notice on portfolio page overhaul

- blockchain/calls/automationBotAggregator.ts
Replaced `replacedTriggerIds` to strings array in automation tx data.
Position to test: `/ethereum/maker/31078`.
> Constant multiply trigger type fix

- components/assetsTable/cellComponents/AssetsTableDataCellAsset.tsx
- components/portfolio/positions/PortfolioPositionAutomationIcons.tsx
- components/portfolio/positions/PortfolioPositionBlock.tsx
- components/portfolio/positions/PortfolioPositionBlockDetail.tsx
- components/portfolio/positions/PortfolioPositionLearn.tsx
- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/portfolio/types.ts
- Made entire position block link,
- same for blocks in Learn with Summer.fi section,
- removed all interactive elements that could be placed in position block before,
- fixed formatting as wrapping entire block in `AppLink` was changing text styles.
> Make entire position block a link

- blockchain/abi/safe-proxy.json
- blockchain/better-calls/dpm-account.ts
- blockchain/better-calls/utils/get-overrides.ts
More info:
https://app.shortcut.com/oazo-apps/story/8425/support-gnosis-safe-in-operation-executor-calls
1. Check if the user is wallet or contract
2. Check if the address has a VERSION.
3. If version is 1.3.0 (only supported by now) we add an access list to the transaction.
> Add an access list to the transaction if a user is a Safe Proxy.

- blockchain/vaults.ts
- components/navigation/content/MyPositionsLink.tsx
- components/navigation/content/MyPositionsOrb.tsx
- components/portfolio/positions/PortfolioPositionsView.tsx
- features/account/AccountData.ts
- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/portfolio/positions/handlers/aave-v2/index.ts
- handlers/portfolio/positions/handlers/ajna/index.ts
- handlers/portfolio/positions/handlers/dsr/index.ts
- handlers/portfolio/positions/handlers/maker/index.ts
- handlers/portfolio/positions/index.ts
- handlers/portfolio/types.ts
- helpers/clients/portfolio-client-data.ts
- helpers/clients/portfolio-client.ts
- helpers/clients/portfolio-positions-count.ts
- pages/portfolio/[address].tsx
- public/locales/en/portfolio.json
Story details: https://app.shortcut.com/oazo-apps/story/12876
Changes:
- portfolio positions parameter `positionsCount`, replies with simple positions list (ids)
- used that with a pipe feedback
- added checks to the owner page pipes (checks if NewPortfolio is enabled, doesn't run them if not)
- changed the label on "Show empty positions" for a more descriptive one
- - that required a separation of filtering and sorting steps in the positions list
> chore: [sc-12876] Separated request for amount of positions

- handlers/portfolio/positions/handlers/aave-like/index.ts
Story details: https://app.shortcut.com/oazo-apps/story/12875
> chore: [sc-12875] Aave V2 steth earn shows APY, but the Aave V3 doesn't

- features/aave/strategies/ethereum-spark-v3-strategies.ts
- features/automation/common/consts.ts
- handlers/product-hub/update-handlers/sparkV3/sparkV3Handler.ts
- handlers/product-hub/update-handlers/sparkV3/sparkV3Products.ts
Story details: https://app.shortcut.com/oazo-apps/story/13019/spark-v3-add-wbtc-dai-multiply-strat
> feature: [sc-13019] Add WBTC-DAI Long strategy to Spark

- public/locales/en/common.json
- added frontend handling for warning
- if liquidation price is equal or above 0.97 * market price, warning should appear (not testable until new package will be released)
> Liquidation price close to market price warning

- features/omni-kit/components/sidebars/OmniFormContentTransaction.tsx
- features/omni-kit/views/OmniFormView.tsx
- public/locales/en/common.json
- fixed issue with missing translations
- converted old translations to omni
- while sending tx, status box should display correct copies
> Updated omni transaction statuses

- handlers/vault/get.ts
https://app.shortcut.com/oazo-apps/story/13164/prod-p-2-3-viewing-other-people-s-maker-positions-is-failing
We can't access vaults created outside summer.
> Revert response for missing vault to 404 status

- features/shared/vaultApi.ts
- handlers/vault/get.ts
In reference to following story [link](https://app.shortcut.com/oazo-apps/story/13164/prod-p-2-3-viewing-other-people-s-maker-positions-is-failing)
- handled properly maker api vault request with recently adjusted empty response
- maker position, for example `29810` should load without any issue
> Adjust maker vault api handling

- components/vault/VaultHeadline.tsx
- features/aave/services/read-position-created-events.ts
- features/omni-kit/controllers/OmniProductController.tsx
- features/omni-kit/helpers/getOmniHeadlineProps.ts
- features/omni-kit/hooks/useOmniProtocolData.ts
- features/omni-kit/observables/getDpmPositionData.ts
- features/omni-kit/protocols/ajna/constants.ts
- helpers/context/ProductContext.ts
- pages/[networkOrProduct]/ajna/omni/[...position].tsx
- pages/[networkOrProduct]/morpho/[...position].tsx
- Added filtering by protocol and raw protocol name to position created events list.
- Fixed improper position header skeleton loading bug - it's not connected to this story, but it was annoying me so I fixed it.
This position was created on Ajna RC10, so it should load: `/ethereum/ajna/omni/borrow/ETH-USDC/2`. Any other position created before that will stuck on infinity loading. Next step is to create nice redirect for when there was old position found and 404 when there was not position at all.
> Fix issue with loading wrong positions in Ajna

- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/portfolio/positions/handlers/aave-v2/index.ts
changed aave pnl calcs to:
```ts
const pnlValue =
positionHistory?.cumulativeDeposit.gt(zero) &&
calculations.netValue
.minus(positionHistory.cumulativeDeposit)
.plus(positionHistory.cumulativeWithdraw)
.div(positionHistory.cumulativeDeposit)
```
- step 1 ...
> fix: fix pnl calculations aave v2 and aave like [sc-13233]

- features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
- fixed case where on reset lending price was set to zero and therefore it was impossible to progress with sending tx
- while opening new position or using empty position, try to deposit some quote token and click reset and try to deposit again - lending price should be set to LUP and you should be able to send tx
> Ajna earn reset lending price fix

- features/omni-kit/components/sidebars/OmniFormFields.tsx
- features/omni-kit/helpers/getOmniBorrowPaybackMax.ts
- features/omni-kit/protocols/ajna/actions/borrow.ts
- features/omni-kit/protocols/ajna/helpers/getAjnaParameters.ts
- features/omni-kit/protocols/ajna/hooks/useAjnaTxHandler.ts
- features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
- features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
- fixed issue related to payback max handling in ajna payback form step, when user didn't have enough quote balance to payback max, `getMaxIncreasedValue` calcs were performed on user quote balance and therefore user was not able to proceed because calculated amount of payback was higher than user balance
- try to click on payback max while having not enough quote amount to payback whole debt, it should be possible to send tx unless other error (for example not enough debt) will popup
> Ajna payback user balance fix

- features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardCardThresholdPrice.tsx
- features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
- Fixed and issue where oracless mode wasn't working on borrow positions because of the usage of `getToken` on unknow token,
- fixed unrelated issue where Threshold price tooltip was shown on content card even when price was zero.
> Fix oracless mode loading on borrow positions

- package.json
- yarn.lock
- bump dma lib version
- liquidation price simulation in ajna borrow position should be in line with liquidation price after sending tx
> Ajna neutral price calcs adjust

- package.json
- yarn.lock
- bumped dma lib version with fix for liquidation price NaN value in ajna borrow position
- no liqudation price NaN value when withdrawing all and payback all in ajna borrow position
> Bump dma library 0.5.26

- features/omni-kit/controllers/OmniProductController.tsx
- fixed  issue where on disconnected wallet token balances were based on address zero which in fact has plenty of tokens of different kind
- on disconnected wallet omni stuff shouldn't show balances
> Omni not connected balances handling

- features/omni-kit/observables/getDpmPositionData.ts
- features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterBorrow.tsx
- features/omni-kit/protocols/ajna/metadata/AjnaLendingDetailsSectionContent.tsx
Second try of fixing that issue.
- Fixed issue where position type was filtered incorrectly on DPM identifying level.
- Fixed unrelated issue where oracless positions where displaying relation of liquidation price to market price.
- Fixed unrelated issue where oracless positions where displaying net value.
> Fix issue with loading wrong type of position on Ajna

- package.json
- yarn.lock
- bump dma lib version with adjusted withdraw close to max ltv warning logic update
- while trying to payback some amount in ajna borrow position and current ltv is within range of 5% to max ltv no warning message about withdrawing should popup unless user will try to withdraw some amount as well
> Adjusted withdraw close to max ltv warning while doing payback

- components/navigation/NavigationNetworkSwitcherButton.tsx
all your base are belong to us
> Set icon size in network switcher

- features/positionHistory/getHistoryEventLabel.ts
- added missing spark event names : Add missing Spark event names in borrow [sc-13325]
(localhost:3000/ethereum/spark/v3/1701#history)
> chore: Add missing Spark event names in borrow [sc-13325]

- blockchain/identifyTokens.ts
- features/aave/services/read-position-created-events.ts
- features/ajna/pool-creator/hooks/usePoolCreatorData.tsx
- features/ajna/pool-finder/components/PoolFinderAddressInput.tsx
- features/ajna/pool-finder/controls/PoolFinderContentController.tsx
- features/ajna/pool-finder/controls/PoolFinderFormController.tsx
- features/ajna/pool-finder/helpers/getOraclessProductUrl.ts
- features/ajna/pool-finder/helpers/parsePoolResponse.ts
- features/ajna/pool-finder/helpers/parseRows.tsx
- features/ajna/pool-finder/helpers/searchAjnaPool.ts
- features/ajna/pool-finder/types.ts
- features/ajna/pool-finder/views/PoolFinderView.tsx
- features/omni-kit/components/OmniDupePositionModal.tsx
- features/omni-kit/hooks/useOmniProtocolData.ts
- features/omni-kit/protocols/ajna/constants.ts
- features/omni-kit/protocols/ajna/helpers/isPoolOracless.ts
- features/omni-kit/views/OmniFormView.tsx
- features/productHub/helpers/getActionUrl.ts
- features/productHub/helpers/parseRows.tsx
- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
- handlers/tokens-info/get.ts
- helpers/context/ProductContext.ts
- Refactored Pool Creator to allow searching for pools across list of networks instead of the one coming from context,
- Modified `identifyTokens$` observable so it does not require entire context as parameter, just network id.
Please note that this PR contains two temporary workarounds to make entire Ajna feature works with changes to `identifyTokens$`. As entire Ajna is currently being refactored to handle multiple networks, it's not work working on perfect solution here, knowing that it's going to be purged in next day or two.
> Pool finder support for Base/other L2 chains

- blockchain/contracts/arbitrum.ts
- blockchain/contracts/base.ts
- blockchain/contracts/goerli.ts
- blockchain/contracts/mainnet.ts
- blockchain/contracts/optimism.ts
- components/sidebar/SidebarSectionStatus.tsx
- features/ajna/pool-creator/hooks/usePoolCreatorData.tsx
- features/omni-kit/helpers/getOmniSidebarTransactionStatus.ts
- features/omni-kit/views/OmniFormView.tsx
- public/locales/en/common.json
- Fixed an issue where etherscan link on base was taking user to mainnet etherscan.
- Added names for Etherscan forks for each network.
> Fix etherscan url on Pool Creator

- blockchain/networks/network-helpers.ts
This pull request adds support for network forks in the getNetworkByName function. Previously, the function only checked for the base network name, but now it also checks for the network name followed by "-test". This ensures that the function can handle network forks properly.
> Add support for network forks in getNetworkByName function

- features/omni-kit/protocols/ajna/helpers/getLendingPriceColor.ts
- fixed color of lending price value in overview section
> Lending price color adjustment

- features/omni-kit/components/sidebars/borrow/OmniBorrowFormContentDeposit.tsx
- features/omni-kit/components/sidebars/borrow/OmniBorrowFormContentGenerate.tsx
- features/omni-kit/components/sidebars/earn/OmniEarnFormContentDeposit.tsx
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentDepositCollateral.tsx
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentOpen.tsx
- features/omni-kit/helpers/getOmniPrimaryButtonLabelKey.ts
- features/omni-kit/helpers/getOmniSidebarButtonsStatus.ts
- features/omni-kit/helpers/getOmniSidebarPrimaryButtonActions.ts
- features/omni-kit/views/OmniFormView.tsx
- Fixed an issue where form was trying to switch network on "Risk" step,
- fixed an issue where "Switch network" button was disabled on any of editing steps,
- fixed an issue with primary button label displaying gibberish in some edge cases,
- hidden token balances until user is connected to correct network to avoid confusion.
> Fix network switching in Omnikit

- features/omni-kit/protocols/ajna/hooks/index.ts
- features/omni-kit/protocols/ajna/hooks/useAjnaData.ts
- features/omni-kit/protocols/ajna/hooks/useAjnaRedirect.ts
- Brought back `useAjnaData` hook that redirects multiply UI to borrow if multiply is not supported for given token.
> Redirect Ajna position from multiply to borrow

- features/omni-kit/components/OmniDupePositionModal.tsx
- features/omni-kit/contexts/OmniProductContext.tsx
- features/omni-kit/protocols/ajna/helpers/getFlowStateFilter.ts
- features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
- features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
- features/omni-kit/views/OmniFormView.tsx
- public/locales/en/common.json
- Updated `ajnaFlowStateFilter` to filter out positions that were open on old versions of Ajna.
- Set `OmniDupePositionModal` as default component with generic translation instead of Ajna ones.
- Added `theme` prop to `OmniDupePositionModal`.
> Adjust Omni dupe modal filtering

- features/aave/services/risk-slider-config.tsx
This pull request adds the ability to configure the risk slider configuration for aave/spark. It introduces a new function, `getRiskRatio`, which retrieves the risk ratio from the local app configuration. The risk ratios are now dynamically set based on the configuration values.
> Configurable aave/spark risk slider minimum/default values

- components/navigation/NavigationMenuDropdownContentListItem.tsx
- features/navigation/controls/NavigationActionsController.tsx
- features/navigation/controls/NavigationController.tsx
- features/navigation/panels/getNavProductsPanel.tsx
- handlers/product-hub/promo-cards/collections/aaveV3.ts
- handlers/product-hub/promo-cards/home.ts
- Made product types in Product tab clickable and removed "View all {{productType}} strategies" link.
- Fixed the way protocol names are displayed in navigation, e.g. "Aave V3" instead of "Aavev3".
- Replaced Optimism Aave WBTC/USDC multiply promo card with same thing, but on Arbitrum.
- Removed usage of `NewNavigation` feature flag.
> Navigation update

- package.json
- scripts/notification-dummy.js
This pull request includes the addition of a notification-dummy file that sets up a socket.io server for handling notifications. This will allow for real-time communication between the server and clients.
Requires:
```
NOTIFICATIONS_HOST="http://localhost:3001"
```
> Add notification-dummy

- features/aave/aave-context.ts
- features/aave/helpers/getStrategyConfig.test.ts
- features/aave/helpers/getStrategyConfig.ts
- pages/[networkOrProduct]/aave/[version]/[vault].tsx
- pages/[networkOrProduct]/spark/[version]/[vault].tsx
This pull request adds the AaveLikeLendingProtocol to the AaveContext and getStrategyConfig functions. This allows for better integration with the Aave lending protocol.
> Add AaveLikeLendingProtocol to AaveContext and getStrategyConfig

- features/ajna/rewards/components/AjnaRewardCard.tsx
- features/subgraphLoader/consts.ts
- handlers/ajna-rewards/getAjnaRewardsData.ts
- fixed issue with reading claimable rewards
- added extra check to avoid situation where user claimed bonus rewards but db, subgraph didn't manage to update on time before claiming regular
> Adjust rewards handling logic

- features/aave/components/AaveMultiplyPositionData.tsx
- features/aave/components/PositionInfoComponent.tsx
- features/aave/helpers/getStrategyConfig.ts
- features/aave/services/get-aave-history-events.ts
- features/omni-kit/components/details-section/modals/OmniMultiplyNetValueModal.tsx
- features/omni-kit/protocols/aave/history/types.ts
- features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataNetValueLending.tsx
- features/positionHistory/types.ts
- features/subgraphLoader/consts.ts
- pages/[networkOrProduct]/aave/[version]/[vault].tsx
- public/locales/en/common.json
This PR updates the Aave cumulative data and net value calculation. It includes changes to the `AaveCumulativeData` and `AaveCumulativesResponse` interfaces, as well as updates to the `useAjnaCardDataNetValueLending` and `getStrategyConfig$` functions. The changes ensure that the net value is calculated correctly based on the market price of the token and include improvements to the cumulative deposit, withdrawal, and fees calculations.
> Update Aave cumulative data and net value calculation

- pages/api/rpcGateway.tsx
`const rpcGatewayUrl = getConfig()?.publicRuntimeConfig.rpcGatewayUrl ?? process.env.RPC_GATEWAY`
- step 1 ...
> fix: get config from next

- pages/api/rpcGateway.tsx
warn instead of throw
- step 1 ...
> fix: warn on missing env

- features/omni-kit/helpers/getOmniFlowStateConfig.ts
- features/omni-kit/protocols/ajna/helpers/getMaxIncreasedValue.ts
- allowance multiplier led to unwanted decimals, added `dp()`
- try to set allowance while doing payback operation in ajna
> Ensure precision while stetting allowance

- features/omni-kit/controllers/borrow/OmniBorrowFormController.tsx
- features/omni-kit/controllers/multiply/OmniMultiplyFormController.tsx
- after closing position TX is completed, Confirm button redirects to default form action
- close multiply or borrow position, after clicking confirm user should moved to adjust or deposit & borrow action
> Ensure proper UX after closing position

- features/productHub/controls/ProductHubFiltersController.tsx
- features/productHub/helpers/getStrippedQueryString.ts
- features/productHub/meta.ts
- features/productHub/views/ProductHubView.tsx
- handlers/product-hub/helpers/get-token-group.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/arbitrum-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/base-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/ethereum-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/optimims-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/types.ts
- Fixed an issue where selecting an option on natural language caused to app crash - from now on selecting token in NLS resets debt/secondary token filter. Keeping those filters sometimes lead to a situation where selected debt token wasn't even available on a list of possible debt tokens for selected collateral.
- Fixed an issue where a lot of Aave products weren't displayed properly in filters because of wrong configuration.
- Simplified sorting in debt token and added same kind of sorting to secondary token filter.
- Added USDC group that contains USDBC.
> Product Finder filtering fixes

- features/aave/components/ManageSectionComponent.tsx
- features/aave/components/PositionInfoComponent.tsx
This pull request adds the `strategyType` prop to the `ManageSectionComponent` and `PositionInfoComponent` components. It also fixes the net value calculation for long Aave earn products.
> Fix net value calculation for long Aave earn products

- features/omni-kit/components/sidebars/OmniFormFields.tsx
- features/omni-kit/components/sidebars/borrow/OmniBorrowFormContentDeposit.tsx
- features/omni-kit/components/sidebars/borrow/OmniBorrowFormContentGenerate.tsx
- features/omni-kit/components/sidebars/borrow/OmniBorrowFormContentPayback.tsx
- features/omni-kit/components/sidebars/borrow/OmniBorrowFormContentWithdraw.tsx
- features/omni-kit/components/sidebars/earn/OmniEarnFormContentDeposit.tsx
- features/omni-kit/components/sidebars/earn/OmniEarnFormContentOpen.tsx
- features/omni-kit/components/sidebars/earn/OmniEarnFormContentWithdraw.tsx
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentDepositCollateral.tsx
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentDepositQuote.tsx
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentOpen.tsx
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormContentWithdrawCollateral.tsx
- fixed issue with auxiliary inputs precision
- it should be possible to use auxiliary input as alternative, simulation should work
> Auxiliary inputs change fix

- components/portfolio/positions/PortfolioPositionsView.tsx
- Fixed an issue when sometimes positions of incorrect type were shown when user selected something in the filters.
> Fix filtering of Ajna positions on Portfolio

- blockchain/transaction-fee/get-optimism-transaction-fee.ts
- features/ajna/pool-creator/hooks/usePoolCreatorData.tsx
- features/ajna/rewards/components/AjnaRewardCard.tsx
- features/omni-kit/hooks/useOmniTxHandler.ts
- features/omni-kit/observables/estimateOmniGas.ts
- helpers/handleTransaction.ts
- propagated gas estimation to tx total cost on l2 since receipt doesn't contain info about l1 fees
- when doing tx using ajna on Base, total tx cost should make sense
> Propagate gas estimation to tx total cost on l2

- features/omni-kit/server/getOmniServerSideProps.ts
- added condition when getting server side props to check whether required params are defined, if not redirect to not-found
- visit `/ethereum/ajna/680`, you should be redirected to not found page
> Omni redirect when lack of url params

- components/portfolio/positions/PortfolioPositionBlock.tsx
This pull request filters out the 'earnings' and 'pnl' details in the PortfolioPositionBlock component.
> Filter out 'earnings' and 'pnl' details in PortfolioPositionBlock

- features/omni-kit/components/details-section/parsers/useOmniCardDataLiquidationPrice.ts
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
- since we are using 'above' or 'below', liquidation ratio should be display as absolute value
- use resolved after position debt in multiply form order
- on Ajna lending position liquidation ratio in card footer should be displayed as absolute value
> Liquidation price ratio as abs value

- features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterBorrow.tsx
- features/omni-kit/protocols/ajna/components/details-section/AjnaLendingDetailsSectionFooter.tsx
- fixed issue where after available to borrow value in details footer section was based on cached value from simulation
- no after label after tx is finished in details footer section
> Fixed issue with persisting after label

- features/omni-kit/components/sidebars/OmniFormContentTransaction.tsx
- features/omni-kit/components/sidebars/borrow/OmniBorrowFormOrder.tsx
- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
- features/omni-kit/contexts/OmniProductContext.tsx
- features/omni-kit/protocols/ajna/metadata/AjnaClaimCollateralFormOrderInformation.tsx
- features/omni-kit/protocols/ajna/metadata/AjnaEarnFormOrder.tsx
- features/omni-kit/protocols/ajna/metadata/AjnaEarnFormOrderInformation.tsx
- features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
- features/omni-kit/protocols/ajna/types.ts
- features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
- features/omni-kit/types.ts
- Removed `cached` prop from form order components.
- Included `shouldShowDynamicLtv` value to use `resolveIfCachedPosition`.
> Fix Dynamic max LTV in post tx order information

- features/omni-kit/components/sidebars/OmniAdjustSlider.tsx
- Cap max value of multiply slider to 0.99
> Cap max value of multiply slider to 0.99

- features/exchange/exchange.ts
We are having issues with reverting txs with this exchange. I want to check if this is the reason by testing this on staging.
> Exclude Woofi on Optimism

- features/omni-kit/protocols/morpho-blue/helpers/getMorphoParameters.ts
Context: https://discord.com/channels/837076147694207067/1168506682691821578/1197197062375211018
- Changed address of ETH in `getMorphoParameters` method.
> Use ETH_ACTUAL address instead of ETH in Morpho Blue dependencies

- features/productHub/helpers/getActionUrl.ts
- Used `LendingProtocol.MorphoBlue` instead of hardcoded value.
> Fix Morpho Blue url in Product Finder

- features/omni-kit/helpers/getOmniPositionUrl.ts
- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
- handlers/portfolio/positions/handlers/morpho-blue/helpers/getMorphoPositionDetails.ts
- handlers/portfolio/positions/handlers/morpho-blue/helpers/getMorphoPositionInfo.ts
- handlers/portfolio/positions/handlers/morpho-blue/helpers/index.ts
- handlers/portfolio/positions/handlers/morpho-blue/index.ts
- handlers/portfolio/positions/handlers/morpho-blue/types.ts
- handlers/portfolio/positions/helpers/getDefaultBorrowishPositionType.ts
- handlers/portfolio/positions/helpers/index.ts
- handlers/portfolio/positions/index.ts
- Added Morpho Blue subgraph to the config and removed `TempGraph` which was long overdue.
- Created `getMorphoDpmPositions` subgraph query.
- Created `getMorphoPositions` handler for Portfolio.
- Added `positionId` to `getOmniPositionUrl` so it can be used for generating urls to existing positions.
Wallet address: `0xbEf4befb4F230F43905313077e3824d7386E09F8`.
> Morph Blue positions in Portfolio

- package.json
- public/locales/en/common.json
- yarn.lock
- Fixed validation translation.
- Updated package to the version that contains a fix.
> Fix liquidity validation issue in Morpho Blue position

- features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
- Hardcoded `shouldShowDynamicLtv` to return `false` at all time in Morpho Blue metadata as it shouldn't be visible at any point for that protocol.
> Remove dynamic LTV from order information

- features/navigation/panels/getNavProtocolsPanel.tsx
> Hide links to multiply and earn for Morpho Blue in navigation

- features/omni-kit/controllers/OmniHistoryController.tsx
- public/locales/en/common.json
- Changed hardcoded "Ajna" in history to `LendingProtocolLabel`.
> Protocol name from context in history screen

- components/sidebar/SidebarSectionFooterButton.tsx
- features/omni-kit/views/OmniFormView.tsx
- Added `withoutNextLink` prop to sidebar that allows to use theme.ui `Link` component skipping Next.js one which clears cache and state when moving between linked pages.
> Fix issue when clicking go to position keeps state of order info

- features/omni-kit/protocols/ajna/helpers/getAjnaParameters.ts
- features/omni-kit/protocols/ajna/helpers/getMaxIncreasedOrDecreasedValue.ts
- features/omni-kit/protocols/morpho-blue/helpers/getMorphoParameters.ts
- added offset to generating value while opening morpho position
- removed unnecessary condition form ajna logic
- minimalized offset while withdrawing collateral
- is should be possible to deposit for example 20 collateral token and click max generate
> Max borrow when open morpho fix

- features/marketing-layouts/components/IconWithPalette.tsx
- features/marketing-layouts/components/index.ts
- features/marketing-layouts/helpers/index.ts
- features/marketing-layouts/helpers/renderLinearGradientStops.tsx
- features/marketing-layouts/icons/index.ts
- features/marketing-layouts/icons/loop.tsx
- features/marketing-layouts/icons/sleep.tsx
- features/marketing-layouts/icons/stack.tsx
- features/marketing-layouts/types.ts
- pages/better-on-summer/test-page.tsx
- Created set of set of components and settings allowing to display icon with extendable palette.
- Created temporary page `/better-on-summer/test-page` for a playground.
So far the icons themselves are broken in figma, so I did not exported them all. Those included in this PR are examples that could be used during development until desing team delivers fixed svgs.
> Icons with configurable main color

- components/layouts/MarketingLayout.tsx
- components/layouts/MarketingLayout.types.tsx
- features/marketing-layouts/helpers/index.ts
- features/marketing-layouts/helpers/renderCssGradient.ts
- features/marketing-layouts/types.ts
- pages/better-on-summer/test-page.tsx
- Added `backgroundGradient` prop to `MarketingLayout` component that allows displaying gradient in the background based on array of colors.
- Created `renderCssGradient` function that transforms an array of colors to css gradient format.
> Landing page layout

- features/aave/services/get-aave-history-events.ts
- filtered out Ajna events from Aave.
- `/ethereum/aave/v3/84#history` following position should contain only Aave events
> Filter out Ajna events from Aave.

- features/productHub/controls/ProductHubContentController.tsx
- features/productHub/hooks/useProductHubBanner.tsx
- Added additional filters to Product Finder banners so Ajna Pool Finder shows when no protocol is selected or Ajna is one of selected protocols.
> Filter Ajna Pool Finder banner in Product Finder 

- features/marketing-layouts/types.ts
- features/productHub/components/ProductHubPromoCardsList.tsx
- features/productHub/controls/ProductHubPromoCardsController.tsx
- features/productHub/types.ts
- features/productHub/views/ProductHubView.tsx
- pages/better-on-summer/test-page.tsx
- Added Product Finder to Marketing Template interface and view.
- Extracted `ProductHubPromoCardsList` from Product Finder as separated component so the list can be generated independently from Product Finder settings.
- Product Finder design wasn't adjusted to the new layouts as this is not a part of current epic; for more info see here: https://discord.com/channels/837076147694207067/1199024181447237652/1200138180746301480
> Add Product Finder to Marketing Template

- components/layouts/MarketingLayout.tsx
- features/marketing-layouts/components/MarketingTemplateBanner.tsx
- features/marketing-layouts/components/MarketingTemplateProductBox.tsx
- features/marketing-layouts/components/index.ts
- features/marketing-layouts/types.ts
- features/marketing-layouts/views/MarketingTemplateBlockView.tsx
- features/marketing-layouts/views/MarketingTemplateView.tsx
- pages/better-on-summer/[...slug].tsx
- Created `MarketingTemplateBanner` component.
- Various mobile fixes.
> UI component: MarketingTemplateBanner

- handlers/portfolio/positions/helpers/getPositionsAutomations.ts
This pull request adds the Aave trigger types to the getPositionsAutomationsParams interface. Previously, the autoBuy and autoSell trigger types were missing the AaveBasicBuyV2 and AaveBasicSellV2 options. This update ensures that these options are included, allowing for more comprehensive automation of Aave positions.
> Add Aave trigger types to getPositionsAutomationsParams

- components/SimpleCarousel.tsx
- Changed UI of `SimpleCarousel` on mobile - according to the design, instead of prev/next arrows there should be a list of dots below slider.
> Simple Carousel mobile UI

- features/aave/components/BasicAutomationDetailsView.tsx
- features/aave/manage/containers/OptimizationControl.tsx
- features/aave/manage/services/calculations/get-trigger-execution-price.ts
- features/aave/manage/sidebars/AutoBuySidebarAaveVault.tsx
- features/aave/manage/sidebars/AutoSellSidebarAaveVault.tsx
The update involves using a newly created function, getDenomination, from the calculations service. This function is used to set the currency code in both the AutoSellSidebarAaveVault and AutoBuySidebarAaveVault sidebars. It's also introduced in BasicAutomationDetailsView to show the correct denomination in the views. A minor adjustment in OptimizationControl's nextPrice calculation is dually covered.
> Update currency denomination in sidebars and details view

- contentful/mappers/mapLandingInfoBlock.ts
- contentful/queries/getLandingPageBySlug.ts
- contentful/types/rawResponses.ts
- features/marketing-layouts/components/MarketingTemplateBanner.tsx
- features/marketing-layouts/components/MarketingTemplateHero.tsx
- features/marketing-layouts/components/MarketingTemplateInfoBox.tsx
- features/marketing-layouts/components/MarketingTemplateMarkdown.tsx
- features/marketing-layouts/components/MarketingTemplateProductBox.tsx
- helpers/getNextParsedUrl.ts
- Created `getNextParsedUrl` function that parses `string` url into nextjs link format.
- Fixed an issue where links weren't displayed in `MarketingTemplateInfoBox` component.
- Created custom links handler for Contentful Rich Text parser.
- Fixed an issue where tokens list wasn't displayed in `MarketingTemplateHero` component.
> Fix links on Landing Pages

- features/omni-kit/helpers/getOmniPrimaryButtonLabelKey.ts
- features/omni-kit/views/OmniFormView.tsx
- fixed condition which was previously broken by mistake
- while switching to borrow or multiply position type, button should have correct labels
> Switch to borrow or multiply label

- blockchain/prices.ts
- handlers/portfolio/positions/helpers/getTokensPrices.ts
- handlers/product-hub/update-handlers/aaveV2/aaveV2Handler.ts
- handlers/product-hub/update-handlers/aaveV3/aaveV3Handler.ts
- handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
- handlers/product-hub/update-handlers/maker/makerHandler.ts
When ticker value is not found will log error on the server and fallback to 0 price for that token instead of crashing entire page data response.
Also extended logs in getTokenPrice to easier track the error source in the future.
> Proposed error handling for missing tickers

- features/omni-kit/components/sidebars/OmniAdjustSlider.tsx
- features/omni-kit/contexts/OmniProductContext.tsx
- features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
- package.json
- yarn.lock
- limited slider max value to max ltv rounded down
- bumped library version with fix for payback action
- max on slider limited to max ltv
- working payback action
> Limit max on morpho multiply slider

- contentful/mappers/mapLandingProductFinderBlock.ts
- contentful/types/rawResponses.ts
- Add support for `token` and `initialNetwork`.
> Landing Page Product Finder missing config 

- blockchain/contracts/arbitrum.ts
- blockchain/contracts/base.ts
- blockchain/contracts/goerli.ts
- blockchain/contracts/mainnet.ts
- blockchain/contracts/optimism.ts
- package.json
- yarn.lock
- Added `yvCurve-USDM-sDAI-f/DAI` to config.
- Removed `YIELDBTC-WBTC` and `YIELDETH-ETH` as they are no longer in use.
> Add `yvCurve-USDM-sDAI-f/DAI` to PF as oracless pool

- handlers/portfolio/constants.ts
- handlers/portfolio/positions/handlers/aave-like/helpers.ts
- handlers/portfolio/positions/handlers/maker/index.ts
- handlers/portfolio/positions/handlers/maker/types.ts
- handlers/portfolio/positions/helpers/getAutomationData.ts
- handlers/portfolio/positions/helpers/getPositionsAutomations.ts
This pull request adds an emptyAutomations constant to the Aave-like helpers and removes unused code. It adds triggerType to the automation subgraph query and uses it for filtering, without decodeTriggerDataAsJson.
> Add empty automations, triggerType and remove unused code

- handlers/portfolio/constants.ts
- handlers/portfolio/positions/handlers/aave-like/helpers.ts
- handlers/portfolio/positions/helpers/getAutomationData.ts
- handlers/portfolio/positions/helpers/getPositionsAutomations.ts
This pull request refactors the automation handling in the portfolio positions code. It includes changes to the `commonDataMapper` function, the `automationQuery` GraphQL query, and the `getPositionsAutomations` function. The changes ensure that automations are correctly retrieved and processed based on the position type and trigger type.
> Refactor automation handling in portfolio positions

- features/positionHistory/getHistoryEventLabel.ts
- add missing `AAVEDepositBorrow` event
check locally : localhost:3000/base/aave/v3/244#history
> chore: add missing label

- features/aave/manage/sidebars/SidebarManageAaveVault.tsx
- removed redirect to simulation after position closed
- removed forced page reload after adjusting position
- after closing aave position or adjusting, when user will click on button form state should change back to editing state
> Aave remove redirect or reload after successful tx when clicking on btn

- components/HeadTags.tsx
This pull request refactors the og:image meta tags in the HeadTags.tsx file. The changes include adding a key attribute to the og:image and og:image:secure_url meta tags and updating the content attribute to use the ogImage variable if it exists.
> Refactor og:image meta tags in HeadTags.tsx

- helpers/triggers/setup-triggers/get-setup-trigger-config.ts
Renamed the naming convention for AaveV3 to 'aave3' within the trigger configuration setup. This modification aligns the key used to identify this protocol in the setup process with the expected keys, thus ensuring accurate trigger configuration.
> Update AaveV3 naming in trigger configuration

- components/HeadTags.tsx
- public/locales/en/common.json
`getOgLabels` function has been implemented to retrieve the appropriate OG title and description based on the URL and translation. This allows for more customized and targeted OG tags for different pages on the website.
> Add semi dynamic OG title and description

- components/GenericMultiselect.tsx
- features/productHub/controls/ProductHubFiltersController.tsx
This pull request adds a new prop called `fitContents` to the `GenericMultiselect` component. When set to `true`, the component's height will adjust to fit its contents. This allows for more flexibility in displaying options within the component.
> Add fitContents prop to GenericMultiselect component

- handlers/portfolio/positions/handlers/aave-like/helpers.ts
This pull request updates the defaultList in the emptySutomations commonDataMapper. The change ensures that the defaultList is updated based on the protocol, excluding 'AAVE' and 'Spark'. This improves the functionality and accuracy of the automations.
> Update defaultList in emptySutomations commonDataMapper

- components/portfolio/positions/PortfolioPositionsView.tsx
- handlers/portfolio/positions/handlers/ajna/helpers/getAjnaIsOraclessAndNotEmpty.ts
- handlers/portfolio/positions/handlers/ajna/helpers/index.ts
- handlers/portfolio/positions/handlers/ajna/index.ts
- handlers/portfolio/types.ts
- added `isOraclessAndNotEmpty` in handler interface so it's possible to determine whether position is oracless and is not empty to show it later in portfolio as not empty position
- self explanatory, test it using not empty ajna oracless position
> Show not empty oracless positions in portfolio as default

- features/omni-kit/protocols/ajna/helpers/getAjnaMinMaxAndRange.tsx
- features/omni-kit/protocols/ajna/metadata/AjnaEarnSlider.tsx
- package.json
- yarn.lock
- bumped lib version with ajna earn validation adjustments when LUP below HTP
- adjusted ajna earn slider handling when LUP below HTP
- when LUP below HTP it should be possible to deposit to current bucket or move lending price to higher ranges
> Adjust ajna slider handling when lup is below htp

- features/ajna/pool-finder/helpers/parsePoolResponse.ts
- helpers/formatters/format.ts
- in pool finder we have 2x columns with displays collateral and quote token, if tokens symbols are very long it breaks styles. Added method to shorten it in strategy column
- shortened token symbols in pool finder strategy column
> Shorten tokens symbol in pool finder if necessary

- features/aave/components/AaveBorrowPositionData.tsx
- features/aave/components/AaveMultiplyPositionData.tsx
- features/aave/components/order-information/OpenAaveStopLossInformationLambda.tsx
- features/aave/manage/helpers/map-stop-loss-from-lambda.ts
- features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx
- handlers/portfolio/positions/handlers/aave-like/helpers.ts
- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/portfolio/positions/handlers/maker/index.ts
- handlers/portfolio/positions/helpers/getPositionsAutomations.ts
New stop loss UI fixes:
[[BUG] - New Stop-Loss - After Setting up or updating stop-loss a message reads that vault will update in 30 seconds but screen never updates](https://app.shortcut.com/oazo-apps/story/14334/bug-new-stop-loss-after-setting-up-or-updating-stop-loss-a-message-reads-that-vault-will-update-in-30-seconds-but-screen)
[[BUG] - New Stop-Loss - When LTV is equal to 0 'NaN' is displayed for 'Saving compared to liquidation'](https://app.shortcut.com/oazo-apps/story/14356/bug-new-stop-loss-when-ltv-is-equal-to-0-nan-is-displayed-for-saving-compared-to-liquidation)
[[BUG] - Overview - LTV tooltip reads 'Stop-Loss not set' even when it's ON](https://app.shortcut.com/oazo-apps/story/14345/bug-overview-ltv-tooltip-reads-stop-loss-not-set-even-when-it-s-on)
[[BUG] - Portfolio's …
> New stop loss UI fixes

- features/omni-kit/protocols/morpho-blue/settings.ts
The RETH token has been added to the supported token list in the Omni-kit Morpho-Blue protocol. In addition, the corresponding mapping for 'RETH-ETH' has been updated in the settings file.
> Add RETH to supported tokens list

- blockchain/better-calls/dpm-account.ts
- features/aave/components/order-information/OpenAaveStopLossInformationLambda.tsx
- features/aave/hooks/useGasEstimation.tsx
- features/aave/hooks/useTransactionCostWithLoading.tsx
- features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx
- features/aave/manage/sidebars/AaveManagePositionTrailingStopLossLambdaSidebar.tsx
- features/aave/open/helpers/get-aave-like-stop-loss-params.ts
- features/aave/open/helpers/use-lambda-debounced-stop-loss.ts
- features/aave/open/helpers/use-lambda-debounced-trailing-stop-loss.ts
- features/aave/open/sidebars/components/AaveOpenPositionStopLossLambdaSidebar.tsx
- features/aave/open/sidebars/components/StopLossLambdaInProgressStateView.tsx
- features/aave/types/base-aave-context.ts
- features/aave/types/base-aave-event.ts
- features/automation/common/txDefinitions.types.ts
- features/web3OnBoard/useConnection.tsx
- helpers/triggers/get-triggers/get-triggers-types.ts
- helpers/triggers/setup-triggers/setup-aave-stop-loss.ts
- helpers/triggers/setup-triggers/setup-aave-trailing-stop-loss.ts
- helpers/triggers/setup-triggers/setup-triggers-types.ts
- Real gas estimation for Aave Stop Loss & Trailing Stop Loss
- Removed not used code from triggers
- Removed a new trigger types. Frontend doesn't need to know what are current types.
- Added a hook for Gas Estimations
- Performance update for the  `WalletManagement` hook.
> Add Gas Estimations For Stop Loss Transactions

- features/aave/manage/state/triggersAaveStateMachine.ts
This pull request adds the aaveTrailingStopLossDMA trigger to the hasActiveProtection function in order to include it in the list of active protection triggers for the AaveV3 lending protocol.
> Add aaveTrailingStopLossDMA trigger to hasActiveProtection function

- features/aave/components/AaveStopLossManageDetails.tsx
- features/aave/open/helpers/use-lambda-debounced-stop-loss.ts
- features/aave/open/helpers/use-lambda-debounced-trailing-stop-loss.ts
- features/aave/types/base-aave-event.ts
- handlers/portfolio/positions/helpers/getPositionsAutomations.ts
This pull request fixes a bug in the stop loss configuration comparison logic. The bug caused incorrect comparison results when the stop loss level or token changed. The fix ensures that the comparison is accurate in all cases.
> Fix stop loss configuration comparison bug

- features/aave/manage/sidebars/AaveManagePositionTrailingStopLossLambdaSidebar.tsx
- public/locales/en/common.json
This pull request updates the trailing stop loss link in the AaveManagePositionTrailingStopLossLambdaSidebar component to point to the correct external link.
> Update trailing stop loss link in AaveManagePositionTrailingStopLossLambdaSidebar

- features/aave/helpers/getStrategyConfig.ts
- features/omni-kit/server/getOmniServerSideProps.ts
- pages/[...rest].tsx
- pages/[networkOrProduct]/aave/[version]/[...strategy].tsx
- pages/[networkOrProduct]/aave/[version]/[vault].tsx
- pages/[networkOrProduct]/maker/[vault]/index.tsx
- pages/[networkOrProduct]/spark/[version]/[...strategy].tsx
- pages/[networkOrProduct]/spark/[version]/[vault].tsx
- pages/better-on-summer/[...slug].tsx
- pages/portfolio/[address].tsx
The position could not load because it was trying to read the tokens from events before filtering the protocol and the events had ajna-only tokens there (not mapped in the tokens config). Moved the filtering first.
Added INTERNAL_LINKS constant for not-found page.
> Fix position not loading and add not-found page constant

- features/automation/contexts/AutomationContextInput.tsx
This pull request adds conditional balance information for the automation context. The balance info is only fetched for positions on the mainnet. For non-mainnet positions, the automation is handled with lambdas and an observable with empty data is used.
> Add conditional balance info for automation context (mainnet only)

- features/aave/components/AaveTrailingStopLossManageDetails.tsx
- features/aave/open/helpers/get-aave-like-trailing-stop-loss-params.ts
Modified the existing code to correctly display the trailing distance for short positions in Aave. This is achieved by introducing a new variable called 'currentTrailingDistanceValue'. The 'currentTrailingDistanceValue' represents the trailing distance for short positions and is used to calculate the 'dynamicStopPrice' and 'trailingDistanceLambdaValue'.
> Update Aave to accurately display trailing distance for short positions

- features/aave/strategies/index.ts
Capitalized the variables "collateralToken" and "debtToken" outside of their condition checks to ensure uppercase consistency. This change is applied to the part where Aave strategy filters tokens by product type.
> Refactor token conversion in Aave strategies

- handlers/portfolio/positions/handlers/aave-like/helpers.ts
- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/portfolio/positions/helpers/getAutomationData.ts
- handlers/portfolio/positions/helpers/getPositionsAutomations.ts
This pull request refactors the position automations in Aave-like handlers. It fixes a bug where part of the automation data retrieval was disabled. The changes include updating the `commonDataMapper` function and the `getAaveLikeBorrowPosition` and `getAaveLikeMultiplyPosition` functions. Additionally, the `getPositionsAutomations` function has been modified to not filter out executed and removed triggers (its done on the query level).
> Refactor position automations in portfolio Aave-like handlers

- features/aave/strategies/ethereum-spark-v3-strategies.ts
This pull request refactors the automation feature checks in the spark strategy configurations to include the new feature "SparkProtectionLambdaEthereum". This ensures that the feature is properly enabled for the specified strategy types and token pairs.
> Refactor automation feature checks in spark strategy configurations

- features/aave/strategies/arbitrum-aave-v3-strategies.ts
- features/aave/strategies/ethereum-aave-v3-strategies.ts
This pull request updates the Aave V3 strategies to include support for partial take profit. It modifies the `borrowStrategies`, `multiplyStrategies`, and `earnStrategies` arrays to use the `AaveV3PartialTakeProfitLambdaArbitrum` and `AaveV3PartialTakeProfitLambdaEthereum` features instead of the `AaveV3TrailingStopLossLambdaArbitrum` and `AaveV3TrailingStopLossLambdaEthereum` features.
> Update Aave V3 strategies for partial take profit

- features/omni-kit/protocols/erc-4626/actions/earn.ts
- features/omni-kit/protocols/erc-4626/actions/index.ts
- features/omni-kit/protocols/erc-4626/constants.ts
- features/omni-kit/protocols/erc-4626/helpers/getErc4626Parameters.ts
- features/omni-kit/protocols/erc-4626/helpers/index.ts
- features/omni-kit/protocols/erc-4626/hooks/index.ts
- features/omni-kit/protocols/erc-4626/hooks/useErc4626Data.ts
- features/omni-kit/protocols/erc-4626/hooks/useErc4626TxHandler.ts
- features/omni-kit/protocols/erc-4626/metadata/index.ts
- features/omni-kit/protocols/erc-4626/metadata/useErc4626Metadata.tsx
- features/omni-kit/protocols/erc-4626/settings.ts
- features/omni-kit/protocols/erc-4626/types.ts
- features/omni-kit/server/getOmniServerSideProps.ts
- pages/[networkOrProduct]/ajna/[...position].tsx
- pages/[networkOrProduct]/erc-4626/[...position].tsx
- pages/[networkOrProduct]/morphoblue/[...position].tsx
- pages/[networkOrProduct]/omni/aave/[version]/[...position].tsx
- pages/[networkOrProduct]/omni/spark/[...position].tsx
- public/locales/en/common.json
- Created a whole bunch of empty functions and mocks required for basic Omnikit support that are going to replaced with actions from library.
- Created Omnikit configuration for semi-new type of product/protocol.
- Created empty page for said protocol.
- Modified `getOmniServerSideProps` method to allow overwriting tokens from URL to custom ones.
`/ethereum/erc-4626/earn/steakhouse-USDC` address should load fine with empty UI and mocked data.
> Basic configuration of ERC-4626 products in Omnikit

- components/SidebarAccordion.tsx
- components/Skeleton.tsx
- components/infoSection/InfoSectionTable.tsx
- features/aave/components/AavePartialTakeProfitManageDetails.tsx
- features/aave/manage/containers/AaveManageTabBar.tsx
- features/aave/manage/containers/AaveManageView.tsx
- features/aave/manage/containers/OptimizationControl.tsx
- features/aave/manage/helpers/map-partial-take-profit-from-lambda.ts
- features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
- features/aave/manage/sidebars/partial-take-profit-components/PreparingPartialTakeProfitSidebarContent.tsx
- features/aave/manage/state/manageAaveStateMachine.ts
- features/aave/open/helpers/get-aave-like-partial-take-profit-params.ts
- features/aave/open/helpers/get-aave-like-stop-loss-params.ts
- features/aave/open/helpers/use-lambda-debounced-partial-take-profit.ts
- features/aave/open/state/openAaveStateMachine.ts
- features/aave/types/base-aave-context.ts
- features/aave/types/base-aave-event.ts
- helpers/formatters/format.ts
- helpers/triggers/get-triggers/get-triggers-types.ts
- helpers/triggers/setup-triggers/setup-aave-partial-take-profit.ts
- helpers/triggers/setup-triggers/setup-triggers-types.ts
This pull request includes the following commits:
- Some component style fixes
- `Skeleton` interactive color
- `InfoSectionTable` has skeleton when loading
- Parse history events to display take profit realized transfers
- Added PnL value to the take profit details
- Modified how we handle value/value change in the details
- Handle adding/updating stop loss during add/manage take profit automation
- Some minor fixes
> Partial take profit fixes [pt.2]

- components/DetailsSectionContentCard.tsx
- components/infoSection/InfoSectionTable.tsx
- features/aave/components/AavePartialTakeProfitManageDetails.tsx
- features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
- features/omni-kit/components/details-section/OmniContentCard.tsx
- public/locales/en/common.json
This pull request removes the modalAsTooltip prop from the OmniContentCard and DetailsSectionContentCard components. The prop is no longer needed and has been causing issues.
> Remove modalAsTooltip prop from OmniContentCard and DetailsSectionContentCard

- features/aave/hooks/useOptimizationSidebarDropdown.tsx
- features/aave/manage/helpers/map-partial-take-profit-from-lambda.ts
- features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
- features/aave/manage/sidebars/partial-take-profit-components/PreparingPartialTakeProfitSidebarContent.tsx
- features/aave/manage/state/triggersAaveStateMachine.ts
Fixes:
- Optimization tab wont automatically select `auto-buy` now
- Added validation for current LTV > trigger LTV
- Fixed sidebar dropdown not updating after view change when position had automation set
- Fixed loading the current trigger withdrawal LTV value (wasn't loaded at all)
> Batch of Partial Take profit fixes

- components/vault/ProtectionControl.tsx
- features/aave/manage/helpers/map-stop-loss-from-lambda.ts
- features/aave/manage/helpers/map-trailing-stop-loss-from-lambda.ts
- features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
- features/aave/open/helpers/use-lambda-debounced-partial-take-profit.ts
- handlers/portfolio/constants.ts
- handlers/portfolio/positions/helpers/getPositionsAutomations.ts
- public/locales/en/common.json
- Brings back the starting TP price validation
- Fixes the update button loading status on various occasions
- Adds take profit icon to all aave/spark products (with trigger ID handling)
This pull request adds the functionality to set take profit automations and trigger types. It also updates the stop-loss and take-profit messages and warnings. Additionally, it refactors the resetXStateData function to handle actions conditionally.
> Partial take profit fixes [pt.4]

- features/aave/manage/helpers/map-partial-take-profit-from-lambda.ts
- features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
- features/aave/manage/sidebars/partial-take-profit-components/PreparingPartialTakeProfitSidebarContent.tsx
- features/aave/open/helpers/get-aave-like-partial-take-profit-params.ts
- features/aave/open/helpers/use-lambda-debounced-partial-take-profit.ts
- helpers/triggers/setup-triggers/setup-aave-partial-take-profit.ts
This pull request fixes the configuration of the partial take profit feature in the Aave management module. It addresses issues related to the starting take profit price and the percentage options for both long and short strategies. Additionally, it updates the stop-loss level and trailing distance labels.
> Partial take profit fixes [pt.8]

- features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
- features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx
- features/aave/manage/sidebars/AaveManagePositionTrailingStopLossLambdaSidebar.tsx
- helpers/triggers/setup-triggers/setup-aave-auto-buy.ts
- helpers/triggers/setup-triggers/setup-aave-auto-sell.ts
- helpers/triggers/setup-triggers/setup-aave-partial-take-profit.ts
- helpers/triggers/setup-triggers/setup-aave-stop-loss.ts
- helpers/triggers/setup-triggers/setup-aave-trailing-stop-loss.ts
This pull request adds an import for the `getLocalAppConfig` function and uses it to set the `shouldSkipValidation` header in the `setupAaveLikePartialTakeProfit` function. This allows for conditional skipping of validation based on the local app configuration.
If validation is suppressed there is an error informing that the user proceeds at its own risk.
> Add getLocalAppConfig import and use it to set shouldSkipValidation header

- features/aave/components/AavePartialTakeProfitManageDetails.tsx
This pull request updates the code to include actual eth/weth tokens in the mapping for the realized profit to wallet. It also refactors the reduceHistoryEvents function to handle different token addresses for collateral and debt tokens.
> Change realized profit to wallet mapping to include actual eth/weth tokens

- components/TabBar.tsx
- features/omni-kit/automation/controllers/OmniAutomationFormController.tsx
- features/omni-kit/controllers/OmniLayoutController.tsx
- features/omni-kit/controllers/OmniOptimizationOverviewController.tsx
- features/omni-kit/controllers/OmniProtectionOverviewController.tsx
- handle resetting from transaction to manage step if user switch automation sidebars or tabs when tx is not in progress
> Automation step reset on tab and sidebar change

- blockchain/prices.constants.ts
- features/omni-kit/protocols/erc-4626/components/Erc4626ApyTooltip.tsx
- features/omni-kit/protocols/erc-4626/helpers/getErc4626ApyParameters.ts
- features/omni-kit/protocols/erc-4626/helpers/getErc4626Claims.ts
- package.json
- server/rewrites.ts
- yarn.lock
Story details: https://app.shortcut.com/oazo-apps/story/14820
The getErc4626ApyParameters function is refactored to incorporate new interfaces and fetch real-time data over hardcoded values. This refactoring enriches the response data handling various reward tokens and market situations. Alongside, a rewrite rule is added to the server configuration, redirecting '/api/morpho' requests to the correct API URL.
Updated the function fetching token prices in prices.constants.ts to use the Fetch API instead of ajax from rxjs. This also involves updating the "@oasisdex/dma-library" to version 0.6.35 and adjusting the getErc4626ApyParameters function to work with the real token prices data. Additionally, a new getErc4626Claims helper function was introduced for fetching claim details.
> feat: [sc-14820] [FE] Integrate Claims & Rewards functions

- features/omni-kit/protocols/erc-4626/components/Erc4626ApyTooltip.tsx
- features/omni-kit/protocols/erc-4626/components/details-section/Erc4626DetailsSectionContentEstimationLoader.tsx
- features/omni-kit/protocols/erc-4626/components/details-section/index.ts
- features/omni-kit/protocols/erc-4626/components/sidebar/Erc4626EstimatedMarketCap.tsx
- features/omni-kit/protocols/erc-4626/contexts/Erc4626CustomStateContext.tsx
- features/omni-kit/protocols/erc-4626/helpers/getErc4626PositionParameters.ts
- features/omni-kit/protocols/erc-4626/hooks/useErc4626TxHandler.ts
- features/omni-kit/protocols/erc-4626/metadata/useErc4626Metadata.tsx
- features/omni-kit/protocols/erc-4626/settings.ts
- features/omni-kit/protocols/erc-4626/state/Erc4626CustomStateProvider.tsx
- features/omni-kit/protocols/erc-4626/types.ts
- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- helpers/formatters/format.ts
- package.json
- public/locales/en/common.json
- yarn.lock
- Updated rewards settings ERC-4626 vaults.
- Updated ERC-4626 subgraph request and interface.
- Displayed missing values on position's headline.
> ERC-4626 rewards tokens market cap config

- components/history/PositionHistory.tsx
- features/omni-kit/protocols/erc-4626/helpers/getErc4626PositionAggregatedData.ts
- features/omni-kit/protocols/erc-4626/history/erc2626DefaultHistoryEvent.ts
- features/omni-kit/protocols/erc-4626/history/mapErc4626Events.ts
- features/omni-kit/protocols/erc-4626/history/types.ts
- features/omni-kit/protocols/erc-4626/hooks/useErc4626Data.ts
- features/omni-kit/protocols/erc-4626/observables/getErc4626AggregatedData.ts
- features/positionHistory/filterAndGroupByTxHash.ts
- features/positionHistory/getHistoryEventLabel.ts
- features/subgraphLoader/consts.ts
- features/subgraphLoader/types.ts
- pages/[networkOrProduct]/erc-4626/[...position].tsx
- public/locales/en/common.json
Story details: https://app.shortcut.com/oazo-apps/story/14862
This commit adds handling and mapping of ERC4626 history events. It includes adding methods for fetching aggregated data, mapping between different events types and updates in displaying event labels. With this update, the application now supports more complete and accurate tracking of transaction history for ERC4626 protocol.
> feat: [sc-14862] [FE] History for ERC-4626

- features/omni-kit/protocols/erc-4626/helpers/getErc4626ApyParameters.ts
Story details: https://app.shortcut.com/oazo-apps/story/14915
This commit updates the naming of parameters in the fetchFromFunctionsApi function call to adhere to standard naming conventions. Additionally, the assignment of the 'per1kUsd' field is now conditional, resulting in undefined if the token symbol is not 'MORPHO'. This ensures better data consistency and correctness.
> chore: [sc-14915] [BE] Small Improvements in the API

- handlers/portfolio/positions/handlers/erc-4626/index.ts
- Added missing `positionId` to method returning position URL.
> Fix ERC-4626 position portfolio link

- features/subgraphLoader/consts.ts
- change history sorting
[  <Please explain how to test your changes>
- step 1 ...](http://localhost:3000/ethereum/erc-4626/earn/steakhouse-USDC/1467#history)
> fix: fix history order in erc4626 vaults

- features/omni-kit/protocols/morpho-blue/settings.ts
Story details: https://app.shortcut.com/oazo-apps/story/14962
This commit introduces a new connectorToken ('SUSDE-USDT') to the map in the settings.ts file.
> chore: [sc-14962] Add Morpho Market

- package.json
- pages/api/exchange/[[...params]].tsx
- yarn.lock
Story details: https://app.shortcut.com/oazo-apps/story/14928
The connector token check for 'toTokenAddress' and 'fromTokenAddress' key has been modified to consider token addresses in lowercase. This enhancement ensures a broader and inclusive match, considering token addresses, which might be in different letter cases.
> feat: [sc-14928] [CI Task] Allow ConnectorTokens to be available through the 1inch API call

- helpers/triggers/get-triggers/get-triggers-request.ts
- if automation triggers api fail, we return default response with 0 automations enabled
- add error in request method so you will be able to simulate issue with api
> Ensure that position is accessible when automation api throws error

- features/omni-kit/components/sidebars/OmniInputSwap.tsx
- features/omni-kit/protocols/erc-4626/components/Erc4626HeadlineApy.tsx
- features/omni-kit/protocols/erc-4626/components/details-section/Erc4626DetailsSectionContentOpen.tsx
- features/omni-kit/protocols/erc-4626/hooks/useErc4626ApySimulation.ts
Partialy covers https://app.shortcut.com/oazo-apps/story/14917/bug-steakhouse-wbtc-current-apy-estimating-earnings-net-value-and-vault-allocation-breakdown-are-not-loading
- Fix issue with infinity loading of APY data when all values were equal to zero.
- Fix issue with showing ✨ next to the APY with empty tooltips when no rewards were available.
- Fix issue with duplicated tokens in swap input when default token was declared in the config.
> Minor APY issues on ERC-4626

- features/subgraphLoader/consts.ts
This pull request fixes the `vault` address in the erc4626 position query by adding it as a parameter in the `positions` query.
How to test: 
http://localhost:3000/ethereum/erc-4626/earn/steakhouse-USDT/1467#overview
> Fix `vault` address in erc4626 position query

- features/navigation/panels/getNavProductsPanel.tsx
- features/navigation/panels/getNavProtocolsPanel.tsx
- features/omni-kit/protocols/erc-4626/components/details-section/Erc4626DetailsSectionFooter.tsx
- features/omni-kit/protocols/erc-4626/settings.ts
- package.json
- public/locales/en/common.json
- yarn.lock
- Changed protocol label in navigation for ERC-4626 type of products in Products > Earn panel.
- Added "Earn" link to Protocols > Morpho Blue panel in navigation.
- Changed description of modal in "Vault Fee" in ERC-4626 position overview footer and made it shared between all MetaMorpho products.
- Removed ETH and WBTC vaults from config.
> ERC-4626 pre-release updates

- .github/workflows/dev-cache.yaml
- .github/workflows/prod-cache.yaml
This pull request adds the CONFIG_URL environment variable to the dev and prod cache workflows. This variable is used to configure the cache and is sourced from the secrets.CONFIG_URL secret.
> Add CONFIG_URL environment variable to dev and prod cache workflows

- features/omni-kit/protocols/aave-like/helpers/getAaveLikeAutomationMetadataValues.ts
- helpers/triggers/get-triggers/get-triggers-types.ts
This pull request adds support for Spark triggers to the existing codebase. It includes changes to the `getAaveLikeAutomationMetadataCommonValues` function to handle Spark triggers for stop loss, trailing stop loss, auto sell, auto buy, and partial take profit. The necessary types and mappings have also been updated to accommodate Spark triggers.
> Add support for Spark triggers

- features/omni-kit/components/sidebars/OmniInputSwap.tsx
- Fixed an issue where input was showing zero address balances when user wallet wasn't connected.
- Fixed an issue where input was showing random balances when user was connected in wrong network.
- Fixed an issue where default token wasn't available in the list if user had zero balance of it. Also, from now default token will always stay on top and is not considered in sorting by tokens balance usd value.
> Swap input minor fixes

- features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
This pull request fixes the fee calculation in the OmniMultiplyFormOrder function. The calculation was incorrect due to a mistake in the precision and price values used. This PR corrects the precision and price values to ensure accurate fee calculation.
> Fix fee calculation in OmniMultiplyFormOrder

- features/omni-kit/automation/components/auto-buy-sell/OmniAutoBSSidebarController.tsx
This pull request updates the trigger and target LTV values in the OmniAutoBSSidebarController. The triggerLtv and targetLtv values have been adjusted to improve the functionality of the AUTO_BUY automation feature.
> Update trigger and target LTV values in OmniAutoBSSidebarController

- features/omni-kit/protocols/aave-like/helpers/getAaveLikeNotifications.tsx
- features/omni-kit/protocols/aave-like/metadata/useAaveLikeMetadata.tsx
This pull request adds Aave-like omni automation notifications to the codebase. It includes changes to the `getAaveLikeNotifications` function and the `useAaveLikeMetadata` hook. These changes allow for the display of notifications related to trailing stop-loss execution price increases.
> Add Aave-like omni automation notifications

- features/omni-kit/automation/hooks/useOmniAutoBSOrderInformationItems.ts
This pull request refactors the labels in the useOmniAutoBSOrderInformationItems function to dynamically select the appropriate label based on the automation feature type. This improves code readability and maintainability.
> Refactor labels in useOmniAutoBSOrderInformationItems

- features/omni-kit/contexts/OmniProductContext.tsx
- features/omni-kit/helpers/getOmniAutomationSidebarPrimaryButtonActions.ts
- features/omni-kit/helpers/getOmniSidebarPrimaryButtonActions.ts
- features/omni-kit/types.ts
- features/omni-kit/views/OmniAutomationFormView.tsx
- features/omni-kit/views/OmniFormView.tsx
This pull request adds the positionId parameter to the OmniFormView component and uses it in the useOmniProductTypeTransition hook. This allows for better handling of transitions and resolves an issue with the resolvedId variable.
> Add positionId to OmniFormView and use it in useOmniProductTypeTransition

- features/omni-kit/helpers/getOmniPositionUrl.ts
- features/omni-kit/protocols/aave-like/helpers/aaveLikeFlowStateFilter.ts
- features/omni-kit/views/OmniFormView.tsx
Fix omni kit DPM filtering + add aave/spark omni support for the link in modal
> Fix omni kit DPM filtering + add aave/spark omni support for the link in modal

- features/omni-kit/controllers/OmniProductController.tsx
- features/omni-kit/observables/getDpmPositionData.ts
This pull request fixes the issue with omni aave/spark earn/borrow/multiply switching. The code changes ensure that the correct position type is returned based on the collateral token, quote token, and protocol.
> Fix omni aave/spark earn/borrow/multiply switching

- features/omni-kit/automation/hooks/useOmniPartialTakeProfitDataHandler.tsx
This pull request refactors the useOmniPartialTakeProfitDataHandler function to calculate the startingTakeProfitPriceLong and startingTakeProfitPriceShort values based on the dynamicParams. This ensures that the correct values are used for these variables, improving the accuracy of the calculations.
> Refactor useOmniPartialTakeProfitDataHandler to calculate startingTakeProfitPriceLong and startingTakeProfitPriceShort based on dynamicParams

- features/omni-kit/automation/components/partial-take-profit/OmniPartialTakeProfitSidebarController.tsx
- features/omni-kit/automation/hooks/useOmniAutoBSOrderInformationItems.ts
- features/omni-kit/automation/hooks/useOmniAutomationOrderInformationItems.tsx
- features/omni-kit/automation/hooks/useOmniPartialTakeProfitDataHandler.tsx
- features/omni-kit/automation/hooks/useOmniPartialTakeProfitOrderInformationItems.ts
- features/omni-kit/automation/hooks/useOmniStopLossOrderInformationItems.ts
- features/omni-kit/automation/hooks/useOmniTrailingStopLossOrderInformationItems.ts
This pull request fixes the issue with the next trigger price handling in the omni aave/spark take profit automation. It also adjusts the loading states to ensure a smoother user experience.
> Fix next trigger price handling in omni aave/spark take profit automation + adjusted loading states

- pages/[networkOrProduct]/aave/[version]/[...position].tsx
- pages/[networkOrProduct]/spark/[...position].tsx
- added missing serverside translations to props
- deprecated urls shouldn't complain about missing translations
> Fix missing server side translations on deprectated url

- features/omni-kit/observables/getPositionFromUrlParams.ts
- when fork is usd get the `CreatePosition` events from fork instead of subgraph
- doesnt work for morphoblue - due to the multiple markets and subgraph call
- create aave position on fork
> feat: fetch positions from blokchain events if fork is used

- features/migrations/useMigrationBannerMeta.tsx
- features/productHub/hooks/useProductHubBanner.tsx
- handlers/portfolio/positions/helpers/getAllDpmsForWallet.ts
- helpers/applicationLinks.ts
- fixed issue with migration banner in PH
- fixed issue with filters in portfolio
- product filters in portfolio should work as expected
- migration banner should redirect to position (if only 1 position available to migrate, or to portfolio if more)
> Migration banner and portfolio filters fix

- features/omni-kit/components/sidebars/OmniInputSwap.tsx
- data-testid='deposit-token-selector'
- data-testid='deposit-token-list'
> Adding data-testid attributes to Morpho Steakhouse deposit token selector

- features/refinance/hooks/useInitializeRefinanceContext.ts
- features/refinance/hooks/useSdkSimulation.tsx
- features/refinance/hooks/useSdkTransaction.tsx
- public/locales/en/common.json
- fixed typo
- fixed issue with simulation not being cleared when user goes back to strategy step
> Refinance banner typo fix

- features/refinance/helpers/getRefinanceSidebarButtonStatus.ts
- features/refinance/hooks/useSdkSimulation.tsx
- features/refinance/views/RefinanceFormView.tsx
- blocked button when simulation is loading
- when either give or refinance simulation is being loaded, button should have loading state and be disabled
> Refinance block button when simulation is loading

- features/productHub/helpers/parseRows.tsx
It was extremely annoying to work with Product Hub since buttons were removed because there was no way to preview position link without clicking it or opening it in new tab. And on local env, it may take a while to load position page, so precious minutes were lost here and there.
- Added support for `ProductHubDebug` in Product Hub.
- Added action button to each table row and removed clickable rows in debug moge.
Feel free to expand the debug mode if you feel like it.
> Add debug mode to Product Hub

- features/refinance/contexts/RefinanceGeneralContext.tsx
- features/refinance/hooks/useRefinanceTxHandler.ts
- updated of owner after give
- when user will complete give tx, and then decide tu return to product hub to pick different strategy, give tx should be skipped
> Refinance update of owner after give

- features/aave/manage/state/triggersAaveStateMachine.ts
- features/omni-kit/protocols/aave-like/helpers/aaveLikeFlowStateFilter.ts
- features/omni-kit/protocols/aave-like/hooks/useAaveLikeData.ts
- features/omni-kit/protocols/aave-like/metadata/useAaveLikeMetadata.tsx
- helpers/lambda/triggers/get-triggers/get-triggers-config.ts
- helpers/lambda/triggers/get-triggers/get-triggers-request.ts
- helpers/lambda/triggers/get-triggers/get-triggers-types.ts
- fixed issue where position automations were taken from not existing position therefore dpm with automations could be reused while opening new position
- for aavelike protocols, if dpm have automations enabled it shouldn't be possible to reuse it
> Aavelike flowstate automation fix

- features/refinance/contexts/RefinanceGeneralContext.tsx
- features/refinance/controllers/RefinanceFlowSidebarController.tsx
- features/refinance/helpers/getRefinanceFlowStateFilter.ts
- features/refinance/hooks/useInitializeRefinanceContext.ts
- force creation of dpm or use existing one without any create position events
- while doing refinance only empty DPM should be used
> Restrict reusability of DPM in refinance

- components/GenericMultiselect.tsx
Ensured selected is defined before accessing its properties in GenericMultiselect. This prevents potential crashes due to null reference exceptions when trying to access label, icon, image, or token of an undefined selected item.
> Fix null reference exception in GenericMultiselect

- features/omni-kit/automation/components/auto-buy-sell/OmniAutoBSSidebarController.tsx
Story details: https://app.shortcut.com/oazo-apps/story/15382
> fix: [sc-15382] Auto-sell in omni kit uses values wrong way around in the desciption

- components/context/PreloadAppDataContextProvider.tsx
- components/portfolio/positions/PortfolioPositionsView.tsx
- features/aave/open/sidebars/components/SidebarOpenAaveVaultStopLoss.tsx
Adding data-testid="portfolio-positions-controls" attribute
> Adding data-testid attribute to Portfolio - Positions controls

- handlers/portfolio/positions/handlers/aave-v2/ds-proxy-position.ts
Story details: https://app.shortcut.com/oazo-apps/story/15542
Added URL field in the Aave v2 handler file to enhance data tracking capabilities. This update allows easy access to specific data related to the given address on the Aave v2 protocol.
> fix: [sc-15542] [BUG] - Aave V2 positions on DS Proxy showing as Not Found

- features/omni-kit/protocols/morpho-blue/settings.ts
https://app.shortcut.com/oazo-apps/story/15547/add-wsteth-eth-94-5-and-96-fixed-exchange-rate-markets
> Add support for multiple markets in morpho-blue settings

- features/omni-kit/controllers/OmniLayoutController.tsx
- features/omni-kit/controllers/OmniProductController.tsx
- features/omni-kit/helpers/getOmniHeadlineProps.ts
- added max ltv param to position headline if there are more than one market available for given pair
> Max ltv in overview headline if multiple markets

- features/omni-kit/automation/hooks/useOmniPartialTakeProfitDataHandler.tsx
- helpers/lambda/triggers/setup-triggers/setup-partial-take-profit.ts
This pull request refactors the `useOmniPartialTakeProfitDataHandler` function to directly use the `maxLoanToValue` property instead of calculating it from the `category` object. This simplifies the code and improves readability.
> Refactor useOmniPartialTakeProfitDataHandler to use maxLoanToValue directly

- features/omni-kit/protocols/morpho-blue/settings.ts
- removed entry token from morpho settings
- for wsteth-eth pair deposit token should be wsteth
> Wsteth-eth yield loop deposit wsteth as default

- features/aave/manage/sidebars/migration/MigrateAaveSuccessStateView.tsx
- helpers/getAaveLikeStrategyUrl.ts
- fixed go to position link in migration UI
- link go to position should work as expected
> Migration go to position link fix

- features/omni-kit/automation/components/auto-buy-sell/OmniAutoBSSidebarController.tsx
- adjusted default values on slider for auto sell feature
- target ltv should equal to current position ltv, trigger should be 5% higher
> Auto sell tweak default slider values

- features/omni-kit/observables/getPositionFromUrlParams.ts
- features/refinance/components/steps/RefinanceProductTableStep.tsx
- features/refinance/constants.ts
- features/refinance/contexts/RefinanceContext.tsx
- features/refinance/controllers/RefinanceModalController.tsx
- features/refinance/helpers/getRefinanceProductHubDataParser.ts
- features/refinance/helpers/getRefinanceStrategiesToBeFiltered.ts
- added filtering of strategies based on user dpm events
- read docs added in code
> Refinance PH strategies filtering

- features/refinance/disabledMorphoPairs.ts
- features/refinance/helpers/getRefinanceStrategiesToBeFiltered.ts
This pull request disables the MorphoBlue pairs in the refinance strategies filter. Previously, these pairs were not being properly filtered out. With this change, the disabled MorphoBlue pairs ['WSTETH/USDA', 'PTWEETH/USDA'] will be excluded from the filter.
> Disable MorphoBlue pairs in refinance strategies filter

- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/portfolio/positions/handlers/aave-like/mapDpmProtocolNameToUIName.ts
This pull request fixes an issue where the new swapped position was not being listed correctly on the Portfolio page. The problem was caused by a mapping error in the `mapDpmProtocolNameToUIName` function. This pull request includes a fix for the mapping function to ensure that the position is displayed correctly.
> Fix position listing in Portfolio page

- components/portfolio/positions/PortfolioPositionBlock.tsx
- features/omni-kit/automation/helpers/getIsLastAutomationOfKind.ts
- features/omni-kit/automation/helpers/getOmniAutomationSidebarRaysBanner.tsx
- features/omni-kit/contexts/OmniGeneralContext.tsx
- features/omni-kit/controllers/OmniProductController.tsx
- features/omni-kit/helpers/getOmniSidebarRaysBanner.tsx
- features/omni-kit/protocols/aave-like/helpers/mapAaveLikeRaysMultipliers.ts
- features/omni-kit/protocols/aave-like/hooks/useAaveLikeData.ts
- features/omni-kit/protocols/ajna/helpers/mapAjnaRaysMultipliers.ts
- features/omni-kit/protocols/ajna/hooks/useAjnaData.ts
- features/omni-kit/protocols/erc-4626/helpers/mapErc4626RaysMultipliers.ts
- features/omni-kit/protocols/erc-4626/hooks/useErc4626Data.ts
- features/omni-kit/protocols/morpho-blue/helpers/mapMorphoBlueRaysMultipliers.ts
- features/omni-kit/protocols/morpho-blue/hooks/useMorphoData.ts
- features/omni-kit/types.ts
- features/omni-kit/views/OmniAutomationFormView.tsx
- features/omni-kit/views/OmniFormView.tsx
- features/rays/consts.ts
- features/rays/getProtocolBoost.ts
- features/rays/getRaysNextProtocolBonus.ts
- features/rays/getRaysUserMultipliers.ts
- features/rays/getSwapBoost.ts
- features/rays/mapUserAndPositionRays.ts
- features/rays/types.ts
- handlers/portfolio/positions/handlers/aave-like/index.ts
- handlers/rays/getRaysMappedNetwork.ts
- handlers/rays/getRaysMappedProtocol.ts
- handlers/rays/getRaysMultipliers.tsx
- pages/api/rays/multipliers/index.tsx
- public/locales/en/common.json
- added real data to rays banners etc.
- real data used in rays banners in overview
> Rays real data

- features/refinance/components/steps/RefinanceSwapSection.tsx
- features/refinance/components/steps/RefinanceWhatsChangingStep.tsx
- features/refinance/contexts/RefinanceGeneralContext.tsx
- features/refinance/hooks/useInitializeRefinanceContextBase.ts
This pull request updates the fee price calculation in the `RefinanceSwapSection` and `RefinanceWhatsChangingStep` components. It replaces the previous calculation with a new function `getTokenUsdPrice` that retrieves the USD price of a token. This ensures more robust fee price calculation.
> Update fee price calculation and add getTokenUsdPrice

- features/aave/strategies/arbitrum-aave-v3-strategies.ts
- features/aave/strategies/base-aave-v3-strategies.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/arbitrum-mainnet.ts
- handlers/product-hub/update-handlers/aaveV3/aave-v3-products/base-mainnet.ts
- added aave v3 markets
- markets visible in ph and working as expected
> Aave v3 markets update

- features/productHub/types.ts
- features/productHub/views/ProductHubView.tsx
- features/refinance/components/RefinancePosition.tsx
- features/refinance/components/RefinancePositionView.tsx
- features/refinance/components/steps/RefinanceHighlightedChangeSection.tsx
- features/refinance/components/steps/RefinanceProductTableStep.tsx
- features/refinance/controllers/RefinanceModalController.tsx
- features/refinance/helpers/getNetAPY.ts
- features/refinance/helpers/getRefinanceProductHubDataParser.ts
- features/refinance/hooks/useSimulationPositionData.tsx
- features/refinance/state/refinanceFormReducto.types.ts
- handlers/portfolio/positions/handlers/aave-like/getRawPositionDetails.ts
- public/locales/en/common.json
Previously, the borrow rate was used to calculate the net APY for refinance positions. This pull request introduces a separate netApy field that accurately represents the net APY based on the current LTV. The borrow rate is now used solely for calculating the increase in debt over one year at the current market utilization. This change improves the accuracy of the net APY calculation and provides more meaningful information to users.
> "Implement separate netApy and borrow costs comparison for refinance"

- features/omni-kit/automation/constants.ts
- updated SL max slider value offset
- it should be possible to add SL with max value
> Update stop loss max offset

- components/LazySummerBanner.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVault.tsx
- features/multiply/manage/sidebars/SidebarManageMultiplyVaultManageStage.tsx
- features/sidebar/getPrimaryButtonLabel.ts
- features/sidebar/getSidebarTitle.ts
- helpers/extractSidebarHelpers.ts
- public/locales/en/common.json
- Updated Lazy Summer banner text to remove launch date reference
- Added Lazy Summer integration to vault management flow:
- Added "Try it now" button with gradient styling after vault closure
- Integrated Lazy Summer sidebar content in vault management
- Added position closed state handling
- Updated translations:
- Added "Position Closed" text
- Added "Try it now" button text
- Added support for `otherAction` in sidebar title and button label logic
1. Test vault closure flow:
- Open a multiply vault
- Navigate to close vault option
- Complete the closure transaction
- Verify Lazy Summer content appears
- Check "Try it now" button styling and functionality
2. Verify translations:
- Check "Position Closed" text appears after closure
- Verify "Try it now" button text is correct
3. Test …
> Add lazy close step for maker
