blockchain/better-calls/account-factory.ts
blockchain/better-calls/dpm-account.ts
blockchain/better-calls/utils/index.ts

Switch to BigNumber.js to get estimate gas without underflow issue.

:bug: Estimating error

---

features/aave/services/readPositionCreatedEvents.ts

- removed start with undefined
- there should be no case when flow sidebar disappears when proxy has to be created

Fix proxy consumed pipe

---

features/ajna/positions/common/sidebars/AjnaFormContentRisk.tsx
helpers/applicationLinks.ts

- updated link
- in ajna risk step check if link redirects to correct page

Ajna audits link update

---

public/locales/en/common.json

Update rewards info copies

---

features/ajna/positions/borrow/controls/AjnaBorrowPositionController.tsx
features/ajna/positions/common/controls/AjnaFaqController.tsx
features/ajna/positions/earn/controls/AjnaEarnPositionController.tsx
features/content/faqs/FaqLayout.tsx
features/content/faqs/ajna/borrow/en.mdx
features/content/faqs/ajna/earn/en.mdx

Covers:
https://app.shortcut.com/oazo-apps/story/10036/add-borrow-info-page
https://app.shortcut.com/oazo-apps/story/10037/update-earn-info-page
- Added content to FAQs for Borrow and Earn positions,
- modified FAQ component so it allows to skip its default header so it can be replaced with proper details section header.

🧿 Ajna FAQs

---

features/positionHistory/getHistoryEventLabel.ts

- adjusted condition for `AjnaSupplyQuote` method so if it used for opening position proper label is used
- open earn position should have `Open position` event in history

Adjust history event label

---

features/ajna/positions/common/helpers/getFlowStateConfig.ts

- fixed issue where allowance step was not included but should be
- try on ajna borrow position withdraw & payback action without having sufficient allowance, allowance step should popup

Allowance withdraw borrow fix

---

components/history/PositionHistoryItemDetails.tsx
features/ajna/positions/common/helpers/mapEarnEvents.ts
features/positionHistory/mapPositionHistoryResponse.ts
features/positionHistory/types.ts
features/subgraphLoader/consts.ts

- extended earn history with lending price
- all earn events should have lending price

Extend earn history with lending price

---

features/productHub/controls/ProductHubNaturalLanguageSelectorController.tsx
handlers/product-hub/helpers/index.ts
handlers/product-hub/promo-card-collections-parsers/ajnaLpHandler.ts
pages/ajna/[...slug]/index.tsx

Fix build / Remove ajnaEarnProducts

---

public/locales/en/common.json

🧿 Remove "lorem ipsum" from Ajna benefits

---

server/database/migrations/025-ajna-rewards.sql
server/database/schema.prisma

added new tables:
```graphql
model AjnaRewardsWeeklyClaim {
id           Int      @id @default(autoincrement())
timestamp    DateTime @default(now())
week_number  Int
user_address String
proof        String[]
amount       String
@@unique([week_number, user_address], name: "week_number_userAddress_unique_id")
@@map("ajna_rewards_weekly_claim")
}
model AjnaRewardsDailyClaim {
id           Int      @id @default(autoincrement())
timestamp    DateTime @default(now())
day_number   Int
user_address String
amount       String
week_number  Int
@@unique([day_number, user_address], name: "day_number_userAddress_unique_id")
@@map("ajna_rewards_daily_claim")
}
model AjnaRewardsMerkleTree {
week_number  Int      @unique
timestamp    DateTime @default(now()) …
```

feat: add ajna rewards tables

---

features/aave/open/state/openAaveStateMachine.ts
features/stateMachines/transactionParameters/transactionParametersStateMachine.ts

A batch of fixes for bugs found on Aave V3 automation.
- fixed gas estimation
- this fixes opening Aave V3 position with stop loss (in one flow), so try that :)

Aave V3 stop loss fixes

---

package.json
yarn.lock

- Bump dma lib 0.3.32
- deposit fee in ajna form should be calculated correctly

Bump dma lib 0.3.32

---

package.json
yarn.lock

- Bump dma lib 0.3.33
- when adjusting earn position which is below lup, user should be able to withdraw all quote tokens

Bump dma lib 0.3.33

---

features/ajna/positions/earn/controls/AjnaEarnFormOrderInformation.tsx
package.json
yarn.lock

- used isEarningFees from library to determine whether deposit fee item will display or not in order informations
- when setting price bucket below lup deposit fee should be always present in order information

Ajna deposit fee always below lup

---

features/ajna/positions/earn/controls/AjnaEarnPositionController.tsx
package.json
yarn.lock

- updated current yield
- in ajna manage position view, current yield should be set up to net apy

Ajna current yield update

---

components/history/PositionHistoryItemDetails.tsx

- taken into consideration if pool is short or long when displaying lending prices in history
- for short pool lending price should be displayed as for long earn pool positions

Ajna history lending price pool type condition

---

features/ajna/positions/common/sidebars/AjnaFormContentRisk.tsx
features/ajna/positions/earn/sidebars/AjnaEarnFormContentNft.tsx
features/content/faqs/ajna/borrow/en.mdx
features/content/faqs/ajna/earn/en.mdx
features/homepage/AjnaHomepageView.tsx
handlers/product-hub/promo-cards/collections/generic.ts
helpers/applicationLinks.ts

Updated Ajna KB/docs links
> Updated Ajna KB/docs links
- Updated Ajna KB/docs links,
- updated Ajna KB/docs links,
- updated Ajna KB/docs links.
Updated Ajna KB/docs links
```
Updated Ajna KB/docs links
Updated Ajna KB/docs links
Updated Ajna KB/docs links
```
Updated Ajna KB/docs links

🧿 Updated Ajna KB/docs links

---

package.json
yarn.lock

- Update lib addresses 0.0.29
- it should be possible to play with ajna on mainnet

Update lib addresses 0.0.29

---

features/ajna/positions/earn/components/AjnaEarnInput.tsx
features/ajna/positions/earn/helpers/resolveLendingPriceIfOutsideRange.ts

- improved ajna earn input handling
- when user click outside of earn price input value should snap to default value

Improve ajna earn input handling

---

features/ajna/positions/common/views/AjnaFormView.tsx
helpers/useFeatureToggle.ts

- added `AjnaSuppressValidation` flag that disable button disable status

Ajna give possibility to suppress button disable status

---

features/ajna/positions/earn/helpers/getAjnaEarnData.ts

- earn position should display properly

Fix earn position regression

---

features/ajna/positions/common/notifications.tsx
features/ajna/positions/common/validation.tsx
helpers/applicationLinks.ts
public/locales/en/common.json

- updated ajna liquidation warning copy

Update warning about liquidation

---

blockchain/contracts/arbitrum.ts
blockchain/contracts/goerli.ts
blockchain/contracts/mainnet.ts
blockchain/contracts/optimism.ts

Fix CBETH-ETH Ajna pool key

---

public/locales/en/common.json

🧿 Fix typo on Ajna landing page

---

features/ajna/positions/borrow/components/ContentFooterItemsBorrow.tsx
features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
features/ajna/positions/earn/components/ContentFooterItemsEarnManage.tsx
features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
features/ajna/rewards/useAjnaRewards.ts

- Fixed an issue where displayed Ajna tokens balance on position page was taken for connected user, not position owner.

🧿 Display Ajna tokens balance on position page

---

features/ajna/positions/borrow/components/ContentFooterItemsBorrow.tsx
features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
features/ajna/positions/common/hooks/useAjnaTxHandler.ts
features/ajna/positions/common/sidebars/AjnaFormFields.tsx
features/ajna/positions/common/validation.tsx
features/vaultsOverview/parsers.tsx
handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
helpers/useFeatureToggle.ts
package.json
yarn.lock

- turned ajna feature flag on
- turned off max withdraw and max borrow items from overview footer
- turned off max withdraw and max borrow values above inputs (max withdraw also for earn)
- it should be possible to borrow from buckets below htp

Suppress some of ajna validations

---

features/ajna/positions/common/hooks/useAjnaTxHandler.ts

- Send with gas estimation fix

Send with gas estimation

---

features/homepage/HomepageView.tsx

Set Earn as default product on Product Finder on homepage

---

features/ajna/positions/earn/components/AjnaEarnInput.tsx
features/ajna/positions/earn/components/AjnaEarnSlider.tsx
features/ajna/positions/earn/helpers/resolveLendingPriceIfOutsideRange.ts
features/ajna/positions/earn/helpers/snapToPredefinedValues.ts

Ajna earn input fix

---

features/ajna/rewards/useAjnaRewards.ts

- fixed issue with ajna rewards inifnity loading on earn position
- use 463 earn position on mainnet and check whether ajna rewards is displayed in overview section footer

Ajna rewards hook fix

---

features/ajna/positions/earn/components/AjnaEarnInput.tsx

<Please add short list of changes
- adjusted decimal places in ajna earn input to show the sam value as in slider label
- self explanatory, verify on ETH/USDC pool and for example on RETH/ETH

Ajna earn input decimals adjustment

---

public/locales/en/common.json

- updated tooltip
- step 1 ...

Updated ajna rewards tooltip

---

features/ajna/positions/earn/controls/AjnaEarnPositionController.tsx
public/locales/en/common.json

- changed 90 to 30 days avg apy in ajna open and manage earn position header

Ajna change 90 to 30 day avg apy

---

features/ajna/positions/common/helpers/getAjnaPoolsTableData.ts
handlers/product-hub/update-handlers/ajna/ajnaHandler.ts

fix: fix ajna earn apy

---

features/ajna/positions/earn/controls/AjnaEarnPositionController.tsx

- changed Apr 30d average within ajna heading on open / manage position

Apr 30d average

---

features/ajna/positions/common/helpers/getAjnaPoolData.ts
features/ajna/positions/common/helpers/getAjnaPoolsTableData.ts
features/ajna/positions/earn/controls/AjnaEarnPositionController.tsx
features/subgraphLoader/consts.ts
handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
package.json
yarn.lock

- Lender apr ajna earn update (in product hub and current yield when opening or managing earn position)

Lender apr ajna earn update

---

features/shared/jwt.ts

- fixed issue with referrals where user was not able to accept invitation link
- generate referral link and on another account accept invitation, then verify if everything saved properly in db

Referral fix

---

features/ajna/positions/borrow/components/ContentFooterItemsBorrow.tsx
features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
features/ajna/positions/common/sidebars/AjnaFormFields.tsx
package.json
yarn.lock

- enabled max withdraw values on ajna borrow UI which were previously suppressed
- on borrow position user should see max withdraw amount in overview section, order informations and value should be correct

Bring back max withdraw

---

components/history/PositionHistoryItemDetails.tsx
features/ajna/positions/common/helpers/mapBorrowishEvents.ts
features/positionHistory/getHistoryEventLabel.ts
public/locales/en/common.json

- added handling for ajna multiply events
- you can use position 456 from mainnet, verify whether history is displayed correctly

Ajna multiple history

---

package.json
yarn.lock

- Bumped dma lib version
- max withdraw in ajna positions, for example 671 on mainnet should be calculated correctly

Bump dma lib version

---

actions/ajna/multiply.ts
public/locales/en/common.json

- Handle edge case minLTVs better where initial deposits are too low relative to pool min debt

[BUG] Min LTV dust limit edge case

---

blockchain/better-calls/dpm-account.ts

Change first address in access list to user's proxy.

:bug: user can't close postion from safe wallet

---

features/ajna/common/ajnaUnifiedHistoryEvent.ts
features/ajna/positions/common/helpers/mapEarnEvents.ts
features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
features/positionHistory/mapPositionHistoryResponseEvent.ts
features/positionHistory/types.ts
features/subgraphLoader/consts.ts

- Ajna total earnings and pnl for earn positions UI calcs
- go through bunch of ajna earn positions and verify whether total earnings and pnl does make sense

Ajna total earnings and pnl for earn positions UI calcs

---

features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx

Earn content card format fix

---

blockchain/token-metadata-list/maker.ts

- Fix coinbase ticker for wsteth

Fix coinbase ticker for wsteth

---

features/ajna/positions/common/observables/getAjnaPosition.ts
features/vaultsOverview/containers/PositionsTable.tsx
features/vaultsOverview/parsers.tsx

- added handling for Ajna multiply positions on owner page
- you can test it by finding borrow position on mainnet and converting it locally in db to multiply

Ajna multiply owner page

---

features/ajna/positions/borrow/controls/AjnaBorrowOverviewController.tsx
features/ajna/positions/borrow/sidebars/AjnaBorrowFormOrder.tsx
features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
package.json
yarn.lock

- usage of liquidationPriceT0Np in fronted to show correct value in overview and order information section
- bump lib version
- all ajna borrow positions should show correct liquidation price

Liquidation price at t0 neutral price

---

features/ajna/positions/earn/helpers/getLendingPriceColor.ts

Fixes the lending price color.

Ajna overview lending price color fix

---

public/locales/en/common.json

Story details: https://app.shortcut.com/oazo-apps/story/10436

fix: [sc-10436] update copy of LTV warning

---

components/navigation/NavigationNetworkSwitcherL2BeatButton.tsx
public/locales/en/common.json
theme/index.tsx

- remove link styles and making it looks more consistent
- update the title to "Learn about L2's"
- update interactive color in the theme since the new interactive color is too similar to the current critical color, we decide to reverse it at this moment till we figure out another new color.
- check network switcher styles

Improvements to the L2Beat section in the network switcher

---

features/ajna/positions/common/contexts/AjnaProductContext.tsx
features/ajna/positions/common/controls/AjnaProductController.tsx
features/ajna/positions/common/helpers/getAjnaPositionCumulatives.ts
features/ajna/positions/common/observables/getPositionCumulatives.ts
features/ajna/positions/earn/helpers/getAjnaEarnData.ts
features/ajna/positions/multiply/controls/AjnaMultiplyOverviewController.tsx
features/subgraphLoader/consts.ts
features/subgraphLoader/types.ts

Library changes: https://github.com/OasisDEX/oasis-earn-sc/pull/389/files
- Create query to get cumulatives from dpmProxy account on Subgraph
- Create observable to resolve cumulatives
- Pass data down to Ajna Multiply Product Context
- Pass cumulatives in to pnl method on AjnaPosition
Go to multiply setup page for an ajna position
Observe whether the PnL is displaying as expected

PnL Ajna Overview Data

---

features/ajna/positions/multiply/components/AjnaMultiplySlider.tsx

- updated slider label with liquidation price t0 neutral price
- liquidation price in overview and on slider should be the same

Use liquidation price t0np in slider

---

features/ajna/common/components/AjnaProductHubIntro.tsx

- Remove coming soon conditional
- Go to /ajna/multiply
- Check that product hub table shows

Remove Coming Soon Flag

---

analytics/analytics.ts
features/dsr/helpers/dsrDeposit.tsx

- implemented mixpanel tracking for DSR input and depositing

Mixpanel tracking for DSR

---

features/ajna/positions/common/helpers/getFlowStateConfig.ts

- added missing actions in dpm flow config
- open for example USDC/ETH position, you shouldn't be asked for allowance while doing adjust or close action

Ajna multiply allowance fix

---

features/ajna/positions/borrow/controls/AjnaBorrowPositionController.tsx
features/ajna/positions/multiply/controls/AjnaMultiplyPositionController.tsx
features/content/faqs/ajna/multiply/en.mdx

- Copy across FAQs from Borrow
- Update the language
- Add a Summer.fi fee description that is suitable for Multiply
- Go to ethereum/ajna/borrow/ETH-USDC#position-info
- Confirm that the FAQs appear
- And the language is appropriate for Multiply products

Multiply FAQs

---

blockchain/token-metadata-list/ajna.ts

`worldcoin-wld` instead of `worldcoin`

Update WLD coingecko ticker

---

components/assetsTable/cellComponents/AssetsTableDataCellRiskNoProtectionAvailableIcon.tsx
features/vaultsOverview/parsers.tsx
public/locales/en/common.json

Owner page: fixes column issues and adds info about protection not available

---

README.md

Updating README file with extra notes to setup dev env locally

Updating README file with extra notes to setup dev env locally

---

features/aave/open/sidebars/SidebarOpenAaveVault.tsx
public/locales/en/common.json

Story details: https://app.shortcut.com/oazo-apps/story/10651

fix: [sc-10651] [Aave v3 multiply] button copy change to indicate the next step is setting up stop loss

---

components/vault/ProtectionControl.tsx

Story details: https://app.shortcut.com/oazo-apps/story/10655

chore: [sc-10655] [Aave v3 multiply] Update stop loss banner copy on Aave v2 

---

analytics/analytics.ts
features/aave/manage/state/manageAaveStateMachine.ts
features/stateMachines/transactionParameters/transactionParametersStateMachine.ts

Story details: https://app.shortcut.com/oazo-apps/story/10642

Aave - Resets the adjust data on slider change

---

features/aave/manage/containers/AaveManageTabBar.tsx
features/aave/open/sidebars/SidebarOpenAaveVault.tsx
features/aave/open/state/openAaveStateMachine.ts
features/automation/common/consts.ts
features/automation/common/helpers.ts
features/automation/metadata/aave/stopLossMetadata.ts
features/vaultsOverview/parsers.tsx

Story details: https://app.shortcut.com/oazo-apps/story/10724

Aave v3 stop loss - added CBETH and RETH

---

components/navigation/NavigationNetworkSwitcher.tsx

Add NetworkButton key

---

public/locales/en/common.json

Changed the card title: Earn on your Dai
<details>
<summary>Changed the card title: Earn on your Dai</summary>
Changed the card title: Earn on your Dai
</details>

Changed the card title: Earn on your Dai

---

package.json
yarn.lock

Update automation lib `1.5.0-alpha.8` -> `1.5.0`

Update automation lib

---

features/ajna/positions/common/helpers/getFlowStateConfig.ts

- adjusted adjust config to check if value used in allowance is defined
- added missing actions
- try for example CBETH/ETH pool, open position with limited allowance, once opened try to borrow some more ETH without depositing CBETH, allowance flow should be skipped in this case

Adjust flow config

---

features/aave/open/containers/AaveOpenView.tsx

Fixes bug crashing the app on Aave Optimism

Added SimulateSectionComponent to AutomationContextInput

---

package.json
yarn.lock

chire: bump automation version `1.5.2`

---

package.json
yarn.lock

- bumped dma lib to 0.4.5
- simulated liquidation price on ajna borrow / multiply positions should make a sense

Bump dma lib 0.4.5

---

features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx

- adjusted after available to withdraw to take into account deposits as well
- correct value of after available to withdraw

Adjust after available to withdraw

---

blockchain/contracts/arbitrum.ts
blockchain/contracts/goerli.ts
blockchain/contracts/mainnet.ts
blockchain/contracts/optimism.ts
features/productHub/meta.ts
handlers/product-hub/promo-cards/ajnaLp.ts

- Commented out sDAI pool,
- commented out DAI on NLS on borrow in Product Finder,
- replaced sDAI promo card with the one, that it originally took place.
Patch Product Finder data, look for sDai, hopefully you didn't found it.

Hide sDai pool

---

features/ajna/positions/common/controls/AjnaProductController.tsx
features/ajna/positions/common/hooks/useAjnaData.ts
features/ajna/positions/common/hooks/useAjnaRedirect.ts

Partially covers https://app.shortcut.com/oazo-apps/story/10787/optimize-ajna-position-page
- Extracted all Ajna position observables from controller to dedicated hook,
- extracted all Ajna position redirecting logic from controller to dedicated hook.
See if open/manage position is still working as intended.

Ajna data hook

---

public/locales/en/common.json

Typo in oracless risk step

---

components/constants.ts
features/dsr/components/DsrDetailsSection.tsx
features/dsr/components/DsrSimulationSection.tsx
features/dsr/containers/DsrView.tsx
features/dsr/containers/DsrViewContainer.tsx
features/dsr/helpers/dsrPot.ts

the calculation of DSR rates in simulation has been changed.
for now apy has been calculated as if it's apr ( apr/365 = daily rate - and then multiplied by the number of the days).
go to :
http://localhost:3000/earn/dsr/0x9EA650f8185929DD63d242c3d8dCa9292BF7B155#overview
use 100 000 usd as input and compare with simualtion at:
https://app.sparkprotocol.io/sdai/

chore: update dsr apy formula

---

blockchain/contracts/arbitrum.ts
blockchain/contracts/goerli.ts
blockchain/contracts/mainnet.ts
blockchain/contracts/optimism.ts
features/productHub/meta.ts
handlers/product-hub/promo-cards/ajnaLp.ts

Uncommented previously removed SDAI pool
Patch Product Finder and look for SDAI/USDC.

Enable SDAI pool

---

features/ajna/positions/common/components/contentCards/ContentCardEarnNetValue.tsx
features/ajna/positions/earn/components/ContentFooterItemsEarnManage.tsx
features/ajna/positions/earn/components/ContentFooterItemsEarnOpen.tsx
features/ajna/positions/earn/controls/AjnaEarnOverviewManageController.tsx
features/ajna/positions/earn/controls/AjnaEarnOverviewOpenController.tsx

https://app.shortcut.com/oazo-apps/story/10147/manage-earn-overview-data
https://app.shortcut.com/oazo-apps/story/10164/open-earn-simulation
in oracless mode: 
- removed rewards from manage overview
- removed values that depends on market price from overview
- using oracless earn verify if there is anything in overview of open / manage flow which depends on market price
- rewards in manage shouldn't be visible in overview footer

Ajna earn oracless overview

---

blockchain/contracts/index.ts
components/AutomationContextProvider.tsx
features/aave/services/readPositionCreatedEvents.ts
features/web3OnBoard/bridge-connector.ts

- Tokens can be extended only for mainnet.

:bug: Fix token addresses for Optimism

---

features/ajna/positions/common/observables/getDpmPositionData.ts

- Added a check to overwrite WETH as ETH in returned DPM position data.
Test if `/ethereum/ajna/multiply/ETH-DAI/1005` is loading properly.

Fix WETH in DPM position data

---

.github/workflows/aws-prod-rollback.yaml
.github/workflows/aws-staging-rollback.yaml

- Updated rollback to allow rollback all commits vs only releases.
- Valid rollback commits up to 2 weeks old.
- Changed the hashed to be 7 chars long to match github short hashes.
- Run the workflow in staging

Update rollback workflow

---

analytics/analytics.ts
features/dsr/helpers/dsrDeposit.tsx

- TxHash on top level on the event
- Added `isMintingSDai`
- Added `convert` operation

Extend analytics for DSR

---

public/locales/en/common.json

- changed copy of error related to dust limit
- verify whether copy has been updated on UI

Ajna dust limit copy change

---

features/aave/components/AaveHeader.tsx
features/aave/components/order-information/OutstandingDebtInformation.tsx

-  Remove bug in Aave header that causes infinite reloading.
- The button `Go to position` works right now.
Story details: https://app.shortcut.com/oazo-apps/story/10904

:bug: Fix infinite reloading of Aave Header

---

features/newsletter/NewsletterView.tsx
pages/api/newsletter-subscribe.tsx
public/locales/en/common.json

Disable newsletter

---

features/aave/strategies/index.ts
features/vaultsOverview/pipes/positions.ts

- Mark position as dangerous or warning in owner page 
- Fix issue with not found on manage aave positions.

Position Overview - mark position as dangerous and warning

---

package.json
yarn.lock

See https://github.com/OasisDEX/oasis-earn-sc/pull/424 for details

[FIX] USDC/WBTC Close to Coll Fix

---

features/ajna/common/controls/AjnaPoolCreatorController.tsx
helpers/applicationLinks.ts
public/locales/en/common.json

- Updated translations for Ajna pool creator.
`/ajna/pool-creator`

Pool creator copy update

---

public/locales/en/common.json

Updating incorrect 'Payback' noun to 'Pay back' verb

Updating incorrect 'Payback' noun to 'Pay back' verb

---

components/SimulateTitle.tsx
features/ajna/positions/common/hooks/useAjnaData.ts

- fixed issue where known, curated tokens were displayed as ?
- use in oracless combination of known token and some random token, known token icon should be displayed correctly

Ajna fix known icons

---

blockchain/identifyTokens.ts
features/ajna/positions/common/hooks/useAjnaData.ts
features/poolFinder/helpers/parsePoolResponse.ts

- called `toLowerCase()` method on addresses in identifyTokens observable
- tokens should be recognized as expected

Fix identify tokens casing

---

features/aave/components/DebtInput.tsx
features/aave/strategies/ethereum-aave-v3-strategies.ts
features/content/faqs/aave/borrow/en.mdx
features/content/faqs/aave/borrow/index.tsx

The updated FAQs regarding 'Borrow with Aave' feature have been added, including a comprehensive guide and risk explanation for users. The updates were necessary to provide more information and transparency for users about borrowing process and associated risks.
Moreover, in 'ethereum-aave-v3-strategies.ts', the associated FAQ for positionInfo is updated from 'AaveMultiplyFaq' to 'AaveBorrowFaq' to reflect the new content."
The 'Generate' action in the DebtInput component has been refactored to 'Borrow'. This modification better aligns with the borrowing schema of Aave, and the change is made for more precise user interface. In addition, it's relevant to newly incorporated FAQs related to 'Borrow with Aave' feature to provide a more consistent experience for users.
[SC-11214][SC-11268]

chore: [sc-11214] & [sc-11268] Updating 'Position Info' tab

---

content/dsr-notification.tsx
features/borrow/manage/containers/ManageVaultDetails.tsx
features/earn/guni/manage/containers/GuniManageMultiplyVaultDetails.tsx
features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx

Story details: https://app.shortcut.com/oazo-apps/story/11261

feat: [sc-11261] Remove DSR rate notification Banner

---

features/ajna/positions/common/getAjnaSidebarTitle.tsx
features/ajna/positions/common/sidebars/AjnaFormContentRisk.tsx
features/ajna/positions/common/views/AjnaFormView.tsx
public/locales/en/common.json

- changed copy of banner and disclaimer for ajna oracless
- correct copies of banner and oracless disclaimer

Ajna oracless disclaimer lite

---

helpers/useFeatureToggle.ts

AjnaPoolFinder set to true

---

features/poolCreator/hooks/usePoolCreatorData.tsx
features/poolFinder/helpers/parsePoolResponse.ts

- when accesing properties on identifiedTokens object, all addresses has been converted to lower case
- no issues in pool creator when using upper case letters

Ajna casing fix

---

public/locales/en/common.json

updated based on suggestion from Roberto

Update referral message

---

blockchain/calls/merkleRedeemer.ts

fixed redeemer address

---

yarn.lock

fixed yarn lock

---

pages/ajna/pool-creator.tsx
pages/ajna/pool-finder/[product].tsx
public/locales/en/common.json

- Added custom titles to pool finder and pool creator, so they have something more than generic "Summer.fi × Ajna".

Update pool finder and creator page titles

---

blockchain/prices.ts
features/referralOverview/userApi.ts
features/shared/followApi.ts
features/shared/jwt.ts
features/shared/vaultApi.ts
features/subgraphLoader/useSubgraphLoader.ts
features/termsOfService/termsAcceptanceApi.ts
features/walletAssociatedRisk/walletRiskApi.ts
handlers/product-hub/index.ts
helpers/staticPaths.ts
pages/api/tokensPrices.tsx

- Remove `basePath` from the application code. All requests from the app to our `/api` should be relative.

feat: [sc-11385] Frontend app is broken when URL contains `www`

---

features/referralOverview/ReferralLanding.tsx
features/vaultsOverview/containers/ConnectWalletPrompt.tsx

fixed refferal landing button

---

components/context/ProductContextProvider.tsx
components/context/TOSContextProvider.tsx
features/aave/strategies/ethereum-spark-v3-strategies.ts
features/walletAssociatedRisk/WalletAssociatedRisk.tsx
helpers/context/ProductContext.ts
pages/ajna/pool-finder/[product].tsx

- Removed unnecessary console log
- vMoved walletAssociatedRisk to TOS context
- Added ProductContextHandler to pool finder

Context fixes

---

.eslintrc.json

updated no-shadow rule to support TS
code

updated no-shadow rule to support TS

---

pages/ajna/pool-creator.tsx

Add ProductContextHandler to pool creator

---

yarn.lock

Update package dependencies version

---

actions/aave-like/open/get-open-deposit-borrow-position-parameters.ts

- Fix issue in Aavelike manage params file

[Test] Aave Regression on Spark branch

---

features/homepage/AjnaHomepageView.tsx
features/homepage/common/Hero.tsx
public/locales/en/common.json

- Updated copy in landing page hero component,
- updated default max widths for hero text.

Update Landing Page Header / SubHeader Copy

---

components/GenericMultiselect.tsx
features/productHub/meta.ts

Added Spark protocol to product hub filters
Added filter options feature flag support

feat: [sc-11192] ✨ Spark Product Hub filters + select filters feature flag support

---

actions/aave-like/manage/get-manage-position-parameters.ts
actions/aave-like/open/get-open-position-parameters.ts

- added borrow manage parameters
- open spark borrow position
- try to manage it

feat: [sc-11192] ✨ [Frontend] Borrow manage parameters

---

features/ajna/positions/borrow/controls/AjnaBorrowFormController.tsx

Temporary hide adjust panel on Ajna Borrow.

Hide borrow adjust

---

features/aave/strategies/ethereum-spark-v3-strategies.ts
features/productHub/controls/ProductHubContentController.tsx
helpers/useFeatureToggle.ts

Added useFeatureToggles hook
Additional spark v3 feature toggles
Better product hub filtering

Spark Feature toggle kit

---

features/aave/strategies/ethereum-spark-v3-strategies.ts
features/content/faqs/spark/borrow/en.mdx
features/content/faqs/spark/borrow/index.tsx
features/content/faqs/spark/earn/en_v3.mdx
features/content/faqs/spark/earn/index.tsx
features/content/faqs/spark/multiply/en.mdx
features/content/faqs/spark/multiply/index.tsx

Story details: https://app.shortcut.com/oazo-apps/story/11752

feat: [sc-11752] [Frontend] Update position info for Spark Borrow,  Spark Multiply, Spark Earn

---

features/aave/setup-aave-v3-context.ts
features/aave/setup-spark-v3-context.ts

Story details: https://app.shortcut.com/oazo-apps/story/11754

fix: [sc-11754] [BUG-staging][Aave v3][earn] sdai/lusd 

---

features/aave/manage/services/aave-v3/getManageAaveV3PositionStateMachineServices.ts

Story details: https://app.shortcut.com/oazo-apps/story/11717

fix: [sc-11717] [BUG][Spark][Borrow] Position fails to switch to Multiply

---

components/vault/HistoryControl.tsx
features/aave/manage/containers/AaveManageTabBar.tsx
public/locales/en/common.json

Now it uses correct protocol name.

Changed the label on the disabled history tab in Aave-like position

---

features/aave/components/LiquidationPriceCard.tsx
features/aave/components/SidebarAdjustRiskView.tsx
features/aave/open/sidebars/SidebarOpenAaveVault.tsx
features/aave/services/risk-slider-config.tsx
features/aave/types/strategy-config.ts

Story details: https://app.shortcut.com/oazo-apps/story/11793

fix: Liquidation price is not denominated in collateral/debt terms

---

lendingProtocols/LendingProtocol.ts

Changed Spark V3 -> Spark

---

.codesandbox/tasks.json
blockchain/networks/get-rpc-provider.ts
handlers/product-hub/index.ts

- Better error handling for product hub,
-Check if `getRpcProvider` runs on the server and returns the correct version of the JSON provider.

Add error handling and provider selection logic

---

features/aave/components/order-information/PriceImpact.tsx
features/aave/services/risk-slider-config.tsx

- Format Liquidation Price with proper formatter
- Displaying price impact in regard to strategy type.

chore: [sc-11241] [Frontend] short positions issues

---

features/aave/strategies/arbitrum-aave-v3-strategies.ts
features/aave/strategies/optimism-aave-v3-strategies.ts

disable borrow strategies

---

features/ajna/positions/earn/helpers/getAjnaEarnWithdrawMax.ts
features/ajna/positions/earn/sidebars/AjnaEarnFormContentWithdraw.tsx
package.json
yarn.lock

- removed rounding when calculating max withdraw 
- adjusted max withdraw digits to quote token precision
- user should be able to withdraw all from position without getting error than he is trying to withdraw more quote tokens than he has in position

Ajna earn max withdraw rounding removal

---

package.json
yarn.lock

chore: bump automation to `1.5.4`

---

features/ajna/positions/earn/components/AjnaEarnSlider.tsx
features/ajna/positions/earn/consts.ts
features/ajna/positions/earn/helpers/getMinMaxAndRange.ts

- adjusted htp and momp offsets on Ajna earn slider
- go to earn UI, offset from htp should be 2%, from momp 5%

Ajna earn slider offsets change

---

features/aave/aave-context-provider.tsx

Add proper aave like context for spark v3

---

components/context/ConfigContextProvider.tsx
features/productHub/hooks/useProductHubData.ts
features/productHub/views/ProductHubView.tsx
handlers/product-hub/types.ts
helpers/clean-object.ts
helpers/config/access-config-context.ts

Fixes:
- merging config (overrides) using `merge` instead of spread
- filtering product hub items
- remade cleaning function

Fixes on the default (fallback) config

---

components/TopBanner.tsx

Fixes the top banner name check

---

theme/tokenIcons.tsx

Removes annoying stop-color error

Removes annoying stop-color error

---

features/ajna/positions/common/observables/getAjnaPositionAggregatedData.ts
package.json
yarn.lock

- integrated changes from lib to handle whether position bucket is frozen
- either find position on pool which has non zero debt to be liquidated and which is in bucket that suppose to be frozen or tweak code manually in lib to mock bucket being frozen

Frozen bucket lib integration

---

features/aave/helpers/createFollowButton.ts
features/aave/open/state/openAaveStateMachine.ts
features/aave/strategies/ethereum-aave-v3-strategies.ts
features/aave/strategies/ethereum-spark-v3-strategies.ts
features/aave/strategies/index.ts
features/automation/metadata/maker/stopLossMetadata.ts
features/borrow/open/pipes/openVault.ts
features/borrow/open/tests/openVault.test.ts
features/multiply/open/pipes/openMultiplyVault.ts
features/sidebar/getSidebarTitle.ts
helpers/config/access-config-context.ts
helpers/useTomfoolery.ts

- swapped getAppConfig to getLocalAppConfig in every place where the context might be unavailable

Swap getAppConfig to getLocalAppConfig

---

package.json
yarn.lock

chore: bump automation to `1.5.7`

---

.github/workflows/build.yml
blockchain/networks/forks-config.ts
components/FeatureToggleRedirect.tsx
components/GenericMultiselect.tsx
components/context/ConfigContextProvider.tsx
features/aave/hooks/useAaveLikeConfig.ts
features/aave/strategies/arbitrum-aave-v3-strategies.ts
features/aave/strategies/common.ts
features/aave/strategies/ethereum-aave-v3-strategies.ts
features/aave/strategies/optimism-aave-v3-strategies.ts
features/aave/types/strategy-config.ts
features/borrow/open/tests/openVault.test.ts
features/productHub/meta.ts
helpers/config/index.ts
helpers/config/types.ts
package.json
pages/ajna/pool-creator.tsx
pages/ajna/pool-finder/[product].tsx
pages/earn/dsr/[wallet].tsx
scripts/get-config-types.ts
yarn.lock

- added `get-config-types` script
- it pulls the config from `CONFIG_URL` env and creates `types/config` type with the current config and feature enums

Generate AppConfig type on app launch and build

---

Dockerfile

- possible fix for staging build failing

Fix staging

---

Dockerfile

Continuing the work from https://github.com/OasisDEX/oasis-borrow/pull/2900

Moved yarn install (and postinstall) after env definition in dockerfile

---

Dockerfile
package.json
scripts/get-config-types.js

Changed the get config script to js, so it runs with no ts-node, brought back the old dockerfile sequence with the addition of CONFIG_URL env.

Staging fix 5

---

pages/[networkOrProduct]/ajna/[...position].tsx
pages/[networkOrProduct]/ajna/[id].tsx
pages/[networkOrProduct]/maker/[vault]/index.tsx

- added gas context in all required places which was for some reason deleted
- working gas estimations on ajna postions and for maker automation features

Fix lack of gas estimation

---

components/context/PreloadAppDataContextProvider.tsx

#Preload app data condition fix
- fixed condition
- app should load

Preload app data condition fix

---

features/navigation/panels/getNavProductsPanel.tsx
public/locales/en/common.json

-add exposure missing translation
- nothing to test

Exposure missing translation

---

components/swapWidget/SwapWidget.tsx
features/navigation/panels/getNavProductsPanel.tsx
features/swapWidget/SwapWidgetChange.ts
package.json
yarn.lock

- added handling for initializing swap widget with predefined variant action (swap / bridge)
- using new navigation, try to open widget by click on swap or bridge, in both cases widget should be opened with proper action

Swap widget predefining variant

---

features/aave/strategies/ethereum-aave-v3-strategies.ts
features/aave/strategies/ethereum-spark-v3-strategies.ts

- Disabled AaveV3/SparkV3 short strategies

Disable AaveV3/SparkV3 short strategies

---

features/aave/manage/sidebars/SidebarManageAaveVault.tsx
features/aave/strategies/ethereum-aave-v3-strategies.ts
features/aave/strategies/ethereum-spark-v3-strategies.ts

- Added config from https://github.com/OasisDEX/oazo-configuration/pull/46
- Brought back the configs

Bring back strategies, disable close to dai

---

features/navigation/helpers/getProductBorrowNavItems.ts

- fixed condition so proper borrow product is picked up for navigation
- in navigation borrow product should have rewards and the highest liquidity

Fix nav borrow product condition

---

.github/workflows/aws-prod-rollback.yaml
.github/workflows/aws-staging-rollback.yaml

Some of the workflow were using different secret names that stored same values and performed same functions. This PR is to remove duplicates.

Align secrets used in GH Actions

---

pages/about.tsx
pages/brand.tsx
pages/security.tsx

Static pages fixes

---

.github/workflows/aws-staging.yaml

Increase GH action ram limit

---

.dockerignore
.github/workflows/aws-staging.yaml
Dockerfile
package.json

Reverts staging build changes

---

.github/workflows/aws-prod-rollback.yaml
.github/workflows/aws-staging-rollback.yaml

Updating the rollback GHAs with the new names

Update rollback GHAs

---

package.json
yarn.lock

Another possible fix for portfolio page.

Revert some package updates

---

blockchain/calls/cdpManager.ts
package.json
yarn.lock

Due to unknown issue passing `BigNumber` values to maker calls broke. This fixes it (cast to number).

Fix maker bignumber issues

---

features/ajna/positions/common/helpers/getAjnaPoolData.ts
features/ajna/positions/common/helpers/getAjnaPoolData.types.ts
features/subgraphLoader/consts.ts

- update pending inflator handling due to changes in subgraph structure
- no issues with subgraph call regarding ajna pool

Update pending inflator handling

---

features/productHub/views/ProductHubRouteHandler.tsx
helpers/useScrollToTop.ts
pages/about.tsx
pages/cookie.tsx
pages/privacy.tsx
pages/terms.tsx

Minor UX issue fix reported by a user.

Scroll to top on page changes (static + product hub lists)

---

.github/workflows/aws-staging.yaml
.github/workflows/dev-cache.yaml
Dockerfile
package.json
server/database/schema.prisma
yarn.lock

Another approach to faster staging deploy times.

🤌 molto bene docker immagine

---

Dockerfile

change docker cmd

---

Dockerfile

added yarn migrate

---

Dockerfile

revert changes (the CMD is set in AWS config)

revert changes (the CMD is set in AWS config)

---

.github/workflows/nextjs-bundle-analysis.yml
package.json

Added nextjs-bundle-analysis

---

features/borrow/open/containers/OpenVaultView.tsx
features/multiply/open/containers/OpenMultiplyVaultView.tsx

Added wallet connection requirement to maker vaults

---

.github/workflows/dev-cache.yaml

- cache action checks if cache-key hits and skips download if it does (way faster)
- additionally it removes other caches (not needed cause outdated)

Upgrade cache action

---

.github/workflows/nextjs-bundle-analysis.yml

Fix nextjs analyze action
This makes this action only on my branch

Fix nextjs analyze action

---

.github/workflows/prod-cache.yaml

- added two caches: one for main and one for dev branch
- also fixes removal of old dev branch caches (introduced in #3000 but not working cause its set to master branch)

[GH Actions] Cache for dev and main

---

.github/workflows/dev-cache.yaml
.github/workflows/prod-cache.yaml

Please dont remove nextjs cache

---

package.json

Update DMA Lib

---

.github/workflows/dev-cache.yaml
.github/workflows/prod-cache.yaml

gh actions-cache delete doesnt have a key param (list does)

Fix gh actions-cache delete

---

components/sidebar/SidebarSectionHeaderSelect.tsx
components/vault/VaultHeader.tsx
components/vault/VaultHeadlineDetails.tsx

Fixes couple of annoying warnings

---

actions/aave-like/adjust/get-adjust-position-parameters.ts
actions/aave-like/close/get-close-aave-parameters.ts
actions/aave-like/helpers/index.ts

Set proper flashloan token on optimism and base

Set proper flashloan token on optimism and base

---

actions/aave-like/helpers/index.ts
actions/aave-like/open/get-open-position-parameters.ts
blockchain/token-metadata-list/token-configs.ts
features/aave/strategies/base-aave-v3-strategies.ts
package.json
yarn.lock

Added aaveLike.flashLoanTokens from config
Removed switch-to-borrow on earn strategy
Changed USDBC display digits (not precision!)
Bumped addresses version (proper balancer address)

Aave V3@Base fixes

---

features/automation/protection/stopLoss/state/stopLossTriggerData.ts

- converted trigger type to string
- nothing to test now

Prep stop-loss data v2 adjustment

---

blockchain/calls/automationBot.ts

- mapped BN to strings
- SL on automation v2 should work

Spark SL fix

---

components/navigation/content/MyPositionsOrb.tsx
features/ajna/positions/common/components/AjnaDupePositionModal.tsx
features/navigation/controls/AjnaNavigationController.tsx
features/navigation/controls/NavigationController.tsx
features/notices/VaultsNoticesView.tsx
helpers/get-portfolio-link.ts
pages/owner/[address]/index.tsx
pages/portfolio/[address].tsx
public/locales/en/portfolio.json

Story details: https://app.shortcut.com/oazo-apps/story/12443
- Added new (empty) page for portfolio
- - It's behind a new feature flag `NewPortfolio`

🍿 [Portfolio] Route component

---

features/omni-kit/contexts/OmniGeneralContext.tsx
features/omni-kit/contexts/OmniProductContext.tsx
features/omni-kit/controllers/OmniProductController.tsx

- omni contexts improvements, removed unnecessary combination of useEffect and useState
- changed error copies
- everything should work as usual

Omni contexts improvements

---

blockchain/networks/debank-network-names.ts
features/portfolio/constants.ts
features/portfolio/types.ts
pages/api/portfolio/wallet/[address].tsx
pages/portfolio/[address].tsx

- Added api/portfolio/wallet endpoint
- Added some necessary typing
- Debug logging on the new empty portfolio page

🍿 [Portfolio] Wallet endpoint

---

next.config.js
package.json
yarn.lock

Disables automatic locale detection because of https://github.com/ver…cel/next.js/issues/55648

Disables automatic locale detection

---

features/omni-kit/hooks/index.ts
features/omni-kit/hooks/useOmniTxHandler.ts
features/omni-kit/protocols/ajna/helpers/getAjnaOmniParameters.ts
features/omni-kit/protocols/ajna/hooks/useAjnaOmniTxHandler.ts

- extracted common tx handler things that can be reused in omni
- everything should work as usual

Generalize omni tx handler

---

components/SimulateTitle.tsx
features/dsr/components/DsrDetailsSection.tsx
features/dsr/components/DsrSimulationSection.tsx
features/dsr/containers/DsrView.tsx
features/dsr/containers/DsrViewContainer.tsx
public/locales/en/common.json

- added sdai balances to DSR overview
- visit position from story or search for wallet address with sdai and use it

DSR sdai balance support

---

features/ajna/positions/common/views/AjnaFormView.tsx
features/omni-kit/contexts/OmniProductContext.tsx
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
features/omni-kit/views/OmniFormView.tsx

- added Morpho feature toggles
- nothing to test right now

Morpho feature toggles

---

components/vault/GeneralManageControl.tsx

- added feature toggle to turn off vault history check for maker positions
- while using maker with tenderly fork, use `MakerTenderly` feature toggle to make it work

Maker tenderly feature toggle

---

components/Tag.tsx
components/layouts/PortfolioLayout.tsx
components/portfolio/PortfolioHeader.tsx
components/portfolio/PortfolioOverview.tsx
components/portfolio/PortfolioOverviewItem.tsx
features/portfolio/types.ts
pages/api/portfolio/positions/[address].tsx
pages/portfolio/[address].tsx
public/locales/en/portfolio.json
theme/index.tsx
ts_modules/i18next.d.ts

- PortfolioHeader
- PortfolioOverview
- PortfolioLayout
- Simple RWD view for the above

🍿 [Portfolio] First batch of components - header + overview

---

features/omni-kit/contexts/OmniProductContext.tsx
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx

- removed duplicated value from omni metadata, both in ajna and morpho
- nothing to test

Remove duplication from metadata

---

features/omni-kit/components/sidebars/OmniFormContentSummary.tsx
features/omni-kit/contexts/OmniProductContext.tsx
features/omni-kit/controllers/earn/OmniEarnFormController.tsx
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
features/omni-kit/protocols/morpho-blue/state/MorphoOmniCustomStateProvider.tsx
features/omni-kit/views/OmniFormView.tsx

- handled omni metadata optionals
- nothing to test

Omni metadata optionals

---

features/aave/services/read-position-created-events.ts
features/omni-kit/protocols/morpho-blue/constants.ts
features/omni-kit/protocols/morpho-blue/helpers/morphoFlowStateFilter.ts
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
features/omni-kit/types.ts

- added morpho dpm filter
- nothing to test right now

Morpho DPM filter

---

components/portfolio/PortfolioOverview.tsx
components/portfolio/helpers/getPortfolioChangeColor.ts
components/portfolio/helpers/getPortfolioChangeSign.ts
components/portfolio/helpers/index.ts

- Exported `getPortfolioChangeColor` and `getPortfolioChangeSign`.

Export common Portfolio change functions

---

features/ajna/positions/common/helpers/getAjnaPoolData.ts
features/ajna/positions/common/helpers/getAjnaPoolData.types.ts
features/subgraphLoader/consts.ts

- removed pending inflator from subgraph query as it will be removed soon
- fetching pending inflator directly from blockchain
- everything ajna related should work as usual

Get pending inflator form blockchain

---

features/vaultHistory/vaultHistory.ts

- at some point chainId was introduced in automation event but was not handled everywhere 
- `ethereum/maker/30439#history` SL history should show correct data instead of zeros

Add missing chainId to automation events

---

pages/api/rpcGateway.tsx

chore: fe get rid of stage [sc-12593]

---

.github/workflows/aws-staging.yaml

Added new docker env var for gateway url

Added new docker env var

---

components/portfolio/blog-posts/BlogPostBlock.tsx
components/portfolio/blog-posts/BlogPostBlockSkeleton.tsx
components/portfolio/blog-posts/BlogPostDot.tsx
components/portfolio/blog-posts/BlogPosts.tsx
components/portfolio/positions/PortfolioPositionsView.tsx
handlers/blog-posts/get.ts
helpers/types/blog-posts.types.ts
pages/api/blog-posts.tsx

🍿 [Portfolio] Blog posts

---

components/TokenBanner.tsx
components/portfolio/wallet/PortfolioWalletAssets.tsx
components/portfolio/wallet/PortfolioWalletBanner.tsx
components/portfolio/wallet/PortfolioWalletSummary.tsx
components/portfolio/wallet/PortfolioWalletTopAssets.tsx
components/portfolio/wallet/PortfolioWalletView.tsx
lambdas/src/portfolio-assets/index.ts
public/locales/en/portfolio.json
theme/index.tsx

- Updated main Portfolio layout to match container's size from the design,
- created `portfolio` grid variant for Portfolio page,
- updated Portfolio wallet tab numbers formatting,
- added up and down arrows to price change in assets list,,
- added banner at the bottom of Portfolio wallet tab,
- created `TokenBanner` as universal configurable component that could be used outside of Portfolio.

Portfolio wallet updates

---

components/portfolio/wallet/PortfolioWalletBanner.tsx

fixed type import

---

.github/workflows/aws-staging.yaml
Dockerfile.staging
next.config.js
server/config.ts
server/helpers/get-aws-infra-header.ts
server/helpers/get-aws-infra-url.ts

fixed env variable

---

next.config.js

disable sentry back

---

components/portfolio/wallet/PortfolioWalletAssets.tsx

- Changed product name to lowercase in URL.

Fix links in Portfolio assets list

---

components/portfolio/PortfolioHeader.tsx
components/portfolio/PortfolioOverview.tsx
components/portfolio/PortfolioOverviewSkeleton.tsx
components/portfolio/wallet/PortfolioWalletAssets.tsx
helpers/useHash.ts
pages/portfolio/[address].tsx
public/locales/en/portfolio.json

- removed key errors
- fixed `View Assets` link
- added proper etherscan link
- fixed labels
- changed avatar to pixel (sunset was getting the same results for every address)

🍿 [Portfolio] Various fixes

---

pages/api/rpcGateway.tsx

chore: change env handling

---

components/portfolio/PortfolioNonOwnerNotice.tsx
components/portfolio/helpers/usePortfolioMatchingAssets.ts
components/portfolio/wallet/PortfolioWalletBanner.tsx

🍿[Portfolio] Matching assets not loading on empty wallet

---

components/portfolio/LendingRangeDetail.tsx
components/portfolio/positions/PortfolioPositionBlockDetail.tsx
lambdas/src/portfolio-positions/mock.ts
lambdas/src/shared/domain-types.ts
lambdas/src/shared/lending-range.ts
public/locales/en/portfolio.json

https://github.com/OasisDEX/oasis-borrow/assets/5095527/acc2428c-0d0b-4dcc-814d-8020ea3700d0

🍿[Portfolio] Lending range component

---

components/portfolio/PortfolioOverview.tsx
components/portfolio/PortfolioOverviewItem.tsx
components/portfolio/PortfolioOverviewSkeleton.tsx
components/portfolio/blog-posts/BlogPostBlock.tsx
components/portfolio/wallet/PortfolioWalletAssets.tsx
pages/portfolio/[address].tsx

- Fixed and issue with link to wstETH products in assets list,
- adjusted overview section items to match the design,
- updated overview section skeleton loading as it wasn't updated along with changes that were made to loaded version (value instead of link, more blocks etc.) and removed jumping between loaded and loading states,
- added transition to blog posts.

Minor Portfolio fixes

---

package.json

Remove yarn lambdas-dependencies

Remove yarn lambdas-dependencies

---

components/AutomationIcon.tsx
components/portfolio/positions/PortfolioPositionBlock.tsx
components/portfolio/positions/PortfolioPositionBlockDetail.tsx
components/portfolio/positions/PortfolioPositionsView.tsx

- Adjusted tooltips in Portfolio positions view to match those that were implemented in latest months (e.g. Product Finder),
- fixed issue with text wrapping in automation icons.

Portfolio tooltip fixes

---

components/portfolio/PortfolioOverview.tsx
components/portfolio/PortfolioOverviewSkeleton.tsx
pages/portfolio/[address].tsx

🍿 [Portfolio] Remove 24 change from the overview

---

components/portfolio/PortfolioOverview.tsx
components/portfolio/positions/PortfolioPositionBlock.tsx
components/portfolio/positions/PortfolioPositionBlockDetail.tsx
components/portfolio/positions/PortfolioPositionsView.tsx
public/locales/en/portfolio.json

🍿 [Portfolio] RWD fixes

---

components/portfolio/positions/PortfolioPositionsSortingSelect.tsx
public/locales/en/portfolio.json

🍿 [Portfolio] - Net value select on mobile made with sense

---

handlers/portfolio/positions/handlers/aaveV3/index.ts
handlers/portfolio/positions/index.ts
handlers/portfolio/types.ts

🍿 [Portfolio] 🍳 little more boilerplate 🥩

---

components/portfolio/PortfolioOverview.tsx
components/portfolio/positions/PortfolioPositionFeatured.tsx
components/portfolio/positions/PortfolioPositionLearn.tsx

- Shortens values formatting in overview section for big numbers (https://discord.com/channels/837076147694207067/1164169473876578365/1171829110713094335).
- Fix behavior of arrows and slides counter on mobile in Featured for you section (https://discord.com/channels/837076147694207067/1164169473876578365/1171835863286677545).
- Fix spacing on mobile in Learn with Summer.fi section (https://discord.com/channels/837076147694207067/1164169473876578365/1171838500623106148).

Portfolio mobile fixes

---

handlers/portfolio/positions/index.ts
handlers/portfolio/types.ts

- Added price tickers to be available in each positions handler for Portfolio API.

Added price tickers to positions handlers

---

components/portfolio/positions/PortfolioPositionBlock.tsx
components/portfolio/positions/PortfolioPositionsView.tsx
handlers/portfolio/types.ts

- Removed `tokens`,
- added `primaryToken`, `secondaryToken` and `netValue`,

Update `PortfolioPosition` type

---

handlers/portfolio/positions/helpers/getTokensPrices.ts

Portfolio price retry timeout

---

handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
handlers/portfolio/positions/handlers/maker/helpers/getMakerPositionInfo.ts
handlers/portfolio/positions/helpers/getTokensPrices.ts
handlers/portfolio/positions/index.ts
pages/api/positions/[address].tsx

- Added cache'ing to successful portfolio token prices request resposne,
- added `?debug` param to positions API request to return additional data along with (probably failed) positions list,
- fixed formatting in aave-like details.

Caching prices response and minor fixes

---

handlers/portfolio/positions/index.ts

Portfolio - more verbose debug

---

features/subgraphLoader/useSubgraphLoader.ts

Server side subgraph loader

---

handlers/portfolio/positions/handlers/aave-like/helpers.ts
handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/aave-v2/index.ts
handlers/portfolio/positions/index.ts
handlers/portfolio/types.ts

🍿[Portfolio] Aave v2 and v3 yields (steth, wsteth), aave v2 positions

---

handlers/portfolio/positions/handlers/aave-like/helpers.ts
handlers/portfolio/positions/handlers/aave-v2/ds-proxy-position.ts
handlers/portfolio/positions/handlers/aave-v2/index.ts

Story details: https://app.shortcut.com/oazo-apps/story/12774

fix: [sc-12774] [BUG] - Some Aave V2 positions are not listed in /portfolio page

---

handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/aave-v2/index.ts

Story details: https://app.shortcut.com/oazo-apps/story/12779

fix: [sc-12779] [BUG] - Aave V3 positions - Liquidation price incorrectly displayed in $

---

handlers/portfolio/positions/index.ts
handlers/portfolio/types.ts

Portfolio positions cache (2 mins)

---

features/omni-kit/helpers/isShortPosition.ts
handlers/portfolio/positions/handlers/aave-like/index.ts

[Portfolio] Invert liquidationPrice on short positions

---

handlers/portfolio/positions/helpers/getBorrowishPositionType.ts
handlers/portfolio/positions/helpers/getPositionsFromDatabase.ts

Added lowercases to comparisons of user address and network name.

Fix `getPositionsFromDatabase` address comparision

---

helpers/getTokenDisplayName.ts

Fix issue found in sentry

---

handlers/portfolio/positions/handlers/aave-like/index.ts

Fixed Aave liquidation price in portfolio

---

features/vaultsOverview/VaultOverviewView.tsx
public/locales/en/common.json

- Added a banner on old owners page with link to new Portfolio.

New Portfolio banner on owner's page

---

pages/portfolio/[address].tsx

Parse portfolio address better

---

blockchain/ens.ts
components/portfolio/PortfolioHeader.tsx

- low hanging fruit
- no pipes

[Portfolio] ENS names

---

blockchain/better-calls/dpm-account.ts

Reverts OasisDEX/oasis-borrow#3153

Revert "Add type and accessList to dpm execution calls"

---

components/PromoCard.tsx
components/PromoCard.types.tsx
components/portfolio/positions/PortfolioPositionFeatured.tsx
components/portfolio/positions/PortfolioPositionsView.tsx
pages/portfolio/[address].tsx

- Added new set of rules to featured for you section:
- items are in random order,
- hidden all products, that user already has (same network, protocol and exact token pair),
- hidden all products, that doesn't use any of tokes that user has.
- Added loading states to the section.

Enhanced filtering on "Featured for you" section in Portfolio

---

analytics/TrackingFeatureType.ts
analytics/events-types/index.ts
analytics/events-types/migrations-types.ts
analytics/events-types/tx-types.ts
analytics/trackingEvents.ts
analytics/types.ts

- added migrations mixpanel events definition to be later used on UI
- added tx events handling
- nothing to test right now

Mixpanel migrations events

---

handlers/portfolio/positions/handlers/aave-like/helpers.ts
handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/aave-like/types.ts
handlers/portfolio/positions/helpers/getBorrowishPositionType.ts

- include apiVaults response so we get the proper position type

Fix Aave-like position handlers

---

handlers/portfolio/positions/handlers/aave-like/index.ts

Story details: https://app.shortcut.com/oazo-apps/story/12775

fix: [sc-12775] [BUG] - Positions tab - Earnings

---

components/portfolio/positions/PortfolioPositionBlockDetail.tsx
public/locales/en/portfolio.json

Add earnings tooltip to PortfolioPositionBlockDetail

---

handlers/portfolio/positions/helpers/getHistoryData.ts

- added graceful fallback to no details (user will still get a list)
- added sentry logging (cause we're not throwing error)

Make the positions list work without history data 

---

package.json
yarn.lock

Update @sentry/nextjs version

---

features/ajna/positions/common/notifications.tsx
features/ajna/positions/common/observables/getAjnaPositionAggregatedData.ts
features/omni-kit/protocols/ajna/helpers/getAjnaNotifications.tsx
features/omni-kit/protocols/ajna/observables/getAjnaPositionAggregatedData.ts
public/locales/en/common.json

- removed all things related to ajna partial liquidations as these are no longer needed
- no partial liquidation notifications

Remove partial liquidation logic from Ajna

---

handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/helpers/getHistoryData.ts

Fix earnings calculation bug in Aave-like position handler

---

features/aave/strategies/ethereum-spark-v3-strategies.ts

Add feature toggle for SparkWBTCDAI

---

handlers/portfolio/positions/handlers/aave-like/index.ts

Refactor Aave-like position earn netvalue

---

handlers/product-hub/update-handlers/sparkV3/sparkV3Products.ts

Add WBTC/DAI borrow to SparkV3Products

---

actions/aave-like/helpers/index.ts
features/exchange/exchange.ts
helpers/swap.ts
pages/api/exchange/[[...params]].tsx

Update OneInch API version to v5.0

---

features/omni-kit/contexts/OmniProductContext.tsx
features/omni-kit/protocols/ajna/metadata/AjnaEarnDetailsSectionFooter.tsx
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx

- fixed issue with max withdraw amount after pill in earn position
- while adjusting lending price or performing other actions in ajna earn postion, `Available to Withdraw` after pill should show correct value

Ajna earn max withdraw fix

---

features/omni-kit/constants.ts
helpers/useFlowState.ts

Story details: https://app.shortcut.com/oazo-apps/story/13068

feat: [sc-13068] Cap repay all value at 0.005% of debt

---

features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx

- undo recent changes
- positions should load

Fix earn is form valid value in metadata

---

helpers/useFlowState.ts

Fix + refactor useFlowState/allowanceMachineSubscription

---

features/aave/services/read-position-created-events.ts
package.json
yarn.lock

- added `Ajna_rc10` handling
- bump addresses lib
- ajna should work on goerli

Update ajna rc10 goerli

---

features/omni-kit/protocols/ajna/helpers/getAjnaBorrowCollateralMax.ts
package.json
yarn.lock

- bumped lib version
- adjusted calcs regarding max withdraw
- ajna borrow max generate and withdraw should show correct values

Ajna update max generate & withdraw calcs

---

features/omni-kit/components/details-section/parsers/useOmniCardDataNetValue.ts
features/omni-kit/protocols/ajna/components/details-section/modals/AjnaCardDataNetValueModal.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataNetValue.tsx
features/omni-kit/protocols/ajna/metadata/AjnaLendingDetailsSectionContent.tsx
public/locales/en/common.json

Refactor PnL Ajna Modal

---

features/subgraphLoader/consts.ts
features/subgraphLoader/types.ts
features/subgraphLoader/useSubgraphLoader.ts
handlers/portfolio/positions/helpers/getAllDpmsForWallet.ts
handlers/portfolio/positions/helpers/getAutomationData.ts
handlers/portfolio/positions/helpers/getHistoryData.ts
pages/api/subgraph.tsx

- get the subgrpah base url from config
- get subgraphs using their name instead of full urls
- added method to get subgraph url based on config and subgraph name
- step 1 ...

feat: get graph base url from config

---

features/subgraphLoader/useSubgraphLoader.ts

feat: fix ajna georli graph

---

features/omni-kit/protocols/ajna/metadata/AjnaEarnFormOrderInformation.tsx
public/locales/en/common.json

- updated ajna deposit fee tooltip copy
- a correct copy used in deposit fee tooltip

Ajna deposit fee tooltip copy update

---

features/productHub/controls/ProductHubContentController.tsx
features/productHub/controls/ProductHubFiltersController.tsx
features/productHub/views/ProductHubView.tsx

- product hub uses the same chain id everywhere (same prop passed)
- switch between mainnet/testnet, it shouldn't break

Fix chainId bug in ProductHubContentController

---

components/Tooltip.tsx
features/aave/services/read-position-created-events.ts
features/omni-kit/components/details-section/OmniContentCard.tsx
features/omni-kit/controllers/OmniProductController.tsx
features/omni-kit/observables/getDpmPositionData.ts
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataBorrowRate.tsx

- Added redirects to 404 if position specified in url does not exist on latest version of protocol,
- fixed an unrelated issue with `p` and `div` nested in `p` in content cards.

Omnikit redirects

---

package.json
yarn.lock

- bumped addresses lib version to handle rc10 ajna mainnet addresses
- ajna on mainnet should work

Ajna rc10 mainnet config

---

package.json
yarn.lock

- bump dma lib version with fix for invalid  simulation when reopening empty earn ajna position
- reopening empty ajna earn position should have correct simulation

Depositing to Ajna empty earn position simulation adjustment

---

features/omni-kit/components/sidebars/OmniFormFields.tsx
features/omni-kit/constants.ts
features/omni-kit/protocols/ajna/actions/earn.ts
features/omni-kit/state/borrow/borrowFormReducto.constants.ts
features/omni-kit/state/borrow/borrowFormReducto.ts
features/omni-kit/state/borrow/borrowFormReducto.types.ts
features/omni-kit/state/earn/earnFormReducto.constants.ts
features/omni-kit/state/earn/earnFormReducto.ts
features/omni-kit/state/earn/earnFormReducto.types.ts
features/omni-kit/state/multiply/multiplyFormReducto.constants.ts
features/omni-kit/state/multiply/multiplyFormReducto.ts
features/omni-kit/state/multiply/multiplyFormReducto.types.ts
features/omni-kit/state/omniFormReductoActions.ts

- added a buffor when doing max withdraw but not emptying position
- while trying to withdraw all but not closing ajna earn position, it should be possible to do so without getting tx error

Ajna withdraw max offset

---

features/positionHistory/getHistoryEventLabel.ts

- revert names to proper ones
- fix names in subgraph - indexing in progress
- step 1 ...

fix: fix event names

---

features/aave/services/read-position-created-events.ts
features/omni-kit/protocols/ajna/constants.ts
package.json
yarn.lock

- bumped addresses lib version with initial config of rc11
- goerli, base, mainnet

Ajna rc 11

---

blockchain/calls/erc20.ts
blockchain/contracts/base.ts
blockchain/tokens.ts
features/omni-kit/contexts/OmniGeneralContext.tsx
features/omni-kit/controllers/OmniLayoutController.tsx
features/omni-kit/controllers/OmniProductController.tsx
features/omni-kit/helpers/getOmniHeadlineProps.ts
features/omni-kit/hooks/useOmniProtocolData.ts
features/omni-kit/hooks/useOmniTxHandler.ts
features/omni-kit/protocols/ajna/hooks/useAjnaData.ts
features/omni-kit/protocols/ajna/hooks/useAjnaTxHandler.ts
features/omni-kit/views/OmniFormView.tsx
features/shared/balanceInfo.ts
helpers/context/ProductContext.ts
pages/[networkOrProduct]/ajna/omni/[...position].tsx

- fixed issue with oracless balances
- added base explorer url
- open flow for oracless positions on base should load correctly

Ajna oracless Base balances bug

---

features/content/cookie/en.tsx

This pull request refactors the text formatting in the cookie policy to improve readability and consistency.

Refactor cookie policy text formatting

---

blockchain/contracts/index.ts
blockchain/identifyTokens.ts

- updated handling for tokens with zero address

Oracless token identify issue

---

features/omni-kit/protocols/ajna/actions/common.ts
features/omni-kit/protocols/ajna/helpers/getAjnaParameters.ts

- replaced hardcoded network ajna multiply
- try on different network than mainnet

Replace hardcoded network ajna multiply

---

features/exchange/exchange.ts
features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
features/omni-kit/constants.ts
features/omni-kit/observables/index.ts
features/omni-kit/observables/omniExchangeQuote.ts
features/omni-kit/protocols/ajna/actions/common.ts
features/omni-kit/protocols/ajna/actions/multiply.ts

- fixed issue where quote was called with wrong parameters on Base
- quote should work as expected on Base

Ajna swap quote omni adjustment

---

features/content/faqs/ajna/earn/en.tsx

How much does it cost update

---

features/omni-kit/protocols/ajna/hooks/useAjnaTxHandler.ts

- Passed correct proxy owner
- open multiply ajna should work

Pass correct proxy owner

---

features/omni-kit/constants.ts
features/omni-kit/protocols/ajna/actions/earn.ts
features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterBorrow.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaLendingDetailsSectionFooter.tsx
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
package.json
yarn.lock

- fixed issue with after pill showing wrong value
- bumped dma lib version with max generate calculation adjustments
- max generate shouldn't become smaller when user tries to deposit more and more collateral, it should be capped either at pool liquidity level or on max generate value from lib

Ajna max generate fee adjustment

---

features/aave/components/AaveBorrowManageComponent.tsx
features/aave/components/AaveBorrowPositionData.tsx
features/aave/components/AaveMultiplyManageComponent.tsx
features/aave/components/AaveMultiplyPositionData.tsx
features/aave/components/SparkTokensBannerController.tsx
features/aave/helpers/eligible-spark-position.ts
helpers/applicationLinks.ts
package.json
public/locales/en/common.json
public/static/img/spark-tokens-banner.svg
tsconfig.json

This pull request adds a new component called SparkTokensBannerController and updates the applicationLinks and locales files. The SparkTokensBannerController component is responsible for displaying a banner that informs users about earning SPK tokens with their Spark position on Summer.fi. The applicationLinks file is updated to include a link to more information about SPK tokens. The locales file is updated to include translations for the banner title, description, and button text.

Add SparkTokensBannerController and update applicationLinks and locales

---

package.json
yarn.lock

- Bumped dma lib 0.5.32
- ajna open multiply should open with proper raw protocol name

Bump dma lib 0.5.32

---

features/aave/constants.ts
features/aave/helpers/getStrategyConfig.test.ts
features/aave/helpers/getStrategyConfig.ts
features/aave/services/read-position-created-events.ts
helpers/context/ProductContext.ts

- fixed issue where aave logic was reading last position created event without filtering
- `https://staging.summer.fi/base/aave/v3/17 ` should load

Fix aave reading position events

---

public/locales/en/common.json

Update wording for Ajna Oracless - Lite -> Permissionless

---

features/ajna/pool-creator/controls/PoolCreatorController.tsx
public/locales/en/common.json

- Changed form title on success screen from "Configure new Ajna pool" to "New Ajna pool created".

Update pool creator title

---

features/omni-kit/protocols/ajna/helpers/isPoolSupportingMultiply.ts

Add USDBC to multiply-safe tokens list for Ajna Base

---

features/ajna/rewards/helpers/getAjnaRewards.ts
features/ajna/rewards/hooks/useAjnaRewards.ts
features/ajna/rewards/types.ts
features/subgraphLoader/consts.ts
features/subgraphLoader/types.ts
handlers/ajna-rewards/getAjnaRewardsData.ts

- adjusted ajna rewards read data logic
- payload prep
- working api call with response according to new interface + payload

Read new rewards on UI

---

blockchain/abi/ajna-bonus-redeemer.json
blockchain/abi/ajna-reedemer.json
blockchain/better-calls/send-generic-transaction.ts
blockchain/contracts/arbitrum.ts
blockchain/contracts/base.ts
blockchain/contracts/goerli.ts
blockchain/contracts/mainnet.ts
blockchain/contracts/optimism.ts
features/ajna/pool-creator/hooks/usePoolCreatorData.tsx
features/ajna/rewards/components/AjnaRewardCard.tsx
features/ajna/rewards/controls/AjnaRewardsController.tsx
handlers/ajna-rewards/getAjnaRewardsData.ts
package.json
public/locales/en/common.json
yarn.lock

- provided handling for claiming ajna rewards (bonus & regular)
- rewards claiming should work with good UX (not testable right now)

Handle rewards txs

---

components/context/AccountContextProvider.tsx
helpers/context/ProductContext.ts

This pull request moves the user analytics data to a separate file for better organization and maintainability.
Story: https://app.shortcut.com/oazo-apps/story/13526

chore: [sc-13526] Move `MixpanelIdentify` to AccountContext so that it is able to be triggered on everypage.

---

features/web3OnBoard/init-web3-on-board.ts

Remove ledgerModule from initWeb3OnBoard

---

features/aave/manage/contexts/aave-manage-state-machine-context.tsx

This pull request refactors the Aave manage state machine context by wrapping the children components in a fragment to avoid unnecessary rendering.

Refactor Aave manage state machine context

---

features/omni-kit/observables/estimateOmniGas.ts

- fixed issue with wrong decimals and wrong max gas fee
- correct estimates

Omni gas estimation fix

---

features/omni-kit/components/details-section/modals/OmniMultiplyNetValueModal.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaLendingDetailsSectionContent.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataNetValueLending.tsx
features/omni-kit/protocols/ajna/helpers/getAjnaCumulatives.ts
features/subgraphLoader/consts.ts
features/subgraphLoader/types.ts

This pull request updates the cumulative values in the OmniMultiplyNetValueModal component and the useAjnaCardDataNetValueLending function. It includes changes to the netValueTokenPrice, cumulatives, and netValueUSD variables. The updates ensure that the cumulative values are calculated correctly and displayed accurately in the UI.

Update cumulative values in OmniMultiplyNetValueModal and useAjnaCardDataNetValueLending

---

package.json
yarn.lock

- bumped lib with fix for closing to quote
- it should be possible to close to quote ajna multiply position

Ajna base close to quote fix

---

features/aave/components/AaveMultiplyManageComponent.tsx
features/aave/components/AaveMultiplyPositionData.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaLendingDetailsSectionContent.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataNetValueLending.tsx
features/omni-kit/protocols/ajna/helpers/getAjnaCumulatives.ts
features/subgraphLoader/consts.ts
features/subgraphLoader/types.ts

Update cumulative values

---

features/aave/components/AaveMultiplyPositionData.tsx
features/aave/components/ManageSectionComponent.tsx
features/aave/components/PositionInfoComponent.tsx
features/aave/services/get-aave-history-events.ts
features/omni-kit/components/details-section/modals/OmniMultiplyNetValueModal.tsx
features/omni-kit/protocols/aave/history/types.ts
features/omni-kit/protocols/ajna/components/details-section/AjnaLendingDetailsSectionContent.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataNetValueLending.tsx
features/omni-kit/protocols/ajna/helpers/getAjnaCumulatives.ts
features/subgraphLoader/consts.ts
features/subgraphLoader/types.ts
handlers/portfolio/positions/helpers/getHistoryData.ts

This pull request fixes the PnL data sources on earn positions and adds new ajna cumulative data sources to keep the interface in sync.

Fix PnL data sources,add new ajna cumulative data sources, refactor net value and pnl calculations

---

features/omni-kit/constants.ts
features/omni-kit/observables/estimateOmniGas.ts

- added handling for L1 fees when estimating gas on Base
- correct estimate values while performing ajna actions

Fix Ajna L1 gas fees

---

features/omni-kit/protocols/ajna/history/mapBorrowishEvents.ts
features/positionHistory/getHistoryEventLabel.ts

- Adjusted ajna history handling
- ajna multiply positions should display history records

Adjust ajna history handling

---

features/omni-kit/protocols/ajna/components/details-section/AjnaLendingDetailsSectionContent.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataNetValueLending.tsx
package.json
yarn.lock

This pull request updates the AjnaLendingDetailsSectionContent and useAjnaCardDataNetValueLending files. It removes unnecessary imports and refactors the cumulatives parameter in useAjnaCardDataNetValueLending.
Only merge after this is merged _and deployed_: https://github.com/OasisDEX/oasis-earn-sc/pull/556

Update AjnaLendingDetailsSectionContent and useAjnaCardDataNetValueLending

---

features/aave/manage/sidebars/SidebarManageAaveVault.tsx

Fix calculation of maximum collateral amount for eth group assets pair

Fix calculation of maximum collateral amount for eth group assets pair

---

blockchain/contracts/arbitrum.ts
blockchain/contracts/base.ts
blockchain/contracts/goerli.ts
blockchain/contracts/index.ts
blockchain/contracts/mainnet.ts
blockchain/contracts/optimism.ts
components/history/PositionHistory.tsx
components/history/PositionHistoryItem.tsx
features/dsr/containers/DsrHistory.tsx
features/omni-kit/controllers/OmniHistoryController.tsx
features/vaultHistory/VaultHistoryEntry.tsx
features/vaultHistory/VaultHistoryView.tsx
features/vaultHistory/vaultHistory.ts
features/vaultHistory/vaultHistory.types.ts
helpers/applicationLinks.ts
public/locales/cn/common.json
public/locales/en/common.json
public/locales/es/common.json

- removed ethtx support and ensured that link in history to etherscan is based on position network
- no ethtx link in positions history, link to etherscan based on position network

Remove ethtx and ensure that link is based on position network

---

features/aave/manage/sidebars/GetReviewingSidebarProps.tsx

Added validations to new secondary actions

Added validations to new secondary actions

---

features/web3OnBoard/init-web3-on-board.ts

This commit integrates dynamic wallet handling into the initialization of web3 onboarding. It leverages the local app config to determine which wallets should be initialised. This enhances scalability by allowing the addition or removal of wallets without altering the codebase, simply by modifying the app's configuration. It also refines type definitions by importing the WalletInit type.

Implement dynamic wallet configuration in web3 onboarding

---

features/aave/components/AaveMultiplyPositionData.tsx
features/aave/components/PositionInfoComponent.tsx

This pull request removes the pnl modal in the AaveMultiplyPositionData and PositionInfoComponent files.

Remove pnl modal in AaveMultiplyPositionData and PositionInfoComponent

---

public/locales/en/common.json

Added that the gas is not included in the calculations

Add to PnL copy

---

pages/_app.tsx

- moved adroll script out of head
- adroll should work

Adroll script adjust

---

package.json
yarn.lock

- fixed issue with liquidation price not being updated while doing multiply
- bumped lib version with fix for multiply fees
- on ajna multiply UI verify whether liquidation price is changing when moving slider
- fees should be taken while doing multiply adjust or close

Fix liquidation price when multiply and fees

---

package.json
yarn.lock

- Added yfi-dai mainnet pool
- yfi-dai pool accessible as curated pool on UI

Added yfi-dai mainnet pool

---

features/omni-kit/protocols/ajna/metadata/AjnaEarnSlider.tsx

- adjusted ajna earn slider step calculation
- user should be move slider dot from min all way to max without weird offsets
- slider dot should be align with slider colors

Adjust earn slider step

---

features/ajna/rewards/components/AjnaRewardCard.tsx
handlers/ajna-rewards/getAjnaRewardsData.ts

- adjusted filtering of ajna rewards based on chain id
- regular and bonus rewards should display properly

Ajna rewards chain id filtering adjust

---

features/ajna/rewards/components/AjnaRewardCard.tsx
public/locales/en/common.json

- Ajna card disclaimer update
- check if copy is correct

Ajna card disclaimer update

---

public/locales/en/common.json

- Update deposit fees copies
-  self explanatory

Update deposit fees copies

---

handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionDetails.ts
handlers/portfolio/types.ts
public/locales/en/portfolio.json

- Lending range portfolio labels adjust
-  self explanatory

Lending range portfolio labels adjust

---

components/RcSlider.tsx
components/dumb/SliderValuePicker.tsx
features/omni-kit/protocols/ajna/metadata/AjnaEarnSlider.tsx
package.json
yarn.lock

- added rc-slider component which has much better handling than theme-ui slider
- currently enabled for ajna earn form, should provide precise handling of slider values when adjusting lending price

Add rc-slider as optional component

---

helpers/applicationLinks.ts

The DS proxy link was linking to the wrong place

Update proxy link

---

features/omni-kit/protocols/ajna/components/details-section/modals/AjnaCardDataRewardsTooltip.tsx
features/omni-kit/protocols/ajna/components/details-section/modals/AjnaCardDataTotalAjnaRewardsModal.tsx

- adjusted rewards tooltip and modal to avoid showing negative values
- claimable next period should show correct value

Adjust rewards tooltip and modal

---

package.json
yarn.lock

- Morpho apy calcs
- correct apy on UI

Morpho apy calcs

---

features/omni-kit/protocols/ajna/helpers/getAjnaEarnData.ts

- Ajna take bucket with the highest lps
- on UI the buckets with the highest lps should be used for displaying position data

Ajna take bucket with the highest lps

---

features/omni-kit/controllers/borrow/OmniBorrowFormController.tsx
features/omni-kit/controllers/multiply/OmniMultiplyFormController.tsx
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
features/subgraphLoader/useSubgraphLoader.ts
pages/[networkOrProduct]/ajna/[...position].tsx

- turned safety switch on
- removed redirect
- removed possibility to change between borrow and multiply
- updated base subgraph url
To be updated
- safety switch on banners

Prepare old ajna base handling

---

handlers/portfolio/positions/handlers/aave-v2/ds-proxy-position.ts

- returns early if there is no subgraph history
context :
1. there is no subgrpah history because the position was created and closed on defisaver
2. there is 0 debt and 1 (!wei) collateral
- step 1 ...

fix: return early if no data

---

pages/[networkOrProduct]/ajna/[...position].tsx

- if position on base and ajna base set as false redirect to old ajna

Redirect to old ajna from base

---

package.json
yarn.lock

- bump lib version with update of liquidation price formula for morpho
- correct liquidation price on UI

Morpho liquidation price formula update

---

features/content/faqs/morphoblue/borrow/en.tsx
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
helpers/applicationLinks.ts

- added morpho blue borrow faq

Morpho Borrow FAQ

---

package.json
yarn.lock

- bumped lib with fix
- correct liquidation to markete price

Liquidation to market price fix

---

public/locales/en/common.json

Morpho copies update

---

features/omni-kit/components/OmniDupePositionModal.tsx
features/omni-kit/protocols/ajna/helpers/getMaxIncreasedOrDecreasedValue.ts

- Undo precision adjustment
- changed link do `a` to force app rerender

Undo precision adjustment

---

blockchain/better-calls/erc20.ts
features/omni-kit/protocols/ajna/hooks/useAjnaRedirect.ts

- fixed issue with redirect
- fixed issue with reading token precision
- ajna oracless earn UI should work

Earn oracless fix

---

handlers/portfolio/positions/helpers/getAllDpmsForWallet.ts
handlers/portfolio/positions/index.ts

- additional mapping was added to handle protocols per given position created events and dpms
- check linked story

Fix missing position

---

features/omni-kit/protocols/ajna/history/mapBorrowishEvents.ts
features/positionHistory/getHistoryEventLabel.ts

-  adjusted event kind
- deposit borrow , repay withdraw events should be visible in history

Ajna history event adjust

---

features/omni-kit/protocols/morpho-blue/helpers/getMorphoParameters.ts
package.json
yarn.lock

- fixed issue with lack of max ltv validation
- adjusted withdraw offset
- try to generate more than maximum, error should popup
- max withdraw should leave minimal amount of dust

Max ltv error morpho

---

handlers/portfolio/positions/helpers/getAllDpmsForWallet.ts

- Kuba fix addressed the issue of missing positions from dpm list https://github.com/OasisDEX/oasis-borrow/pull/3397/files
- This PR addresses the fact that the missing positions had the same coll/debt as the parent dpm rather than respecting the debt/coll from the create event
- Go here http://localhost:3000/ethereum/aave/v3/84#overview
- Go here http://localhost:3000/portfolio/0x0F8C58eDf65cbD972D175bFE481bc16fA8dEee45#positions and find the corresponding aave v3 #84 lending position and confirm correct token pair is shown

fix(dpm positions): ensure positions created from dpm createEvents have correct coll/debt tokens

---

features/ajna/rewards/components/AjnaRewardCard.tsx
public/locales/en/common.json

Remove rewards disclaimer

---

components/sidebar/SidebarSectionFooterButton.tsx

Like in title. Let's not speak about how it got there.

Remove red background from primary button in Omnikit

---

features/omni-kit/protocols/ajna/helpers/getAjnaParameters.ts
features/omni-kit/protocols/morpho-blue/helpers/getMorphoParameters.ts

- Dont use withdraw all offset when zero debt
- if position has 0 debt it should be possible to withdraw whole collateral

Dont use withdraw all offset when zero debt

---

features/omni-kit/components/OmniValidationWithLink.tsx

- Lower than validation adjust
- warning messages should display correctly

Lower than validation adjust

---

features/subgraphLoader/consts.ts
handlers/portfolio/positions/handlers/morpho-blue/helpers/getMorphoPositionInfo.ts
handlers/portfolio/positions/handlers/morpho-blue/index.ts
handlers/portfolio/positions/handlers/morpho-blue/types.ts

- fixed issue with subgraph query
- check story description

Morpho portfolio bug fix

---

handlers/portfolio/positions/helpers/getAllDpmsForWallet.ts

- Dpm list mapping in portfolio adjustment
- all user positions should be visible in portfolio and mapped to correct type

Dpm list mapping in portfolio adjustment

---

package.json
yarn.lock

- Bumped dma lib 0.6.11
- when withdrawing more than user have in morpho position, error should popup

Bump dma lib 0.6.11

---

handlers/portfolio/positions/handlers/ajna/helpers/getAjnaPositionInfo.ts
handlers/portfolio/positions/helpers/getBorrowishPositionType.ts
handlers/portfolio/positions/helpers/getDefaultBorrowishPositionType.ts

- position type in portfolio should always reflect current position type (when you visit position)
- `/portfolio/0x0F8C58eDf65cbD972D175bFE481bc16fA8dEee45#positions` Ajna positions with id 84 should be multiply

Fix issue with incorrect Ajna position type in portfolio

---

features/ajna/rewards/helpers/getAjnaRewards.ts
features/ajna/rewards/hooks/useAjnaRewards.ts

- always check cliamed weeks on mainnet as we only distribute ona mainnet.
- It caused different reward amounts beinging shown  between base and mainnet
- step 1 ...

fix: fix claimed amounts

---

public/locales/en/common.json

Update morpho blue description

---

features/web3OnBoard/init-web3-on-board.ts

This pull request refactors the initialization and configuration of web3OnBoard. It includes changes to the mapNetwork and getChains functions, as well as updates to the getWallets function.
Loads RPC url from the config with some hardcoded fallback.

Refactor web3OnBoard initialization and configuration

---

package.json
yarn.lock

- Bumped dma lib 0.6.12 which bring back multiply fees to ajna actions
- ajna multiply actions should charge fees

Bump dma lib 0.6.12

---

blockchain/better-calls/dpm-account.ts
features/aave/components/banners/index.ts
features/aave/components/banners/stop-loss-banner.tsx
features/aave/hooks/useProtectionSidebarDropdown.tsx
features/aave/manage/containers/AaveManageTabBar.tsx
features/aave/manage/containers/ProtectionControlWrapper.tsx
features/aave/manage/contexts/triggers-aave-state-machine-context.tsx
features/aave/manage/state/triggersAaveStateMachine.ts
helpers/isAnyValueDefined.ts
public/locales/en/common.json

- Fix perfmormnace issue with auto sell
- New protection view and logic for aave

Fix performance issue with Aave Basic Sell

---

components/vault/VaultHeadline.tsx
features/aave/components/AaveHeader.tsx
features/aave/manage/containers/AaveManageView.tsx
features/aave/types/strategy-config.ts
public/locales/en/common.json

Current LTV in Aave manage position header

---

features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataAvailableToWithdrawEarn.tsx

Fix available to withdraw earn ajna copy

---

components/ComparisionTable.tsx
components/ComparisonTable.tsx
features/marketing-layouts/components/MarketingTemplateMarkdown.tsx
features/marketing-layouts/types.ts
features/marketing-layouts/views/MarketingTemplateBlockView.tsx
pages/better-on-summer/[...slug].tsx

- Created `ComparisonTable` component.
- Added `ComparisonTable` as a possible component to be used in `MarketingTemplateProductFinderBlocks`.

UI component: ComparisonTable

---

public/locales/en/common.json

Update buy and sell messages to use "Auto" instead of "Basic"

Update buy and sell messages to use "Auto" instead of "Basic"

---

components/ComparisonTable.tsx
features/productHub/hooks/useProductHubRouter.tsx

- Fixed an issue with Product Hub where filters weren't kept when product was changed in natural language selector.
- Added missing keys in `ComparisonTable` and `MarketingTemplateHero`.

Landing Page templates minor bugfixes

---

features/omni-kit/protocols/ajna/helpers/isPoolWithRewards.ts

- Added `AJNA-DAI`, `STYETH-DAI` and `YFI-DAI` to list of pools supporting rewards on Ethereum mainnet.

Update list of pools with rewards

---

contentful/api.ts
contentful/mappers/mapCommonBlockProperties.ts
contentful/mappers/mapLandingInfoBlock.ts
contentful/mappers/mapLandingPageBannerBlock.ts
contentful/mappers/mapLandingPageBenefitBlock.ts
contentful/mappers/mapLandingPageProductBlock.ts
contentful/queries/getEntryCollection.ts
contentful/queries/getLandingPageBySlug.ts
contentful/types/blocksCollection.ts
contentful/types/rawResponses.ts
features/marketing-layouts/components/MarketingTemplateMarkdown.tsx
features/marketing-layouts/types.ts
package.json
pages/better-on-summer/[...slug].tsx
yarn.lock

- Fixed entire mechanism related to loading content with `preview` flag.
- Added native Contentful renderer for rich text using `@contentful/rich-text-react-renderer`.
- Removed `react-markdown`.
- Added support for SEO tags in Landing Page.
- Fixed an issue with title displayed as subtitle.

Landing Page templates major & minor updates

---

.github/workflows/aws-staging.yaml
blockchain/networks/get-rpc-provider.ts
blockchain/networks/network-helpers.ts
blockchain/networks/networks-config.ts
contentful/api.ts
next-i18next.config.js
server/prisma.ts

- Set `NODE_ENV` to `staging` in `aws-staging.yaml`.
- Did couple adjustment in files using `NODE_ENV` value so everything that suppose to happen on staging is still happening on that environment.

Set NODE_ENV on staging to `staging`

---

.github/workflows/aws-staging.yaml
blockchain/networks/get-rpc-provider.ts
blockchain/networks/network-helpers.ts
blockchain/networks/networks-config.ts
contentful/api.ts
next-i18next.config.js
server/prisma.ts

Reverts OasisDEX/oasis-borrow#3480

Revert "Set NODE_ENV on staging to `staging`"

---

contentful/api.ts
contentful/queries/getEntryCollection.ts
contentful/queries/getLandingPageBySlug.ts
pages/better-on-summer/[...slug].tsx

- Added handling for `/preview` in URL for page preview handling.

Preview parameter in Landing Pages

---

features/omni-kit/protocols/ajna/helpers/getAjnaBorrowDebtMin.ts

- no `From xxx` over generate input when number of loans below 10

Ajna debt min method fix

---

components/portfolio/positions/PortfolioPositionBlock.tsx

Fixed portfolio styles issue

---

components/portfolio/positions/PortfolioPositionBlock.tsx
components/portfolio/positions/PortfolioPositionBlockDetail.tsx
features/migrations/migrationsClient.ts
handlers/portfolio/types.ts
public/locales/en/portfolio.json

Fixed reported issues: incorrect spark styles and tooltips messasges

Fixed reported issues styles and tooltips

---

handlers/portfolio/positions/handlers/aave-like/helpers.ts
handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/helpers/getAutomationData.ts
handlers/portfolio/positions/helpers/getPositionsAutomations.ts
package.json
yarn.lock

Portfolio: load automation on L2s

Update Aave-like helpers and automation data retrieval

---

handlers/portfolio/positions/handlers/morpho-blue/helpers/getMorphoPositionDetails.ts

- added multiply case in morpho handler
- morpho multiply position with values in portfolio

Morpho multiply portfolio

---

features/content/faqs/morphoblue/multiply/en.tsx
package.json
yarn.lock

- bumped lib version with correlated position logic update
- fixed typo in faq
- no fees on yield loop positions in ajna & morpho

Correlated position logic update

---

features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx

- added additional check to withFees flag
- while doing actions on correlated position in morpho or ajna, no summer fees should be in order informations

Multiply form order summer fee handling

---

components/assetsTable/cellComponents/AssetsTableDataCellAsset.tsx
components/portfolio/positions/PortfolioPositionBlock.tsx
components/portfolio/positions/PortfolioPositionsView.tsx

This pull request includes a code refactor and a fix for a rendering issue that was causing undefined values to be displayed.

Refactor code and fix rendering issue

---

contentful/mappers/mapLandingPageProductBlock.ts
contentful/mappers/mapLandingProductFinderBlock.ts
features/marketing-layouts/components/MarketingTemplateProductBox.tsx

- Fixed issues where gql data were mapped to `null` instead `undefined`.
- Fixed a bug with `MarketingTemplateProductBox` where in some configuration flex position was incorrect.

Landing Page templates minor bugfixex last part

---

components/ComparisonTable.tsx
contentful/mappers/mapLandingPageComparisonTableBlock.ts
contentful/mappers/mapLandingPageProductBlock.ts
contentful/queries/getLandingPageContentByIds.ts
contentful/types/rawResponses.ts
features/marketing-layouts/components/MarketingTemplateProductBox.tsx
features/marketing-layouts/types.ts
features/marketing-layouts/views/MarketingTemplateBlockView.tsx

- Added an option to `ComparisonTable` to highlight selected column.
- Updated content structure of `MarketingTemplateProductBox` (more optional files, additional content image and some type fixes).

Post release Landing Page component updates

---

components/ComparisonTable.tsx
features/marketing-layouts/views/MarketingTemplateBlockView.tsx

- Fix an issue with placement of border below comparison table header,
- Fix an issue with generating grid for `MarketingTemplateBlockView` component.

Fix grids on Landing Page

---

features/positionHistory/getHistoryEventLabel.ts

add more missing `AAVEv3` labels
- step 1 ...

chore: missing labels - part 2

---

features/aave/strategies/ethereum-spark-v3-strategies.ts

- updated spark yield loop strategies with default slippage
- all yield loop strategies should have default slippage in place

Update spark yield loop default slippage

---

public/locales/en/common.json
public/locales/es/common.json
public/locales/pt/common.json

- changed Current yield to APY

Unify APY terminology

---

features/aave/components/AavePositionHeader.tsx
lendingProtocols/aave-like-common/yields/index.ts
lendingProtocols/aave-v3/pipelines/prepare-aave-total-value-locked.ts

-Aave TVL and APY fix in yield loop earn positions
- both APY and TVL in position header should be correct

Aave TVL and APY fix

---

components/portfolio/positions/PortfolioPositionBlockLendingRangeDetail.tsx
handlers/portfolio/positions/index.ts

Fixed label of lending state in portfolio for Earn LP positions

---

features/omni-kit/protocols/ajna/helpers/getAjnaEarnWithdrawMax.ts

- added negative to zero handler
- ajna earn max withdraw in overview footer can't be negative

Ajna earn withdraw max negative to zero

---

features/aave/components/AaveStopLossManageDetails.tsx
features/aave/manage/containers/ProtectionControlWrapper.tsx
features/aave/manage/helpers/map-stop-loss-from-lambda.ts
features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx
features/aave/open/helpers/use-lambda-debounced-stop-loss.ts
features/aave/open/sidebars/components/SidebarOpenAaveVaultStopLoss.tsx
helpers/triggers/common/types.ts
helpers/triggers/get-triggers/get-triggers-request.ts
helpers/triggers/get-triggers/get-triggers-types.ts
helpers/triggers/get-triggers/index.ts
helpers/triggers/get-triggers/use-get-triggers.ts
helpers/triggers/setup-triggers/get-setup-trigger-config.ts
helpers/triggers/setup-triggers/setup-aave-stop-loss.ts
helpers/triggers/setup-triggers/setup-triggers-types.ts

This pull request refactors the Aave stop loss functionality to support the Spark protocol. It includes changes to several files to update the protocol references and add support for the SparkV3 protocol.

Refactor Aave stop loss functionality to support spark

---

features/aave/manage/sidebars/migration/MigrateWelcomeStateView.tsx
features/aave/manage/sidebars/migration/StartMigrateStateView.tsx
features/aave/open/state/openAaveStateMachine.ts
helpers/getAaveLikeStrategyUrl.ts
pages/[networkOrProduct]/aave/[version]/[vault].tsx
pages/[networkOrProduct]/aave/[version]/migrate/[address]/index.tsx
public/locales/en/common.json

Added MigrateWelcomeStateView (not final)

Semi done MigrateWelcomeStateView

---

features/ajna/rewards/hooks/useAjnaRewards.ts
features/ajna/rewards/types.ts
features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterBorrow.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterEarnManage.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterMultiply.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaEarnDetailsSectionFooter.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataBorrowRate.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataProjectedAnnualRewards.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataTotalAjnaRewards.tsx
handlers/ajna-rewards/getAjnaRewardsData.ts
pages/ajna/rewards.tsx
public/locales/en/common.json

- added ajna rewards yield cals
- rewards in position view are per specific position, not total per owner
- self explanatory, check story description

Ajna rewards yield calcs

---

contentful/queries/getLandingPageBySlug.ts
contentful/types/rawResponses.ts
features/marketing-layouts/helpers/getMarketingTemplatePageProps.ts
features/marketing-layouts/types.ts
pages/better-on-summer/[...slug].tsx

Add SEO Open Graph image to landing page and marketing templates.

Add SEO Open Graph image to landing page and marketing templates

---

features/omni-kit/protocols/ajna/actions/borrow.ts
features/omni-kit/protocols/ajna/helpers/getAjnaParameters.ts
features/omni-kit/protocols/ajna/helpers/getAjnaPositionAggregatedData.ts
features/omni-kit/protocols/ajna/history/ajnaDefaultHistoryEvent.ts
features/omni-kit/protocols/ajna/history/mapAjnaLendingEvents.ts
features/omni-kit/protocols/ajna/history/types.ts
features/omni-kit/protocols/ajna/hooks/useAjnaTxHandler.ts
features/subgraphLoader/consts.ts
package.json
yarn.lock

- changed re-stamping condition to use interest rates
- bumped lib version with update of netural price handling
- re-stamp should happen only if its in user's interest
- correct simulation of borrow position actions

Update neutral price handling & re-stamp

---

features/stateMachines/allowance/AllowanceView.tsx
features/stateMachines/allowance/state/createAllowanceStateMachine.ts

ResolvingToken in AllowanceView

ResolvingToken in AllowanceView

---

features/ajna/rewards/hooks/useAjnaRewards.ts
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataBorrowRate.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataProjectedAnnualRewards.tsx
features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataTotalAjnaRewards.tsx
handlers/ajna-rewards/getAjnaRewardsData.ts
public/locales/en/common.json

- split rewards per position type
- improved getting last day rewards 
- ajna borrow & earn position on the same pool should show rewards per position type

Split rewards per position type

---

features/aave/manage/containers/ProtectionControlWrapper.tsx

Disables the new stop loss on existing stop loss positions (so only feature toggle enables it)

Disables the new stop loss on existing stop loss positions

---

package.json
yarn.lock

- updated lib to the newest version
- try to connect hardware wallet using wallet connect, no issue expected

Wallet connect lib update

---

package.json
yarn.lock

This reverts commit 64d726542960d24d3a5624e740deb3024de212b6.
- reverted package bump since it's still not working
- wallet connect modal should work

Revert "Wallet connect lib update (#3549)"

---

features/aave/manage/helpers/use-automation-primary-button.ts
features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx
features/aave/manage/sidebars/AutoBuySidebarAaveVault.tsx
features/aave/manage/sidebars/AutoSellSidebarAaveVault.tsx

- Add/Refactor protection information to AaveManagePositionStopLossLambdaSidebar
- Add useAutomationPrimaryButton helper function
- Refactor code to improve performance and readability

Refactor new protection information sidebar

---

helpers/getTokenDisplayName.ts

- temporary mapped MKR symbol which is address to `MKR`
- MKR pools should be recognized as standard pool with oracle

MKR temporary symbol mapping

---

features/aave/components/AaveMultiplyPositionData.tsx
features/omni-kit/protocols/aave/components/details-sections/parsers/index.ts
features/omni-kit/protocols/aave/components/details-sections/parsers/useAaveCardDataNetValueLending.tsx

- Bring back aave and spark pnl which was removed by accident while doing refactor
- working PnL in aave & spark multiply overview section

Bring back aave and spark pnl

---

components/rewards/RewardsModal.tsx

- adjusted styles so text is displayed on mobile in line instead of 3x separate blocks

Adjust rewards modal mobile styles

---

features/ajna/rewards/components/AjnaRewardCard.tsx

- Adjusted rewards card mobile styles

Adjust rewards card mobile styles

---

features/omni-kit/protocols/ajna/components/details-section/parsers/useAjnaCardDataProjectedAnnualRewards.tsx

- fixed issue where Anul rewards where displayed as NaN on empty position

Annual reward ajna NaN fix

---

features/aave/services/calculate-view-values-for-position.tsx

- fixed aave borrow rate nan in portfolio
- empty borrow aave position in portfolio shouldn't show borrow rate as NaN

Fix aave borrow rate nan in portfolio

---

features/subgraphLoader/consts.ts
handlers/portfolio/positions/handlers/morpho-blue/helpers/getMorphoPositionDetails.ts
handlers/portfolio/positions/handlers/morpho-blue/index.ts
handlers/portfolio/positions/handlers/morpho-blue/types.ts

- Fixed morpho blue NaN max ltv in portfolio

Fix morpho blue NaN max ltv in portfolio

---

components/vault/ProtectionControl.tsx
features/aave/hooks/useMinNetValue.ts
features/aave/manage/containers/ProtectionControlWrapper.tsx
features/automation/protection/common/controls/ProtectionDetailsControl.tsx
features/automation/protection/common/controls/ProtectionFormControl.tsx

This pull request refactors the AaveV3 and SparkV3 protection control banners to improve code readability and maintainability. It includes changes to the ProtectionControl, useMinNetValue, ProtectionControlWrapper, ProtectionDetailsControl, and ProtectionFormControl components.

Refactor AaveV3 and SparkV3 protection control banners

---

features/aave/components/AaveBorrowPositionData.tsx
features/aave/components/AaveMultiplyPositionData.tsx
features/aave/components/order-information/OpenAaveStopLossInformationLambda.tsx

Removed trigger machine usage on open aave/spark (prod bug)

Removed trigger machine usage on open aave/spark

---

components/vault/VaultErrors.tsx
features/aave/helpers/mapErrorsToErrorVaults.tsx
features/form/errorMessagesHandler.ts
helpers/triggers/setup-triggers/setup-triggers-types.ts
public/locales/en/common.json

Auto Sell / Auto Buy / Stop Loss cross validations

Auto Sell / Auto Buy / Stop Loss cross validations

---

features/positionHistory/getHistoryEventLabel.ts
public/locales/en/common.json

- handle trailing sl position history labels
- try `http://localhost:3000/arbitrum/aave/v3/188#history`

feat: add trailing sl handling

---

features/productHub/hooks/useProductHubBanner.tsx

- check feature toggle before displaying migrations banner

Migration banner feature toggle usage

---

features/aave/manage/state/migrateAaveStateMachine.ts
features/aave/setup-spark-v3-context.ts
features/stateMachines/allowance/AllowanceView.tsx
features/stateMachines/allowance/state/createAllowanceStateMachine.ts

- Display External Spark Position
- Allowance amount always with decimal places
- Take the allowance for migration up to protocol token balance

Migrations issue

---

features/aave/hooks/useOptimizationSidebarDropdown.tsx
features/aave/manage/helpers/map-trailing-stop-loss-from-lambda.ts
features/aave/manage/state/getBasicAutomationAaveStateMachine.ts
features/aave/manage/state/triggersAaveStateMachine.ts
helpers/triggers/get-triggers/get-triggers-types.ts
helpers/triggers/setup-triggers/setup-triggers-types.ts

Add missing support for Spark trailing stop loss

---

features/aave/components/LackOfFlashloanLiquidityModal.tsx
features/aave/components/order-information/FlashLoanInformation.tsx
features/aave/manage/sidebars/migration/MigrateWelcomeStateView.tsx
features/aave/manage/sidebars/migration/index.tsx
features/aave/manage/state/migrateAaveStateMachine.ts
features/web3OnBoard/injected-wallet-interactions.ts
helpers/hooks/useBalancerLiquidity.ts
public/locales/en/common.json

- Nice network name when you are adding dev-net instead of fork 
- Copy for migartions
- Modal about lack of liquidity on Balancer (used in migration)

Migration - Copy Update & Flashloan Liquidity Modal

---

handlers/portfolio/positions/handlers/aave-like/helpers.ts
handlers/portfolio/positions/helpers/getPositionsAutomations.ts
package.json
yarn.lock

Update trigger types in portfolio

---

blockchain/tokens/arbitrum.ts
blockchain/tokens/optimism.ts

- add eth actual config to arb and optm

Add eth actual to arb and otp

---

components/vault/VaultActionInput.tsx
components/vault/sidebar/SidebarFields.tsx
features/omni-kit/components/sidebars/OmniFormFields.tsx

Updating 'Payback' to 'Pay back'

---

features/omni-kit/protocols/morpho-blue/settings.ts
package.json
yarn.lock

- add `ezEth-eth` market to morpho
- add `ezEth` to the list of `eth` correlated assets
- step 1 ...

feat: add `EZETH-ETH` to morpho-blue

---

features/aave/components/AaveBorrowPositionData.tsx
features/aave/components/AaveMultiplyPositionData.tsx
features/aave/components/CostToBorrowContentCard.tsx

- fixed issue  with wrong denomination
- cost to borrow in aave-like positions denominated in debt token

Fix aave cost to borrow

---

features/omni-kit/protocols/morpho-blue/settings.ts

- add `EZETH`  to multiply supported tokens
- step 1 ...

chore: add missing markets

---

features/positionHistory/getHistoryEventLabel.ts

- add missing history labels
go to : http://localhost:3000/arbitrum/aave/v3/157#history
and check top 3 items

fix: add missing history items labels

---

features/omni-kit/controllers/OmniLayoutController.tsx

- fixed condition
- current price visible in postion heading

Bring back missing current price

---

features/aave/components/AavePartialTakeProfitManageDetails.tsx
features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx
features/aave/manage/sidebars/AaveManagePositionTrailingStopLossLambdaSidebar.tsx

This PR fixes the calculation in the code and adds the useInterval hook for refreshing trigger data.

Partial take profit fixes [pt.6]

---

features/aave/components/AavePartialTakeProfitManageDetails.tsx
features/aave/manage/containers/OptimizationControl.tsx
features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx

This pull request adds a simple view option to the AavePartialTakeProfitManageDetails component. It also updates the slider step in the AaveManagePositionStopLossLambdaSidebar.tsx file.

Add simple view option to AavePartialTakeProfitManageDetails component

---

features/aave/manage/sidebars/AaveManagePositionPartialTakeProfitLambdaSidebar.tsx
features/aave/manage/sidebars/AaveManagePositionStopLossLambdaSidebar.tsx
features/aave/manage/sidebars/AaveManagePositionTrailingStopLossLambdaSidebar.tsx

Add getLocalAppConfig on the lambda enabled sidebars import and use it to disable validation

Add getLocalAppConfig import and use it to disable validation

---

components/history/PositionHistoryItemDetails.tsx

- handle `AutomationUpdated` event as autoamtion event
- step 1 ...

chore: add `AutomationUpdated`

---

features/positionHistory/getHistoryEventLabel.ts

- add ahandling for `AAVEV3Withdraw` events
- step 1 ...

chore: add missing `AAVEV3Withdraw` history label

---

components/DetailsSection.tsx
features/omni-kit/automation/components/OmniAutoBSOverviewDetailsSection.tsx
features/omni-kit/automation/components/OmniStopLossOverviewDetailsSection.tsx
features/omni-kit/automation/components/OmniTrailingStopLossOverviewDetailsSection.tsx
features/omni-kit/controllers/OmniProtectionOverviewController.tsx

- Add order to Protection details elements

Add order to Protection details elements

---

features/aave/components/AavePartialTakeProfitManageDetails.tsx
features/aave/hooks/useOptimizationSidebarDropdown.tsx
features/aave/services/get-aave-history-events.ts
features/positionHistory/types.ts
features/subgraphLoader/consts.ts
public/static/img/take-profit-chart-ltv.svg

- Small refactor of a dropdown config in optimization tab (use feature flags)
- Profit realized to wallet uses different, more accurate field from history subgraph

Partial take profit fixes [pt.11]

---

handlers/portfolio/positions/helpers/getAutomationData.ts
handlers/portfolio/positions/helpers/getPositionsAutomations.ts

This pull request refactors the portfolio automation handling logic so we display executed recurring triggers.

Refactor automation triggers filtering logic

---

pages/api/gasPrice/index.ts

HOTFIX: Add gasApiKey header to API request

HOTFIX: Add gasApiKey header to API request

---

pages/api/gasPrice/index.ts

Add gasApiKey header to API request

Add gasApiKey header to API request

---

components/constants.ts
server/services/susdeOracle.ts
server/services/usdeOracle.ts

- fixed precisions
- correct precisions

Fix susde and usde oracles

---

features/omni-kit/protocols/erc-4626/components/details-section/Erc4626DetailsSectionContent.tsx
features/omni-kit/protocols/erc-4626/helpers/getErc4626ApyParameters.ts
features/omni-kit/protocols/erc-4626/hooks/index.ts
features/omni-kit/protocols/erc-4626/hooks/useErc4626ApySimulation.ts

- Integrated token market cap selector into simulation calculations.
- Created `useErc4626ApySimulation` hook to calculate APY simulation on the front-end.

ERC-4626 position local simulation calculations

---

features/omni-kit/protocols/erc-4626/hooks/useErc4626ApySimulation.ts

- Fix issue with `depositAmount` not refreshing simulation

Fix issue with `depositAmount` not refreshing simulation

---

components/vault/VaultHeadlineDetails.tsx
features/omni-kit/protocols/erc-4626/components/Erc4626HeadlineApy.tsx
features/omni-kit/protocols/erc-4626/components/index.ts
features/omni-kit/protocols/erc-4626/hooks/useErc4626ApySimulation.ts
features/omni-kit/protocols/erc-4626/metadata/useErc4626Metadata.tsx

- Integrated headline APY with estimated reward token price.

ERC-4626 headline APY simulation

---

package.json
yarn.lock

chore: bump `@oasisdex/automation@1.6.5`

---

features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterEarnOpen.tsx
features/omni-kit/protocols/ajna/helpers/getAjnaPoolData.ts
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
features/subgraphLoader/consts.ts
package.json
yarn.lock

- go to : http://localhost:3000/ethereum/ajna/earn/SUSDE-DAI#setup

fix: 7 day averagy apy - ajna earn

---

features/omni-kit/protocols/erc-4626/hooks/useErc4626ApySimulation.ts

Fixed loader issue in ERC-4626 APY calculation

---

features/omni-kit/protocols/erc-4626/settings.ts

Remove WBTC ERC-4626 vault from config

---

package.json
yarn.lock

chore: bump library `@oasisdex/dma-library@0.6.49`

---

features/refinance/components/RefinanceHeader.tsx
features/refinance/components/RefinanceModal.tsx
features/refinance/components/index.ts
public/locales/en/common.json

- added simple refinance modal component to be able to simulate actual refinance UI env
- added modal header component with dummy data for now
- nothing to test at this moment

Refinance modal and modal header components

---

components/AutomationIcon.tsx
components/infoSection/InfoSection.tsx
components/infoSection/Item.tsx
components/infoSection/ItemValueWithIcon.tsx
components/portfolio/positions/PortfolioPositionAutomationIcons.tsx
features/refinance/components/RefinanceAutomationSection.tsx
features/refinance/components/RefinanceHeader.tsx
features/refinance/components/RefinanceModal.tsx
features/refinance/components/RefinancePositionView.tsx
features/refinance/components/index.ts
features/refinance/types.ts
pages/[networkOrProduct]/maker/[vault]/index.tsx
public/locales/en/common.json

This PR covers also following story:
https://app.shortcut.com/oazo-apps/story/14258/automation-section-component
- added refinance position view component
- nothing to test currently

Refinance position view

---

features/omni-kit/automation/hooks/useOmniStopLossDataHandler.tsx
features/productHub/helpers/getActionUrl.ts
handlers/portfolio/positions/handlers/aave-like/helpers.ts
handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/aave-like/types.ts
handlers/portfolio/positions/index.ts
handlers/portfolio/types.ts
helpers/clients/portfolio-client.ts
package.json

- fixes stop loss level calculation
- adds UseOmniKitLinks feature toggle, changes the portfolio and product links for aave/spark to use omni kit

Fix stopLossLevel calculation and add useOmniKitLinks parameter

---

features/omni-kit/observables/omniExchangeQuote.ts
features/omni-kit/protocols/aave-like/metadata/useAaveLikeMetadata.tsx
helpers/triggers/get-triggers/get-triggers-request.ts

Aave/Spark + Omni kit - Fix price impact

---

components/InfoSectionWithGradient.tsx
components/infoSection/Item.tsx
components/sidebar/SidebarSection.tsx
features/refinance/components/RefinanceAbout.tsx
features/refinance/components/RefinanceCardWrapper.tsx
features/refinance/components/RefinanceModal.tsx
features/refinance/components/steps/RefinanceHighlightedChangeSection.tsx
features/refinance/components/steps/RefinanceReviewChangesSection.tsx
features/refinance/components/steps/RefinanceRouteSection.tsx
features/refinance/components/steps/RefinanceStrategyStep.tsx
features/refinance/components/steps/RefinanceSwapSection.tsx
features/refinance/components/steps/RefinanceTransactionStep.tsx
features/refinance/components/steps/RefinanceWhatsChangingStep.tsx
features/refinance/components/steps/index.ts
features/refinance/controllers/RefinanceFormController.tsx
features/refinance/types.ts
features/refinance/views/RefinanceFormView.tsx
features/refinance/views/index.ts
public/locales/en/common.json
public/static/img/refinance-tx.svg

This one covers also following stories
- https://app.shortcut.com/oazo-apps/story/14255/highlighted-change-banner-component
- https://app.shortcut.com/oazo-apps/story/14257/swap-route-details-component
- added 3 out of 4 steps components with dummy data
- nothing to test currently

Refinance sidebar steps

---

features/omni-kit/contexts/OmniGeneralContext.tsx
features/refinance/RefinanceContext.tsx
features/refinance/components/RefinanceModal.tsx
features/refinance/components/RefinanceSimulation.tsx
features/refinance/controllers/ChangeOwnerSidebar.tsx
features/refinance/controllers/index.ts
features/refinance/types.ts
features/refinance/views/RefinanceFormView.tsx

- added dummy allowance step UI with basic config
- added tx manager to refinance context
- nothing to test now

Init allowance and tx manager

---

features/aave/aave-context-provider.tsx

Fix aave on forks

---

features/aave/helpers/getEmptyAaveLikePosition.ts
features/aave/open/containers/AaveOpenStateMachineContext.tsx
features/omni-kit/helpers/getOmniPositionUrl.ts
features/omni-kit/helpers/useOmniLendingValidations.tsx
features/omni-kit/protocols/aave-like/helpers/getAaveLikeParameters.ts

This pull request includes refactoring of the AaveOpenStateMachineContext and getOmniPositionUrl functions. The changes improve code readability and maintainability.

Refactor AaveOpenStateMachineContext and getOmniPositionUrl

---

features/omni-kit/helpers/getOmniNetValuePnlData.ts

This pull request refactors the getOmniNetValuePnlData.ts file to improve the accuracy of calculations. The changes include updating the calculation of pnlPercentageUsd and inUsd variables.

Refactor getOmniNetValuePnlData.ts to improve calculation accuracy

---

package.json
yarn.lock

- fix close to collateral for all protocols
- step 1 ...

chore: bump dma-library / fix close to collateral

---

package.json
yarn.lock

Reverts OasisDEX/oasis-borrow#3772

Revert "chore: bump dma-library / fix close to collateral"

---

features/productHub/meta.ts
handlers/product-hub/helpers/get-token-group.ts

Added susde token group to allow filtering on usde too.

added susde token group

---

package.json

This pull request updates the @oasisdex/addresses package to version 0.1.58.

Update @oasisdex/addresses to version 0.1.58

---

package.json
yarn.lock

chore: bump `dma-library` -  fix close to collateral #2

---

features/aave/components/ErrorMessageCannotDepositDueToProtocolCap.tsx

- Disable/Comment out supply cap validation
- Should be able to withdraw or payback debt for this position https://summer.fi/ethereum/spark/borrow/WBTC-DAI/1784#overview

fix: comment out supply cap warning

---

features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx

Story details: https://app.shortcut.com/oazo-apps/story/15139

fix: [sc-15139] [BUG] - Wrong SummerFi on Spark Postions

---

features/refinance/components/RefinanceHeader.tsx
features/refinance/components/RefinanceModal.tsx
public/locales/en/common.json

- added simple condition to disable refinance ui on mobile
- on mobile info that refinance is available only on desktop

Refinance not available on mobile

---

features/omni-kit/helpers/getOmniValidations.ts
package.json
yarn.lock

This pull request updates the @oasisdex/dma-library package to version 0.6.52 and reverts the weekend change (its now fixed in the lib).

Update @oasisdex/dma-library to version 0.6.52

---

features/omni-kit/observables/getPositionFromUrlParams.ts
features/omni-kit/protocols/morpho-blue/helpers/getMorphoPositionWithPairId.ts

- Morpho fixed issue with overwriting market it

Morpho fix issue with overwriting market it

---

features/omni-kit/protocols/aave-like/helpers/aaveLikeFlowStateFilter.ts
features/omni-kit/protocols/aave-like/metadata/useAaveLikeMetadata.tsx

This pull request adds a new optional parameter, positionTriggers, to the aaveLikeFlowStateFilter function in the aaveLikeFlowStateFilter.ts file. The positionTriggers parameter allows for more flexibility in filtering flow states based on triggers.

Add positionTriggers parameter to aaveLikeFlowStateFilter function

---

components/portfolio/PortfolioOverview.tsx

- fixed migration link in portfolio
- migration link in portfolio header should work as expected

Fix migration link in portfolio

---

package.json
yarn.lock

Reverts OasisDEX/oasis-borrow#3802

Revert "Update lifi packages + lock viem version"

---

package.json
yarn.lock

🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡 🤡

Revert "Revert "Update lifi packages + lock viem version""

---

features/productHub/meta.ts
helpers/applicationLinks.ts

Fix Product Hub help links

---

features/refinance/helpers/getRefinanceAaveLikeInterestRates.ts

- refinance fix temporarly issue with subgraph query by not asking for interest rates for aave and different networks
- refinance UI should load

Refinance fix temporarly issue with subgraph query

---

features/refinance/components/RefinancePortfolioBanner.tsx
features/refinance/components/steps/RefinanceProductTableStep.tsx
features/refinance/contexts/RefinanceContext.tsx
features/refinance/contexts/RefinanceGeneralContext.tsx
features/refinance/controllers/RefinanceModalController.tsx
features/refinance/helpers/getRefinanceContextInput.ts
features/refinance/helpers/getRefinanceProductHubDataParser.ts
features/refinance/hooks/useInitializeRefinanceContext.ts
features/refinance/hooks/useRefinanceTxHandler.ts
features/refinance/hooks/useSdkSimulation.tsx
features/refinance/hooks/useSdkTransaction.tsx
features/refinance/hooks/useSimulationPositionData.tsx
public/locales/en/common.json

- added market prices to the context
- it should be possible to get market prices per given tokens

Refinance provide market prices

---

features/aave/components/SimulateSectionComponent.tsx
features/omni-kit/components/details-section/OmniOpenYieldLoopDetails.tsx
features/omni-kit/components/details-section/OmniOpenYieldLoopSimulation.tsx
features/omni-kit/controllers/OmniOverviewController.tsx
features/omni-kit/hooks/useOmniSidebarTitle.tsx
features/omni-kit/protocols/aave-like/metadata/useAaveLikeMetadata.tsx
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
features/omni-kit/protocols/morpho-blue/settings.ts

Fix yield loop simulation calculations

Fix yield loop simulation calculations

---

features/omni-kit/components/details-section/OmniOpenYieldLoopFooter.tsx
features/omni-kit/helpers/calculateOmniYieldsSimulation.ts
features/omni-kit/hooks/useOmniEarnYields.ts
features/omni-kit/hooks/useOmniSimulationYields.ts
helpers/lambda/yields/get-yields-types.ts

- Use 1d as currentApy
- Block yield calls on Borrow

Yield loop fixes #2

---

features/refinance/components/steps/RefinanceReviewChangesSection.tsx
public/locales/en/common.json

- fixed automation status change in order information
- correct automation status in order information

Refinance automation status fix

---

blockchain/prices.constants.ts
features/refinance/helpers/getRefinanceProductHubDataParser.ts

- added ph items filter based on available liquidity
- no positions with liquidity less than 5% more than outstanding debt should be surfaced

Refinance PH available liquidity filter

---

features/aave/strategies/ethereum-aave-v3-strategies.ts
features/aave/strategies/optimism-aave-v3-strategies.ts
features/omni-kit/components/details-section/OmniOpenYieldLoopDetails.tsx
features/omni-kit/constants.ts
features/omni-kit/protocols/ajna/metadata/useAjnaMetadata.tsx
handlers/product-hub/update-handlers/ajna/ajnaHandler.ts

Yield loops - fix missing strategies

---

features/refinance/components/steps/RefinanceSwapSection.tsx
features/refinance/hooks/useSdkSimulation.tsx

- Fixed percentage calculations
- check price impact and slippagoe on refinance order details

Fixed percentage calculations

---

features/refinance/components/RefinanceHeader.tsx
features/refinance/components/RefinancePositionView.tsx
features/refinance/components/RefinanceSimulation.tsx

- for shorts we are denominating in debt/collateral 
- human readable liquidation price for short positions

Refinance fix short liquidity price

---

features/omni-kit/protocols/ajna/helpers/isPoolWithRewards.ts

Updating the Ajna rewards and pools

Update Ajna Rewards Pools 25-4-24

---

features/positionHistory/getHistoryEventLabel.ts
public/locales/en/common.json

- added history event label handling

Refinance history event label

---

features/omni-kit/components/details-section/OmniOpenYieldLoopSimulation.tsx
public/locales/en/common.json

Small copy changes - see: https://discord.com/channels/837076147694207067/1227910155274813580/1233018950686871646

Changed copy

---

features/omni-kit/protocols/aave-like/components/AaveLikeContentFooterBorrow.tsx
features/omni-kit/protocols/aave-like/components/AaveLikeContentFooterMultiply.tsx
features/omni-kit/protocols/aave-like/components/AaveLikeCostToBorrowContentCardModal.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterBorrow.tsx
features/omni-kit/protocols/ajna/components/details-section/AjnaContentFooterMultiply.tsx
features/omni-kit/protocols/morpho-blue/components/details-sections/MorphoContentFooterBorrow.tsx
features/omni-kit/protocols/morpho-blue/components/details-sections/MorphoContentFooterMultiply.tsx
handlers/product-hub/update-handlers/ajna/ajnaHandler.ts

Story details: https://app.shortcut.com/oazo-apps/story/15388

fix: [sc-15388] Ajna LP strategies are using Ajna Yield loop APYs in product finder if both are available

---

blockchain/contracts/arbitrum.ts
blockchain/contracts/base.ts
blockchain/contracts/goerli.ts
blockchain/contracts/mainnet.ts
blockchain/contracts/optimism.ts
blockchain/token-metadata-list/token-configs.ts
blockchain/tokens/mainnet.ts
handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
package.json
yarn.lock

Added support for UNI-V2 DAI Ajna Poll

UNiV2-DAI Ajna Pool

---

features/omni-kit/protocols/ajna/helpers/isPoolWithRewards.ts

Updating the pool rewards for Ajna Rewards Update
- Adding UNI-V2 LP / Dai pair to rewards
- Updating other pool reward amounts
- Check to see if UNI-V2 / Dai pair has stars and correct amount from product finder
- Confirm other pools have correct amount of tokens in product finder

Update Ajna Reward Pools 2/5/24

---

features/omni-kit/helpers/getOmniHeadlineProps.ts
features/omni-kit/helpers/getTokenNameForHeadline.ts

Added a mechanism to use custrom name for headline on open/manage position

Mechanism to use custrom token name for headline

---

features/multiply/manage/containers/ManageMultiplyVaultDetails.tsx

- Added RefinanceBanner to multiply
- open maker multiply position, check if you can see Refinance banner visible

Added RefinanceBanner to multiply

---

features/productHub/types.ts
features/refinance/components/steps/RefinanceProductTableStep.tsx
features/refinance/helpers/getRefinanceProductHubDataParser.ts

- Refactored calculations of the refinance borrow rates
- refinance maker position
- on table step check displayed borrow rates for target positions

Refactored calculations of the refinance borrow rates

---

features/refinance/components/steps/RefinanceWhatsChangingStep.tsx
features/refinance/helpers/replaceETHwithWETH.ts
features/refinance/helpers/replaceTokenSymbolWETHWithETH.ts
features/refinance/views/RefinanceFormView.tsx

https://app.shortcut.com/oazo-apps/story/15401/the-target-position-pair-is-not-used-in-the-copy-for-the-last-step-in-refinance
- Fixed target position pair not used in the copy for the last step in refinance
- check linked story

Fixed target position pair not used in the copy for the last step in refinance

---

features/aave/manage/containers/AaveManageTabBar.tsx
features/omni-kit/controllers/OmniLayoutController.tsx

Add DisableNetValueCheck to AaveManageTabBar and OmniLayoutController

feat: Add DisableNetValueCheck to AaveManageTabBar and OmniLayoutController

---

features/refinance/components/steps/RefinanceStrategyStep.tsx

Disabled earn strategy in refinance

Disabled earn strategy in refinance

---

public/locales/en/common.json

update position swap permissions copy

---

handlers/portfolio/positions/handlers/morpho-blue/index.ts
handlers/portfolio/positions/helpers/getAutomationData.ts
handlers/portfolio/positions/helpers/getPositionsAutomations.ts
package.json
yarn.lock

Add MB automations support in portfolio

Add MB automations support in portfolio

---

features/aave/strategies/arbitrum-aave-v3-strategies.ts
features/aave/strategies/base-aave-v3-strategies.ts

Reverts OasisDEX/oasis-borrow#3835

Revert "adding 2 pairs"

---

handlers/product-hub/update-handlers/morpho-blue/morphoBlueHandler.ts

- Updated morpho earn description in PH so it contains ltv

Update morpho earn description in PH

---

features/omni-kit/automation/helpers/getAutomationMetadataValues.ts
features/omni-kit/automation/helpers/getMappedAutomationMetadataValues.ts
features/omni-kit/contexts/OmniProductContext.tsx
features/omni-kit/controllers/OmniProductController.tsx
features/omni-kit/helpers/getOmniValidations.ts
features/omni-kit/helpers/useOmniLendingValidations.tsx
features/omni-kit/hooks/useOmniInitialization.ts
features/omni-kit/protocols/aave-like/metadata/useAaveLikeMetadata.tsx
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
features/omni-kit/state/automation/auto-bs/getAutomationAutoBSFormDefaults.ts
features/omni-kit/state/automation/common/getAutomationFormDefaults.ts
features/omni-kit/state/automation/partial-take-profit/getAutomationPartialTakeProfitFormDefaults.ts
features/omni-kit/state/automation/stop-loss/getAutomationStopLossFormDefaults.ts
features/omni-kit/state/automation/trailing-stop-loss/getAutomationTrailingStopLossFormDefaults.ts

This pull request fixes the mapping of triggers and flags for MB automations. It includes changes to multiple files to ensure that the correct triggers and flags are used for the automation features.

FixF MB automations triggers/flags mapping

---

features/omni-kit/controllers/OmniProductController.tsx
features/omni-kit/hooks/useOmniTriggersData.ts
features/omni-kit/protocols/morpho-blue/settings.ts
features/omni-kit/types.ts

- fixed issue where we initially were calling triggers endpoint without pool id param and therefore ui state was not initialized properly

Omni automation request with pool id fix

---

components/history/PositionHistoryItemDetails.tsx
features/omni-kit/protocols/morpho-blue/helpers/getMorphoPositionAggregatedData.ts
features/omni-kit/protocols/morpho-blue/history/mapMorphoLendingEvents.ts
features/omni-kit/protocols/morpho-blue/history/types.ts
features/omni-kit/protocols/morpho-blue/hooks/useMorphoData.ts
features/omni-kit/protocols/morpho-blue/observables/getMorphoPositionAggregatedData.ts
features/positionHistory/filterAndGroupByTxHash.ts
features/positionHistory/helpers/getAutomationEvents.ts
features/positionHistory/helpers/index.ts
features/positionHistory/types.ts
features/subgraphLoader/consts.ts
features/subgraphLoader/types.ts

- added handling to morpho automation history
- working automation history

Morpho automation history

---

features/omni-kit/automation/components/auto-buy-sell/OmniAutoBSSidebarController.tsx

- hidden auto buy and sell price inputs
- while setting auto buy or sell on morpho user shouldn't be able to set threshold price

Morpho hide autobs inputs and default to not use threshold prices

---

package.json
yarn.lock

Bump automation package

---

helpers/lambda/triggers/setup-triggers/setup-auto-buy.ts
helpers/lambda/triggers/setup-triggers/setup-auto-sell.ts

- set requirement of setting prices when removing trigger to false
- remove of auto bs triggers should work on morpho

Morpho auto bs trigger remove fix

---

features/omni-kit/automation/helpers/getMappedAutomationMetadataValues.ts

- Fixed spark automation flags
- automation features should load as expected on spark

Fix spark automation flags

---

features/omni-kit/automation/constants.ts
features/omni-kit/automation/hooks/useOmniStopLossDataHandler.tsx

- adjusted offsets to be able to set sl and tsl on yield loops

Adjust sl and tsl slider offsets

---

helpers/clients/portfolio-client.ts
server/rewrites.ts

Untracked - request from Chris
- Switched portfolio lambdas to our new AWS infra as currently portfolio is using outdated lambda without Morpho support
- check summer portfolio value of this wallet
https://staging.summer.fi/portfolio/0xb6462b67fe692223dffb61c8dc8ad080cba180cc#wallet 
- compare with prod value
Expected: should include morpho position value
Actual: dose not include morpho positions

Switched portfolio lambdas to our new AWS infra

---

features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx

- modify how the fee is calcualted , taking into account if we sell/buy collateral - and if the fee is taken from target or source of the swap
- step 1 ...

chore: fix swap fess

---

features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx

fix: fix missing fee source issue

---

blockchain/contracts/arbitrum.ts
blockchain/contracts/base.ts
blockchain/contracts/goerli.ts
blockchain/contracts/mainnet.ts
blockchain/contracts/optimism.ts
package.json
yarn.lock

- added new pair on base
- new pair accessible from UI

Ajna base susdcy-usdc pair

---

handlers/product-hub/index.ts
handlers/product-hub/update-handlers/aaveV3/aaveV3Handler.ts
handlers/product-hub/update-handlers/ajna/ajnaHandler.ts
handlers/product-hub/update-handlers/erc-4626/erc4626Handler.ts
handlers/product-hub/update-handlers/morpho-blue/morphoBlueHandler.ts
handlers/product-hub/update-handlers/sparkV3/sparkV3Handler.ts

Reverts OasisDEX/oasis-borrow#3901

Revert "Fix zero APY product hub bug"

---

features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx

- fixed issue with refinance banner
- morpho open flow should work

Fix morpho opening page

---

features/refinance/components/steps/RefinanceProductTableStep.tsx

- show protocol filter in ph in refinance ui
- user should be able to use protocol filter in ph step

Allow maker refinance to any

---

features/aave/services/read-position-created-events.ts
features/refinance/helpers/getTargetPoolId.ts
features/refinance/hooks/useSimulationPositionData.tsx
handlers/portfolio/positions/handlers/aave-like/helpers.ts

- fixed issue with morpho market while morpho is as target position
- no issue regardint market id being undefined

Refinance fix morpho market id

---

features/aave/manage/services/aave-v2/getManageAaveV2PositionStateMachineServices.ts
features/aave/manage/services/aave-v3/getManageAaveV3PositionStateMachineServices.ts
features/aave/services/get-aave-history-events.ts
features/omni-kit/protocols/aave-like/helpers/getAaveLikePositionData.ts
features/omni-kit/protocols/aave-like/hooks/useAaveLikeData.ts
features/omni-kit/protocols/aave/settings.ts
features/omni-kit/protocols/spark/settings.ts
features/subgraphLoader/types.ts
handlers/portfolio/positions/handlers/aave-like/helpers.ts

- handled recent change in subgraph where we are able to distinguish between aavelike positions on the same dpm
- spark & aave history should be separated in subgraph response even if on the same dpm

Aave like dpm position history split

---

features/omni-kit/helpers/getOmniFilterConsumedProxy.ts
features/omni-kit/protocols/aave-like/helpers/aaveLikeFlowStateFilter.ts
features/omni-kit/types.ts
features/omni-kit/views/OmniFormView.tsx

- allow to reuse dpm proxy if there is only spark or aave position on given dpm and new position will be of different protocol
- if there is already created spark position on dpm, it should be possible to use this dpm to open aave position or other way around

Aave like dpm reusability adjustment

---

features/aave/services/get-aave-history-events.ts
features/subgraphLoader/consts.ts
handlers/portfolio/positions/handlers/aave-like/helpers.ts
handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/aave-v2/ds-proxy-position.ts
handlers/portfolio/positions/handlers/aave-v2/index.ts
handlers/portfolio/positions/helpers/getHistoryData.ts

- get history per specific dpm address & protocol combination
- portfolio should work

Adjust aavelike portfolio handling

---

.npmrc

Remove curly brackets from npm token

---

features/refinance/helpers/getRefinanceStrategiesToBeFiltered.ts

- fixed issue where all markets with given id were filtered out
- only one strategy should be filtered out

Refinance morpho strategies filter fix

---

features/refinance/helpers/getEmode.tsx

To fix Still same Asset not found error for all Aave V3 token when refinancing

Emode upper case patch

---

features/omni-kit/automation/helpers/getMappedAutomationMetadataValues.ts

- fixed issue with hardcoded trigger flags
- aavelike triggers shouldn't overlap on UI

Aave-like automation mapping fix

---

Dockerfile.production

- Adding `.npmrc` file to `Dockerfile.production`

adding `.npmrc` to Dockerfile prod

---

pages/api/exchange/[[...params]].tsx

Update 1inch API header

---

actions/aave-like/helpers/index.ts
features/exchange/exchange.ts
features/omni-kit/constants.ts
helpers/swap.ts

- updated mainnet api version from v4.0 to v4.1

Update mainnet 1inch api version

---

pages/api/exchange/[[...params]].tsx

Update exchange urlCreator

---

.gitignore
features/shared/jwt.ts
handlers/signature-auth/signin.ts

fix: fix safe message

---

features/shared/jwt.ts

fix: safe message - handle empty signature

---

handlers/signature-auth/argent.ts
handlers/signature-auth/eip1271.ts
handlers/signature-auth/eip1272.ts
handlers/signature-auth/signin.ts

Title
Implement EIP-1271 Signature Validation
Changes 👷‍♀️
- Added isValidSignature function to validate signatures using EIP-1271 compatible contracts.
- Defined ABI for isValidSignature function.
- 
How to test 🧪
- sign in using safe or argent wallet

chore: eip1271 comaptible message signature validation

---

.github/workflows/release.yaml

- updating `actions/checkout` to v4
- configuring a user e-mail for git
- adding quotes around git config parameters

Fixing the release GHA

---

features/refinance/stablecoinTokensUpperCase.ts

removed LUSD from emode stablecoin tokens list to set correct emode in SDK

removed LUSD from emode stablecoin tokens list

---

handlers/portfolio/positions/handlers/maker/index.ts

- removed positions with given ilk from portfolio

Filter crv ilk positions from portfolio

---

features/omni-kit/protocols/morpho-blue/settings.ts

- Enabled multiply and automation for mkr pairs on morpho

Enable multiply and automation for mkr pairs on morpho

---

features/aave/manage/contexts/triggers-aave-state-machine-context.tsx
features/aave/manage/state/triggersAaveStateMachine.ts
features/omni-kit/constants.ts
features/omni-kit/hooks/useOmniTriggersData.ts
features/omni-kit/protocols/morpho-blue/metadata/useMorphoMetadata.tsx
helpers/lambda/triggers/get-triggers/get-triggers-request.ts

- fixed issue where flags were not provided as default
- morpho positions should load

Morpho Base fix

---

components/portfolio/PortfolioOverview.tsx
components/portfolio/types/domain-types.ts
public/locales/en/portfolio.json

- added Total rays earned in portfolio header

Total rays earned portfolio

---

components/portfolio/positions/PortfolioPositionBlock.tsx
handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/aave-v2/index.ts
handlers/portfolio/positions/handlers/ajna/index.ts
handlers/portfolio/positions/handlers/dsr/index.ts
handlers/portfolio/positions/handlers/erc-4626/index.ts
handlers/portfolio/positions/handlers/maker/index.ts
handlers/portfolio/positions/handlers/morpho-blue/index.ts
handlers/portfolio/types.ts
helpers/rays/index.ts

- Base amount of rays in portfolio per position

Base amount of rays in portfolio per position

---

features/homepage/HomepageView.tsx

- do hard redirect
- redirect to rays app should work

Rays banner redirect fix

---

components/FlowSidebar.tsx
features/refinance/controllers/RefinanceFlowSidebarController.tsx
helpers/useFlowState.ts

This pull request fixes the issue with the FlowSidebar component in the Maker lending protocol. Previously, when there was no proxy created, the UI would not load properly. This PR addresses this issue by updating the logic in the FlowSidebar component to handle this scenario correctly.

"Fix FlowSidebar ui loading for Maker when there is no proxy created"

---

components/navigation/NavigationRays.tsx
components/portfolio/PortfolioOverview.tsx
components/portfolio/types/domain-types.ts
features/rays/getRaysUser.ts
features/rays/hooks/useUserRays.ts
features/rays/types.ts
handlers/rays/getUserRays.ts
helpers/clients/portfolio-client-data.ts
pages/api/rays/index.ts
pages/portfolio/[address].tsx

- separated rays user data call from portfolio assets call

Separate rays api calls

---

components/portfolio/positions/PortfolioPositionBlock.tsx
features/omni-kit/helpers/getOmniSidebarRaysBanner.tsx
features/omni-kit/protocols/aave-like/helpers/mapAaveLikeRaysMultipliers.ts
features/omni-kit/protocols/aave-like/hooks/useAaveLikeData.ts
features/omni-kit/protocols/ajna/helpers/mapAjnaRaysMultipliers.ts
features/omni-kit/protocols/ajna/hooks/useAjnaData.ts
features/omni-kit/protocols/erc-4626/helpers/mapErc4626RaysMultipliers.ts
features/omni-kit/protocols/erc-4626/hooks/useErc4626Data.ts
features/omni-kit/protocols/morpho-blue/helpers/mapMorphoBlueRaysMultipliers.ts
features/omni-kit/protocols/morpho-blue/hooks/useMorphoData.ts
features/rays/getProtocolBoost.ts
features/rays/getRaysUserMultipliers.ts
features/rays/getSwapBoost.ts
features/rays/getTimeOpenBoost.ts
features/rays/types.ts
features/subgraphLoader/consts.ts
handlers/portfolio/positions/handlers/aave-like/index.ts
handlers/portfolio/positions/handlers/aave-like/types.ts
handlers/portfolio/positions/handlers/aave-v2/index.ts
handlers/portfolio/positions/handlers/ajna/index.ts
handlers/portfolio/positions/handlers/erc-4626/index.ts
handlers/portfolio/positions/handlers/maker/helpers/mapMakerRaysMultipliers.ts
handlers/portfolio/positions/handlers/maker/index.ts
handlers/portfolio/positions/handlers/maker/types.ts
handlers/portfolio/positions/handlers/morpho-blue/index.ts
handlers/portfolio/positions/helpers/getPositionPortfolioRaysWithBoosts.ts
handlers/portfolio/positions/helpers/getRaysMultipliersServerSide.ts
handlers/portfolio/positions/index.ts
handlers/portfolio/types.ts

- added rays multipliers per position in portfolio
- positions in portfolio should have rays with multiples applied

Rays with multipliers in portfolio

---

components/navigation/NavigationRays.tsx
features/homepage/HomepageView.tsx

Update navigation links to include user address in query parameter

Update navigation links to include user address in query parameter

---

features/omni-kit/protocols/morpho-blue/helpers/getMetaMorphoClaims.tsx
package.json
yarn.lock

- updated morpho rewards API
- morpho rewards should be displayed and it should be possible to claim rewards

Update morpho rewards API

---

components/Tabs.tsx
components/assetsTable/AssetsFiltersContainer.tsx
components/swapWidget/SwapWidgetNoSsr.tsx
features/productHub/components/ProductHubLoadingState.tsx
features/productHub/controls/ProductHubFiltersController.tsx
handlers/signature-auth/signin.ts
theme/icons/arb_circle.tsx
theme/icons/bal_circle.tsx
theme/icons/crv_circle.tsx
theme/icons/cseth.tsx
theme/icons/mkr_circle_color.tsx
theme/icons/mpeth.tsx
theme/icons/op_circle.tsx
theme/icons/styeth_circle_color.tsx
theme/icons/susd_circle.tsx
theme/icons/unieth.tsx

- fix safe -> walletconnect -> app issue
- cold start loading time improvement by using the `NEXT_PUBLIC_SWAP_WIDGET_ONBOARDING_HIDDEN=true` environment variable
- fixes some irritating key and SVG errors

fix: safe -> walletconnect -> app issue + other fixes

---

features/omni-kit/protocols/erc-4626/components/details-section/Erc4626DetailsSectionContentRewards.tsx
features/omni-kit/protocols/erc-4626/helpers/getErc4626Claims.ts
features/omni-kit/protocols/morpho-blue/helpers/getMetaMorphoClaims.tsx

- handled different type of claims (for_borrow, for_supply)
- added chainId handling
- nothing to test for now

Morpho rewards claim type handling

---

handlers/portfolio/positions/handlers/morpho-blue/index.ts

- fixed issue with symbols
- portfolio with morpho mkr positions should load

Fix portfolio not being loaded with Morpho MKR positions

---

handlers/risk/get.ts

- force risk re-check if wallet was flagged
- in cases where provider flags wallet by mistake and later fix the issue, risk in database should be updated accordingly

Risk force re-check

---

features/omni-kit/protocols/aave/settings.ts
handlers/product-hub/update-handlers/aaveV3/aave-v3-products/ethereum-mainnet.ts

- disabled MKR multiply aave v3
- no way to open multiply position using MKR token on aave v3

Disable MKR multiply aave v3

---

features/aave/open/helpers/use-lambda-debounced-partial-take-profit.ts

Take profit app error fix

---

actions/aave-like/adjust/get-adjust-position-parameters.ts
actions/aave-like/close/get-close-aave-parameters.ts
actions/aave-like/helpers/index.ts
actions/aave-like/open/get-open-position-parameters.ts
features/omni-kit/protocols/aave-like/helpers/getAaveLikeParameters.ts
features/omni-kit/protocols/aave/settings.ts
handlers/product-hub/update-handlers/aaveV3/aave-v3-products/ethereum-mainnet.ts
package.json
yarn.lock

- added Aave isolated collateral support
- aave v3 collaterals like MKR, LDO, SUSDE, FRAX should work while using multiply

Aave isolated collateral support

---

features/omni-kit/automation/hooks/useOmniStopLossDataHandler.tsx
features/omni-kit/protocols/aave-like/components/AaveLikeDetailsSectionContentManage.tsx

- fixed issue where we were using liquidation threshold instead of max-ltv

Aavelike max-ltv fix

---

features/omni-kit/helpers/getOmniSidebarRaysBanner.tsx
features/omni-kit/views/OmniFormView.tsx

- rays pseudo protocol fix
- correct instant rays on close

Rays pseudo protocol fix

---

features/omni-kit/protocols/aave-like/helpers/getAaveLikeParameters.ts
features/omni-kit/protocols/aave-like/metadata/useAaveLikeMetadata.tsx
features/omni-kit/protocols/aave/settings.ts
features/omni-kit/views/OmniFormView.tsx
handlers/product-hub/update-handlers/aaveV3/aave-v3-products/arbitrum-mainnet.ts
handlers/product-hub/update-handlers/aaveV3/aave-v3-products/ethereum-mainnet.ts
handlers/product-hub/update-handlers/aaveV3/aave-v3-products/optimims-mainnet.ts
package.json
yarn.lock

- if strategy is type of earn (yield loop), show it only as earn in PH
- fixed issue with entry token
- fixed issue with lack of max generate amount above input

Aavelike yield loops only as earn

---

features/omni-kit/protocols/aave-like/helpers/aaveLikeFlowStateFilter.ts
features/omni-kit/views/OmniFormView.tsx

- fixed issue where dupe modal was displayed by mistake
- check story

Aavelike flow state filter adjustment

---

blockchain/aave-v3/aave-v3-pool-data-provider.ts
blockchain/spark-v3/spark-v3-pool-data-provider.ts
lendingProtocols/aave-like-common/get-aave-like-reserve-data.ts
package.json
yarn.lock

- fixed issue with availableToSupply value which didn't take into account accruedToTreasuryScaled
- correct behaviour when cap reached on aavelike positions

Aavelike availableToSupply calcs improvement

---

features/exchange/exchange.ts
features/multiply/manage/pipes/manageMultiplyQuote.ts
features/multiply/manage/pipes/manageMultiplyVault.ts
features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
features/multiply/open/pipes/openMultiplyVaultTransactions.ts
features/omni-kit/observables/omniExchangeQuote.ts

- adjusted maker swap query params and markets
- decent price impact on increase or decrease

Adjust Maker swap logic

---

handlers/product-hub/update-handlers/sparkV3/sparkV3Handler.ts

Add rewards tooltips to product hub in Spark handler

Add rewards tooltips to product hub

---

components/swapWidget/SwapWidget.tsx

Reverts OasisDEX/oasis-borrow#3992

Revert "chore: Disable lifi BridgeSwap temporarily"

---

actions/aave-like/adjust/get-adjust-position-parameters.ts
actions/aave-like/close/get-close-aave-parameters.ts
actions/aave-like/helpers/index.ts
actions/aave-like/open/get-open-position-parameters.ts
features/aave/components/order-information/PriceImpact.tsx
features/aave/components/order-information/StrategyInformationContainer.tsx
features/exchange/exchange.ts
features/multiply/manage/pipes/manageMultiplyVaultTransactions.ts
features/multiply/open/pipes/openMultiplyVaultTransactions.ts
features/omni-kit/components/sidebars/multiply/OmniMultiplyFormOrder.tsx
features/omni-kit/observables/omniExchangeQuote.ts
features/omni-kit/protocols/aave-like/helpers/getAaveLikeParameters.ts
features/omni-kit/protocols/ajna/actions/common.ts
features/omni-kit/protocols/ajna/actions/multiply.ts
features/omni-kit/protocols/ajna/helpers/getAjnaParameters.ts
features/omni-kit/protocols/erc-4626/components/sidebar/Erc4626FormOrder.tsx
features/omni-kit/protocols/erc-4626/helpers/getErc4626Parameters.ts
features/omni-kit/protocols/morpho-blue/helpers/getMorphoParameters.ts
helpers/swap.ts

- added 1inch origin query param
- origin query param should be attach to each swap request

1inch origin query param
